[WIP] UpdateWithOutput() support
linq2db/linq2db pull request #2321
Opened 2020-07-05 22:39 UTC by viceroypenguin

2021-05-07 08:21 UTC, croban commented
This feature would be great!

2021-05-08 11:42 UTC, MaceWindu commented
@viceroypenguin could you summarise what's left here?

2021-05-08 11:47 UTC, MaceWindu commented
In that case let's wait for @sdanyliv opinion. Contexts is his area of expertise :)

2021-05-24 09:59 UTC, MaceWindu commented
@viceroypenguin , i've fixed issue with update output builder context, so you can continue working on it

2021-05-24 10:00 UTC, MaceWindu commented
/azp run test-all

2021-05-24 16:04 UTC, MaceWindu commented
@viceroypenguin , please check failing tests - looks like merged changes in UpdateBuilder are not compatible with your refactoring of builder and you need to refactor it once more

2021-05-26 20:50 UTC, viceroypenguin commented
/azp run test-all

2021-05-27 16:16 UTC, viceroypenguin commented
/azp run test-all

2021-05-28 11:29 UTC, MaceWindu requested changes

2021-05-28 11:29 UTC, MaceWindu commented on Source/LinqToDB/Linq/Builder/UpdateBuilder.cs
> +			var indexedParameters = methodCall.Method.GetParameters()
would be nice to use something more lightweight here instead of dictionary creation with disposable tuples for such a trivial task

2021-05-28 11:29 UTC, MaceWindu commented on Source/LinqToDB/Linq/Builder/UpdateBuilder.cs
> +					// (source, deleted, inserted) => expr(deleted, inserted)
I think we have helper for such task already... cannot find it. @sdanyliv any idea?

2021-05-28 11:29 UTC, MaceWindu commented on Source/LinqToDB/LinqExtensions.Update.cs
> +							ITable<TTarget>					  outputTable)
something wrong with formatting here and for other methods

2021-05-28 11:29 UTC, MaceWindu commented on Source/LinqToDB/SqlQuery/QueryVisitor.cs
>  			VisitX(outputClause.SourceTable);
Use Visit here too. We should review visitors after release to check if we have other places where we bypass main dispatch method...

2021-05-28 11:29 UTC, MaceWindu commented on Tests/Linq/Update/UpdateWithOutputTests.cs
> +namespace Tests.Playground
rename namespace (and delete baselines pr/branch as it will re-generate baselines with new names)

2021-05-28 21:20 UTC, viceroypenguin commented
/azp run test-all

2021-05-29 12:52 UTC, viceroypenguin commented
/azp run test-all

2021-05-29 13:37 UTC, MaceWindu commented
/azp run test-all

2021-05-29 13:45 UTC, MaceWindu approved these changes

2021-05-31 16:10 UTC, viceroypenguin commented
/azp run test-all

2021-06-02 12:06 UTC, viceroypenguin commented
@sdanyliv Approve or review?

2021-06-03 07:51 UTC, merged