Complete Temporary Table support functionality
linq2db/linq2db pull request #2391
Opened 2020-08-05 04:36 UTC by igor-tkachev

Fixes #2368

2020-08-05 04:40 UTC, igor-tkachev commented
/azp run test-all

2020-08-18 01:46 UTC, igor-tkachev commented
/azp run test-all

2020-08-26 02:37 UTC, igor-tkachev commented
/azp run test-all

2020-09-02 13:23 UTC, igor-tkachev commented
/azp run test-all

2020-09-03 15:38 UTC, igor-tkachev commented
/azp run test-all

2020-09-03 16:44 UTC, sdanyliv commented
/azp run test-all

2020-09-03 19:07 UTC, igor-tkachev commented
/azp run test-all

2020-09-03 20:41 UTC, igor-tkachev commented
/azp run test-all

2020-09-04 00:37 UTC, igor-tkachev commented
/azp run test-all

2020-09-09 00:28 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
> +//				(table.TableOptions.HasIsTemporary) != 0 ?
Leaving comments here intentional?

2020-09-09 00:28 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs
> +//			if ((table.TableOptions.HasCreateIfNotExists) != 0)
Leaving comments is intentional?

2020-09-09 00:28 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
> +				BuildPhysicalTable(table, null, defaultDatabaseName : defaultDatabaseName);
If providing parameter names, should provide parameter name for `null`, since that is most likely to be opaque in later reading. `defaultDatabaseName` is self-explanatory here.

2020-09-09 00:28 UTC, viceroypenguin commented on Source/LinqToDB/TempTable.cs
> +		public static Task<TempTable<T>> ToTempTableAsync<T>(
Function above is named `IntoTempTable()`. Should update that to `ToTempTable()` or this to `IntoTempTableAsync()` for matching.

2020-09-09 00:28 UTC, viceroypenguin commented on Source/LinqToDB/TempTable.cs
> +		public static Task<TempTable<T>> ToTableAsync<T>(
Similar naming issue

2020-09-09 00:30 UTC, viceroypenguin commented
Fixes #1201 by way of `TableOptions.CreateIfNotExists`

2020-09-11 13:31 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
> +				BuildPhysicalTable(table, null, defaultDatabaseName : defaultDatabaseName);
This is OBJECT_ID specific behavior.

2020-09-11 13:32 UTC, igor-tkachev commented on Source/LinqToDB/TempTable.cs
> +		public static Task<TempTable<T>> ToTempTableAsync<T>(
Yep.

2020-09-11 13:32 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
> +//				(table.TableOptions.HasIsTemporary) != 0 ?
Not need anymore.

2020-09-11 14:27 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
> +				BuildPhysicalTable(table, null, defaultDatabaseName : defaultDatabaseName);
```suggestion
				BuildPhysicalTable(table, alias: null, defaultDatabaseName: defaultDatabaseName);
```

2020-09-11 14:27 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
> +			BuildPhysicalTable(table, null);
```suggestion
			BuildPhysicalTable(table, alias: null);
```

2020-09-11 14:37 UTC, viceroypenguin approved these changes

2020-09-14 07:10 UTC, ili commented on Source/LinqToDB/TempTable.cs
> +		public static TempTable<T> IntoTempTable<T>(
Two same methods with different names are confusing. User would expect `IntoTable` would create persistent table and `IntoTempTabe` would create temporary one, at least because there are *two* methods. Nobody reads docs :)

2020-09-14 13:47 UTC, MaceWindu commented
linking #1609 to this pr

2020-09-16 11:06 UTC, MaceWindu requested changes
Missing support:
- access temporary tables: https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/create-table-statement-microsoft-access-sql
- sap hana global and local temp tables: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/20d58a5f75191014b2fe92141b7df228.html

2020-09-16 11:07 UTC, MaceWindu commented
release notes draft https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#temporary-tables

2020-09-16 11:10 UTC, MaceWindu commented on Source/LinqToDB/TableOptions.cs
> +		/// Table is global temporary. This option will have effect only for databases that support temporary tables.
makes sense to specify difference between global temp and temp tables

2020-09-16 11:48 UTC, viceroypenguin commented
> release notes draft https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#temporary-tables

@MaceWindu FYI for release notes: also fixes #1201 by way of new options on TableCreation.

2020-10-09 02:18 UTC, igor-tkachev commented on Source/LinqToDB/Data/BulkCopyOptions.cs
> +		/// Gets or sets explicit IsTemporary flag instead of one, configured for copied entity in mapping schema.
Yes, and we can add more.

2020-10-09 03:17 UTC, igor-tkachev commented on Source/LinqToDB/TempTable.cs
> +		public static TempTable<T> IntoTempTable<T>(
Either I already fixed it or I didn't get it :( What two the same methods have different names?

2020-10-09 03:23 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs
> +					"CREATE GLOBAL TEMPORARY TABLE " :
Changed for Firebird.

2020-10-09 10:22 UTC, MaceWindu commented
/azp run test-all

2020-10-09 10:58 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs
> +					"CREATE GLOBAL TEMPORARY TABLE " :
I think we should change oracle to use IsGlobalTemporary instead as it is visible to other sessions, data is not visible. It will match other databases behavior then:
- DB2:
 - CREATE GLOBAL: table visible to other sessions, data not shared (global)
 - DECLARE GLOBAL: table not visible from other sessions (local)
- FB: table visible to other sessions, data not shared (global)
- SQLITE, MYSQL/MARIADB, PGSQL, INFORMIX: table not visible from other sessions (local)
- SAP HANA:
 - GLOBAL: table visible to other sessions, data not shared (global)
 - LOCAL: table not visible from other sessions (local)
- SQL SERVER/SYBASE ASE:
 - ## table visible to other sessions (global)
 - #: table not visible from other sessions (local)

Also available here https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#temporary-tables as table

2020-10-09 10:59 UTC, MaceWindu commented
/azp run test-all

2020-10-09 11:44 UTC, MaceWindu commented
I think we should have more tests for new functionality. SAP HANA tests passed but I don't see temp tables used there

2020-10-13 11:43 UTC, MaceWindu commented
/azp run test-all

2020-10-16 00:56 UTC, igor-tkachev commented
/azp run test-all

2020-10-16 02:41 UTC, igor-tkachev commented
/azp run test-all

2020-10-16 03:02 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs
> +					"CREATE GLOBAL TEMPORARY TABLE " :
We have 3 temp table implementations by different providers:

- session shared structure / session shared data (SqlServer ##)
- session shared structure / session private data (FB)
- session private structure / session private data (SqlServer #)

So, we can explicitly implement those flags and do not care about compatibility/provider support. Users will handle it somehow. Also we can implement some other temp table flags.

Another way is what I tried to implement - to simulate local/global session temp tables.

Probably, the first approach is better. Should I follow it?

2020-10-16 03:25 UTC, igor-tkachev commented
/azp run test-all

2020-10-16 10:15 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs
> +					"CREATE GLOBAL TEMPORARY TABLE " :
+ for first approach, but I don't see value in adding 3rd option. Current separation into two types if looks fine to me: Global == shared structure (with any data isolation level), NonGlobal == session structure. There is no database that have two types of global tables.

2020-10-16 13:18 UTC, igor-tkachev commented
/azp run test-PostgreSQL95

2020-10-16 13:20 UTC, igor-tkachev commented
/azp list

2020-10-18 22:51 UTC, igor-tkachev commented
In order to add a full support for temp tables, we need the following table options:

- IsGlobalTemporaryScope (IsGlobalTemporaryStructure)
- IsLocalTemporaryScope (IsLocalTemporaryStructure)
- IsGlobalTemporaryData
- IsLocalTemporaryData
- IsTransactionTemporaryData

Those options will be applied to

Database | Statement | Scope | Data | Options
-- | -- | -- | -- | --
DB2 | CREATE GLOBAL TEMPORARY TABLE | Global | Session | IsGlobalTemporaryScope + IsLocalTemporaryData
DB2 | DECLARE GLOBAL TEMPORARY TABLE | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
Firebird | CREATE GLOBAL TEMPORARY TABLE … ON COMMIT DELETE ROWS (default) | Global | Transaction | IsGlobalTemporaryScope + IsTransactionTemporaryData
Firebird | CREATE GLOBAL TEMPORARY TABLE … ON COMMIT PRESERVE ROWS | Global | Connection | IsGlobalTemporaryScope + IsLocalTemporaryData
Informix | CREATE TEMP TABLE | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
MySql | CREATE TEMPORARY TABLE | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
Oracle | CREATE GLOBAL TEMPORARY TABLE … ON COMMIT DELETE ROWS   (default) | Global | Transaction | IsGlobalTemporaryScope + IsTransactionTemporaryData
Oracle | CREATE GLOBAL TEMPORARY TABLE … ON COMMIT PRESERVE ROWS | Global | Session | IsGlobalTemporaryScope + IsLocalTemporaryData
Oracle | CREATE PRIVATE TEMPORARY TABLE (18c) | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
PostgreSQL | CREATE TEMPORARY TABLE … ON COMMIT DELETE ROWS | Session | Transaction | IsLocalTemporaryScope + IsTransactionTemporaryData
PostgreSQL | CREATE TEMPORARY TABLE … ON COMMIT PRESERVE ROWS | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
PostgreSQL | CREATE TEMPORARY TABLE … ON COMMIT DROP | Transaction | Transaction | NOT SUPPORTED ???
SAP Hana | CREATE GLOBAL TEMPORARY TABLE | Global | Session | IsGlobalTemporaryScope + IsLocalTemporaryData
SAP Hana | CREATE LOCAL TEMPORARY TABLE | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
SqlServer | CREATE TABLE #TableName | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
SqlServer | CREATE TABLE ##TableName | Last Session | Global | IsGlobalTemporaryScope + IsGlobalTemporaryData
SqlServer | DECLARE @TableName TABLE | Batch | Batch | NOT SUPPORTED
Sybase | CREATE TABLE #TableName | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
Sybase | CREATE TABLE ##TableName | Last Session | Global | IsGlobalTemporaryScope + IsGlobalTemporaryData

Also I am going to add the IsTemporary option to implement Local/Local temp table

Database | IsTemporary
-- | --
DB2 | IsLocalTemporaryScope + IsLocalTemporaryData
Firebird | IsGlobalTemporaryScope + IsLocalTemporaryData + CreateIfNotExists +   DropIfExists
Informix | IsLocalTemporaryScope + IsLocalTemporaryData
MySql | IsLocalTemporaryScope + IsLocalTemporaryData
Oracle | IsGlobalTemporaryScope + IsLocalTemporaryData + CreateIfNotExists +   DropIfExists
PostgreSQL | IsLocalTemporaryScope + IsLocalTemporaryData
SAP Hana | IsLocalTemporaryScope + IsLocalTemporaryData
SqlServer | IsLocalTemporaryScope + IsLocalTemporaryData
Sybase | IsLocalTemporaryScope + IsLocalTemporaryData

2020-10-20 07:26 UTC, ili commented on Source/LinqToDB/TempTable.cs
> +		public static TempTable<T> IntoTempTable<T>(
@igor-tkachev sorry, missed your comment:

- IntoTempTable https://github.com/linq2db/linq2db/pull/2391/files#diff-b9674cc2be27bba1242f41616b7b34c598e717fd273d8e26c2290313dba5a9e8R1118
- IntoTable https://github.com/linq2db/linq2db/pull/2391/files#diff-b9674cc2be27bba1242f41616b7b34c598e717fd273d8e26c2290313dba5a9e8R1145

There are few methods in `TempTable.cs` with name `IntoTable` returning `TempTable<T>` - this is confusing

2020-10-20 14:04 UTC, igor-tkachev commented on Source/LinqToDB/TempTable.cs
> +		public static TempTable<T> IntoTempTable<T>(
The difference is IntoTempTable automatically adds TableOptions.IsTemporary option.

2020-10-21 03:44 UTC, igor-tkachev commented
/azp run test-all

2020-10-21 13:29 UTC, igor-tkachev commented
/azp run test-all

2020-10-22 04:12 UTC, igor-tkachev commented
/azp run test-all

2020-10-23 02:31 UTC, igor-tkachev commented
/azp run test-all

2020-10-24 22:21 UTC, igor-tkachev commented
/azp run test-all

2020-10-25 00:23 UTC, igor-tkachev commented
/azp run test-all

2020-10-25 05:09 UTC, igor-tkachev commented
/azp run test-all

2020-10-26 14:54 UTC, sdanyliv reviewed
There are missing tests for
IntoTempTable(IEnumerable)  
IntoTempTableAsync() - 2 overloads

Missed tests in especially in SelectMany variant
IsTemporary(with boo IsTemporary)
TableOptions()

At least one test for `Insert`, `Update`, `Detete`, `Merge` but with TableOptions and temporary tables.

2020-11-02 15:38 UTC, MaceWindu requested changes

2020-11-02 15:38 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/IDataProvider.cs
> +		TableOptions       SupportedTableOptions { get; }
Do we use it or this property is for informational purposes only?

2020-11-02 15:38 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs
> +			TableOptions.IsLocalTemporaryStructure  |
```suggestion
```

2020-11-02 15:38 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/DB2/DB2DataProvider.cs
> +			TableOptions.IsTransactionTemporaryData |
```suggestion
```

2020-11-02 15:38 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs
> +			TableOptions.IsLocalTemporaryData       |
```suggestion
			TableOptions.IsLocalTemporaryData       |
			TableOptions.IsTransactionTemporaryData |
```

2020-11-02 18:58 UTC, igor-tkachev commented on Source/LinqToDB/TableOptions.cs
> +		/// Table is temporary (table structure is not visible to other sessions). This option will have effect only for databases that support temporary tables.
yes

2020-11-02 19:05 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/IDataProvider.cs
> +		TableOptions       SupportedTableOptions { get; }
For information. I use it in tests.

2020-11-02 19:10 UTC, igor-tkachev commented
/azp run test-all

2020-11-03 02:33 UTC, igor-tkachev commented
/azp list

2020-11-03 02:37 UTC, igor-tkachev commented
/azp run test-all

2020-11-03 04:14 UTC, igor-tkachev commented
/azp run test-all

2020-11-03 13:31 UTC, MaceWindu approved these changes

2020-11-03 23:23 UTC, merged