Add a ConcurrentDictionary cache to back ReflectionExtensions.GetItemType
linq2db/linq2db pull request #2453
Opened 2020-08-29 00:40 UTC by to11mtm

While working on another Library I noticed that calls `ReflectionExtensions.GetItemType` added up in certain cases (Mostly around `Insert<T>` and bulk copies.) With the benchmarks I'm running off a local branch I'm seeing some performance boosts for large series of individual writes.

2020-09-01 12:02 UTC, sdanyliv commented
/azp run test-all

2020-09-01 12:04 UTC, sdanyliv requested changes

2020-09-01 12:04 UTC, sdanyliv commented on Source/LinqToDB/Extensions/ReflectionExtensions.cs
> +					return type.HasElementType ? type.GetElementType() : null;
I think you have to use `t` parameter instead of creating closure,

2020-09-02 00:05 UTC, to11mtm commented on Source/LinqToDB/Extensions/ReflectionExtensions.cs
> +					return type.HasElementType ? type.GetElementType() : null;
Good Catch. Thanks!

2020-09-02 00:22 UTC, to11mtm commented
I'm also seeing some warnings from build due to nullable references, I'll clean those up.

2020-09-03 07:59 UTC, MaceWindu approved these changes

2020-09-03 08:00 UTC, merged