Add MappingSchema MemoryCache to DataConnection
linq2db/linq2db pull request #2496
Opened 2020-09-19 18:18 UTC by to11mtm

Use a MemoryCache for Mapping Schemas added to a DataConnection for reduced GC Pressure.

2020-09-20 13:43 UTC, sdanyliv commented
Have you tested difference in allocations?

2020-09-20 13:47 UTC, sdanyliv commented
/azp run test-all

2020-09-20 15:20 UTC, to11mtm commented
Haven't looked at the raw profiler data yet but based on raw numbers for a test doing 1000 Open->Write1Row->Close:

  - Using Cloned DataConnection for each insert:  3000-3400 msg/Sec
  - Creating DataConnection with Built `Linq2DbOptions` containing mapping schema
      - Before Patch: 2700-3000 msg/Sec
      - After Patch: 2900-3200 msg/Sec

2020-10-05 11:05 UTC, MaceWindu commented
/azp run test-all

2020-10-05 11:08 UTC, MaceWindu requested changes
I like this change, but it breaks scenario where user wants to modify mapping schema only for specific connection instance. At least we should alter comment on this method to reflect new behavior.

2020-10-05 13:03 UTC, MaceWindu commented
/azp run test-all

2020-10-05 22:10 UTC, to11mtm commented
> 
> 
> I like this change, but it breaks scenario where user wants to modify mapping schema only for specific connection instance. At least we should alter comment on this method to reflect new behavior.

Could you explain? I thought that the logic would handle most (sane) use cases since the key is based on the MappingSchema configurationId (unless library user gives different mapping schema same names, auto-increment will handle uniqueness on the rest)

2020-10-06 11:05 UTC, MaceWindu commented
I'm talking about code like that:
```cs
// method1
using(var db = GetConnection())
{
    // do some stuff
}
// method2
using(var db = GetConnection())
{
    // modify mapping schema. as connection instance has own copy of schema, it will not affect other connections
    db.MappingSchema.AddSomething
    // do some stuff
}

```

but such approach is not a "sane" one, that's why I'm fine if we break it

2020-10-06 11:53 UTC, MaceWindu commented
/azp run test-all

2020-10-06 14:40 UTC, MaceWindu commented
/azp run test-all

2020-10-06 15:09 UTC, MaceWindu requested changes
don't merge, miniprofiler-related tests fail

2020-10-07 09:43 UTC, MaceWindu commented
/azp run test-all

2020-10-07 09:44 UTC, MaceWindu approved these changes
tests fixed. We were using different mapping schemas with same name in test and this pr broke this scenario, so I changed mapping schema name in test to be unique.

2020-10-07 09:45 UTC, MaceWindu commented
@sdanyliv , @Shane32 , @viceroypenguin are we good with this change? Need to decide ASAP, as I wan't to finalize next release

2020-10-07 10:03 UTC, viceroypenguin approved these changes

2020-10-07 10:03 UTC, viceroypenguin commented
I'm good with pulling it in.

2020-10-07 10:25 UTC, sdanyliv approved these changes

2020-10-07 13:15 UTC, MaceWindu commented
/azp run test-all

2020-10-07 14:47 UTC, MaceWindu commented
/azp run test-all

2020-10-07 15:12 UTC, Shane32 commented on Source/LinqToDB/Data/DataConnection.cs
> +			var key = new { BaseSchema = MappingSchema.ConfigurationID, AddedSchema = mappingSchema.ConfigurationID };
This could be a value tuple... but C# does define `.Equals` for anonymous types as needed for this use

2020-10-07 15:12 UTC, Shane32 commented on Source/LinqToDB/Data/DataConnection.cs
> +		private static readonly MemoryCache _combinedSchemas = new MemoryCache(new MemoryCacheOptions());
I recommend that we always set the `SizeLimit` option when creating `MemoryCache` instances.  This will require the `Size` property to be set within `GetOrCreate` below.

2020-10-07 15:12 UTC, Shane32 commented on Tests/Linq/Data/MiniProfilerTests.cs
> +				db.AddMappingSchema(new MappingSchema(context));
I'm guessing that a new `MappingSchema` always creates a new `ConfigurationID`.  Assuming so, having a size limit prevents poorly written client code of the above nature (meaning, where they create a new `MappingSchema` for each created `DataConnection`) from adding an unbounded number of entries to the cache (limited only by the sliding expiration).

2020-10-07 15:20 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnection.cs
> +			var key = new { BaseSchema = MappingSchema.ConfigurationID, AddedSchema = mappingSchema.ConfigurationID };
we don't use value tuple in our code to avoid dll hell issue for  users of older .net framework versions

2020-10-07 15:22 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnection.cs
> +		private static readonly MemoryCache _combinedSchemas = new MemoryCache(new MemoryCacheOptions());
If test baselines generation will fail again, I'll look into it, otherwise - we can do it in next release :smile:

2020-10-08 10:45 UTC, merged