Test for #2564
linq2db/linq2db pull request #2565
Opened 2020-10-20 13:52 UTC by jogibear9988

2020-10-20 15:15 UTC, jogibear9988 commented
/azp run test-all

2020-10-20 19:08 UTC, jogibear9988 commented
/azp run test-all

2020-10-20 19:37 UTC, sdanyliv commented
/azp run test-all

2020-10-21 10:15 UTC, jogibear9988 commented
/azp run test-all

2020-10-21 10:23 UTC, jogibear9988 commented
/azp help

2020-10-21 10:26 UTC, jogibear9988 commented
/azp run test-oracle

2020-10-21 10:30 UTC, MaceWindu commented
/azp list

2020-10-21 12:03 UTC, jogibear9988 commented
/azp run test-oracle

2020-10-21 12:19 UTC, jogibear9988 commented
/azp run test-oracle

2020-10-21 12:24 UTC, viceroypenguin approved these changes
LGTM. Check w/ @MaceWindu or @sdanyliv for final approval though

2020-10-21 16:11 UTC, viceroypenguin commented
@jogibear9988  Looks like Oracle treats the difference between two datetime values as a timespan of some sort. You'll need to look at how to convert it on the Oracle side into the individual parts rather than doing the multiply/divide stuff you have right now.

2020-10-21 22:54 UTC, jogibear9988 commented
/azp run test-oracle

2020-10-22 05:47 UTC, jogibear9988 commented
/azp run test-oracle

2020-10-22 12:08 UTC, jogibear9988 commented
@viceroypenguin do I need to do something that the builds do not fail? it sais something about rebase, but i did that

2020-10-22 12:12 UTC, viceroypenguin commented
@jogibear9988 looks like the failures in the last two tests are things @MaceWindu needs to fix since they're part of how the baselines project gets merged. I'll let him review and fix.

2020-10-22 12:13 UTC, viceroypenguin approved these changes

2020-10-24 14:19 UTC, MaceWindu commented
/azp run test-all

2020-10-24 14:22 UTC, MaceWindu requested changes
I don't see detailed tests for new diff implementation. We already have datediff tests so it makes sense to enable them for oracle.

2020-10-24 14:22 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.DateTime.cs
> +					DateParts.Millisecond => "(CAST ({1} as DATE) - CAST ({0} as DATE)) * 86400000",
this doesn't look right. ranges less that day rounded to 1 day?

2020-10-24 14:24 UTC, MaceWindu commented
Ah, didn't noticed you enabled them. let me check once more

2020-10-24 14:44 UTC, MaceWindu requested changes

2020-10-24 14:44 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.DateTime.cs
> +					DateParts.Millisecond => "(CAST ({1} as DATE) - CAST ({0} as DATE)) * 86400000",
Why we use date here? It doesn't work with less that second parts. I suggest to change it to `TIMESPAN` and add corresponding datepart tests as I don't see it in our `DateTimeFunctionsTests`

2020-10-24 14:44 UTC, MaceWindu commented
Ok, this works, but we need to fix milliseconds support

2020-10-25 19:00 UTC, jogibear9988 commented on Source/LinqToDB/Sql/Sql.DateTime.cs
> +					DateParts.Millisecond => "(CAST ({1} as DATE) - CAST ({0} as DATE)) * 86400000",
Don't know what I should do now.
If I cast to timestamp it does not work.
I'm not an oracle expert.

2020-10-25 19:11 UTC, jogibear9988 commented
found this:
http://www.dba-oracle.com/t_timestamp_math_elapsed_times.htm

uses this code

     (extract(hour from tim_col2)-extract(hour from tim_col1))*3600+
       (extract(minute from tim_col2)-extract(minute from tim_col1))*60+
      * extract(second from tim_col2)-extract(second from tim_col1))*1000 ms from check_time

should we switch to this? or make it optional?
it make's not really sense to use this code if DataType is date

2020-10-25 19:14 UTC, jogibear9988 commented
it's also missing day.
so if we use this, the sql get's much complexer (and maybe slower)

2020-10-26 11:26 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.DateTime.cs
> +					DateParts.Millisecond => "(CAST ({1} as DATE) - CAST ({0} as DATE)) * 86400000",
it works (in sql), but produce interval instead of number of days (https://docs.oracle.com/database/121/SQLRF/sql_elements001.htm#g196492), so it timestamp used, additional sql required to convert interval value to number

2020-10-26 11:40 UTC, jogibear9988 commented on Source/LinqToDB/Sql/Sql.DateTime.cs
> +					DateParts.Millisecond => "(CAST ({1} as DATE) - CAST ({0} as DATE)) * 86400000",
yes, I think then we need code like this https://github.com/linq2db/linq2db/pull/2565#issuecomment-716196525
as dates are not with milliseconds, maybe it's possible to leave the code like this.
if someone needs ms support, maybe then he could work on this

2020-10-26 11:42 UTC, jogibear9988 commented on Source/LinqToDB/Sql/Sql.DateTime.cs
> +					DateParts.Millisecond => "(CAST ({1} as DATE) - CAST ({0} as DATE)) * 86400000",
i've no oracle system atm, so i could only test on customer system, and so it takes forever

2020-11-08 06:50 UTC, jogibear9988 commented
@MaceWindu what about this now? could we merge this?
we could create a extra ticket for oracle millisecond support with datetime types

2020-11-08 13:01 UTC, MaceWindu commented
I would prefer to have milliseconds support (we could use other sql only for them). Don't like incomplete features

2020-11-08 14:07 UTC, jogibear9988 commented
me too, but I‘ve no oracle to work at the moment (and no time). at earliest i could work on this in february next year. but i use a fork of linq2db at the moment cause i need that support, what I don‘t like.
ant it works better with the patch then before, also before there was no error that it would not work, there is only incorrect sql.

2020-11-08 14:08 UTC, jogibear9988 commented
maybe we create an extra issue oracle millisecond support, and assign to me. and i look to fix at start of next year

2020-11-08 14:08 UTC, MaceWindu commented
I will check it a bit later today. Shouldn't be a lot of work

2020-11-08 16:52 UTC, MaceWindu commented
ok, oracle support added, also fixed overflow for db2 on large intervals

2020-11-08 16:52 UTC, MaceWindu commented
/azp run test-all

2020-11-08 17:01 UTC, viceroypenguin approved these changes

2020-11-12 22:12 UTC, merged