Add QueryAsync extension methods.
linq2db/linq2db pull request #2589
Opened 2020-11-03 00:33 UTC by perfectsquircle

I may be missing something, but DataConnectionExtensions seems to missing the Async counterparts to `Query<T>(...)` methods. I was a little confused when they didn't show up in intellisense.

![image](https://user-images.githubusercontent.com/5839185/97933867-384b6400-1d31-11eb-9a19-0887f493692f.png)

Let me know if there is a better way to access QueryAsync, or if they're omitted intentionally.

2020-11-03 00:33 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2589) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2589) before we can accept your contribution.<br/><br/>:x: perfectsquircle [sign now](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2589)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/linq2db/linq2db?pullRequest=2589) it.</sub>

2020-11-03 13:37 UTC, MaceWindu requested changes
Thanks. Please add CancellationToken parameter to new methods.

2020-11-04 22:40 UTC, perfectsquircle commented
Ok, updated the PR. Let me know if there's anywhere I should be adding test coverage or documentation.

2020-11-04 23:01 UTC, MaceWindu commented
Looked at those extensions closely and see that it's a bit messy:
-  we already have async versions of those methods in form of `QueryToListAsync` and `QueryToArrayAsync`
- those methods have two versions - with token and without token

@sdanyliv any good reason we implemented it like that?

@perfectsquircle 
if you don't mind - could you add async version for remaining 5 Query methods (9 in total, you added QueryAsync for 4 of them)

Regarding tests - it should be easy to add async version of test using test for sync version but I don't see even sync version of test for most of them, only 3 of 9 methods are tested in DataExtensionTests.cs using following tests TestScalar1, TestScalar2, TestObject2. We would appreciate if you can add both sync and async tests for remaining `Query` methods too.

2020-11-05 13:11 UTC, sdanyliv commented
@MaceWindu, maybe it is better to return `IAsyncEnumerable` for these methods?

2020-11-06 16:30 UTC, perfectsquircle commented
@MaceWindu if you feel like QueryAsync would be redundant with QueryToListAsync and QueryToArrayAsync, that's fine. I'd rather use existing methods than spread the public interface even wider, and making DataConnectionExtensions even bigger.

I can also just do

```csharp
dataConnection.SetCommand("select 123").QueryAsync<int>()
```

2020-11-06 16:30 UTC, closed without merging

2020-11-06 17:06 UTC, MaceWindu commented
It is not like I think it will be redundant, but I agree that we should postpone it for now. You unintentionally rised issue with our async API surface - it is not systematic. Earliest versions of async API provide ToList/ToArray methods, later we started to use Task<IEnumerable> but probably IAsyncEnumerable is correct answer here. Also cancellation token use differ between methods.

We should take timeout to think and decide on async API guidelines. After that we will review/refactor existing API.