Add DateDiff function for Access
linq2db/linq2db pull request #2604
Opened 2020-11-06 19:37 UTC by yarecky1

Fixes #2598

2020-11-06 19:37 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2604) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2604) before we can accept your contribution.<br/><br/>:x: yarecky1 [sign now](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2604)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/linq2db/linq2db?pullRequest=2604) it.</sub>

2020-11-08 10:47 UTC, yarecky1 commented
@sdanyliv OK, Finished.

2020-11-08 10:51 UTC, sdanyliv commented
Enable tests for Access. Just remove exclusion.
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/DateTimeFunctionsTests.cs#L1207

2020-11-08 13:09 UTC, MaceWindu requested changes

2020-11-08 13:09 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.DateTime.cs
> +					DateParts.Millisecond => "s",
as DateDiff for Access doesn't support milliseconds (and access in general), I think we should throw exception for this qualifier (user always could use seconds directly)

2020-11-08 13:11 UTC, MaceWindu commented
/azp list

2020-11-08 13:52 UTC, MaceWindu commented
/azp list

2020-11-08 13:52 UTC, MaceWindu commented
/azp run test-all

2020-11-10 16:04 UTC, MaceWindu commented
/azp run test-all

2020-11-10 16:26 UTC, jogibear9988 commented
I don‘t like that we throw on ms. Cause then you need to maintain different code for different databases, if you like ms precission where it‘s available

2020-11-10 17:30 UTC, viceroypenguin commented
@jogibear9988 Honestly, I would argue that the exception is the proper response. If I am using l2db with one database engine, and then I switch to another to another engine, I would expect that l2db would hide variances where possible and make it visible that the difference is insurmountable. If Access does not support ms, and I am unaware of the nuance of Access, I would want to know up front that Access doesn't support ms, instead of getting a result that is possibly incorrect based on how my code is written.

2020-11-10 22:03 UTC, sdanyliv commented
/azp run test-all

2020-11-12 20:15 UTC, MaceWindu approved these changes

2020-11-12 20:15 UTC, merged