[MiniProvider] Fix datareader expression resolve for wrapped provider
linq2db/linq2db pull request #2627
Opened 2020-11-15 22:21 UTC by MaceWindu

Fix #2499

2020-11-15 22:22 UTC, MaceWindu commented
/ap run test-all

2020-11-15 22:22 UTC, MaceWindu commented
/azp run test-all

2020-11-16 00:18 UTC, viceroypenguin commented on Source/LinqToDB/Linq/DataReaderWrapCache.cs
> +		private static readonly ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, IDataReader>?> _readerMappings = new ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, ID
For the number of times this will change, I was recently introduced to a faster way than `ConcurrentDictionary<,>`. See [here](https://ayende.com/blog/192324-A/always-profile-the-hidden-cost-of-serializing-large-object-graphs-to-json), or proof [here](https://github.com/viceroypenguin/DictionaryBenchmark/blob/master/DictionaryBenchmark/BenchmarkDotNet.Artifacts/results/DictionaryBenchmark.DictionaryTest-report-github.md). Cost is probably negligible, but FYI. No comments from me for using the easier path of `ConcurrentDictionary<,>`, just wanted to offer options.

2020-11-16 00:19 UTC, viceroypenguin approved these changes

2020-11-16 11:01 UTC, MaceWindu commented on Source/LinqToDB/Linq/DataReaderWrapCache.cs
> +		private static readonly ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, IDataReader>?> _readerMappings = new ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, ID
Interesting idea, but I don't see (or missed) statement that dictionary copy constructor is thread-safe

2020-11-16 11:02 UTC, MaceWindu commented
Will be merged later as I want to estimate performance impact of this change

2020-11-16 11:05 UTC, sdanyliv commented on Source/LinqToDB/Linq/DataReaderWrapCache.cs
> +		private static readonly ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, IDataReader>?> _readerMappings = new ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, ID
I don't like static cache. Better to create similar using MemoryCache. We do not know which solution user can use and how many mapping schema can be created. As a key use not MappingSchema itself but its Id.

2020-11-16 11:07 UTC, sdanyliv requested changes
Use `MemoryCache` instead of `ConcurrentDictionary`.

2020-11-16 11:20 UTC, viceroypenguin commented on Source/LinqToDB/Linq/DataReaderWrapCache.cs
> +		private static readonly ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, IDataReader>?> _readerMappings = new ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, ID
@sdanyliv has a good point on MemoryCache, so I'll defer to that for actual advice.

To answer the question, the thread safe is because you create a new dictionary and then assign the dictionary after the fact. It relies on the copy being made before the assignment, so the dictionary exposed by the class field is only ever read from, not written to. It also relies on the being able to generate duplicate values and throw away the lost one, because the race condition means one thread may not get to keep the value it created in the dictionary and that key's value must be regenerated next time through.

2020-11-16 11:22 UTC, MaceWindu commented on Source/LinqToDB/Linq/DataReaderWrapCache.cs
> +		private static readonly ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, IDataReader>?> _readerMappings = new ConcurrentDictionary<Tuple<Type, MappingSchema>, Func<IDataReader, ID
Ah, true.

2020-11-17 00:24 UTC, MaceWindu commented on Source/LinqToDB/Mapping/MappingSchema.cs
>  			var key = new { Type = type, ConfigurationID };
this method was allocating a lot due to being hotpath, now it should be better, as don't allocate closue object here anymore, only key. Wonder if it makes sense to use struct for key here performance-wise.

When we have time, we should mark closure-less lambdas static and try refactor remaining to use context/avoid closures.

2020-11-17 00:24 UTC, MaceWindu commented
/azp run test-all

2020-11-17 00:27 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/MemoryCacheExtensions.cs
> +				// do not want to add the entry to the cache
I'm not sure I understand your comment here. A `using` would always call `.Dispose()`, but even w/ a using, if the factory throws, it won't call `.SetValue()`. Do you not want to call `.Dispose()` if we throw?

2020-11-17 00:33 UTC, viceroypenguin commented on Source/LinqToDB/Mapping/MappingSchema.cs
>  			var key = new { Type = type, ConfigurationID };
I wonder if we should also consider either re-implementing `ValueTuple<>` or revisiting pulling in System.ValueTuple. Neither would be for query use, but would be for key use to reduce allocations in situations like this.

2020-11-17 00:37 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/MemoryCacheExtensions.cs
> +				// do not want to add the entry to the cache
Ah. `entry.Dispose()` is the call that actually plugs the value into the `cache`.

2020-11-17 00:39 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/MemoryCacheExtensions.cs
> +				// do not want to add the entry to the cache
Would the following make more sense?
```csharp
result = factory(entry, key, context);
using (var entry = cache.CreateEntry(key))
  entry.SetValue(result);
```

If we create the entry after we execute the factory, we don't have to worry about whether the entry gets saved into the cache or not.

2020-11-17 00:41 UTC, viceroypenguin approved these changes
Approve in general principle.

2020-11-17 08:29 UTC, sdanyliv approved these changes

2020-11-17 12:42 UTC, MaceWindu commented on Source/LinqToDB/Common/Internal/Cache/MemoryCacheExtensions.cs
> +				// do not want to add the entry to the cache
that's code from MS (https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/MemoryCacheExtensions.cs) and actually I see they changed it 2 month ago due to memory leak issue. Probably we need to sync this code

2020-11-17 12:47 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/MemoryCacheExtensions.cs
> +				// do not want to add the entry to the cache
I still don't see why creating the entry before calling factory makes sense. I wonder if msft is assuming factory won't throw?

2020-11-17 19:35 UTC, MaceWindu commented
/azp run test-all

2020-11-19 21:53 UTC, MaceWindu commented
/azp run test-all

2020-12-15 10:22 UTC, merged