Fix multiple active resultsets per-connection support for supporting providers
linq2db/linq2db pull request #2728
Opened 2020-12-22 13:13 UTC by MaceWindu

Fix #2643

Following providers already supported it:
- DB2
- Oracle (both native and managed providers)
- SQL CE
- SQLite using Microsoft.Data.SQLite
- Sybase using managed AdoNetCore.AseClient provider

Fixed support for following providers:
- SQL Server with MARS enabled
- Access (both OleDb and ODBC providers)
- SAP HANA (native provider)
- SQLite over System.Data.SQLite
- Sybase native provider

Following providers doesn't support it:
- Firebird
- Informix (both IDS and DB2 providers. SQLI not tested, but I'm sure it also doesn't support it)
- MySQL (both MySQL.Data and MySqlConnector)
- npgsql
- SQL Server without MARS
- SAP HANA (ODBC provider)

2020-12-22 13:13 UTC, MaceWindu commented
/azp run test-all

2020-12-22 13:22 UTC, sdanyliv requested changes

2020-12-22 13:22 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/Access/AccessODBCDataProvider.cs
> +			return new CallOnDisposeRegion(() => dataConnection.DisposeCommand());
Avoid not needed closure allocation. Pass dataConnection into constructor. Same places below.

2020-12-22 13:22 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/Sybase/SybaseDataProvider.cs
> +				return new CallOnDisposeRegion(() => dataConnection.DisposeCommand());
Add provider flag for this.

2020-12-22 13:31 UTC, viceroypenguin commented on Tests/Linq/Data/DataConnectionTests.cs
> +		string context)
```suggestion
				string context)
```

2020-12-22 13:32 UTC, viceroypenguin commented on Tests/Linq/Data/DataConnectionTests.cs
> +		string context)
```suggestion
				ProviderName.DB2)] string context)
```

2020-12-22 13:32 UTC, viceroypenguin commented on Tests/Linq/Data/DataConnectionTests.cs
> +		string context)
```suggestion
				ProviderName.DB2)] string context)
```

2020-12-22 13:32 UTC, viceroypenguin approved these changes

2020-12-22 14:46 UTC, MaceWindu commented
- moved command dispose to provider flags
- added recently added provider flags to flags equals/gethashcode
- fixed MARS support for sap hana odbc and informix providers and moved them to supported list

2020-12-22 14:47 UTC, MaceWindu commented
/azp run test-all

2020-12-22 15:23 UTC, MaceWindu commented
on hold, implementation uncovered unexpected expectations in our code to have command object in some places :)

2020-12-22 15:41 UTC, MaceWindu commented
/azp run test-all

2020-12-23 09:20 UTC, MaceWindu commented
moving it to 3.3 as command disposal makes command unavailable on data connection after query and we need to review depending usecases carefully. And maybe introduce some extra API to expose command data in such cases.

2021-01-08 19:30 UTC, bgrainger commented
Following on from https://github.com/npgsql/npgsql/issues/462#issuecomment-756787766:

> PostgreSQL simply doesn't have a mechanism that would allow an efficient MARS implementation.

This is also true for the MySQL database protocol. After a query is sent to the MySQL server by the client, the server starts streaming the entire result set back to the client. Until the "EOF" packet is received (from the server), no other client/server communication can take place. At that point, the first result set is no longer "active", so it's never possible to have _multiple_ active result sets.

The best you can do is buffer all rows in-memory on the client. Due to performance/memory usage concerns, this should be an explicit decision by the application (which can be as simple as `.Query<T>(...).ToList()` in Dapper).

2021-01-11 11:47 UTC, MaceWindu commented
/azp run test-all

2021-01-11 11:58 UTC, MaceWindu commented
Changes to DataConnection.Command.

Because with command disposal and recreation with MARS enabled, DataConnection.Command property becomes less useful and predictable, I've deprecated it alongsize with two other public API for command management:
- `Command {get;set;}`
- `DisposeCommand()`: internal API with public access modifier, replaced with internal `DisposeCurrentCommand()`
- `CreateCommand()`: internal API with public access modifier, replaced with internal `CreateNewCommand()`

Alternatives for disposed APIs:
- access to command parameters: alteady existing `DataConnection.LastParameters` (also fixed T4 generation for stored procedures to use this property)
- access to command SQL: already existing property `DataConnectionLastQuery`
- new `DataConnection.OnCommandInitialized` event added. Event triggered after command initialization and allow command inspection and replacement
- existing `DbCommandProcessorExtensions.Instance` extension point

Other changes:
- following `Command` property deprecation, most of code that used it switched to non-creating `CurrentCommand` property
- fixed `DataConnection.ExecuteNonQuery` to not ignore command parameter
- MARS support disabled by default and hidden behind `Configuration.EnableMultipleActiveResultSetsSupport` option.

2021-01-11 12:28 UTC, viceroypenguin commented on Source/LinqToDB/Common/Configuration.cs
> +		/// execution.
```suggestion
		/// Note that enabling this feature means the <see cref="DataConnection.Command"/> will be
		/// disposed after every command execution.
```

2021-01-11 12:28 UTC, viceroypenguin commented on Tests/Linq/Data/DataConnectionTests.cs
> +						// this query will be executed outside of TransactionScope transaction as it wasn't enlisted into connection
Maybe add another comment that this may be updated per #2676 ?

2021-01-11 12:28 UTC, viceroypenguin commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> +		public bool        SupportsMARSWithNewCommand     { get; set; }
Should be `SupportsMarsWithNewCommand`, per naming convention: "The PascalCasing convention, used for all identifiers except parameter names, capitalizes the first character of each word (including acronyms over two letters in length)" [here](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)

2021-01-11 12:28 UTC, viceroypenguin commented on Source/LinqToDB/Common/Configuration.cs
> +		/// execution.
Also, maybe this sentence goes into the `<remarks>` tag instead of the `<summary>` tag?

2021-01-11 13:29 UTC, MaceWindu commented
/azp run test-all

2021-01-11 16:03 UTC, MaceWindu commented
/azp run test-all

2021-01-11 16:06 UTC, MaceWindu commented
interesting side-effect - when both command and data reader disposed, System.Data.SQLite and native sybase provider clear parameters collection, so LastParameters is empty when mars option enabled.
Which means this option in not compatible with output parameters for stored procedures. Actual only for native sybase provider, so it is not a big deal, but maybe we should copy parameters for this provider with mars enabled?

2021-01-11 16:07 UTC, MaceWindu commented
ADO.NET is fun (not really).

2021-01-11 16:19 UTC, MaceWindu commented
/azp run test-all

2021-01-11 22:39 UTC, sdanyliv commented
@MaceWindu, probably it is better to change `LastParameters` to `DataParameter[]?` type?

2021-01-12 07:35 UTC, MaceWindu commented
@sdanyliv I don't want to allocate array for each query. Taking into account sqlite/sybase providers support I will move command disposal to init phase of next command instead.

2021-01-12 10:04 UTC, MaceWindu commented
/azp run test-sqlite

2021-01-14 09:03 UTC, MaceWindu commented
/azp run test-all

2021-01-16 12:45 UTC, MaceWindu commented
/azp run test-all

2021-01-16 13:41 UTC, MaceWindu commented
/azp run test-all

2021-01-16 15:22 UTC, MaceWindu commented
/azp run test-all

2021-01-16 16:22 UTC, MaceWindu commented
/azp run test-all

2021-01-16 16:59 UTC, MaceWindu commented
/azp run test-all

2021-01-18 13:49 UTC, MaceWindu commented
/azp run test-all

2021-01-18 16:47 UTC, MaceWindu commented
/azp run test-all

2021-01-21 11:36 UTC, MaceWindu commented
/azp run test-all

2021-01-21 12:14 UTC, MaceWindu commented
/azp run test-all

2021-01-21 12:19 UTC, MaceWindu commented
@linq2db, I really want to see this PR in next release if we agree on breaking changes:
- users requre to rerun their T4 templates if they have stored procedures in model
- `DataConnection.Command` property is obsoleted and will contain no data after data reader (select) queries (as it will contain fresh instance of command)

2021-01-21 12:24 UTC, viceroypenguin commented
Depending on how many users have stored procedures in their model (I don't, but I know there are plenty of environments where sprocs are required by DBAs, etc.), #1 is probably enough of a breaking change to require 4.0. I make no opinion on whether _this_ release should be 4.0 vs this waits until we're ready for 4.0; only that this should not be in a point release for the library. Or at least for the .ttinclude packages.

Secondary concern: what about users that use sprocs but don't use the model to generate? Will they be forced to update their hand-generated models?

2021-01-21 12:28 UTC, MaceWindu commented
> what about users that use sprocs but don't use the model to generate? Will they be forced to update their hand-generated models?

if they used `Command` property to access output parameters then yes for two reasons:
- they will get obsolete warnings
- if they used `QueryProc` API, that returns data sets, `Command` will be useless as it will be erased with new instance

2021-01-21 13:22 UTC, viceroypenguin commented
Then I'd say mark `[Obsolete]` for v4 and remove in v5. This requires users to make changes for correct operation, so we should use v4 to indicate to users that they should be aware and make changes if necessary. IMHO. Open to other opinions though.

2021-01-21 15:26 UTC, MaceWindu commented
Ok, then I think we will do following:
- cherrypick various small fixes from this pr (missing ConfigureAwait, DisposeAsync, sybase bulk copy fixes, etc) into 3.3
- create v4 branch, where we will accumulate changes for v4 and configure publishing to azure artifacts

2021-01-22 12:06 UTC, MaceWindu commented
/azp run test-all

2021-01-22 14:55 UTC, MaceWindu commented
Also I'm reverting #86 here, as 1 in `tinyint(1)` for mysql doesn't mean it could have only 1 bit of data.

2021-01-22 14:56 UTC, MaceWindu commented
/azp run test-all

2021-01-23 11:40 UTC, MaceWindu commented
/azp run test-all

2021-01-23 11:47 UTC, MaceWindu commented
/azp run test-all

2021-03-28 14:49 UTC, MaceWindu commented
/azp run test-all

2021-03-28 14:49 UTC, MaceWindu commented
/azp run test-sybase

2021-03-28 15:16 UTC, MaceWindu commented
/azp run test-all

2021-03-28 15:17 UTC, MaceWindu commented
/azp run test-sybase

2021-03-28 15:18 UTC, sdanyliv commented on Source/LinqToDB/Data/DataConnection.QueryRunner.cs
> +	using LinqToDB.DataProvider;
Move inside namespace.

2021-03-28 15:18 UTC, sdanyliv commented on Source/LinqToDB/Data/DataConnection.cs
> +		public event OnCommandInitializedEventHandler? OnCommandInitialized;
Think about interceptors, looks like DataConnection has too much events.

2021-03-28 15:49 UTC, jods4 commented on Source/LinqToDB/Data/DataConnection.cs
> +		public event OnCommandInitializedEventHandler? OnCommandInitialized;
Note that `Command` was useful as an easy way to setup some provider-specific properties in a simple one-shot way for the next query.  For example, set `FetchSize` on an `OracleCommand`.

This would still be possible with `OnCommandInitialized` and is somewhat more intuitive than knowing you could manipulate the next command, but it's also more convoluted.

For a one-shot parameter, you need to subscribe the event, write the actual code, then unsubscribe (ideally in a `finally` block in case something goes wrong but the `DataConnection` can be used further).

Interceptors are a powerful concept but it would be nice to also have a simple API to modify the next query.
For example, maybe:
```csharp
db.NextCommand(c => (c as OracleCommand).FetchSize = 100));
// Do something
db.Table.ToList();
```

2021-04-03 13:42 UTC, MaceWindu commented
Notes on implementation:
- interceptors supported on both `DataConnection` and `DataContext` instances
- interceptors supported by `DataConnection` fluent configuration builder
- to leverage `DataConnection.Command` removal migration issues, mentioned by @jods4 (and to support single query-scoped cases), I've added extensions that provide access to command using one-time interceptors
- while implementation is inspired by `EF.Core` interceptors, it is different, especially in aggregation part to support one-time interceptors
- aggregation, removal and one-time events infrastructure is internal implementation and not exposed to users

2021-04-03 13:43 UTC, MaceWindu commented
/azp run test-all

2021-04-03 13:43 UTC, MaceWindu commented
/azp run test-sybase

2021-04-03 14:48 UTC, MaceWindu commented
As requested I will add one more interceptor to this PR to better demonstrate this functionality

2021-04-03 16:47 UTC, MaceWindu commented
- replaced `OnBeforeConnectionOpen`, `OnBeforeConnectionOpenAsync`, `OnConnectionOpened`, `OnConnectionOpenedAsync` events on `DataConnection` with interceptor.
- I didn't added one-time helpers for those events as I don't see good use-case for them right now
- [functionality degradation]: it was possible to unsubscribe from events but we don't allow interceptor removal. I don't see it as a big isssue without seeing real use-case for it (same as previous entry). Also user could emulate required behavior by setting disable flag it in custom interceptor
- found out that `DataContext.CloseAfterUse` actually wasn't working properly and were disposing connection always. Fixed. We should cherrypick it to master

2021-04-03 16:48 UTC, MaceWindu commented
/azp run test-all

2021-04-03 16:48 UTC, MaceWindu commented
/azp run test-sybase

2021-04-03 19:00 UTC, viceroypenguin commented
> * ~we will copy command parameters to `DataConnection.LastParameters` propery instead of setting it to parameters collection from command. This will preserve last parameters even if command was disposed~ `LastParameters` is gone to Oblivion
> * `DataConnection.Command` property becames even less useful with those changes and even misleading, so we obsolete it (or remove, it this PR will be postponed till v4 release)

Suggestions: Per the above, we should add another PR to `Obsolete` both of these things in 3.4. I'm not opposed to removing in 4.0, given major version num and breaking changes are allowed, but would like to have a little lead time for the (probably rare) users that are using those things.

2021-04-03 19:16 UTC, viceroypenguin commented on Source/LinqToDB/Configuration/LinqToDbConnectionOptions.cs
> +		public List<IInterceptor>?                   Interceptors        { get; }
Question: do we want a user to be able to edit this list after it's been assigned here? Perhaps it should be `IReadOnlyList<>` to indicate inflexibility?

2021-04-03 19:16 UTC, viceroypenguin commented on Source/LinqToDB/Configuration/LinqToDbConnectionOptionsBuilder.cs
> +		public List<IInterceptor>?                   Interceptors        { get; private set; }
Question: do we want a user to be able to edit this list after it's been assigned here? Perhaps we should use a `private List<>` so we can add to it, but public api is `public IReadOnlyList<>? Interceptors => _interceptors;`.

2021-04-03 19:16 UTC, viceroypenguin commented on Source/LinqToDB/Data/CommandInfo.cs
> +						rd.OnBeforeCommandDispose = RebindParameters;
These two lines are repeated throughout the file. Should abstract to `SetRebindParameters(rd);`

2021-04-04 10:26 UTC, MaceWindu commented
> Suggestions: Per the above, we should add another PR to Obsolete both of these things in 3.4.

We cannot obsolete them as we cannot provide alternative in v3 for it

2021-04-04 10:26 UTC, MaceWindu commented
/azp run test-all

2021-04-04 10:26 UTC, MaceWindu commented
/azp run test-sybase

2021-04-05 13:59 UTC, MaceWindu commented
/azp run test-all

2021-04-05 13:59 UTC, MaceWindu commented
/azp run test-sybase

2021-04-05 14:40 UTC, MaceWindu commented
/azp run test-all

2021-04-05 14:40 UTC, MaceWindu commented
/azp run test-sybase

2021-04-07 11:11 UTC, sdanyliv approved these changes

2021-04-07 15:58 UTC, merged