[Feature] Dynamic type handling for Raw Queries.
linq2db/linq2db pull request #2741
Opened 2020-12-28 16:45 UTC by sdanyliv

2020-12-28 16:49 UTC, sdanyliv commented
/azp run test-all

2020-12-28 18:45 UTC, sdanyliv commented
/azp run test-all

2020-12-28 19:58 UTC, Shane32 approved these changes
Looks great!

2020-12-28 19:58 UTC, Shane32 commented on Source/LinqToDB/Data/CommandInfo.cs
> +		static MethodInfo      _expandoAddMethodInfo     = MemberHelper.MethodOf(() => ((IDictionary<string, object>)null!).Add("", ""));
```suggestion
		static readonly ConstructorInfo _expandoObjectConstructor = MemberHelper.ConstructorOf(() => new ExpandoObject());
		static readonly MethodInfo      _expandoAddMethodInfo     = MemberHelper.MethodOf(() => ((IDictionary<string, object>)null!).Add("", ""));
```
readonly?

2020-12-29 09:12 UTC, MaceWindu requested changes

2020-12-29 09:12 UTC, MaceWindu commented on Tests/Linq/Linq/DynamicResultTests.cs
> +		public void DynamicQueryViaDynamic([IncludeDataSources(TestProvName.AllSQLite)] string context, [Values(1, 10)] int param)
add sqlserver 2019 sequential access provider to tests to test CreateDynamicObjectReader

2020-12-29 09:12 UTC, MaceWindu commented on Source/LinqToDB/Data/CommandInfo.cs
> +							additionalKey, isSingleValue: false);
rename isSingleValue to isScalar?

2020-12-29 09:40 UTC, sdanyliv commented on Source/LinqToDB/Data/CommandInfo.cs
> +							additionalKey, isSingleValue: false);
Make sense.

2020-12-29 09:42 UTC, sdanyliv commented on Tests/Linq/Linq/DynamicResultTests.cs
> +		public void DynamicQueryViaDynamic([IncludeDataSources(TestProvName.AllSQLite)] string context, [Values(1, 10)] int param)
I can do that for possible regressions. in the future. But originally algorithm read data exactly in sequential order.

2020-12-29 13:42 UTC, viceroypenguin approved these changes

2020-12-29 14:00 UTC, sdanyliv commented
/azp run test-all

2020-12-29 17:09 UTC, sdanyliv commented
/azp run test-all

2020-12-29 17:41 UTC, sdanyliv commented
/azp run test-all

2020-12-29 17:51 UTC, sdanyliv commented
/azp run test-all

2020-12-29 21:48 UTC, igor-tkachev approved these changes

2020-12-30 09:31 UTC, MaceWindu approved these changes

2021-02-02 16:06 UTC, merged