Lower allocations to improve ConvertBinaryToSql performance
linq2db/linq2db pull request #2774
Opened 2021-01-16 22:21 UTC by to11mtm

When profiling some benchmarks I noticed that there was a lot of traffic around `.ConvertBinaryToSql` (especially in bulk insert scenarios). 

I did some research and adapted [this](https://stackoverflow.com/a/24343727/2937845) into something that worked with StringBuilder.

Doing 'before/after' tests with this change show a pretty big improvement on paths where `.ConvertBinaryToSql` is called (with payloads in the 512b-1kb range, as much as 30% in a library benchmark against fast local IO)

2021-01-17 21:33 UTC, viceroypenguin commented on Source/LinqToDB/Common/StringBuilderExtensions.cs
> +			}
Can you please review and compare if this might be better? I believe that there are optimizations the JIT does on a `foreach` on an array vs using an index.
```suggestion
			foreach (var b in bytes
			{
				var val = lookup32[b];
				sb.Append((char)val);
				sb.Append((char) (val >> 16));
			}
```

2021-01-18 05:22 UTC, to11mtm commented on Source/LinqToDB/Common/StringBuilderExtensions.cs
> +			}
It looks like it's either a wash or a little bit worse. 

On one hand, the generated ASM is essentially identical or only one byte better for the `foreach` version.

On the other hand, `foreach` comes in with ~6 more bytes of IL. I tossed both versions into sharplab:

https://sharplab.io/#gist:360c05b61e74e8c6ecdec7a3ee34797c

2021-01-18 10:01 UTC, MaceWindu commented
BTW, maybe you want to address another issue in this area? When we generate sql statement log, we write parameter values and for binary parameters it generates full literal, which leads to OOM-exception in string builder on big binaries.
There is no big value in binary parameter value logged and I propose to log only first N bytes for it (maybe with some option like `long MaxBinaryParameterLogSize` with -1 for unlimited loging)

2021-01-18 12:01 UTC, viceroypenguin commented on Source/LinqToDB/Common/StringBuilderExtensions.cs
> +			}
Regarding benchmarks: You should always use Benchmark.NET to run benchmarks. The library is written to correctly test micro-benchmarks and has tools to manage various things that can affect benchmark performance. Here's an updated copy of your code w/ Benchmark.NET: http://share.linqpad.net/x3j7fk.linq On my machine, the `foreach` is .1us faster, but within the margin of error. I would say it is worth the difference (given how negligible the difference is) in either direction to have more idiomatic code (i.e. use the `foreach`), but that's my personal opinion.

2021-01-18 12:59 UTC, to11mtm commented on Source/LinqToDB/Common/StringBuilderExtensions.cs
> +			}
>I would say it is worth the difference (given how negligible the difference is) in either direction to have more idiomatic code (i.e. use the foreach), but that's my personal opinion.

I'm fine with switching it to `foreach` given the lack of difference, but if we are adding something like @MaceWindu 's suggested `MaxBinaryParameterLogSize` for SqlText logging purposes we may need to stick with the for loop

2021-01-18 14:17 UTC, to11mtm commented
> 
> 
> BTW, maybe you want to address another issue in this area? When we generate sql statement log, we write parameter values and for binary parameters it generates full literal, which leads to OOM-exception in string builder on big binaries.
> There is no big value in binary parameter value logged and I propose to log only first N bytes for it (maybe with some option like `long MaxBinaryParameterLogSize` with -1 for unlimited logging)

I wouldn't mind giving it an attempt, but peeking at how we are building those out I would have to take a deep dive at things to make sure change only impacts fetching for logging versus when we require the built SQL. May take more time.

Are `.GetSqlText` and/or `PrintParameters` ever used for actual SQL sent To DB and not just debugging/etc? if answer is that they are never used for actually sending for DB, I had idea; in `PrintParameters`, if item is byte array, we could send in either an `ArraySegment` (Net45/etc) or `Span<char>` (NetStandard2.0+) to an overload with the span/segment sliced to appropriate length based on setting.

 - in `PrintParameters`, if item is byte array, use

2021-01-18 14:19 UTC, MaceWindu commented
> Are .GetSqlText and/or PrintParameters ever used for actual SQL sent To DB and not just debugging/etc? 

nope, this is intended for debug/logging only.

2021-01-18 14:20 UTC, MaceWindu commented
It would be nice to have some triming indication in log, like ellipsis after parameter value

2021-01-18 14:50 UTC, to11mtm commented
>  some triming indication in log, like ellipsis after parameter value

I think easiest thing to do at least for `PrintParameters` would be something like this; it avoids having to poke at `ValueToSqlBuilder` too much:

```
foreach (var p in parameters)
				{
					sb.Append("DECLARE ");
					PrintParameterName(sb, p);
					sb.Append(' ');
					PrintParameterType(sb, p);
					sb.AppendLine();

					sb.Append("SET     ");
					PrintParameterName(sb, p);
					sb.Append(" = ");
					if (p.Value is byte[] bytes                           &&
					    bytes.Length > Configuration.MaxByteLengthLogging &&
					    ValueToSqlConverter.CanConvert(typeof(byte[])))
					{
						var trimmed =
							new byte[Configuration.MaxByteLengthLogging];
						Array.Copy(bytes, 0, trimmed, 0,
							Configuration.MaxByteLengthLogging);
						ValueToSqlConverter.TryConvert(sb, trimmed);
						sb.AppendFormat(
							$"-- Truncated for logging, actual length is {bytes.Length}");
					}
					else if (!ValueToSqlConverter.TryConvert(sb, p.Value))
						FormatParameterValue(sb, p.Value);
					sb.AppendLine();
				}
```

2021-01-18 14:59 UTC, to11mtm commented on Source/LinqToDB/Common/StringBuilderExtensions.cs
> +			}
> 
> 
> Regarding benchmarks: You should always use Benchmark.NET to run benchmarks. The library is written to correctly test micro-benchmarks and has tools to manage various things that can affect benchmark performance. Here's an updated copy of your code w/ Benchmark.NET: http://share.linqpad.net/x3j7fk.linq 

BTW thank you for showing me how to use Benchmark.NET in Linqpad... IDK why I never tried it that way.

2021-01-18 15:18 UTC, to11mtm commented
@MaceWindu I think the above would cover the major case? The only things I think it would not cover are:

 - `InlineParameters` I'm assuming would still have problems with this; however I would assume in that case they would still get an OOM executing the SQL anyway, so I think it's not concern
 - If someone inlines a hard coded byte array directly in a query expression, I'm assuming this will not catch it. But I feel like that case is a bit too absurd of a use case to worry about.

2021-01-18 15:24 UTC, MaceWindu commented
If user use binary literals, it's not much we can do about it.
Also could you add `Binary` type support in print parameters?

2021-01-18 17:06 UTC, to11mtm commented
@MaceWindu Can you see if my latest commit works for our needs?

2021-01-19 11:56 UTC, MaceWindu requested changes

2021-01-19 11:56 UTC, MaceWindu commented on Source/LinqToDB/Common/Configuration.cs
> +		public static int MaxByteLengthLogging { get; set; } = 1024;
- add notes that -1 means no-trimming
- not sure it makes sense to have such big limit by default, something around 100 should be enough?
- I would prefer `MaxBinaryLengthLogging` name

Also I think we should handle another unlimited type here: string (with own setting limited to e.g. 200 chars)

2021-01-19 11:56 UTC, MaceWindu commented on Source/LinqToDB/Common/StringBuilderExtensions.cs
> +				string s =i.ToString("X2");
spaces formatting around `=`

2021-01-19 11:56 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +							$"-- Truncated for logging, actual length is {bytes.Length}");
as we print comment below variable, change comment to: `value above truncated for logging, actual length is {bytes.Length}` ?

2021-01-19 17:25 UTC, to11mtm commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +							$"-- Truncated for logging, actual length is {bytes.Length}");
got it

2021-01-19 17:25 UTC, to11mtm commented on Source/LinqToDB/Common/StringBuilderExtensions.cs
> +				string s =i.ToString("X2");
Done.

2021-01-19 17:35 UTC, viceroypenguin commented on Source/LinqToDB/Common/Configuration.cs
> +		public static int MaxStringParameterLengthLogging { get; set; } = 200;
I believe that commentary about specific values belongs in the `<remarks />` tag instead of in the `<summary />` tag. @MaceWindu can correct me if he doesn't like this?
```suggestion
		/// <summary>
		/// Determines the length after which logging of string data in SQL will be truncated.
		/// Truncation is recomended to avoid Out-Of-Memory exceptions when getting SqlText from <see cref="TraceInfo"/>
		/// or <see cref="IExpressionQuery"/> for logging or other purposes.
		/// </summary>
		/// <remarks>
		///  This value defaults to 200. 
		/// Use a value of -1 to disable truncation.
		/// Use a value of 0 to truncate all data.
		/// </remarks>
		public static int MaxStringParameterLengthLogging { get; set; } = 200;
```

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/Common/Configuration.cs
> +using LinqToDB.Linq;
Move `using LinqToDB.Linq;` inside namespace.

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/Access/AccessMappingSchema.cs
> +using LinqToDB.Common;
Move `using LinqToDB.Common;` inside namespace.

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/Firebird/FirebirdMappingSchema.cs
> +using LinqToDB.Common;
Move `using LinqToDB.Common;` inside namespace.

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/SQLite/SQLiteMappingSchema.cs
> +using LinqToDB.Common;
Move `using LinqToDB.Common;` inside namespace.

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/SapHana/SapHanaMappingSchema.cs
> +﻿using LinqToDB.Common;
Move `using LinqToDB.Common;` inside namespace.

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/Sybase/SybaseMappingSchema.cs
> +using LinqToDB.Common;
Move `using LinqToDB.Common;` inside namespace.

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +using LinqToDB.Linq;
Move `using LinqToDB.Linq;` inside namespace.

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +					    Configuration.MaxBinaryParameterLengthLogging >=0 &&
```suggestion
					    Configuration.MaxBinaryParameterLengthLogging >= 0 &&
```

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +					         Configuration.MaxBinaryParameterLengthLogging >=0 &&
```suggestion
					         Configuration.MaxBinaryParameterLengthLogging >= 0 &&
```

2021-01-19 17:37 UTC, sdanyliv commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +					         Configuration.MaxStringParameterLengthLogging >=0 &&
```suggestion
					         Configuration.MaxStringParameterLengthLogging >= 0 &&
```

2021-01-19 17:41 UTC, to11mtm commented on Source/LinqToDB/Common/Configuration.cs
> +		public static int MaxByteLengthLogging { get; set; } = 1024;
> add notes that -1 means no-trimming

Done, along with notes that 0 effectively truncates all data which may be useful in some scenarios.

> not sure it makes sense to have such big limit by default, something around 100 should be enough?

I went with the limit of 100; we may want even less but can tweak in future I'm sure.

> I would prefer MaxBinaryLengthLogging name

I changed up the name a bit, might be a little -too- wordy but wanted clarity, because when I tried naming the other one `MaxStringLengthLogging` felt very confusing, like user might not get a `SqlText` longer than that value. So I settled with `MaxBinaryParameterLengthLogging` and `MaxStringParameterLengthLogging`. We may want to tweak further.

> Also I think we should handle another unlimited type here: string (with own setting limited to e.g. 200 chars)

Done.

2021-01-20 00:41 UTC, viceroypenguin commented
/azp run test-all

2021-01-20 03:26 UTC, to11mtm commented on Source/LinqToDB/Common/Configuration.cs
> +		public static int MaxStringParameterLengthLogging { get; set; } = 200;
I'll defer to you and @MaceWindu on that one.

2021-01-20 03:31 UTC, to11mtm commented
I'm noticing that the .sql files generated by baselines are having bits truncated by this, do we need to make a change in CI somewhere to account for this change?:


https://github.com/linq2db/linq2db.baselines/pull/517/files#diff-65291d4185c3e9839c0e707c97a3debf442d7f9410756d44748bca31f91c74f1R14

2021-01-20 11:06 UTC, MaceWindu commented
I'm fine with baselines values truncation, but I noticed that comment placed after parameter value instead of new line

2021-01-20 17:00 UTC, to11mtm commented
> 
> 
> I'm fine with baselines values truncation, but I noticed that comment placed after parameter value instead of new line

I've corrected so that comment will appear on a new line in these cases.

2021-01-29 00:51 UTC, to11mtm commented
/azp run test-all

2021-01-31 23:20 UTC, to11mtm commented
@MaceWindu anything else on this before I re-dev and merge? I don't want to miss 3.3.0 if possible

2021-02-01 11:14 UTC, MaceWindu approved these changes

2021-02-01 14:36 UTC, sdanyliv approved these changes

2021-02-01 14:37 UTC, viceroypenguin approved these changes

2021-02-02 10:03 UTC, merged