Fix issue 2823 (guid data type suppport for Firebird data provider
linq2db/linq2db pull request #2826
Opened 2021-02-08 19:40 UTC by jack128

Test and fix for #2823

2021-02-08 19:40 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2826) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2826) before we can accept your contribution.<br/><br/>:x: jack128 [sign now](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2826)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/linq2db/linq2db?pullRequest=2826) it.</sub>

2021-02-09 10:19 UTC, MaceWindu requested changes
Thanks! Just fix providers used for test

2021-02-09 10:19 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
> +				case DataType.Guid: StringBuilder.Append("CHAR(16) CHARACTER SET OCTETS");                break;
note to other reviewers: this is correct type for GUID in firebird, e.g. see https://firebirdsql.org/refdocs/langrefupd25-intfunc-gen_uuid.html

2021-02-09 10:19 UTC, MaceWindu commented on Tests/Linq/Linq/IssueTests.cs
> +		public void Issue2823Guid([DataSources(false, ProviderName.AccessOdbc)] string context)
please fix data sources attribute to [IncludeDataSources(true, TestProvName.AllFirebird)]

2021-02-09 13:52 UTC, MaceWindu commented
/azp run test-all

2021-02-10 09:51 UTC, MaceWindu approved these changes
Not directly related, but would be nice to add literal generation for guid. I've added suggested changes to test, so if you want to implement it - check `SetValueToSqlConverter` calls in `FirebirdMappingSchema`

2021-02-10 09:51 UTC, MaceWindu commented on Tests/Linq/Linq/IssueTests.cs
> +		public void Issue2823Guid([IncludeDataSources(true, TestProvName.AllFirebird)] string context)
```suggestion
		public void Issue2823Guid([IncludeDataSources(true, TestProvName.AllFirebird)] string context, [Values] bool useParameters)
```

2021-02-10 09:51 UTC, MaceWindu commented on Tests/Linq/Linq/IssueTests.cs
> +				var guid = Guid.NewGuid();
```suggestion
				db.InlineParameters = !useParameters;
				var guid = Guid.NewGuid();
```

2021-02-10 14:25 UTC, jack128 commented on Tests/Linq/Linq/IssueTests.cs
> +				var guid = Guid.NewGuid();
Well, there is a mess with GUIDs in FB NET Provider due that issue http://tracker.firebirdsql.org/browse/DNET-509, so that will be not so easy. I will try in days.

2021-02-10 14:27 UTC, MaceWindu commented on Tests/Linq/Linq/IssueTests.cs
> +				var guid = Guid.NewGuid();
... I see it's quite popular issue when there is no database type for guid and binary used. microsoft sqlite provider also was hit by it :smile:

2021-02-10 20:48 UTC, jack128 commented on Tests/Linq/Linq/IssueTests.cs
> +				var guid = Guid.NewGuid();
No, I will create new issue for discussion and separated PR, it's too complex theme.

2021-02-11 09:17 UTC, MaceWindu commented
/azp run test-all

2021-02-20 11:52 UTC, MaceWindu requested changes

2021-02-20 11:52 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Firebird/FirebirdMappingSchema.cs
> +			_useLegacyGuidEncoding = (fbConnectionType.Assembly is Assembly assembly) && (assembly.GetName().Version < new Version(6, 0, 0, 0));
This is not a correct way to initialize schema with version-specific behavior.
1. version load should be done in provider adapter (`FirebirdProviderAdapter`)
2. provider instance should configure schema on creation based on version. Check how some other providers do it. E.g. `InformixDataProvider` - they create mapping schema as concatenation of static schema instance and schema with version-specific configuration created by adapter

2021-04-06 07:51 UTC, jack128 commented on Source/LinqToDB/DataProvider/Firebird/FirebirdMappingSchema.cs
> +			_useLegacyGuidEncoding = (fbConnectionType.Assembly is Assembly assembly) && (assembly.GetName().Version < new Version(6, 0, 0, 0));
Fixed

2021-04-06 08:52 UTC, MaceWindu commented
Plan to review it later this week and include into 4.0 preview 1

2021-06-05 13:16 UTC, MaceWindu commented
@jack128 
I've decided to remove workaround for client < 6 as:
- it was applied to literal generation, but from issue description I see that problem is not here but in incorrect read logic. This means we will write incorrect data into database (not talking about situation when user update client)
- even v6 client is quite old and I don't think users should expect seamless work of pre-v6 client

If we really want to fix it on our side, we should register custom reader expression, which will reverse bits after we get data from provider. But don't think it worth doing it now without request from user.

2021-06-05 13:16 UTC, MaceWindu commented
/azp run test-all

2021-06-05 13:17 UTC, MaceWindu commented
/azp run test-all

2021-06-05 13:18 UTC, MaceWindu approved these changes

2021-06-05 14:33 UTC, MaceWindu commented
/azp run test-all

2021-06-05 14:58 UTC, MaceWindu commented
/azp run test-all

2021-06-05 16:34 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
> +				case DataType.Guid: StringBuilder.Append("CHAR(16) CHARACTER SET OCTETS");                break;
Note is accurate. Can we add comment here in code for future reviewers who don't look at this PR specifically?

2021-06-05 16:35 UTC, viceroypenguin approved these changes

2021-06-08 12:30 UTC, sdanyliv approved these changes

2021-06-09 07:47 UTC, merged