Feat: Oracle multi-table insert
linq2db/linq2db pull request #2899
Opened 2021-03-16 23:34 UTC by jods4

This PR implements Oracle multi-table inserts (aka INSERT ALL | FIRST).

AFAIK this is Oracle proprietary syntax that no other RDBMS that I know of implements. Its behavior can't be meaningfully emulated, so I suppose this API should throw on providers other than Oracle **but I haven't included that in PR, I don't know how you want to do this**.

Implementation-wise I took heavy inspiration of MERGE, because the statement structure is quite similar. To avoid duplicating code I even directly reused `MergeSourceQueryContext` (with a very small change to enable re-use); maybe its name should be changed? I tried to stick to the same programming patterns / style as the rest of the codebase. **Please review carefully to check if you can simplify some parts and if I didn't forget any special cases.**

If you want a small console app to quickly test the result, I used this one while developing (doesn't require a real Oracle DB, mocks a connection):
https://github.com/jods4/linq2db/blob/insert-all-tests/Source/TestInsertAll/Program.cs

As previously discussed, I noticed that parameters are duplicated when referenced across different expressions, but that's not unique to this statement. Other LinqToDb statements behave the same.

The API has a single entry point `.MultiInsert()` on a queryable (the source query of multi-insert) and then goes into 3 variants.

## 0. Source query for following examples
```csharp
var q =
  from s in db.GetTable<Src>()
  where s.Cond > 4
  select new { s.N, s.Name, Frob = s.N + s.Cond, Unused = s.Name + "_NOT_USED" };
```

## 1. Unconditional insert
A series of `.Into(table, setter)`, ended by `.InsertAll()`:
```csharp
q.MultiInsert()
  .Into(
    db.GetTable<Dest1>(),
    x => new Dest1 { Name = x.Name ?? param, A = x.N })
  .Into(
    db.GetTable<Dest1>(),
    x => new Dest1 { Name = param + x.Name, A = 42 })
  .Into(
    db.GetTable<Dest2>(),
    x => new Dest2 { X = x.N, Y = 1 - x.Frob })		
  .InsertAll();
```
Resulting SQL
```sql
INSERT ALL
	INTO "Dest1"
	(
		"Name",
		A
	)
	VALUES
	(
		Nvl("Name", :param),
		N
	)
	INTO "Dest1"
	(
		"Name",
		A
	)
	VALUES
	(
		:param_1 || "Name",
		42
	)
	INTO "Dest2"
	(
		X,
		Y
	)
	VALUES
	(
		N,
		1 - "Frob"
	)
SELECT
	s."Name",
	s.N,
	s.N + s."Cond" as "Frob"
FROM
	"Src" s
WHERE
	s."Cond" > 4
```

## 2. Conditional INSERT FIRST
A series of `.When(condition, table, setter)`, possibly ended by `.Else(table, setter)`, ended by `.InsertFirst()`.
```csharp
q.MultiInsert()
  .When(
    x => x.N > 10,
    db.GetTable<Dest1>(),
    x => new Dest1 { Name = x.Name, A = x.N }
  )
  .When(
    x => x.N > 100,
    db.GetTable<Dest1>(),
    x => new Dest1 { Name = "This is crazy!", A = x.Frob }
  )
  .Else(
    db.GetTable<Dest2>(),
    x => new Dest2 { X = 1, Y = x.Frob + 2 }
  )
  .InsertFirst();
```
Result:
```sql
INSERT FIRST
WHEN N > 10
	INTO "Dest1"
	(
		"Name",
		A
	)
	VALUES
	(
		"Name",
		N
	)
WHEN N > 100
	INTO "Dest1"
	(
		"Name",
		A
	)
	VALUES
	(
		'This is crazy!',
		"Frob"
	)
ELSE
	INTO "Dest2"
	(
		X,
		Y
	)
	VALUES
	(
		1,
		"Frob" + 2
	)
SELECT
	s.N,
	s."Name",
	s.N + s."Cond" as "Frob"
FROM
	"Src" s
WHERE
	s."Cond" > 4
```

## 3. Conditional INSERT ALL
Same as 2, but ends with `.InsertAll()`.
```csharp
q.MultiInsert()
  .When(
    x => param.Length > 10,
    db.GetTable<Dest1>(),
    x => new Dest1 { Name = x.Name, A = x.N }
  )
  .When(
    x => x.N > 100,
    db.GetTable<Dest1>(),
    x => new Dest1 { Name = param, A = x.Frob }
  )
  .When(
    x => true,
    db.GetTable<Dest2>(),
    x => new Dest2 { X = 1, Y = x.Frob + 2 }
  )
  .InsertAll();
```
Result:
```sql
INSERT ALL
WHEN :Length > 10
	INTO "Dest1"
	(
		"Name",
		A
	)
	VALUES
	(
		"Name",
		N
	)
WHEN N > 100
	INTO "Dest1"
	(
		"Name",
		A
	)
	VALUES
	(
		:param,
		"Frob"
	)
WHEN 1 = 1
	INTO "Dest2"
	(
		X,
		Y
	)
	VALUES
	(
		1,
		"Frob" + 2
	)
SELECT
	s."Name",
	s.N,
	s.N + s."Cond" as "Frob"
FROM
	"Src" s
WHERE
	s."Cond" > 4
```

2021-03-18 19:23 UTC, sdanyliv commented
Well, accurate code. Will review later.
What is missed: tests. If you want help in tests setup, I'll write small guide.

2021-03-18 19:52 UTC, jods4 commented
@sdanyliv yes... I know, sorry :(

I had no idea how you'd test such a feature. 
Also I have the impression that you test everything against real DB instances and although I'm heavily working with Oracle, I don't have access to an Oracle instance at home where I'm doing this.

You can see that I built this by mocking a DbConnection and looking at the SQL.
A testing strategy could be to snapshot those results (when validated) and then keep running the comparison as a test.
It has the benefit of being much faster than actual end-to-end testing and most testing tool would clearly display what's changing in generated SQL and time you change something in the code.

Feel free to grab the code in my testing branch if that's an approach you'd like.

It's not a small feature so I hope that the work I put in it is still helpful.

2021-03-18 19:56 UTC, jods4 commented
I see the build is failing because of value tuples. 
Are you targeting some platforms where they aren't available?
I used them as an efficient way to pack information without allocations, it would be fairly easy to replace them by a regular struct (or even a class / `Tuple` -- at the cost of more memory allocations).


This is unrelated but I noticed that LinqToDb does an amazing work but is allocating a lot of objects internally and makes some heavy-handed usages of LINQ (which is a very nice API but not the most performant one).

2021-03-18 19:57 UTC, sdanyliv commented
We are trying to avoid ValueTuples. It makes problems with other targets.

2021-03-19 12:12 UTC, MaceWindu commented
> AFAIK this is Oracle proprietary syntax that no other RDBMS that I know of implements.

Yes, from all of supported databases only Oracle has it

2021-03-19 12:19 UTC, sdanyliv requested changes
Well, refactoring is needed. See my comment.

2021-03-19 12:19 UTC, sdanyliv commented on Source/LinqToDB/LinqExtensions.cs
> +
Well, it is bad idea to create such classes. You have to create interfaces and put everything into Expression Tree. And then retrieve information in appropriate Builder. Main reason of this requirement - caching. linq2db will not parse the same Expression Tree twice and just reuse generated SQL - fast like a flash,

2021-03-19 12:20 UTC, sdanyliv commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +			var targets = (List<(LambdaExpression? condition, Expression table, Expression setter)>)((ConstantExpression)methodCall.Arguments[1]).Value;
Avoid ValueTuples

2021-03-19 13:01 UTC, MaceWindu requested changes
Regarding tests I want to see following tests (with assert on resulting data):
- base tests for all operations: unconditional insert into 2 tables, insert all into 2 tables, insert first into 2 tables
- parameters/caching tests: test same operation with different parameter values used in: source, condition, insert setter
- as we use merge as example it makes sense to test with enumerable(non-db) source
- special test cases: reduced condition (1=1), anything else?

You probably will need to create two extra tables for insert targets (for source you probably could use existing pre-filled tables like person).
I will send you invite so you will be able to use `/azp run test-oracle` CI testing (will require you to re-submit PR from our repository)

2021-03-19 15:10 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +				"InsertAllUnconditional" => MultiInsertType.Unconditional,
At home I use VS Code. I'll try to align most code but if you spot something during PR and have an extension to fix it automatically, please just go ahead and modify my branch.

2021-03-19 15:11 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +			return methodCall.IsQueryable("InsertAllUnconditional", "InsertAll", "InsertFirst");
I think the matching is purely done on name, so I'll go with `InsertUnconditional` to take no risk of collision with regular Insert. This method name isn't visible in public API anyway.

2021-03-19 15:12 UTC, jods4 commented on Source/LinqToDB/LinqExtensions.cs
> +		public static MultiInsertableSource<TSource> MultiInsert<TSource>(this IQueryable<TSource> source)
OK I will change, it will simplify 1 or 2 bits.
Note that returning a struct is more efficient (no allocation, no virtual dispatch).

2021-03-19 15:14 UTC, MaceWindu commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +			return methodCall.IsQueryable("InsertAllUnconditional", "InsertAll", "InsertFirst");
Expressions with non-public methods is s something we don't use. This doesn't allow users to build expressions manually.
Ping @sdanyliv

2021-03-19 15:14 UTC, jods4 commented on Source/LinqToDB/LinqExtensions.cs
> +		private static int InsertAllUnconditional(IQueryable source, List<(LambdaExpression? condition, Expression target, Expression setter)> targets)
They are targets for the `MethodInfo` of the resulting `Expression` calls of INSERT ALL. 
This is gonna change anyway because of your request for making an Expression tree for each step of the process.

2021-03-19 15:16 UTC, jods4 commented on Source/LinqToDB/SqlQuery/QueryVisitor.cs
> +						foreach (var insert in multi.Inserts)
I noticed when writing but wasn't sure what to do, can you advise? Because `SqlSearchCondition` is not a `SqlStatement`. Same for the next comment.

2021-03-19 15:19 UTC, MaceWindu commented on Source/LinqToDB/SqlQuery/QueryVisitor.cs
> +						foreach (var insert in multi.Inserts)
Visit2(condition). E.g. check SqlMergeOperationClause visitor implementations  which is quite similar to insert with condition here

2021-03-19 15:19 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +			return methodCall.IsQueryable("InsertAllUnconditional", "InsertAll", "InsertFirst");
There will be some refactoring because of the request to merge conditions and setters in one list. I can probably use the public `InsertAll` for the unconditional one as well.

2021-03-19 15:20 UTC, jods4 commented
Thanks for the feedback, I'll try to make all code changes this week-end.

2021-03-19 15:24 UTC, MaceWindu commented
> This is unrelated but I noticed that LinqToDb does an amazing work but is allocating a lot of objects internally and makes some heavy-handed usages of LINQ (which is a very nice API but not the most performant one).

Yep, something we should improve. If you have some specific scenarios we can take care of - you can add them as benchmarks to benchmarks project so we can look into it (https://github.com/linq2db/linq2db/tree/master/Tests/Tests.Benchmarks/Benchmarks/Queries)

2021-03-19 16:41 UTC, jods4 commented
> Yep, something we should improve. If you have some specific scenarios we can take care of - you can add them as benchmarks to benchmarks project so we can look into it

A problem with allocations in general, is that it's hard to notice improvements in isolated benchmarks. When you're benchmarking a small functionality you can allocate _tons_ before the GC kicks in and you won't even notice it too much.

But when the same code is run in the context of a large application that has heavy load, those allocations can contribute to a much larger memory pressure situation and significantly reduce performance.

Less allocations is always good. How much can you afford before it's too much? ... hard to say 🤷‍♂️

2021-03-19 18:11 UTC, jods4 commented on Source/LinqToDB/SqlQuery/QueryVisitor.cs
> +						foreach (var insert in multi.Inserts)
ok in 06dfe3b

2021-03-19 18:11 UTC, jods4 commented on Source/LinqToDB/SqlQuery/QueryVisitor.cs
> +							Find(((SqlMultiInsertStatement)element).Source                         )  ??
ok in 06dfe3b

2021-03-19 18:17 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/MergeSourceQueryContext.cs
>  	class MergeSourceQueryContext : SubQueryContext
Renamed in e51de6cb
Please note the latter was a public class.
I highly doubt it was used by user code, except maybe in 3rd party data-provider?

2021-03-19 19:13 UTC, jods4 commented on Source/LinqToDB/LinqExtensions.cs
> +		public static MultiInsertableSource<TSource> MultiInsert<TSource>(this IQueryable<TSource> source)
Public API unchanged but refactored to use interfaces in e5213b42
Also added XML docs to every method.

2021-03-19 21:20 UTC, jods4 commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		protected virtual void BuildMultiInsertQuery(SqlMultiInsertStatement statement)
Moved to `Oracle11SqlBuilder` in 1ba53a1d.
For all other providers, `BasicSqlBuilder` now throws `SqlException`.

2021-03-19 21:31 UTC, jods4 commented
A note that just occured to me: I didn't add `InsertAllAsync()` nor `InsertFirstAsync()`.
ODP.NET has no real async implementation (neither `Connect`, `ExecuteReader` or `ExecuteNonQuery`, nothing).

So as long as there is no provider offering multi-table inserts with a real `ExecuteNonQueryAsync` implementation, it makes no sense to add those methods. 
Async over sync implementations is generally considered harmful.

2021-03-20 11:11 UTC, jods4 commented on Source/LinqToDB/LinqExtensions.cs
> +		private static int InsertAllUnconditional(IQueryable source, List<(LambdaExpression? condition, Expression target, Expression setter)> targets)
Removed as part of d78186f8 refactoring

2021-03-20 11:12 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +			var targets = (List<(LambdaExpression? condition, Expression table, Expression setter)>)((ConstantExpression)methodCall.Arguments[1]).Value;
Removed as part of d78186f8 refactoring

2021-03-20 11:13 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +			var targets = (List<(LambdaExpression? condition, Expression table, Expression setter)>)((ConstantExpression)methodCall.Arguments[1]).Value;
Removed as part of d78186f8 refactoring

2021-03-20 11:16 UTC, jods4 commented on Source/LinqToDB/LinqExtensions.cs
> +
Ok, I refactored this in d78186f8

Now `LinqExtensions.MultiInsert.cs` is purely about creating an Expression tree matching the fluent calls.
And all the build up of the final statement is done in `MultiInsertBuilder`.

I have create a new extension class `MultiInsertExtensions` for that purpose, there's a good reason see comment below about `InsertUnconditional` naming.

2021-03-20 11:29 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +			return methodCall.IsQueryable("InsertAllUnconditional", "InsertAll", "InsertFirst");
In the end I used `.Insert()` for the unconditional case (part of d78186f8 refactoring).

@MaceWindu  @sdanyliv 
The way builders work right now is not very robust because they only check names, so every fluent extensions has to be unique.

I really want to use `.Into()` and `.Insert()` as it matches the SQL but that clashes with the `INSERT` fluent builder.

For that reason I created a new extension class `MultiInsertExtensions`, that contains only the multi-table insert stuff.
https://github.com/jods4/linq2db/blob/insert-all/Source/LinqToDB/LinqExtensions.MultiInsert.cs#L9

The nice thing about that is that I can _very easily and quickly_ decide if my builder handles an expression, based _only_ on the declaring class **and** there is no more name clashes with `InsertBuilder`:
https://github.com/jods4/linq2db/blob/insert-all/Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs#L14-L15

I think this is very interesting because finding the right builder for an expression is a hot spot!
In `ExpressionBuilder` there are 61 different builders that are all sequentially tested until the right one is found for _every_ bit of expression that must be converted.
And most of those builders would perform (the same) multiple typing tests on the expression plus compare a whole bunch of strings with method name.
Optimizing this dispatch would be beneficial, I think.
https://github.com/jods4/linq2db/blob/insert-all/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs#L28-L88

As an example, as I put my builder last, building `MultiInsert().Into().Into().Into().Insert()` goes through **305 `CanBuild` checks!!** They are not cheap and this is not even counting the dispatches for building the expressions inside those fluent calls.

2021-03-20 11:32 UTC, jods4 commented on Source/LinqToDB/LinqExtensions.cs
> +
Out of curiosity: how do you quickly find out of an Expression is the same as another one already in cache?

2021-03-20 11:41 UTC, MaceWindu commented
@jods4  actually I think we should add async version from start even if it is not supported now. I dont have high hopes for oracle to add it as they have similar sad story for mysql provider with fake async implementations, but it is more easier to implement it and forget about it than later try to remeber what you need to implement. Also it will not require changes from our side - only provider update.

2021-03-20 17:17 UTC, jods4 commented
@MaceWindu I added the async APIs in 3750be0b.

> I dont have high hopes for oracle to add it

After all this time, me neither. They said they're working on it and that it might come H2 2021, though: 
https://twitter.com/OracleDOTNET/status/1360268585017384970

2021-03-20 17:59 UTC, jods4 commented on Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
> +							var whens        = new List<SqlSearchCondition?>(whensCount);
Done in 2753938f

2021-03-20 18:00 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
> +				"InsertAllUnconditional" => MultiInsertType.Unconditional,
I have tried to align everything nicely.
If I missed something let me know or just go ahead and change it, you can commit on this branch.

2021-03-20 18:11 UTC, jods4 commented
@sdanyliv @MaceWindu I made every change you requested, please have another look.

Each is in its own commit so that you can easily follow along. When you're done we can squash the branch if you want.

Still no tests yet.

2021-03-21 13:14 UTC, jods4 commented
@MaceWindu I added 3 basic E2E tests:

> base tests for all operations: unconditional insert into 2 tables, insert all into 2 tables, insert first into 2 tables

There's one for each variation of the statement (unconditional, first, all), each test has 3 targets.

>  special test cases: reduced condition (1=1), anything else?

I included:
- Inserting 2 lines into the same table;
- When true
- When false

Can you help me finish this? I don't know how to run the tests and check if they actually pass...

Could you fill in those last two cases? I'm not too sure about them.
> - parameters/caching tests: test same operation with different parameter values used in: source, condition, insert setter
> - as we use merge as example it makes sense to test with enumerable(non-db) source

2021-03-22 13:02 UTC, MaceWindu commented
> I don't know how to run the tests
to run tests:
1. you need to be a member of linq2db org (already sent invite to you)
2. pr must be created from this repository

2021-03-22 13:07 UTC, MaceWindu commented
> parameters/caching tests: test same operation with different parameter values used in: source, condition, insert setter

just use test parameter value in query (with `[Values(x, null, z)]` attribute, preferrably nullable type with null value included) and assert results contain proper value in target tables based on parameter value

> as we use merge as example it makes sense to test with enumerable(non-db) source
use `IEnumerable` value as source instead of subquery. Will require addional code

2021-03-22 14:28 UTC, jods4 commented
@MaceWindu 
> pr must be created from this repository

What does it mean exactly? How can I do that when my work is in my own Fork?
Will it delete this PR and we'll loose the review and comments -- or should I open a second PR in parallel to this one?

> use IEnumerable value as source instead of subquery. Will require addional code

What kind of SQL is LinqToDb supposed to generate in that case?
Oracle doesn't have `VALUES ()` tables, should it generate some `FROM DUAL UNION ALL`?
Or does LinqToDb execute the statement once for each record in the enumeration (with a `FROM DUAL`)?

2021-03-22 15:06 UTC, MaceWindu commented
> What does it mean exactly? How can I do that when my work is in my own Fork?
create/merge your current branch to one in linq2db repo and create new PR from it

> What kind of SQL is LinqToDb supposed to generate in that case?
see BuildValuesAsSelectsUnion method https://github.com/linq2db/linq2db/blob/59d927f26d2effa5a460f467bec129bb867b6d41/Source/LinqToDB/SqlProvider/BasicSqlBuilder.Merge.cs#L9

2021-03-22 22:45 UTC, jods4 commented
@MaceWindu 
> as we use merge as example it makes sense to test with enumerable(non-db) source

So I looked into that... Merge is a bit different. 

It starts with a table, then `.Merge()` then `.Using()`, which can be used either with `.Using(IQueryable)` or `.Using(IEnumerable)`.
That source is then formatted in a very ad-hoc way in `BuildValuesAsSelectsUnion` if it was an `IEnumerable`.

Multi-table insert starts with a query: `IQueryable.MultiInsert()`. This structure is actually closer to say `INSERT..SELECT`.
With this syntax, if I wanted to use multiple lines from an array as a source of multi-insert (or even plain insert), I suppose I'd do:
```csharp
var source = new[] 
{
  new { ID = 1, Name = "One" },
  new { ID = 2, Name = "Two" },
};

source
  .AsQueryable(db)
  .MultiInsert()
  .Into(/*...*/)
  .Into(/*...*/)
  .Insert();
```

And that should work without any special support from `MultiInsert`.
Except it does not because `.AsQueryable(db)` only suports scalars:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Builder/ArrayBuilder.cs#L90

Or did I not use the right API? How does `INSERT..SELECT` do it, its API is almost the same?

2021-03-26 10:33 UTC, MaceWindu commented
continuted here #2914

2021-03-26 10:33 UTC, closed without merging