[Feature] TagQuery (TagWith)
linq2db/linq2db pull request #2902
Opened 2021-03-18 20:26 UTC by jlukawska

This PR implements TagWith feature #2903 

Fix #2903

2021-03-19 13:42 UTC, MaceWindu requested changes

2021-03-19 13:42 UTC, MaceWindu commented on Source/LinqToDB/SqlQuery/Tag.cs
> +	public class Tag : IQueryElement, ICloneableElement
all ast classes are prefixed with `Sql`, also this is actually just comment, so we should use generic `SqlComment` name

2021-03-19 13:42 UTC, MaceWindu commented on Source/LinqToDB/SqlQuery/Tag.cs
> +		public QueryElementType ElementType => QueryElementType.Tag;
QueryElementType.Comment;

2021-03-19 13:42 UTC, MaceWindu commented on Source/LinqToDB/SqlQuery/Tag.cs
> +		internal static StringBuilder BuildSql(StringBuilder sb, string? tagValue)
sql generation should be moved to SqlBuilder as it is db-dependent:
- access doesn't support comments
- instead of newline removal we should generate multiple single-line comments or multiline comment if supported

2021-03-22 13:54 UTC, jlukawska commented on Source/LinqToDB/SqlQuery/Tag.cs
> +		internal static StringBuilder BuildSql(StringBuilder sb, string? tagValue)
Ok, I've moved sql generation to BasicSqlBuilder, but it doesn't seem very good to duplicate the code in SqlComment.ToString(). I guess it is called for debugging purposes only?

2021-03-22 15:16 UTC, sdanyliv reviewed
When you move tags from `SelectQuery` to `SqlStatement`. Corect this method:
https://github.com/linq2db/linq2db/blob/8246efebdfbd3a7e5ab838b5425dce80a9147da0/Source/LinqToDB/Linq/Query.cs#L241
Like this
```cs
internal override void Init(IBuildContext parseContext, List<ParameterAccessor> sqlParameters)
{
	var statement = parseContext.GetResultStatement();
	statement.Tags.AddRange(parseContext.Builder.Tags);
	Queries.Add(new QueryInfo
	{
		Statement          = statement,
		ParameterAccessors = sqlParameters,
	});
}
```

2021-03-22 15:16 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/Access/AccessSqlBuilderBase.cs
> +		protected override void BuildTag(SelectQuery selectQuery)
I think we have to add tags to `SqlStatement` base class.

2021-03-22 15:16 UTC, sdanyliv commented on Source/LinqToDB/Linq/Builder/TagQueryBuilder.cs
> +				sequence.SelectQuery.Tag.Parts.Add(tag!);
Move tags to `ExpressionBuilder` class. We will reuse them when building `SqlStatement`.

2021-03-22 15:16 UTC, sdanyliv commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +			BuildStep = Step.Tag;           BuildTag(selectStatement.SelectQuery);
Every `SqlStatement` builders should have this BuildTag call.

2021-03-22 15:16 UTC, sdanyliv commented on Source/LinqToDB/SqlQuery/SelectQuery.cs
> +		public SqlComment       Tag     { get; private set; } = null!;
Move to `SqlStatement`

2021-03-27 14:30 UTC, sdanyliv commented on Source/LinqToDB/LinqExtensions.cs
> +		public static IQueryable<TSource> TagQuery<TSource>(this IQueryable<TSource> source, string tagValue)
```suggestion
		public static IQueryable<TSource> TagQuery<TSource>(this IQueryable<TSource> source, [SqlQueryDependent] string tagValue)
```

2021-03-27 16:39 UTC, MaceWindu commented
I will add my commit today or tomorrow with extra tests and support for new ast element in visitors

2021-03-27 17:11 UTC, MaceWindu commented
@jlukawska 
I've made some changes:
- switched to block comment generation instead of multiple line comments with sanitation of comment test to avoid sql injection
- added tests for all statements (except SqlCreateTableStatement)
- fixed visitors so comment not lost on ast conversion. also requred for remote context serialization to work

Remaining issues (should be easy to fix as they all are similar):
- DropTable has no tag
- InsertOrUpdate has no tag for most of providers
- Insert has no tag for MySql
- TruncateTable has no tag for DB2 and postgresql
- Merge has no tag

2021-03-27 17:12 UTC, MaceWindu commented
/azp run test-all

2021-03-28 11:08 UTC, MaceWindu commented on Tests/Base/TestBase.cs
> +			return CustomTestContext.Get().Get<StringBuilder>(CustomTestContext.BASELINE)?.ToString() ?? string.Empty;
completely forgot that baselines not collected when they are not configured. Would be nice if you will refactor it to collect always and just don't save them if they are not configured

2021-03-30 13:23 UTC, MaceWindu commented
/azp run test-all

2021-03-30 13:26 UTC, jlukawska commented
> Remaining issues (should be easy to fix as they all are similar):
> 
>     * DropTable has no tag
> 
>     * InsertOrUpdate has no tag for most of providers
> 
>     * Insert has no tag for MySql
> 
>     * TruncateTable has no tag for DB2 and postgresql
> 
>     * Merge has no tag

Done almost all things: merge is not ready yet (I want to run merge tests on my machine first).

2021-03-30 13:49 UTC, sdanyliv commented
@jlukawska, do not forge to correct this one https://github.com/linq2db/linq2db/pull/2902/files#r602726103

2021-03-31 15:02 UTC, MaceWindu commented
/azp run test-all

2021-03-31 16:56 UTC, jlukawska commented
I'll fix Oracle failures, but what about Sybase? The error is: "There is no server listening at localhost:5000." Seems that the database server is not able to start.

2021-04-01 07:19 UTC, MaceWindu commented
sybase currently doesn't work (works only for mac, but it is not configured for external PRs)

2021-04-06 12:06 UTC, jlukawska commented on Tests/Base/TestBase.cs
> +			return CustomTestContext.Get().Get<StringBuilder>(CustomTestContext.BASELINE)?.ToString() ?? string.Empty;
@MaceWindu if you say "they are not configured" you mean BaselinePath setting (then it seems to work as you expect) or maybe BASELINE_DISABLED checking?

2021-04-06 12:10 UTC, MaceWindu commented on Tests/Base/TestBase.cs
> +			return CustomTestContext.Get().Get<StringBuilder>(CustomTestContext.BASELINE)?.ToString() ?? string.Empty;
hmm, you are right, looks like it is already collecting baselines and [BaselinesPath](https://github.com/linq2db/linq2db/blob/master/CONTRIBUTING.md#userdataprovidersjson-example-with-description) only enables writing to disk

2021-04-08 11:59 UTC, MaceWindu approved these changes

2021-04-08 11:59 UTC, MaceWindu commented
/azp run test-all

2021-04-09 09:33 UTC, sdanyliv approved these changes

2021-04-09 09:37 UTC, merged