Better nulls handling in Contains
linq2db/linq2db pull request #2949
Opened 2021-04-12 20:15 UTC by jods4

1. There is a new configuration `CheckNullInContains` that controls whether LinqToDb attempts to sniff `null` constants in `Sql.In` arguments and include them in a comparison (with `x IN (1,2) or x IS NULL` and `x NOT IN (1, 2) and x IS NOT NULL`) or if it just translates `Sql.In` with `IN` and SQL semantics apply (so `NULL` inside the list has no effect on the outcome).

I did include client-side support to keep things coherent. This applies to `Sql.In`, but not to `Array.Contains` of course, whose client-side behavior is defined by C#.

I noticed regular LinqToDb code makes use of `Sql.In` internally as a helper method, which isn't great esp. if its exact behaviour depends on user configuration. I did a review of all usages and none passes `null` as a list value, so that's ok.

 2. I fixed a bug in SQL builder where negated IN translated `a not in (1, null)` into `a not in (1) or a is not null` which is incorrect because it's true for `1`. The correct version is `a not in (1) and a is not null`.

3. Added a bunch of tests for those cases.

2021-04-12 20:16 UTC, jods4 commented
/azp run test-all

2021-04-12 20:35 UTC, jods4 commented
One more possible bug that I caught after the PR:
`BuildInListPredicate` starts with:
```csharp
if (p.Values == null || p.Values.Count == 0)
{
	BuildPredicate(new SqlPredicate.Expr(new SqlValue(false)));
}
```
Shouldn't that be `new SqlValue(!IsNot)`?
`x in ()` is false, but shouldn't `x not in ()` be true?

2021-04-12 20:48 UTC, jods4 commented
/azp run test-all

2021-04-12 21:10 UTC, jods4 commented
/azp run test-all

2021-04-13 17:23 UTC, jods4 commented
/azp run test-all

2021-04-14 17:12 UTC, jods4 commented
/azp run test-all

2021-04-14 17:19 UTC, jods4 commented
/azp run test-all

2021-04-14 21:06 UTC, jods4 commented
/azp run test-all

2021-04-14 21:58 UTC, jods4 commented
Here's a summary of the SQL generated by the flags in each possible situation:

### CompareNullsAsValues = true
Same behavior as master, default behavior.
`CheckNullsInContains` is ignored when `CompareNullsAsValues` is true.

| C# | SQL 
|---|---
| `x.In(1, 2)` | `x IN (1, 2)`
| `x.In(1, null)` | `x IN (1) OR x IS NULL`
| `x.NotIn(1, 2)` | `x NOT IN (1, 2) OR x IS NULL`
| `x.NotIn(1, null)` | `x NOT IN (1) AND x IS NOT NULL`

### CompareNullsAsValues = false[, CheckNullsInContains = true]
Same behavior as master, alternative config.
This combination isn't very intuitive, it exists because of back compat.

| C# | SQL 
|---|---
| `x.In(1, 2)` | `x IN (1, 2)`
| `x.In(1, null)` | `x IN (1) OR x IS NULL`
| `x.NotIn(1, 2)` | `x NOT IN (1, 2)`
| `x.NotIn(1, null)` | `x NOT IN (1) AND x IS NOT NULL`

### CompareNullsAsValues = false, CheckNullsInContains = false
New in this PR.
Pure SQL semantics without changes.

| C# | SQL 
|---|---
| `x.In(1, 2)` | `x IN (1, 2)`
| `x.In(1, null)` | `x IN (1, null)`
| `x.NotIn(1, 2)` | `x NOT IN (1, 2)`
| `x.NotIn(1, null)` | `x NOT IN (1, null)`

2021-04-17 10:45 UTC, MaceWindu commented
Do we really need new option? Isn't it better to generate sql based only on `CompareNullsAsValues` and database support for NULL in IN?

2021-04-17 11:46 UTC, jods4 commented
@MaceWindu I agree with you it would be better to base SQL generation on `CompareNullsAsValues` only.

The problem with this is backward compatibility.

You can see all cases in the tables I put above.
In v3.3, you must choose between one of the first 2. 

What I would like is option 3, which is straight SQL without additional clauses.
If we were designing from scratch, I think it could simply replace option 2.

Changing this today would change the SQL codegen of existing users and can break their application if they depend on this.

2021-04-17 12:02 UTC, MaceWindu commented
@jods4 something to change in v4 as part of global options removal work?

2021-04-17 15:50 UTC, jods4 commented
@MaceWindu yes, that sounds like the right time to revamp this. 
Just be careful how much you're willing to break in v4. 
A major version is semantically the right time to do breaking changes, but users will still need to upgrade and the more was changed the harder it'll be for them (although I'm ok with that move).

I still believe this is worthy of being merged in v3.4, even if you remove the new option in v4:
- Users who want SQL semantics can have it right now;
- This PR adds a bunch of tests that I had (have...) a hard time making pass. The semantics of those variations are surprisingly tricky so it's good to have them covered by tests, if only to have a reference for the expected behavior;
- In fact, this PR contains a bug fix in addition to the new option;
- This provides an easier migration path to v4. Users that turn `CheckNullsInContains` off in addition to `CompareNullsAsValues` will be forward compatible with v4.

2021-05-08 12:59 UTC, MaceWindu commented
/azp run test-all

2021-05-08 13:08 UTC, MaceWindu commented on Source/LinqToDB/Tools/SqlExtensions.cs
> +			var comparer = EqualityComparer<T>.Default;
BTW, I was thinking to do the same in memory PR, but isn't it breaking change if T implements custom `Equals` logic?

2021-05-08 13:09 UTC, MaceWindu commented on Source/LinqToDB/Tools/SqlExtensions.cs
> +			var comparer = EqualityComparer<T>.Default;
Not like I'm against it still

2021-05-08 13:12 UTC, viceroypenguin commented on Source/LinqToDB/Tools/SqlExtensions.cs
> +			var comparer = EqualityComparer<T>.Default;
I believe any objects that this would be a breaking change are breaking the equals spec regardless, so technically out of bounds for us to _have_ to worry about. Whether we choose to or not... This, however, it a much more performant method, because it doesn't involve 6 separate boxes for value types, so my vote is firmly for this.

2021-05-08 13:23 UTC, MaceWindu commented
@jods4 I'm struggling to understand rationale behind it.

If I understand what's going on here this option allow user to disable `null` support for `IN` in `CompareNullsAsValues = false` mode (default mode)? Or in other words enables strict `IN` semantics without extra null checks support. Right?

2021-05-08 15:40 UTC, MaceWindu requested changes
one case doesn't work:
`withNullContains: true, withNullCompares: false` generates 
`([s].[Int] NOT IN (-1, 2) OR [s].[Int] IS NULL)`
but should
`[s].[Int] NOT IN (-1, 2)`

2021-05-08 15:41 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +			var checkNull       = Configuration.Linq.CheckNullsInContains || Configuration.Linq.CompareNullsAsValues;
@sdanyliv

2021-05-09 10:02 UTC, jods4 commented
> @jods4 I'm struggling to understand rationale behind it.
> 
> If I understand what's going on here this option allow user to disable `null` support for `IN` in `CompareNullsAsValues = false` mode (default mode)? Or in other words enables strict `IN` semantics without extra null checks support. Right?

Yes, main driver here is to have a mode where the generated SQL is predictable and matches exactly the C# code.

Sometimes this can also be handy because putting `NULL` inside a `IN` expression can be a way to disable a condition without actually removing it (as `in (null)` would never be true).

2021-05-09 10:06 UTC, MaceWindu commented on Source/LinqToDB/Tools/SqlExtensions.cs
> +			var comparer = EqualityComparer<T>.Default;
Hmm, you are right. I thought `EqualityComparer<T>.Default` will not call `Equals`

2021-05-09 10:06 UTC, jods4 commented
> one case doesn't work:
> `withNullContains: true, withNullCompares: false` generates
> `([s].[Int] NOT IN (-1, 2) OR [s].[Int] IS NULL)`
> but should
> `[s].[Int] NOT IN (-1, 2)`

I assume you did `s.Int.NotIn(-1, 2)` ? 
That doesn't match my comment above, so it's probably a bug. I'll look into it and check why it wasn't caught by a test.
https://github.com/linq2db/linq2db/pull/2949#issuecomment-819874784

2021-05-09 11:38 UTC, jods4 commented
> > one case doesn't work:
> > `withNullContains: true, withNullCompares: false` generates
> > `([s].[Int] NOT IN (-1, 2) OR [s].[Int] IS NULL)`
> > but should
> > `[s].[Int] NOT IN (-1, 2)`
> 
> I assume you did `s.Int.NotIn(-1, 2)` ?
> That doesn't match my comment above, so it's probably a bug. I'll look into it and check why it wasn't caught by a test.
> [#2949 (comment)](https://github.com/linq2db/linq2db/pull/2949#issuecomment-819874784)

@MaceWindu I believe this is because I never managed to make my tests work properly.
See this comment I made in Slack:
https://linq2db.slack.com/archives/C9JGUKWD8/p1618436002020600

Basically, everything seems right when ran individually, but I'm seeing codegen from different options when all tests run in CI. 
In this case, code behavior is the one from `predicate.WithNull == true` although `CompareNullsAsValues` is supposed to be false!?!

2022-04-24 12:27 UTC, MaceWindu commented
still needed or we can close and drop branch?

2022-04-24 23:00 UTC, jods4 commented
@MaceWindu This is superseded by #3514, I'm gonna close it.
Can you please not drop the branch before #3514 is all good and merged? Just in case I want to look at what I did in this version.

2022-04-24 23:00 UTC, closed without merging