Fix for #2947. Added support for case sensitive search.
linq2db/linq2db pull request #2952
Opened 2021-04-13 11:45 UTC by sdanyliv

Fixes #2947

2021-04-13 11:45 UTC, sdanyliv commented
/azp run test-all

2021-04-14 08:09 UTC, jack128 commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +			static bool IsIgnoreCase(MethodCallExpression mc)
I tried to fix the issue this way, but run into some cache problem. For example 
```
			StringComparison stringComparison;
			Expression<Func<Model.Person, bool>> GetPredicate(string param) => (Model.Person p) => p.LastName.StartsWith(param, stringComparison);
			using (var db = GetDataContext(context))
			{
				stringComparison = StringComparison.CurrentCultureIgnoreCase;
				db.Person.Any(GetPredicate("pupkin"));
				stringComparison = StringComparison.CurrentCulture;
				db.Person.Any(GetPredicate("pupkin")); // 2
			}
```
 linq2db do not call CreateStringPredicate in line 2 (get it from cache???) and search is case-insensitive

2021-04-25 09:23 UTC, sdanyliv commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +			static bool IsIgnoreCase(MethodCallExpression mc)
Good point, yes probably cache may leverage this. attempt. Will take care in this. part.

2021-05-08 13:43 UTC, MaceWindu commented
/azp run test-all

2021-05-08 14:04 UTC, MaceWindu requested changes

2021-05-08 15:50 UTC, MaceWindu commented
For SQL Server 2019 we use case-sensitive database so tests fail. Which rise interesting issue.
I think we shouldn't depend on default match behavior if user specified comparison mode explicitly.

2021-05-12 12:43 UTC, sdanyliv commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +			static bool IsIgnoreCase(MethodCallExpression mc)
Resolved.

2021-05-15 10:55 UTC, MaceWindu commented
/azp run test-all

2021-05-15 14:33 UTC, MaceWindu commented
/azp run test-all

2021-05-15 14:40 UTC, MaceWindu commented
Clarification on what's going on here. This PR updates SQL, generated for Contains/StartsWith/EndsWith methods with `StringComparison` parameter:

- no changes: for calls without parameter we compare as is: using server comparison logic, db or column collation (which one is set)
- when `StringComparison` parameter set we try to generate explicit case-sensitive or case-insensitive comparison (depends on parameter value)

2021-05-15 16:17 UTC, MaceWindu commented
/azp run test-oracle

2021-05-15 22:19 UTC, viceroypenguin approved these changes

2021-05-16 08:04 UTC, MaceWindu commented
/azp run test-oracle

2021-05-16 11:03 UTC, MaceWindu commented
/azp run test-oracle

2021-05-16 11:37 UTC, MaceWindu commented
/azp run test-oracle

2021-05-16 12:32 UTC, MaceWindu commented
/azp run test-oracle

2021-05-16 13:00 UTC, MaceWindu commented
/azp run test-oracle

2021-05-16 13:21 UTC, MaceWindu commented
/azp run test-oracle

2021-05-16 14:00 UTC, merged