Add Sql.Default<T>()
linq2db/linq2db pull request #2954
Opened 2021-04-15 11:13 UTC by jods4

This PR adds an extension to use the SQL `DEFAULT` keyword.
This keyword can be used as an insert value, for example:
```csharp
db.T.Insert(() => new T 
{
  Id = Sql.Default<int>(),
  Name = "Joe",
});
```
Generates:
```sql
insert into T (id, name)
values (default, "Joe")
```
Default is useful when you need to explicitly insert a non-null value but the DB decides what the value actually is, e.g.:
- Identities, sequences;
- Default constraints;
- Triggers.

2021-04-15 15:22 UTC, sdanyliv commented
Maybe run tests and see which providers will fail?

2021-04-15 15:24 UTC, jods4 commented
I love your optimism 😄

2021-04-15 15:25 UTC, jods4 commented
/azp run test-all

2021-04-15 16:36 UTC, jods4 commented
@sdanyliv looks like you were right, not all providers support this old, standard feature.
Tests aren't complete yet but it seems at least Access and SQLite don't support it, possibly others we'll see when tests are complete.

What's LinqToDb approach when a standard SQL feature isn't supported everywhere?
Do we keep it in and just specify which providers to run the tests for?

2021-04-15 16:41 UTC, sdanyliv commented
Not ready to answer this question. Let's see all failing results.

2021-04-15 17:29 UTC, jods4 commented
Results are in, most RDMB support `default` except:
- SQLite
- Access
- Firebird
- Informix
- SAP Hana

2021-04-17 09:49 UTC, MaceWindu commented
Can confirm test results:
- Access doesn't have `DEFAULT` placeholder: https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/insert-into-statement-microsoft-access-sql
- SQLite has only `DEFAULT VALUES` clause which replaces `VALUES` : https://sqlite.org/lang_insert.html
- Firebird added support for `DEFAULT` in v4: https://tracker.firebirdsql.org/browse/CORE-5449, which is not yet added to CI (#2693)
- Informix doesn't have `DEFAULT`, but have another interesting placeholder `USER` for current user id https://www.ibm.com/docs/en/informix-servers/14.10/14.10?topic=statement-values-clause#ids_sqs_0132
- SAP HANA has no `DEFAULT` too https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/20f7f70975191014a76da70c9181720e.html

2021-04-17 09:50 UTC, MaceWindu requested changes

2021-04-17 09:50 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.cs
> +		public static T Default<T>() => throw new NotImplementedException();
```suggestion
		public static T Default<T>() => throw new LinqException($"{nameof(Default<int>)} is only server-side method.");
```

2021-04-17 09:50 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.cs
> +		public static T Default<T>() => throw new NotImplementedException();
Like in other db-only extensions

2021-04-17 09:50 UTC, MaceWindu commented on Tests/Linq/Update/InsertTests.cs
> +					Gender = Gender.Male,
alignment missing

2021-04-17 09:50 UTC, MaceWindu commented on Tests/Linq/Update/InsertTests.cs
> +		public void InsertDefault([DataSources] string context)
add
```suggestion
		public void InsertDefault([DataSources(TestProvName.AllAccess, TestProvName.AllSQLite, TestProvName.AllFirebird, TestProvName.AllInformix, TestProvName.AllSapHana)] string context)
```

2021-04-17 12:59 UTC, MaceWindu commented
@jods4, as I plan to add firebird4 test provider in #2959 it makes sense to wait for it completed and merged

2021-04-17 15:25 UTC, jods4 commented on Tests/Linq/Update/InsertTests.cs
> +		public void InsertDefault([DataSources] string context)
I think you got it backwards, these are all the providers that do _not_ support this feature.

2021-04-17 15:25 UTC, MaceWindu commented on Tests/Linq/Update/InsertTests.cs
> +		public void InsertDefault([DataSources] string context)
`DataSources` excludes providers, passed as parameter

2021-04-17 15:33 UTC, jods4 commented on Tests/Linq/Update/InsertTests.cs
> +					Gender = Gender.Male,
Done in 9cdb39f

2021-04-17 15:33 UTC, jods4 commented on Tests/Linq/Update/InsertTests.cs
> +		public void InsertDefault([DataSources] string context)
I put the providers that supports DEFAULT in 743c29e

2021-04-17 15:34 UTC, jods4 commented
@MaceWIndu I've done the requested changes, this PR is all ready.
I leave it to you to do the Firebird 4 changes and merge.

2021-04-22 20:54 UTC, jods4 commented on Tests/Linq/Update/InsertTests.cs
> +		public void InsertDefault([DataSources] string context)
> DataSources excludes providers, passed as parameter

Ok from the naming I expected the opposite.
It's actually better that way (e.g. in case you add a new provider).

I reversed the tested providers in 01d27a1.

2021-04-23 08:30 UTC, MaceWindu commented on Tests/Linq/Update/InsertTests.cs
> +			TestProvName.AllFirebird,
```suggestion
			ProviderName.Firebird, TestProvName.Firebird3, 
```

2021-04-23 08:30 UTC, MaceWindu commented on Tests/Linq/Update/InsertTests.cs
> +			TestProvName.AllFirebird,
but you need to merge master with FB4 support for it to work

2021-04-23 12:18 UTC, jods4 commented on Tests/Linq/Update/InsertTests.cs
> +			TestProvName.AllFirebird,
@MaceWindu this PR should be all done with respect to `master`. 
I leave it to you to merge and test it into your FB4 branch. (or feel free to merge the other way round).

2021-04-24 09:45 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.cs
> +		public static T Default<T>() => throw new LinqException($"Default is only server-side method.");
not happy with it, but was forced to remove `nameof` here due to strange `CS8084` error on build ¯\_(ツ)_/¯

2021-04-24 09:46 UTC, MaceWindu commented
/azp run test-all

2021-04-24 09:47 UTC, MaceWindu commented
@jods4 , please don't forget to add `feature`/`issue` prefixes to branches

2021-04-24 09:48 UTC, MaceWindu approved these changes

2021-04-24 12:01 UTC, viceroypenguin approved these changes

2021-04-24 12:53 UTC, merged