Add missing Blob datatype mapping
linq2db/linq2db pull request #2956
Opened 2021-04-15 15:25 UTC by jods4

Just a forgotten mapping that prevents `OracleBlob` from working smoothly.

2021-04-15 15:26 UTC, jods4 commented
/azp run test-all

2021-04-15 15:29 UTC, viceroypenguin approved these changes

2021-04-15 15:37 UTC, sdanyliv commented
Bad that here we have no regression tests.

2021-04-15 15:38 UTC, jods4 commented
I don't know what test to write for this change...

2021-04-15 15:41 UTC, sdanyliv commented
Use existing table `LinqDataTypes`, map new class to this table, at least blob column. And mark this column as `DataType.Blob`.

2021-04-15 16:10 UTC, sdanyliv approved these changes

2021-04-15 16:12 UTC, jods4 commented
I attempted to write a test, let's see if it works.

For context, neither of the 2 statements in the test worked before.
`OracleBlob` was converted to a parameter of type `RAW` and that failed.
Explicit `DataType.Blob` was still converted to a parameter of type `RAW` and failed.

We worked around this in 3.3 by using `DataType.VarBinary`, which feels weird in Oracle but works.

/azp run test-all

2021-04-15 16:12 UTC, jods4 commented
/azp run test-all

2021-04-15 16:18 UTC, sdanyliv commented
/azp run test-oracle

2021-04-16 08:10 UTC, jods4 commented
@sdanyliv Tests are OK except 1 Mac and 2 Linux tests where it says the `LinqDataTypes` table doesn't exist??

2021-04-17 09:14 UTC, MaceWindu reviewed
Fixed table/column names. We use following definition (`oracle.sql`):
```sql
CREATE TABLE "LinqDataTypes"
(
	ID               int,
	"MoneyValue"     decimal(10,4),
	"DateTimeValue"  timestamp,
	"DateTimeValue2" timestamp,
	"BoolValue"      smallint,
	"GuidValue"      raw(16),
	"BinaryValue"    blob         NULL,
	"SmallIntValue"  smallint,
	"IntValue"       int          NULL,
	"BigIntValue"    number(20,0) NULL,
	"StringValue"    VARCHAR2(50) NULL
)
```

2021-04-17 09:14 UTC, MaceWindu commented on Tests/Linq/DataProvider/OracleTests.cs
> +		[Table("LINQDATATYPES", IsColumnAttributeRequired = false)]
```suggestion
		[Table("LinqDataTypes", IsColumnAttributeRequired = false)]
```

2021-04-17 09:14 UTC, MaceWindu commented on Tests/Linq/DataProvider/OracleTests.cs
> +			[Column("BINARYVALUE", DataType = DataType.Blob)]
```suggestion
			[Column("BinaryValue", DataType = DataType.Blob)]
```

2021-04-17 09:14 UTC, MaceWindu commented on Tests/Linq/DataProvider/OracleTests.cs
> +				.Select(x => Sql.Expr<int>("LENGTH(BINARYVALUE)"))
```suggestion
				.Select(x => Sql.Expr<int>("LENGTH(\"BinaryValue\")"))
```

2021-04-17 09:14 UTC, MaceWindu commented
/azp run test-oracle

2021-04-17 09:52 UTC, MaceWindu requested changes

2021-04-17 09:52 UTC, MaceWindu commented on Tests/Linq/DataProvider/OracleTests.cs
> +			inserted.Should().BeSameAs(new[] { 1, 1 });
Assert fails, looks like arrays equality not supported by `BeSameAs`

2021-04-17 15:57 UTC, jods4 commented on Tests/Linq/DataProvider/OracleTests.cs
> +			inserted.Should().BeSameAs(new[] { 1, 1 });
Ok, I tried `.Equal(1, 1)` according to FluentAssertions docs it should work.

2021-04-17 15:57 UTC, jods4 commented
/azp run test-oracle

2021-04-17 19:47 UTC, jods4 commented
@MaceWindu all good now, except Mac tests that timed-out and cancelled... as usual.

2021-04-18 08:41 UTC, MaceWindu approved these changes

2021-04-18 08:41 UTC, merged