Allow Parameter Usage on MultipleRowsCopy/MultipleRowsCopyAsync
linq2db/linq2db pull request #2975
Opened 2021-04-29 17:21 UTC by to11mtm

Allow Parameter usage on MultipleRowsCopy/MultipleRowsCopyAsync via `BulkCopyOptions`. Handles #2144

2021-04-29 17:28 UTC, to11mtm commented on Source/LinqToDB/DataProvider/BasicBulkCopy.cs
> +					}
So, I think this could -possibly- be simplified a little bit. I put `LastRowParameterIndex` and `LastRowStringIndex` into `MultipleRowsHelper` since `.Execute()` is what is clearing out the other bits we are comparing to. I'm not certain whether that is considered better or worse than just tracking those values locally in these functions.

other option to clean up would be `if(CurrentCount > rowcount )`->`else if (needRemoveCondition)`.

2021-05-03 21:51 UTC, to11mtm commented
@viceroypenguin If you get a chance can you beat me up on this one please?

2021-05-04 00:29 UTC, viceroypenguin commented
First thing I would suggest is move the `maxParameters` and `maxSqlText` from `MultipleRowsCopyHelperAsync()` method to `MultipleRowsHelper` constructor. Then you can use `maxParameters` to reduce `MaxBatchSize` as necessary (`BatchSize = Math.Min(Math.Max(10, Options.MaxBatchSize ?? 1000), maxParameters / Columns.Count)`; notice the `-1`). This will remove the need to check for max parameters, since the batch size is implicitly less than max parameters. 

The final concern will be the text length. For that, your current solution will work, though I think you can track `LastRowXxx` as local variables rather than properties on the `Helper` object? There's no way to move that boiler-plate that's copied three times into a common method or pattern is there? Seems like just enough code to screw up editing later and get the three out of sync w/ each other.

2021-05-08 13:23 UTC, to11mtm commented
> 
> 
> First thing I would suggest is move the `maxParameters` and `maxSqlText` from `MultipleRowsCopyHelperAsync()` method to `MultipleRowsHelper` constructor. Then you can use `maxParameters` to reduce `MaxBatchSize` as necessary (`BatchSize = Math.Min(Math.Max(10, Options.MaxBatchSize ?? 1000), maxParameters / Columns.Count)`; notice the `-1`). This will remove the need to check for max parameters, since the batch size is implicitly less than max parameters.
> 

Thank you for the feedback! I'll give that a try. I was trying not to be too aggressive in this PR since next round (i.e. another PR) I'd like to optimize the build stage so that we don't re-build the string/parameter lists. I think to do it well we'll want to re-do the loop.

> The final concern will be the text length. For that, your current solution will work, though I think you can track `LastRowXxx` as local variables rather than properties on the `Helper` object? There's no way to move that boiler-plate that's copied three times into a common method or pattern is there? Seems like just enough code to screw up editing later and get the three out of sync w/ each other.

We might be able to pull out at least some of the logic, challenge is each one is just different enough where more indirection feels like as much cognitive load as the duped code.

But, I think overall the loop structure can be improved at least; Rather than Adding the item, and then checking length to decide whether to back off, we can check length at the start of the iteration and decide what to do. I think it will make the code a little cleaner, and will probably be cleaner as it will have less jumps.

2021-05-08 13:27 UTC, viceroypenguin commented
Definitely agree with re-working to check the length before adding. That would simplify all three back to reasonable levels again and don't need to abstract the three versions of the loop into one. 

Personally, I'd say go ahead and do it, rather than trying to piece-meal in two separate PRs, but that's a personal opinion. On the other hand, if you're going to redo it in a second PR, then what you've got works well enough for now I think.

2021-05-08 13:31 UTC, to11mtm commented
> 
> 
> Definitely agree with re-working to check the length before adding. That would simplify all three back to reasonable levels again and don't need to abstract the three versions of the loop into one.
> 
> Personally, I'd say go ahead and do it, rather than trying to piece-meal in two separate PRs, but that's a personal opinion. On the other hand, if you're going to redo it in a second PR, then what you've got works well enough for now I think.

If I wasn't about to deal with a bunch of release stuff at work that's gonna have me busy for a while I'd agree. :)

Question though, based on your other feedback; Should I put the `MaxParameters`/`MaxSqlText` into `SqlProviderFlags`? I think that may be cleaner overall, but it still raises the question of whether we want to have 'Real' `MaxParameters` or ones that make sense for working in .NET

2021-05-18 01:33 UTC, to11mtm commented
I looked into setting MaxBatchSize based on param usage, it unfortunately gets a little hacky to work-around the behavior of Oracle's Array-parameter copy. Might be better to get what is here into 3.4.0 for now, so I am marking ready to see if there is other feedback or if we must make more changes first.

2021-05-29 14:05 UTC, MaceWindu commented
/azp run test-all

2021-05-29 14:28 UTC, MaceWindu requested changes
Could you provide sources for limits for various providers in comments? I see some of them specified but some not

2021-05-29 14:28 UTC, MaceWindu commented on Source/LinqToDB/Data/BulkCopyOptions.cs
> +		/// Gets or sets whether to Always use Parameters for MultipleRowsCopy.
makes sense to add default value information and behavior in this mode like splitting operation into batches if parameters limit reached for operation.

2021-05-29 14:28 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/BasicBulkCopy.cs
> +		protected virtual int MaxParameters => 999;
I think it makes sense to use those options as not max but as default limits and allow user to override them in bulk copy options. This will allow user to workaround issues with incorrect limits

2021-05-29 14:28 UTC, MaceWindu commented on Tests/Linq/Update/BulkCopyTests.cs
> +		public void UseParametersTest([DataSources(false, ProviderName.DB2)] string context)
What's wrong with DB2?

2021-05-29 14:29 UTC, MaceWindu commented
@to11mtm, we plan to release 3.4 next thursday, it would be nice if we can include this one.

2021-05-29 15:44 UTC, MaceWindu commented
/azp run test-all

2021-05-29 15:46 UTC, to11mtm commented
> 
> 
> Could you provide sources for limits for various providers in comments? I see some of them specified but some not

I'll try to find my notes again. Most came from https://www.jooq.org/doc/3.12/manual/sql-building/dsl-context/custom-settings/settings-inline-threshold/ but for the strings I had to look in some other places.

2021-05-29 15:51 UTC, to11mtm commented on Source/LinqToDB/DataProvider/BasicBulkCopy.cs
> +		protected virtual int MaxParameters => 999;
Are you suggesting a name to something like `DefaultMaxParameters` then? or is this name OK?

2021-05-29 15:51 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/BasicBulkCopy.cs
> +		protected virtual int MaxParameters => 999;
Yep, `DefaultMaxParameters ` sounds good

2021-05-29 19:26 UTC, to11mtm commented
/azp run test-all

2021-05-29 19:26 UTC, to11mtm commented
Looks like Firebird may be mad about coercion of nulls. Looking into that and the DB2 failures

2021-05-30 08:04 UTC, MaceWindu commented
Firebird doesn't use type information from parameter, so you need to add it using CAST to first select of UNION

2021-05-31 19:15 UTC, to11mtm commented
/azp run test-firebird

2021-05-31 19:24 UTC, to11mtm commented
> 
> 
> Firebird doesn't use type information from parameter, so you need to add it using CAST to first select of UNION

Yeah I found FirebirdSqlOptimizer.WrapParameters and cried for a few minutes.

I'm giving it a try with just casts on all rows. Ironically, after our other optimizations to SQL building (i.e. #2774) It appears that at least for SQL Server and maybe postgres, Parameters are slower than our string literals at this point.  my guess/assumption is that the cost of marshaling the parameters is eating away any benefits, and because we aren't treating this as a prepared statement there's no gains to be had there either. My hope is that when myself or someone else does a more thorough refactoring of `BulkCopy` we can address some of this and some of the other cruft in BulkCopy/MultipleRowsHelper.

2021-06-01 22:28 UTC, to11mtm commented
/azp run test-firebird

2021-06-02 08:06 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
> +					if (castParameters)
CAST needed only for first select in union. For other rows db will use type information from first type

2021-06-02 08:07 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
> +						if (!string.IsNullOrEmpty(column.DbType))
can we use sql builder here as it already have db-specific type builder method that takes into account db-specific stuff

2021-06-02 12:06 UTC, to11mtm commented on Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
> +						if (!string.IsNullOrEmpty(column.DbType))
If you could give some pointers on which method to try to use in SQLBuilder I can give it a shot after work.

2021-06-02 12:09 UTC, to11mtm commented on Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
> +					if (castParameters)
Yeah in retrospect I don't think it would hurt to make this `if (castParameters && CurrentCount==0)`. I was over-thinking the jump cost lol.

2021-06-02 12:09 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
> +						if (!string.IsNullOrEmpty(column.DbType))
BuildDataType https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs#L2716
but you need to make it `protected internal`

2021-06-03 00:03 UTC, to11mtm commented
/azp run test-all

2021-06-03 00:06 UTC, to11mtm commented on Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
> +						if (!string.IsNullOrEmpty(column.DbType))
I ran into some challenges here (we are using `ISqlBuilder`, can't cleanly internal on an interface,) so tried to solve for this by adding to ISqlBuilder Interface,  `StringBuilder    BuildDataType        (StringBuilder sb, SqlDataType dataType);`. I went with returning the stringbuilder because that was the convention for BuildTableName, Convert, and others.

2021-06-03 08:41 UTC, MaceWindu commented
/azp run test-all

2021-06-03 08:41 UTC, MaceWindu commented
@to11mtm, if you are interested in working on this area more I have several suggestions for improvements:
- issue, similar to one you fought with Firebird, still exists for parameter-less mode when first data row contains nulls (no type information issue for multiple databases)
- instead of query generation for each batch, we can reuse generated SQL for batches of same size
- it makes sense to investigate new batching feature from .net 6 : https://github.com/dotnet/runtime/issues/28633 . Here I would add that some providers already support it. IIRC SAP HANA provider repeat command if command use less parameters than you passed to command, but it is provider with positional parameters, so it is not a common case

2021-06-03 09:53 UTC, MaceWindu commented
/azp run test-all

2021-06-03 11:03 UTC, MaceWindu commented
/azp run test-all

2021-06-03 12:36 UTC, to11mtm commented
> 
> 
> @to11mtm, if you are interested in working on this area more I have several suggestions for improvements:
> 
>     * issue, similar to one you fought with Firebird, still exists for parameter-less mode when first data row contains nulls (no type information issue for multiple databases)
> 
>     * instead of query generation for each batch, we can reuse generated SQL for batches of same size
> 
>     * it makes sense to investigate new batching feature from .net 6 : [dotnet/runtime#28633](https://github.com/dotnet/runtime/issues/28633) . Here I would add that some providers already support it. IIRC SAP HANA provider repeat command if command use less parameters than you passed to command, but it is provider with positional parameters, so it is not a common case

Yeah, I want to do more work on this in future; My big goal is to have version of BulkCopy that will return inserted Identity columns (issue #2960 ), but it is a bigger refactor because every DB that supports returning on MultipleRows has different rules on how to do this right. 

I started looking into re-using the generated SQL, I think for it to be of actual benefit we will need to do more refactoring. Our stringbuild is pretty efficent as-is, to get a worthwhile benefit I think we would have to also `.Prepare()` the statement, and go a little lower level on re-assigning parameter values (at least some data providers, if you add/remove/reassign `DbParameter` on `DbCommand.Parameters` the `.Prepare()` gets thrown out, you have to ONLY touch the actual Value of the existing `DbParameter` object, if that makes sense.)

2021-06-03 14:10 UTC, MaceWindu commented
/azp run test-all

2021-06-03 14:15 UTC, MaceWindu commented
/azp run test-all

2021-06-03 14:17 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/BasicBulkCopy.cs
> +		protected virtual int MaxSqlLength => 100000;
COuld be usful. In baselines I see increase in number of roundtrips e.g. for DB2

2021-06-03 15:52 UTC, merged