Added two tests that demonstrate a DataContext grouping issue #2937
linq2db/linq2db pull request #2999
Opened 2021-05-13 19:48 UTC by yallie

Hi, this pull request has two unit tests that demonstrate the NullReferenceException
when a query with a grouping is executed by `DataContext`, see issue #2937.

I tried to work around the NRE, but now I'm getting an `ObjectDisposedException` instead:

```csharp
using (var dc = new DataContext(context))
{
    // part1: this part works fine
	var dictionary = dc.GetTable<Person>()
		.GroupBy(p => p.FirstName)
		.ToDictionary(p => p.Key);

    // part2: this part throws an ObjectDisposedException 
	var tables = dictionary.ToDictionary(p => p.Key, p => p.Value.ToList());
}
```

That's because the DataContext's query runner redirects all its calls to the
internal DataConnection's query runner, and the data connection is released 
when the first part is executed and DataContext.ReleaseQuery is called.

Any thoughts how this can be addressed?

2021-05-13 19:49 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2999) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2999) before we can accept your contribution.<br/><br/>:x: yallie [sign now](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2999)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/linq2db/linq2db?pullRequest=2999) it.</sub>

2021-05-13 20:04 UTC, yallie commented
The problem is that `Grouping<TKey,TElement>` takes the query runner in the constructor 
and then later tries to reuse it when the query runner is disposed by the DataContext:

[GroupByBuilder.cs#L280](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Builder/GroupByBuilder.cs#L280)

internal class Grouping<TKey,TElement> : IGrouping<TKey,TElement>
{
	public Grouping(
		TKey                    key,
		IQueryRunner            queryRunner,
		List<ParameterAccessor> parameters,
		Func<IDataContext,TKey,object?[]?,IQueryable<TElement>> itemReader)
	{
        ...
    }
    ...

    List<TElement> GetItems()
	{
        // this one's called when _queryRunner is closed
		using (var db = _queryRunner.DataContext.Clone(true))
		{
			...
        }
    }
}
```

Shouldn't it be done the opposite way? Like, take the data context in the constructor,
then later clone it as needed and get the QueryRunner using dataContextClone.GetQueryRunner?

2021-05-14 05:37 UTC, sdanyliv commented
I would suggest to do grouping on the client side. SQL has limitation, you can get only grouping key and aggregation result.
```cs
var dictionary = dc.GetTable<Person>()
                .AsEnumerable()
		.ToDictionary(p => p.FirstName);
```

2021-05-14 05:56 UTC, yallie commented
@sdanyliv, thanks for the suggestion, I'm aware of this limitation.
We already discussed it in #2937.

I have a large BLToolkit-based application with hundreds of queries written like that.
I'm porting it to Linq2db and I need to make sure that all queries work unchanged.
Unfortunately, I have no control of the queries written by end-users.

2021-05-14 06:01 UTC, yallie commented
This pull request actually works around the issue.
Can you please review my changes?

2021-05-14 06:09 UTC, sdanyliv commented
Yes, sure, later today.

2021-05-14 08:17 UTC, MaceWindu requested changes
Please update tests a bit.
Looks correct. Actually I've already faced similar issue and made changes to DataContext here #2941 for future v4

2021-05-14 08:17 UTC, MaceWindu commented on Tests/Linq/Data/DataExtensionsTests.cs
> +			Configuration.Linq.GuardGrouping = false;
use already existing disposable classes, defined in TestBase for scoped options:
https://github.com/linq2db/linq2db/blob/master/Tests/Base/TestBase.cs#L1412
https://github.com/linq2db/linq2db/blob/master/Tests/Base/TestBase.cs#L1442

2021-05-14 09:20 UTC, MaceWindu approved these changes

2021-05-14 09:21 UTC, MaceWindu commented
/azp run test-all

2021-05-14 10:14 UTC, sdanyliv approved these changes

2021-05-14 10:55 UTC, merged