Allow to use private and protected parameterized constructor for mapping
linq2db/linq2db pull request #3147
Opened 2021-08-02 09:38 UTC by ImoutoChan

This PR adds an ability for linq2db to map data to classes with only private or protected constructors. Before this PR only public ones were supported. 

This case is useful when you want to map data to encapsulated rich models, which often have closed constructors.

We can also consider smartly selecting which constructor to use (most suitable based on field names). Right now it will only work for classes with single constructor.

2021-08-02 09:39 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=3147) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=3147) before we can accept your contribution.<br/><br/>:x: ImoutoChan [sign now](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=3147)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/linq2db/linq2db?pullRequest=3147) it.</sub>

2021-08-02 09:43 UTC, sdanyliv commented
/azp run test-sqlite

2021-08-04 13:01 UTC, ImoutoChan commented
What do you think? Can it be merged?

Or did I break something? I don't see which test is broken.

2021-08-04 13:03 UTC, MaceWindu commented
/azp run test-all

2021-08-04 13:07 UTC, viceroypenguin approved these changes

2021-08-04 13:07 UTC, MaceWindu commented
Thanks!

It's failed because we don't support db-specific tests on external pr, so I need to run all tests.

Regarding implementation, I think it should be changed a bit - first probe public constructors and if there is not match then try non-public. Otherwise it could be a regression for existing types with public and non-public constructors

2021-08-04 13:17 UTC, MaceWindu requested changes
see my comment above

2021-08-04 21:28 UTC, ImoutoChan commented
Thank you for your feedback!

I've changed implementation as suggested to try pubic constructor first. I've added one more test to check this specific case. The failed test should also be fixed now.

2021-08-04 21:31 UTC, sdanyliv approved these changes

2021-08-04 21:31 UTC, sdanyliv commented
/azp run test-all

2021-08-05 08:40 UTC, MaceWindu approved these changes

2021-08-05 08:40 UTC, merged