Query Hint Extensions
linq2db/linq2db pull request #3297
Opened 2021-10-27 00:50 UTC by igor-tkachev

Related topics: #2452, #3247, #1787, #1883, #1545, #2448?, #1276?

# Query Extensions

LinqToDB contains different mechanisms to extend and customize generated SQL. Query Extensions are designed to extend SQL on clause and statement level such as table, join, query hints, etc.

## Common Hint Extensions

The ```QueryExtensionScope``` enumeration defines a scope where this extension is applied to. 

| Value | Method | Applied to | Description |
| --- | --- | --- | --- |
| None | Path through methods | ```IQueryable``` | This type of extension should not generate SQL and can be used to implement path through methods such as ```AsSqlServer()``` that converts ```IQueryable``` sequence to ```ISqlServerSpecificQueryable```. |
| TableHint | ```TableHint```, ```With``` | ```ITable``` | Generates table hints. |
| TablesInScopeHint | ```TablesInScopeHint``` | ```IQueryable``` | This method applies provided hint to all the tables in scope of this method. It is supported by the same database providers as TableHint. |
| IndexHint | ```IndexHint``` | ```ITable``` | MySql supports both hint styles: Oracle Optimizer Hints and SqlServer Table Hints. The TableHint extension generates Oracle hints, whereas this extension supports SqlServer hint style. |
| JoinHint | ```JoinHint``` | ```IQueryable``` | Generates join hints. |
| SubQueryHint | ```SubQueryHint``` | ```IQueryable``` | Generates subquery or statement hints. Supported by PostgreSQL. |
| QueryHint | ```QueryHint``` | ```IQueryable``` | Generates statement hints. |

### TableID method and Sql.SqlID class

Some hints require references to table specifications or aliases. LinqToDB automatically generates table and subquery aliases, so the idea to use generated names for hints is definitely not the best. The ```TableID``` method assigns provided identifier to a table and this ID can be used later to generate references to the table. The following methods can be used as hint parameters to generate table references:

| Method | Description |
| --- | --- |
| ```Sql.TableAlias("id")``` | Generates table alias. |
| ```Sql.TableName("id")``` | Generates table name. |
| ```Sql.TableSpec("id")```| Generates table specification. May include query block name. |

### Naming Query Blocks

Oracle and MySql table-level, index-level, and subquery optimizer hints permit specific query blocks to be named as part of their argument syntax. To create these names, use the following methods:

```c#
AsSubQuery("qb_name")
QueryName("qb_name")
```

### Examples

#### Access

```c#
var q =
(
    from p in db.Parent
    select p
)
.QueryHint(AccessHints.Query.WithOwnerAccessOption);
```

```sql
SELECT
    [p].[ParentID],
    [p].[Value1]
FROM
    [Parent] [p]
WITH OWNERACCESS OPTION
```

#### MySql

```c#
var q =
(
    from p in
        (
            from p in db.Parent.TableID("Pr")
                .TableHint(MySqlHints.Table.NoBka)
                .TableHint(MySqlHints.Table.Index, "PK_Parent")
            from c in db.Child.TableID("Ch")
                .IndexHint(MySqlHints.Table.UseKeyForOrderBy, "IX_ChildIndex", "IX_ChildIndex2")
            select p
        )
        .AsSubQuery("qq")
    select p
)
.QueryHint(MySqlHints.Query.NoBka,  Sql.TableSpec("Pr"), Sql.TableSpec("Ch"))
.QueryHint(MySqlHints.Query.SetVar, "sort_buffer_size=16M");
```

```sql
SELECT /*+ NO_BKA(p@qq) INDEX(p@qq PK_Parent) NO_BKA(p@qq, c_1@qq) SET_VAR(sort_buffer_size=16M) */
    `p_1`.`ParentID`,
    `p_1`.`Value1`
FROM
    (
        SELECT /*+ QB_NAME(qq) */
            `p`.`ParentID`,
            `p`.`Value1`
        FROM
            `Parent` `p`,
            `Child` `c_1` USE KEY FOR ORDER BY(IX_ChildIndex, IX_ChildIndex2)
    ) `p_1`
```

#### Oracle

```c#
var q =
(
    from p in
        (
            from c in db.Child
                .TableHint(OracleHints.Hint.Full)
                .TableHint(OracleHints.Hint.Parallel, "DEFAULT")
            join p in db.Parent
                .TableHint(OracleHints.Hint.DynamicSampling, 1)
                .TableHint(OracleHints.Hint.Index, "parent_ix")
                .AsSubQuery("Parent")
            on c.ParentID equals p.ParentID
            select p
        )
        .AsSubQuery()
    select p
)
.QueryHint(OracleHints.Hint.NoUnnest, "@Parent");
```

```sql
SELECT /*+ FULL(p_1.c_1) PARALLEL(p_1.c_1 DEFAULT) DYNAMIC_SAMPLING(t1@Parent 1) INDEX(t1@Parent parent_ix) NO_UNNEST(@Parent) */
    p_1."ParentID",
    p_1."Value1"
FROM
    (
        SELECT
            p."ParentID",
            p."Value1"
        FROM
            "Child" c_1
                INNER JOIN (
                    SELECT /*+ QB_NAME(Parent) */
                        t1."ParentID",
                        t1."Value1"
                    FROM
                        "Parent" t1
                ) p ON c_1."ParentID" = p."ParentID"
    ) p_1
```

#### PostgreSQL

```c#
var q =
(
    from p in
        (
            from p in
                (
                    from p in db.Parent
                    from c in db.Child
                    where c.ParentID == p.ParentID
                    select p
                )
                .SubQueryHint(PostgreSQLHints.ForUpdate)
                .AsSubQuery()
            where p.ParentID < -100
            select p
        )
        .SubQueryHint(PostgreSQLHints.ForShare)
    select p
)
.SubQueryHint(PostgreSQLHints.ForKeyShare + " " + PostgreSQLHints.SkipLocked);
```

```sql
SELECT
    p_1."ParentID",
    p_1."Value1"
FROM
    (
        SELECT
            p."ParentID",
            p."Value1"
        FROM
            "Parent" p,
            "Child" c_1
        WHERE
            c_1."ParentID" = p."ParentID"
        FOR UPDATE
    ) p_1
WHERE
    p_1."ParentID" < -100
FOR SHARE
FOR KEY SHARE SKIP LOCKED
```

#### SqlCe

```c#
from p in db.Person
    .TableHint(SqlCeHints.Table.Index, "PK_Person")
    .With(SqlCeHints.Table.NoLock)
select p;
```

```sql
SELECT
    [p].[FirstName],
    [p].[PersonID],
    [p].[LastName],
    [p].[MiddleName],
    [p].[Gender]
FROM
    [Person] [p] WITH (Index(PK_Person), NoLock)
```

#### SQLite

```c#
from p in db.Person.TableHint(SQLiteHints.Hint.IndexedBy("IX_PersonDesc"))
where p.ID > 0
select p;
```

```sql
SELECT
    [p].[FirstName],
    [p].[PersonID],
    [p].[LastName],
    [p].[MiddleName],
    [p].[Gender]
FROM
    [Person] [p] INDEXED BY IX_PersonDesc
WHERE
    [p].[PersonID] > 0
```

#### SqlServer

```c#
var q =
(
    from c in db.Child
        .TableHint(SqlServerHints.Table.SpatialWindowMaxCells(10))
        .IndexHint(SqlServerHints.Table.Index, "IX_ChildIndex")
    join p in
        (
            from t in db.Parent.With(SqlServerHints.Table.NoLock)
            where t.Children.Any()
            select new { t.ParentID, t.Children.Count }
        )
        .JoinHint(SqlServerHints.Join.Hash) on c.ParentID equals p.ParentID
    select p
)
.QueryHint(SqlServerHints.Query.Recompile)
.QueryHint(SqlServerHints.Query.Fast(10))
.QueryHint(SqlServerHints.Query.MaxGrantPercent(25));
```

```sql
SELECT
    [p].[ParentID],
    [p].[Count_1]
FROM
    [Child] [c_1] WITH (SPATIAL_WINDOW_MAX_CELLS=10, Index(IX_ChildIndex))
        INNER HASH JOIN (
            SELECT
                [t].[ParentID],
                (
                    SELECT
                        Count(*)
                    FROM
                        [Child] [t1]
                    WHERE
                        [t].[ParentID] = [t1].[ParentID]
                ) as [Count_1]
            FROM
                [Parent] [t] WITH (NoLock)
            WHERE
                EXISTS(
                    SELECT
                        *
                    FROM
                        [Child] [t2]
                    WHERE
                        [t].[ParentID] = [t2].[ParentID]
                )
        ) [p] ON [c_1].[ParentID] = [p].[ParentID]
OPTION (RECOMPILE, FAST 10, MAX_GRANT_PERCENT=25)
```

## Database Specific Hint Extensions

The extension methods above are common and can be used to generate SQL for all  [...]

2021-10-29 22:21 UTC, igor-tkachev commented
/azp run test-all

2021-10-31 21:33 UTC, igor-tkachev commented
/azp run test-all

2021-11-01 14:06 UTC, igor-tkachev commented
/azp run test-all

2021-11-01 14:50 UTC, igor-tkachev commented
/azp run test-all

2021-11-25 23:55 UTC, igor-tkachev commented
/azp run test-all

2021-11-28 23:37 UTC, igor-tkachev commented
/azp run test-all

2021-11-29 14:47 UTC, igor-tkachev commented
/azp run test-all

2021-11-29 16:18 UTC, igor-tkachev commented
/azp run test-all

2021-11-30 19:00 UTC, igor-tkachev commented
/azp run test-all

2021-12-07 20:43 UTC, igor-tkachev commented
/azp run test-all

2021-12-10 23:06 UTC, igor-tkachev commented
/azp run test-all

2021-12-11 20:19 UTC, igor-tkachev commented
/azp run test-all

2021-12-14 04:11 UTC, igor-tkachev commented
/azp run test-all

2021-12-14 18:22 UTC, igor-tkachev commented
/azp run test-all

2021-12-14 20:28 UTC, sdanyliv commented
/azp run test-all

2021-12-15 19:19 UTC, igor-tkachev commented
/azp run test-all

2021-12-16 20:15 UTC, sdanyliv commented
There is needs to specify Temporal hints. 

- SQL Server [Temporal Tables](https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver15)
- Oracle [FlashBack query](https://docs.oracle.com/cd/E11882_01/appdev.112/e41502/adfns_flashback.htm#ADFNS01004)

Probably in separate PR, but keep in mind how to do that.

2021-12-28 08:34 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs
> +					var hint = (SqlValue)ext.Arguments["hint"];
Maybe define constant for it? I see it used in multiple places.

2021-12-30 17:58 UTC, jods4 commented
@igor-tkachev Thanks so much for that, it's a really useful feature!
I have some complex Oracle queries where removing hints is the difference between 10s and 1h+ execution times...

I'm currenty on holidays but I'll have a look when I'm back at work to see if I could build the equivalent queries with the proposed API. You can ping me if I forget!

Happy holidays and thank you all for this awesome lib 🎄🥳

2022-01-02 06:20 UTC, igor-tkachev commented
/azp run test-all

2022-01-02 21:31 UTC, igor-tkachev commented
/azp run test-postgresql

2022-01-03 19:55 UTC, igor-tkachev commented
/azp run test-all

2022-01-03 22:05 UTC, igor-tkachev commented
/azp run test-all

2022-01-03 22:15 UTC, igor-tkachev commented
/azp run test-all

2022-01-06 18:43 UTC, igor-tkachev commented
/azp run test-all

2022-01-07 01:57 UTC, igor-tkachev commented
/azp run test-all

2022-01-07 13:15 UTC, MaceWindu requested changes
First part of code review

2022-01-07 13:15 UTC, MaceWindu commented on Source/LinqToDB/ServiceModel/RemoteDataContextBase.cs
> +					var dp   = (IDataProvider)Activator.CreateInstance(type);
Not really happy with this change...
With it user will need provider binaries on client side for it to work. For heavy unmanaged providers (or providers not supported on client platform) it will be a big issue.
As I can understand it is done to simplify SqlBuilder creation. If so, it would be better to pass null to sqlbuilder constructor instead of provider.

And in case we decide to go with this new approach and create provider here - it will be better to create only one instance, not per remote context instance.

2022-01-07 13:20 UTC, MaceWindu commented
BTW, taking into account changes to providers/sqlbuilders PR should target v4 and rebased on dev.4 branch

2022-01-07 14:35 UTC, MaceWindu commented
Missing(?) providers support:
- `Access`: I found only this query [option](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/with-owneraccess-option-declaration-microsoft-access-sql). Not clear if it even makes sense to implement, up to you
- `DB2 LUW`: various options, e.g. in [`select`](https://www.ibm.com/docs/en/db2/11.5?topic=queries-select-statement)
- `DB2 z/OS`: various options, e.g. in [`select`](https://www.ibm.com/docs/en/db2-for-zos/12?topic=queries-select-statement)
- `Firebird`: I see [here](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html) following candidates: [`WITH LOCK`](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-dml-with-lock), [`PLAN`](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-dml-select-plan), [`FOR UPDATE`](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref-dml-for-update)
- `Informix`: at least [optimizer directives](https://www.ibm.com/docs/en/informix-servers/14.10?topic=segments-optimizer-directives) supported, but I also see [`FOR READ ONLY / UPDATE`](https://www.ibm.com/docs/en/informix-servers/14.10?topic=statements-select-statement) hints in statements syntax
- `MariaDB`: makes sense to check if `MariaDB` has own options, absent in MySQL https://mariadb.com/kb/en/selecting-data/
- `SAP HANA`: also have [`for update, etc`](https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.05/en-US/20fcf24075191014a89e9dc7b8408b26.html) clauses and `WITH HINT(...)`
- `ASE`: a lot of stuff, e.g. in [`select`](https://help.sap.com/viewer/e0d4539d39c34f52ae9ef822c2060077/16.0.4.1/en-US/ab3e9a97bc2b10149c02ff1c52f92cb4.html)

2022-01-07 17:18 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Access/AccessODBCSqlBuilder.cs
> +			if (Provider is AccessODBCDataProvider provider)
I am not sure I want to leave it like this. The reason why the SqlBuilder did not have reference to DataProvider is old design that came from BLToolkit to support LINQ over WCF. I am going to review this all later.

2022-01-08 20:50 UTC, igor-tkachev commented on Source/LinqToDB/ServiceModel/RemoteDataContextBase.cs
> +					var dp   = (IDataProvider)Activator.CreateInstance(type);
I agree. This part needs to be redesigned anyway. I would move all the remote stuff from main project to Tools or something. So, lets get it back for now.

2022-01-08 20:57 UTC, igor-tkachev commented on Tests/Linq/Linq/TableIDTests.cs
> +		//[Test]
Not finished yet.

2022-01-08 21:10 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/DatabaseSpecificQueryable.cs
> +		{
IEnumerable heritage. 

```c#
public interface IEnumerable<out T> : IEnumerable
{
    IEnumerator<T> GetEnumerator();
}

public interface IEnumerable
{
    IEnumerator GetEnumerator();
}
```

2022-01-08 21:20 UTC, igor-tkachev commented
@sdanyliv also mentioned Oracle Flashback and SqlServer temporal tables support

https://docs.oracle.com/cd/E11882_01/appdev.112/e41502/adfns_flashback.htm#ADFNS1008
https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver15

It is not hint related, however it can be now easily implemented with QueryExtensions.

2022-01-08 21:23 UTC, igor-tkachev commented
/azp run test-all

2022-01-08 21:26 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Access/AccessODBCSqlBuilder.cs
> +			if (Provider is AccessODBCDataProvider provider)
Switched back to nullable provider.

2022-01-08 23:49 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs
> +		private static readonly ConcurrentQueue<SqlServerDataProvider> _providers = new();
fixed

2022-01-10 11:01 UTC, MaceWindu commented on Tests/Linq/Tests.csproj
> +	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
duplicate entry

2022-01-10 13:42 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +				return $"MAX_EXECUTION_TIME({value})";
use invariant culture for int->string conversion

2022-01-10 13:44 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +		public static IQueryable<TSource> QueryBlockHint<TSource, TParam>(
Why this method is in `MySqlHints`. From first sight I don't see anything mysql-specific here

2022-01-10 13:47 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
> +				return $"FIRST_ROWS({value})";
use invariant culture to format numbers

2022-01-10 13:50 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
> +		// Not implemented:
maybe add details why it is not implemented?

2022-01-10 13:51 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +		[Sql.QueryExtension(ProviderName.MySql, Sql.QueryExtensionScope.QueryHint, typeof(HintWithParametersExtensionBuilder), " ", ", ")]
Does it need `NoneExtensionBuilder` as extension in Oracle Hints class?

2022-01-10 15:33 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +				return "SPATIAL_WINDOW_MAX_CELLS=" + value;
use invariant culture for numbers formatting

2022-01-10 15:46 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +			public const string KeepPlan                           = "KEEP PLAN   ";
why it has spaces?

2022-01-10 15:46 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +				return "SPATIAL_WINDOW_MAX_CELLS=" + value;
same for other int/decimal values below

2022-01-10 16:39 UTC, MaceWindu commented on Source/LinqToDB/LinqExtensions.cs
> +		/// <returns>Query covered in sub-query.</returns>
here and in other places: `covered` -> `converted` ?

2022-01-10 16:46 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.QueryExtensionAttribute.cs
> +		public class QueryExtensionAttribute : Attribute
xml-doc needed on public API

2022-01-10 16:50 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.TableID.cs
> +				Type = type;
formatting

2022-01-10 16:53 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.TableID.cs
> +			public bool Equals(SqlID other)
is it needed? it's struct so by-value comparison already here

2022-01-11 03:11 UTC, igor-tkachev commented on Tests/Linq/Tests.csproj
> +	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
fixed

2022-01-11 03:11 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +				return $"MAX_EXECUTION_TIME({value})";
fixed

2022-01-11 03:12 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
> +				return $"FIRST_ROWS({value})";
fixed

2022-01-11 03:12 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +				return "SPATIAL_WINDOW_MAX_CELLS=" + value;
fixed

2022-01-11 03:13 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +			public const string KeepPlan                           = "KEEP PLAN   ";
fixed

2022-01-11 03:23 UTC, igor-tkachev commented on Source/LinqToDB/LinqExtensions.cs
> +		/// <returns>Query covered in sub-query.</returns>
no idea what it means :)

2022-01-11 03:41 UTC, igor-tkachev commented on Source/LinqToDB/Sql/Sql.TableID.cs
> +			public bool Equals(SqlID other)
No, Resharper generated.

2022-01-11 03:42 UTC, igor-tkachev commented on Source/LinqToDB/Sql/Sql.TableID.cs
> +				Type = type;
fixed

2022-01-11 04:13 UTC, igor-tkachev commented
/azp run test-all

2022-01-11 14:40 UTC, igor-tkachev commented
/azp run test-sqlserver

2022-01-11 15:42 UTC, igor-tkachev commented
/azp run test-sqlserver

2022-01-11 16:39 UTC, igor-tkachev commented
/azp run test-sqlserver

2022-01-11 18:03 UTC, igor-tkachev commented
/azp run test-sqlserver

2022-01-12 05:06 UTC, igor-tkachev commented
/azp run test-all

2022-01-12 05:07 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
> +		// Not implemented:
All implemented.

2022-01-12 14:10 UTC, igor-tkachev commented
/azp run test-all

2022-01-12 14:11 UTC, igor-tkachev commented on Source/LinqToDB/Sql/Sql.QueryExtensionAttribute.cs
> +		public class QueryExtensionAttribute : Attribute
done

2022-01-13 06:25 UTC, igor-tkachev commented
/azp run test-all

2022-01-13 06:37 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +		[Sql.QueryExtension(ProviderName.MySql, Sql.QueryExtensionScope.QueryHint, typeof(HintWithParametersExtensionBuilder), " ", ", ")]
fixed

2022-01-13 11:33 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.generated.cs
> +		public static IMySqlSpecificTable<TSource> JoinFixedOrderHint<TSource>(this IMySqlSpecificTable<TSource> table)
Can we add xml-doc with hint text generation?

2022-01-13 11:39 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
> +		// https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements006.htm
Sync with list of hints for oracle 21? https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Comments.html#GUID-9B25245A-9884-4031-BAE0-538B4206194E

2022-01-13 11:46 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +			[Sql.Expression("USE PLAN N'{0}'")]
is it correct? we don't generate literal from string in expressions?

2022-01-13 11:47 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +			[Sql.Expression("USE PLAN N'{0}'")]
I don't really like this situation if we don't generate literal - there is no escaping applied to string in that case...

2022-01-13 14:03 UTC, MaceWindu commented on Source/LinqToDB/SqlQuery/SqlQueryExtension.cs
> +		public Dictionary<string,ISqlExpression> Arguments     { get; } = new();
does it make sense to make it nullable or it is always not empty?

2022-01-13 14:56 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
> +			else if (selectQuery?.QueryName is {} queryName)
shouldn't `if (selectQuery?.QueryName is {} queryName)` be a top-level condition? so we do nothing otherwise? or I miss something?

2022-01-13 14:57 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
> +			else if (selectQuery?.QueryName is {} queryName)
BTW, I see similar pattern in some other places, e.g. oraclesqlbuilder

2022-01-13 16:50 UTC, MaceWindu commented on Source/LinqToDB/Linq/Expressions.cs
> +//			#region SqlID
not needed/not implemented yet?

2022-01-13 16:53 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		protected virtual void StartStatementQueryExtensions(SelectQuery? selectQuery)
this probably should be overriden in access sql builder as it doesn't support comments in sql

2022-01-13 16:58 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		static readonly ConcurrentDictionary<Type,ISqlExtensionBuilder> _extensionBuilders = new()
don't know if it worth it, but if it is read-only collection we can use plain Dictionary here and type field as IReadOnlyDictionary

2022-01-13 16:58 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		static readonly ConcurrentDictionary<Type,ISqlExtensionBuilder> _extensionBuilders = new()
nevemind, I see it modified below

2022-01-14 20:17 UTC, igor-tkachev commented
/azp run test-all

2022-01-17 20:30 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.generated.cs
> +		public static IMySqlSpecificTable<TSource> JoinFixedOrderHint<TSource>(this IMySqlSpecificTable<TSource> table)
what kind?

2022-01-17 20:30 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
> +		// https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements006.htm
done

2022-01-17 20:36 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +			[Sql.Expression("USE PLAN N'{0}'")]
No, we do not. Most of the hints use string parameters to construct SQL

```c#
[Sql.Expression("INDEXED BY {0}")]
public static string IndexedBy(string value)
{
	return "INDEXED BY " + value;
}
```

2022-01-17 20:37 UTC, igor-tkachev commented on Source/LinqToDB/SqlQuery/SqlQueryExtension.cs
> +		public Dictionary<string,ISqlExpression> Arguments     { get; } = new();
always not empty

2022-01-17 20:41 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
> +			else if (selectQuery?.QueryName is {} queryName)
There is some logic where QueryName can be null.

2022-01-17 20:51 UTC, igor-tkachev commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		protected virtual void StartStatementQueryExtensions(SelectQuery? selectQuery)
absolutely

2022-01-17 20:53 UTC, igor-tkachev commented on Source/LinqToDB/Linq/Expressions.cs
> +//			#region SqlID
not needed anymore

2022-01-17 20:54 UTC, igor-tkachev commented
/azp run test-all

2022-01-18 17:03 UTC, igor-tkachev commented
/azp run test-postgresql

2022-01-21 14:59 UTC, igor-tkachev commented
/azp run test-postgresql

2022-01-21 22:15 UTC, igor-tkachev commented
/azp run test-postgresql

2022-01-21 23:01 UTC, igor-tkachev commented
/azp run test-postgresql

2022-01-22 00:06 UTC, igor-tkachev commented
/azp run test-all

2022-01-28 01:05 UTC, igor-tkachev commented
/azp run test-all

2022-01-28 14:47 UTC, igor-tkachev commented
/azp run test-all

2022-01-29 12:11 UTC, MaceWindu commented
/azp run test-all

2022-01-29 12:53 UTC, MaceWindu requested changes
- would be great to have article about hints in https://github.com/linq2db/docs/tree/master/source/articles
- what we plan to do about old hint API (`DataConnection.QueryHints`, `DataConnection.NextQueryHints`, `WithTableExpression`, `With`) - are they still valueable or we should at least obsolete them? I see in tests we suppress Obsolete warning (`QueryHintsTests.cs`), but attribute is missing
- providers for test `OptionNoPerformanceSpoolTest("SqlServer.Contained")` need tuning (fails with `Expected: String containing "OPTION (NO_PERFORMANCE_SPOOL)"`)
- as we have breaking changes here - feature should go to v4 release and branch should be rebased on `dev.4` branch

I've restarted tests to generate fresh baselines. Probably additional issues will be rised after I review baselines

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSpecific.cs
> +		/*
remove?

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SQLite/SQLiteSpecific.cs
> +	public interface ISQLiteSpecificQueryable<out TSource> : IQueryable<TSource>
remove?

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SQLite/SQLiteSpecific.cs
> +		[LinqTunnel, Pure]
remove?

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		public void BuildExpression(ISqlExpression expr, bool buildTableName, bool checkParentheses, bool throwExceptionIfTableNotFound = true)
why it's made public? Also we usually we pass `StringBuilder` in such cases

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		public string BuildSqlID(Sql.SqlID id)
public needed?

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> +				^ IsNamingQueryBlockSupported                  .GetHashCode()
duplicate line

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> -				&& AcceptsOuterExpressionInAggregate    == other.AcceptsOuterExpressionInAggregate
revert removal

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
> +//			if (query.SqlQueryExtensions != null)
remove?

2022-01-29 12:53 UTC, MaceWindu commented on Tests/Linq/Extensions/DocExampleTests.cs
> +		public void AccessTest([IncludeDataSources(TestProvName.AllAccess)] string context)
enable remote context  for test?

2022-01-29 12:53 UTC, MaceWindu commented on Tests/Linq/Extensions/DocExampleTests.cs
> +/*
remove

2022-01-29 12:53 UTC, MaceWindu commented on Tests/Linq/Extensions/AccessTests.cs
> +		public void QueryHintTest([IncludeDataSources(TestProvName.AllAccess)] string context)
enable remote context

2022-01-29 12:53 UTC, MaceWindu commented on Tests/Linq/Extensions/AccessTests.cs
> +		public void WithOwnerAccessOptionTest([IncludeDataSources(TestProvName.AllAccess)] string context)
enable remote context

2022-01-29 12:53 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +			[Sql.Expression("USE PLAN N'{0}'")]
Not convinced. I don't see tests for UsePlan, but test for `UseHint` (method above) clearly generates literal. (unfortunatelly, without `N` for some reason)

2022-01-29 17:18 UTC, MaceWindu commented
additional changes to document on release:
- better outer query removal for `select * (subquery)` queries
- SqlServer 2014 and 2019 dialects added to support version-specific hints

2022-01-31 02:05 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSpecific.cs
> +		/*
done

2022-01-31 02:06 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SQLite/SQLiteSpecific.cs
> +		[LinqTunnel, Pure]
done

2022-01-31 02:08 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SQLite/SQLiteSpecific.cs
> +	public interface ISQLiteSpecificQueryable<out TSource> : IQueryable<TSource>
done

2022-01-31 03:35 UTC, igor-tkachev commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		public void BuildExpression(ISqlExpression expr, bool buildTableName, bool checkParentheses, bool throwExceptionIfTableNotFound = true)
fixed

2022-01-31 03:40 UTC, igor-tkachev commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +		public string BuildSqlID(Sql.SqlID id)
This is a base interface member. It can be either public or private.

2022-01-31 03:43 UTC, igor-tkachev commented on Tests/Linq/Extensions/DocExampleTests.cs
> +		public void AccessTest([IncludeDataSources(TestProvName.AllAccess)] string context)
fixed

2022-01-31 03:43 UTC, igor-tkachev commented on Tests/Linq/Extensions/DocExampleTests.cs
> +/*
fixed

2022-01-31 03:44 UTC, igor-tkachev commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> +				^ IsNamingQueryBlockSupported                  .GetHashCode()
fixed

2022-01-31 03:46 UTC, igor-tkachev commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> -				&& AcceptsOuterExpressionInAggregate    == other.AcceptsOuterExpressionInAggregate
fixed

2022-01-31 03:47 UTC, igor-tkachev commented on Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
> +//			if (query.SqlQueryExtensions != null)
fixed

2022-01-31 03:53 UTC, igor-tkachev commented on Tests/Linq/Extensions/AccessTests.cs
> +		public void QueryHintTest([IncludeDataSources(TestProvName.AllAccess)] string context)
fixed

2022-01-31 03:53 UTC, igor-tkachev commented on Tests/Linq/Extensions/AccessTests.cs
> +		public void WithOwnerAccessOptionTest([IncludeDataSources(TestProvName.AllAccess)] string context)
fixed

2022-01-31 04:09 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +			[Sql.Expression("USE PLAN N'{0}'")]
I removed these hints. Both are very questionable, UsePlan is actually useless. Developers will be able esely implement it with common hints if they need it.

2022-01-31 04:11 UTC, igor-tkachev commented
The "Query Extensions" article has been added to https://github.com/linq2db/docs/blob/master/source/articles/sql/Query-Extensions.md.

2022-01-31 04:40 UTC, igor-tkachev commented
/azp run test-all

2022-01-31 15:55 UTC, igor-tkachev commented
/azp run test-all

2022-01-31 20:45 UTC, igor-tkachev commented
/azp run test-all

2022-02-01 08:46 UTC, MaceWindu approved these changes
https://linq2db.github.io/articles/sql/Query-Extensions.html

2022-02-02 16:30 UTC, igor-tkachev commented
/azp run test-all

2022-02-02 16:54 UTC, MaceWindu commented
/azp run test-all

2022-02-02 20:20 UTC, igor-tkachev commented
/azp run test-all

2022-02-02 20:39 UTC, igor-tkachev commented
/azp run test-all

2022-02-03 00:35 UTC, merged