[WIP] Row constructors
linq2db/linq2db pull request #3339
Opened 2021-11-11 23:40 UTC by jods4

This PR adds support for SQL Row Constructors, which basically are SQL tuples, usually with syntax `ROW (1, 2)` or just `(1, 2)`.

### Design 
Row constructors are only server-side, they're always represented by a call to `Sql.Row(1, 2)` and they can't be passed as parameters.

The returned type is `SqlRow<T1, T2>`. 
Tuples with more elements simply nest `SqlRow` in the second argument: e.g. `SqlRow<int, SqlRow<int, int>>`  for a triple.
This may look inefficient but remember this will never be instantiated. It's only a compilation-time type to enforce static types.
The benefit when compared to `SqlRow<T1, T2, T3>` is that I only declared a single type and declared all its operators (such as `>`, `<`) once.
I created `Sql.Row` overloads up to 8 values. With this design, it's trivial to add more if so desired.

Sadly types are stictly checked by C# and I see no way to relax the constraints a bit when it comes to nullable types.
If one side has a `int?` and the other has not, a cast is required:
```csharp
// Error, SqlRow<int, int> incompatible with SqlRow<int, int?>
// Needs a cast (int?)2
Row(1, 2) == Row(3, null) 
```

Row constructors are always evaluated without `CompareNullsAsValues`. The problem here is that generated row ctor code must behave the same as equivalent code in DB without row ctor, and nothing makes sense (to me) for row ctor expressions.

There is no attempt to completely or partially evaluate a `SqlRow` expression, at least for now. 
For example in `(1, 2, 3) = (4, 5, 6)` one could check if any pair of values are constant that are different, or if one is null, and the whole expression is statically false. If any pair of values are constants that are the same, in theory the expression could be shortened.
Notice that in DB that don't support row ctors natively, this expression is converted by SqlOptimizer into an equivalent predicate and that runs through the optimizer and would be simplified.

### IS [NOT] NULL
The following translations are used when not supported:
```
(1, 2) IS NULL     -> 1 IS NULL AND 2 IS NULL
(1, 2) IS NOT NULL -> 1 IS NOT NULL AND 2 IS NOT NULL
```

### Comparisons
The following translations are used when not supported:
```
(1, 2) = (3, 4)        -> 1 = 3 and 2 = 4
(1, 2) <> (3, 4)       -> 1 <> 3 or 2 <> 4
(1, 2, 3) > (4, 5, 6)  -> 1 > 4 or 1 = 4 and 2 > 5 or 1 = 4 and 2 = 5 and 3 > 6
(1, 2, 3) >= (4, 5, 6) -> 1 > 4 or 1 = 4 and 2 > 5 or 1 = 4 and 2 = 5 and 3 >= 6
Likewise for < and <=
```

### [NOT] IN 
When not supported, expands to a big OR: 
```
(1, 2) IN ((3, 4), (5, 6)) -> (1, 2) = (3, 4) OR (1, 2) = (5, 6)
```
This gets translated further in case the provider doesn't support comparisons either, see above.

### OVERLAPS
As described in a comment below, emulating the precise behavior of OVERLAPS in SQL is practically impossible. 
Client-side C# support would in theory be possible but is much less useful.
Approximate, but still useful, behavior is possible but is left for future improvements, if so desired.

In this PR, OVERLAPS is only available natively, which means in DB that have support and only for specific types (i.e. dates and intervals).

Because of the combinatoric explosion of valid type pairs, the static C# typing of `.Overlaps()` accepts any type at all. At runtime the types are validated and a specific error message is thrown if they are invalid (e.g. numbers).

```
(date'2020-01-01', date'2020-12-31') OVERLAPS (date'2020-07-01', null) -- true
```

### [NOT] BETWEEN
When not supported, converts to two comparisons:
```
1     BETWEEN 2 AND 3 -> 1 >= 2 AND 1 <= 3
1 NOT BETWEEN 2 AND 3 -> 1 < 2 OR 1 > 3
```
This gets translated further in case the provider doesn't support comparisons either, see above.

### Comparisons to (SELECT)
Providers that natively support Row Constructors can compare them to a sub-select query returning a single row of the same cardinality.

This might probably be emulated with a [NOT] EXISTS in other providers but I leave this to future improvements, if someone wants it.

The public API is like any scalar comparison to a sub-select: write a query returning a `Sql.Row()` and ends it with `.Single()`. Or if it might return more than one row, use `.First()` as appropriate.
Since any `object` can be compared for equality, the `.Single()` call is not actually needed for operators `==` and `!=`.

```csharp
from x in db.Source
where Sql.Row("name", x.B) >= 
  (from y in db.OtherSource
   where y.Id == 42
   select Sql.Row(y.Name, 0))
  .Single()
select x
```

Results in :
```sql
where ('name', x.B) >= (select y.Name, 0 from OtherSource y where y.id = 42)
```

Note that it's a runtime error to try to select `SqlRow` in the main SELECT clause, and `SqlRow` must be the only selected value.

> I've tried to define an implicit conversion from `IQueryable<SqlRow>` to `SqlRow` to avoid the `.Single()` and make it easier, but C# forbids the definition of implicit conversions from an interface.
>
> I don't think (?) linq2db has support for `>= [ANY|ALL] (SELECT multiple rows)`, please tell me if it does and I'll check it works properly.

### TBD: more features coming
Complete support would include UPDATE SET.

### Provider support
| Provider | Comparisons | IS NULL | IN | OVERLAPS | BETWEEN | Comp. to (SELECT)
| --- | --- | --- | --- | --- | --- | ---
| Access | ⬇ | ⬇ | ⬇ | ⛔ | ⬇ | ⛔ 
| DB2 | ✅ | ⬇ | ⬇ | ✅ | ✅| ✅ 
| Firebird | ⬇ | ⬇ | ⬇ | ⛔ | ⬇ | ⛔  
| Informix | ✅ (1) | ⬇ | ✅ (1) | ⛔ | ⬇ | ✅
| MySQL | ✅ | ⬇ | ✅ | ⛔ | ⬇ | ✅
| Oracle | ✅ (2) | ⬇ | ✅ | ✅ | ⬇ | ✅
| Postgre | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
| SQLite | ✅ | ⬇ | ⬇ | ⛔ | ✅ | ✅
| SapHana | ⬇ | ⬇ | ⬇ | ⛔ | ⬇ | ⛔ 
| SqlCe | ⬇ | ⬇ | ⬇ | ⛔ | ⬇ | ⛔ 
| SqlServer | ⬇ | ⬇ | ⬇ | ⛔ | ⬇ | ⛔ 
| Sybase | ⬇ | ⬇ | ⬇ | ⛔ | ⬇ | ⛔ 

Notes:
1. Informix uses `ROW (1, 2)` syntax
2. Oracle needs extra brackets on the right-hand side to disambiguate syntax: `(1, 2) = ( (3, 4) )`

2021-11-11 23:43 UTC, jods4 commented
Sorry guys, it looks like I messed up my previous PR 😅. This is the continuation of the work in #3027.

I have added some initial work on UPDATE, rebased on 3.5.2 and merged the #3321.
With that fix from @sdanyliv included, updates now look good, I'm almost feature-complete.

Teaser codegen:
```sql
UPDATE
SET
        ("Dest1".A, "Dest1".B) = (
                        y.N,
                        "Dest1".A + 1
                FROM
                        "Src" y
        )
WHERE
        "Dest1"."Id" = 1
```

2021-11-15 18:04 UTC, sdanyliv commented
I'm still don't like this. Better to create `SqlRow: ISqlExpression` AST. In this case even `SqlSetExpression` will be not changed. Later it is easy to generate Row update automatically.

2021-11-16 01:39 UTC, jods4 commented
@sdanyliv ok, it's an easy enough change.
It was a little bit of work to create the class `SqlRow : ISqlExpression` but past this work I agree the result is actually better and easier to manipulate.

I am hitting one small roadblock, though :(
Here, when analyzing the setters in an UPDATE:
https://github.com/linq2db/linq2db/blob/61b9e5b06cb1defd23c2d6955439fc0ed52ad6f0/Source/LinqToDB/Linq/Builder/UpdateBuilder.cs#L458

The issue is that here the setters are just `Expression`, not `ISqlExpression`. They are converted into `SqlField` by very specific code in `GetField`.
What's the best way to check and convert them to `SqlRow`? 
I have put `Extension(BuilderType)` on all `Sql.Row()` methods and would rather not duplicate the logic of `SqlRow` creation :/

What do you think?

2021-11-16 08:54 UTC, MaceWindu commented
BTW, at some point it would be nice to refactor `SqlSetExpression` to support more forms of `set` like here https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver15

2021-11-16 09:17 UTC, sdanyliv commented
Use `builder.ConvertToSqlExpression(ctx, fieldExpr, columnDescriptor, false)`. See below code example. Or also it can `ConvertToSql` method

2022-02-06 20:53 UTC, jods4 commented
Sorry it took me so long, I was quite busy and had no time to work on this. 
Patience is rewarded, though: 

I have finished the refactoring requested by @sdanyliv as well as rounded up a few issues/tasks.
This PR is feature-complete and I don't intend on adding/changing the code anymore 🎉🎉🎉
-- barring any findings during tests, of course.

As such it's a great time to start reviewing the PR @sdanyliv @MaceWindu 
I tried to make "logical" commits but in the end there were so many changes over time that it's better for you to just look at the final diff.
There are less changes than you might expect, albeit a few non-trivial ones. 😉

The last piece missing before merge and release is tests, of course. 
I'll start writing tests for every feature of this PR.

2022-02-06 20:55 UTC, jods4 commented
/azp run test-all

2022-02-06 20:56 UTC, jods4 commented
There are no tests for Row constructors yet, but for my own sanity I want to check that everything else is still working ok, hence the run above 👆

2022-02-07 22:52 UTC, jods4 commented
/azp run test-all

2022-02-08 22:50 UTC, jods4 commented
/azp run test-all

2022-02-11 22:31 UTC, jods4 commented
/azp run test-all

2022-02-13 18:03 UTC, jods4 commented
/azp run test-all

2022-02-27 17:02 UTC, jods4 commented
/azp run test-all

2022-03-06 16:52 UTC, jods4 commented
/azp run test-all

2022-03-06 17:18 UTC, jods4 commented
/azp run test-all

2022-03-06 22:48 UTC, jods4 commented
/azp run test-all

2022-03-06 23:49 UTC, jods4 commented
/azp run test-all

2022-03-07 21:36 UTC, jods4 commented
/azp run test-all

2022-03-08 23:02 UTC, jods4 commented
/azp run test-all

2022-03-09 08:19 UTC, jods4 commented
@MaceWindu @sdanyliv I'm done!
This is ready for final review and merging.

The remaining tests failure are unrelated to `SqlRow`, it looks like flacky tests whose results are inconsistent from one run to the next.

2022-03-12 15:44 UTC, MaceWindu commented
/azp run test-all

2022-03-12 17:08 UTC, MaceWindu requested changes

2022-03-12 17:08 UTC, MaceWindu commented on Tests/Linq/Linq/SqlRowTests.cs
> +			[IncludeDataSources(TestProvName.AllOracle /* TestProvName.AllPostgreSQL, ProviderName.DB2 */)] string context)
pass `true` as first parameter to enable remote context tests

2022-03-12 17:08 UTC, MaceWindu commented on Tests/Linq/Linq/SqlRowTests.cs
> +			[IncludeDataSources(
pass `true` as first parameter to enable remote context tests

2022-03-12 17:08 UTC, MaceWindu commented on Tests/Linq/Linq/SqlRowTests.cs
> +			[IncludeDataSources(
pass `true` as first parameter to enable remote context tests

2022-03-12 17:08 UTC, MaceWindu commented on Tests/Linq/Linq/SqlRowTests.cs
> +			[IncludeDataSources(ProviderName.DB2, TestProvName.AllPostgreSQL)] string context)
pass `true` as first parameter to enable remote context tests

2022-03-12 17:08 UTC, MaceWindu commented on Tests/Linq/Linq/SqlRowTests.cs
> +			[IncludeDataSources(
pass `true` as first parameter to enable remote context tests

2022-03-12 17:08 UTC, MaceWindu commented on Tests/Linq/Linq/SqlRowTests.cs
> +	[TestFixture]
we need test that execute same query with different values in row to ensure query/parameter caching works properly for rows

2022-03-12 20:39 UTC, MaceWindu commented
/azp run test-all

2022-03-12 21:06 UTC, MaceWindu commented
/azp run test-all

2022-03-12 21:06 UTC, jods4 commented on Source/LinqToDB/Data/DbCommandProcessor/DbCommandProcessorExtensions.cs
> +		public static IDataReader ExecuteReaderExt(this IDbCommand cmd, CommandBehavior commandBehavior) =>
Good catch, this is part of my dev setup and shouldn't have been committed.
It's so that the connections can be mocked, which I find far faster and more convenient than working against a real DB during dev.

2022-03-12 21:15 UTC, jods4 commented on Source/LinqToDB/Sql/Sql.Row.cs
> +				if (!IsValidRow(knownExpressions![0]!) || !IsValidRow(knownExpressions![1]!))
Ok, removed. It's much simpler as I don't need a custom attribute, then.

I think the main reason behind this was to provide extensions for non-date types and fallbacks for RDBMS that don't support OVERLAPS.

This was left out because the semantics of SQL-standard OVERLAPS are too complicated to emulate exactly. You can do a good enough approximation but I didn't want to make that kind of decisions in this PR, so I kept OVERLAPS native-only at the moment.

2022-03-12 21:17 UTC, jods4 commented on Tests/Linq/Linq/SqlRowTests.cs
> +			[IncludeDataSources(TestProvName.AllOracle /* TestProvName.AllPostgreSQL, ProviderName.DB2 */)] string context)
Noted

2022-03-12 21:18 UTC, jods4 commented on Tests/Linq/Linq/SqlRowTests.cs
> +	[TestFixture]
Not sure how many tests like that you want and what's the best approach.
Could you add those tests please?

2022-03-12 21:23 UTC, jods4 commented
@MaceWindu I've done all the requested changes, except the one about tests with varying values, see above.

2022-03-12 22:10 UTC, MaceWindu commented
Ok, I've also found some issue with remote context.

2022-03-12 22:47 UTC, MaceWindu commented
@jods4 
I've made some fixes, but after marking SqlSetExpression.Column as nullable I've found several places where Rows not taken into account.

Could you please review each such place (now it gives compilation error) and add Rows support with tests or if it is not possible to have rows there - add supporession operator?

2022-03-14 20:25 UTC, jods4 commented
@MaceWindu I fixed it.
All I had to do is made `Column` throw if the setter is a row expression.
That's the right thing to do in all the places where nullness isn't checked, because it means a row expression is not supported in this context (e.g. in an INSERT).

Codepaths that support rows do appropriate checks, so no other change was required.

2022-03-14 20:25 UTC, jods4 commented
/azp run test-all

2022-03-15 09:12 UTC, MaceWindu commented
With exception it again crash in query serializer

2022-03-15 09:19 UTC, MaceWindu commented
Also please restore nullability on Column property (with exception) and add suppressions on callsites. I want callers be aware of it being optional.

2022-03-15 09:26 UTC, jods4 commented
@MaceWindu 
> With exception it again crash in query serializer. That's initial reason why I removed exception and made it nullable.

OK I missed the query serializer as a place that needs to support Row expressions.
As such, I think the proper way to go is to modify the query serializer to check for `Row == null` first.

> But there were around 10 more places where Row check were missing and I'm not sure they all cannot have Row set.

The only place `Row` is supported is inside an update and I tried to update all places related to that.
Query serializer is something I didn't consider as impacted and I was wrong. If there are others we should fix them as they come up.

> Also please restore nullability on Column property (with exception) and add suppressions on callsites. I want callers be aware of it being optional.

We can do that but it's a lot of callsites.
I think the current pattern is ok because if you don't support Row then Column is indeed not nullable.
If you support Row and don't check the nullable Row first, you'll get an exception (hopefully in tests).

2022-03-15 11:24 UTC, MaceWindu commented
Not really alot. as I said it's about 10 places where ! should be added

2022-03-15 11:24 UTC, MaceWindu commented
> As such, I think the proper way to go is to modify the query serializer to check for Row == null first.

yes, that's how it should be done with current code

2022-03-16 20:25 UTC, jods4 commented
@MaceWindu I fixed the serialization.
Also made Column nullable as you requested. There was indeed only 12 places impacted, the build said 96 errors but that's because it builds 8 times :(
I kept the exception in anyway, because `Column` was not nullable before and that's how it's intended to be used. Incorrect usage should fail fast to catch bugs.

2022-03-16 20:25 UTC, jods4 commented
/azp run test-all

2022-03-17 09:26 UTC, MaceWindu approved these changes

2022-03-18 10:33 UTC, sdanyliv commented on Source/LinqToDB/SqlQuery/SqlSetExpression.cs
> +		public SqlSetExpression(ISqlExpression[] row, ISqlExpression? expression)
Why you have introduced Row? Why not just reuse Column property? SqlRow is already `ISqlExpression`. Everything should be be simpler.

2022-03-18 13:30 UTC, jods4 commented on Source/LinqToDB/SqlQuery/SqlSetExpression.cs
> +		public SqlSetExpression(ISqlExpression[] row, ISqlExpression? expression)
`Column` is expected to be a single column field, as the name implies. There are 40+ places that reference it with this assumption.

`Row` is a clear name that explicitly tells you it's not a single field setter but a row value setter. It's already an array of expression which is the most straightforward to use. 
Most importantly: it's makes it easy to see which code supports rows (just a handful) and which code is oblivious of rows (most of the 40+ others). In fact Column contains a fail-fast when that assertion is wrong (as was the case of the serializer that I forgot).

2022-03-18 13:34 UTC, jods4 commented on Source/LinqToDB/SqlQuery/SqlSetExpression.cs
> +		public SqlSetExpression(ISqlExpression[] row, ISqlExpression? expression)
@sdanyliv 
And I forgot the _main_ reason.
This would not be a plain `SqlRowExpression` straight from query.
Look at the update builder and at `GetField()` in particular. This is how the array of expressions is built.
That part was tricky for me and I don't feel confident changing it much.

2022-03-29 09:35 UTC, MaceWindu commented
@sdanyliv failing test generates `(:p_1, :p_2) OVERLAPS ((:p_3, :p_4))` but should generate `(:p_1, :p_2) OVERLAPS (:p_3, :p_4)`
@jods, could you clarify when double brackets needed for oracle?

2022-03-29 09:52 UTC, jods4 commented
@MaceWindu from my experiments, when a row value is on the right-hand side of a binary operator, e.g.:
```
(1, 2) = ( (1, 2) )
(1, 2) <= ( (1, 2) )
```
I believe Oracle parser has an ambiguity at this position and thinks brackets are the usual grouping/precedence brackets.

I see @sdanyliv has refactored `OVERLAPS` into a binary operator. I think this is why it's now handled by my double-bracketing code in Oracle provider.

The relevant code is here:
https://github.com/linq2db/linq2db/pull/3339/files#diff-82c262d6464c4218de01a7298f57148dc8c3a3ad973baf9eaccf24529d3c28ebR255-R267

Maybe you should pass the operator and don't double-bracket `OVERLAPS`.

2022-03-29 11:27 UTC, sdanyliv commented
/azp run test-all

2022-03-29 15:04 UTC, viceroypenguin approved these changes

2022-03-30 11:00 UTC, sdanyliv commented
/azp run test-all

2022-03-30 12:11 UTC, sdanyliv commented
/azp run test-all

2022-03-30 12:13 UTC, MaceWindu commented
/azp run test-all

2022-03-30 12:14 UTC, MaceWindu commented
Fix #2204

2022-03-30 12:15 UTC, MaceWindu commented
and fix #2657

2022-03-31 11:52 UTC, sdanyliv approved these changes

2022-03-31 11:56 UTC, merged