Feature isnull sqlserver
linq2db/linq2db pull request #3353
Opened 2021-11-17 10:23 UTC by marcnet80

https://github.com/linq2db/linq2db/issues/3314

2021-11-17 10:32 UTC, MaceWindu commented
@marcnet80 , thanks!

I will accept it, but note that this is not a fix for #3314 - #3314 is about automatic generation of `ISNULL` isntead of `COALESCE` in sql queries and is more complex.

For #3314 we cannot just detect complex `COALESCE` parameters and replace it with `ISNULL` - it's an easy part. Trick with `ISNULL` is that it assigns result type using type of first parameter, which could result in data loss when second parameter returned (when parameter types differ, e.g. by length for strings).

I actually have fix for #3314 but it requires tests and I currently busy with other tasks.

2021-11-17 10:38 UTC, MaceWindu requested changes

2021-11-17 10:38 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerExtensions.cs
> +		public static T IsNull<T>(this ISqlServerExtensions? ext, [ExprParameter] T? value, [ExprParameter] T replacementValue) => throw new LinqException($"'{nameof(IsNull)}' is server - side method.");
Why `replacementValue` is not nullable? It should be possible to use nullable value here too.

2021-11-17 10:38 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerExtensions.cs
> +		[Sql.Extension("ISNULL({value}, {replacementValue})", ServerSideOnly = true)]
Would be nice to have `IsNullableType` set here, but I don't see `IfAllParametersNullable` [here](https://github.com/linq2db/linq2db/blob/cf1c77b45b7734f9dcf31970d6efee78ac2ba11e/Source/LinqToDB/Sql/IsNullableType.cs). If you can add it (and use it in nullability detenction logic) - it would be great.

2021-11-17 10:39 UTC, MaceWindu commented
/azp run test-all

2021-11-17 19:38 UTC, marcnet80 commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerExtensions.cs
> +		public static T IsNull<T>(this ISqlServerExtensions? ext, [ExprParameter] T? value, [ExprParameter] T replacementValue) => throw new LinqException($"'{nameof(IsNull)}' is server - side method.");
I wanted to make this function more strict, but I ok with you comment.

2021-11-17 19:39 UTC, marcnet80 commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerExtensions.cs
> +		[Sql.Extension("ISNULL({value}, {replacementValue})", ServerSideOnly = true)]
added

2021-11-18 09:13 UTC, MaceWindu approved these changes

2021-11-18 11:39 UTC, MaceWindu commented
/azp run test-all

2021-11-18 13:12 UTC, viceroypenguin commented on Source/LinqToDB/Sql/IsNullableType.cs
> +			IfAllParametersNullable
Reduce future code difference when new enum values are added.

```suggestion
			IfAllParametersNullable,
```

2021-11-18 13:12 UTC, viceroypenguin commented on Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
>  				}
@MaceWindu should we suggest a switch to the new `switch`-expression here? Not sure you're opinion on those.

2021-11-18 13:12 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerExtensions.cs
> +		[Sql.Extension("ISNULL({value}, {replacementValue})", ServerSideOnly = true, IsNullable = Sql.IsNullableType.IfAllParametersNullable)]
@MaceWindu  I know you suggested `IfAllParametersNullable`, but I think this should actually just be `SameAsLastParameter`. The whole point of this function on the server side is that if the first value is null, we take the second value, so only the last parameter's nullability is relevant for the nullability of the expression, right?

2021-11-18 13:16 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerExtensions.cs
> +		[Sql.Extension("ISNULL({value}, {replacementValue})", ServerSideOnly = true, IsNullable = Sql.IsNullableType.IfAllParametersNullable)]
Don't think this is correct. E.g. for call with such parameters `ISNULL(not-nullable, nullable)` it will return true, when it should be false. I agree that in that case there is no need for function call, but it's how it could be called by user anyway

2021-11-18 13:17 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
>  				}
I have no strong opinion on that. If @marcnet80 wants, he can change it

2021-11-18 13:20 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerExtensions.cs
> +		[Sql.Extension("ISNULL({value}, {replacementValue})", ServerSideOnly = true, IsNullable = Sql.IsNullableType.IfAllParametersNullable)]
Oh. I was reading it as `AnyParametersNullable`, not `AllParametersNullable`. I'm good then.

2021-11-18 18:04 UTC, viceroypenguin approved these changes

2021-11-18 18:05 UTC, marcnet80 commented on Source/LinqToDB/Sql/IsNullableType.cs
> +			IfAllParametersNullable
added

2021-11-18 18:07 UTC, marcnet80 commented on Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
>  				}
@viceroypenguin, changed to switch-expression.

2021-11-18 18:13 UTC, sdanyliv commented on Tests/Linq/Linq/IsNullTests.SqlServer.cs
> +				Assert.That(query.ToString().Contains("ISNULL([c_1].[CategoryName], @defaultCategory)"));
Execute query, then get `db.LastQuery`, we need to ensure that database accepts that and query logged for baselines.

2021-11-18 18:13 UTC, sdanyliv commented on Tests/Linq/Linq/IsNullTests.SqlServer.cs
> +				var supplierQuery = GetSupplierIdWithMaxUnitPrice(categoryId, db);
Same, execute query.

2021-11-18 20:53 UTC, marcnet80 commented on Tests/Linq/Linq/IsNullTests.SqlServer.cs
> +				Assert.That(query.ToString().Contains("ISNULL([c_1].[CategoryName], @defaultCategory)"));
added

2021-11-18 20:53 UTC, marcnet80 commented on Tests/Linq/Linq/IsNullTests.SqlServer.cs
> +				var supplierQuery = GetSupplierIdWithMaxUnitPrice(categoryId, db);
added

2021-11-19 09:54 UTC, MaceWindu commented
/azp run test-all

2022-03-03 22:34 UTC, MaceWindu commented
/azp run test-all

2022-03-04 10:28 UTC, MaceWindu commented
/azp run test-all

2022-03-04 14:41 UTC, merged

2022-03-04 14:41 UTC, MaceWindu commented
@marcnet80  thanks!