Refactored remoting
linq2db/linq2db pull request #3410
Opened 2022-01-27 16:45 UTC by lsoft

Closed #3409 

In general, the code refactoring itself is quite simple - the `ILinqService` interface has been cloned, and interfaces like `IWcfLinqClient`+`IWcfLinqService` are now not related to the `linq2db` logic, but to the network transport.

The classes themselves in the former `ServiceModel` folder have changed little, the main change in that code is the change in the signature of the `ExecuteScalar` methods. I think this competent person should look into the edit in more detail.

I draw your attention - I renamed the `ServiceModel` folder itself to `Remote`, this is now a more correct meaning for it.

Wcf, soap, grpc parts are separated into different `csproj`. The `Examples` folder has been created and contains 3 examples.

Что еще надо сделать:

- [x] Вынесение частей ремотинга из основного репозитория `linq2db`
- [x] Асинхронщина на сервере, за исключением `ExecuteBatch`.
- [ ] Поддержка нескольких (в т.ч. разнородных) запросов за один сетевой вызов (батчинг). Убрать `ExecuteBatch`, если он окажется не нужен. Сделать его асинхронным, если он окажется нужным (соотв. TODO в коде осталось)
- [ ] Замена сериализатора, предположительно существующий относительно нетороплив.
- [ ] После всех модификаций доработать тесты.
- [ ] Бекпортировать в 3.х чтобы не ждать релиза v.4.
- [ ] `\\\` комменты на новые компоненты.

2022-01-27 16:48 UTC, lsoft commented
@MaceWindu @sdanyliv думаю уже можно глянуть крупноблочный дизайн и дать обратную связь, если есть такая возможность. Спасибо!

2022-01-29 11:15 UTC, MaceWindu requested changes
First address non-examples issues

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Wcf/LinqToDB.Remote.Wcf.csproj
> +		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
also not needed, I don't see any templates in project

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Wcf/LinqToDB.Remote.Wcf.csproj
> +		<AssemblyName>linq2db.remote.wcf</AssemblyName>
`linq2db.Remote.WCF`

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
same comments as for WCF project below

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<TargetFrameworks>net6.0</TargetFrameworks>
probably we can use only `netstandard2.0` target?

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<AssemblyName>linq2db.remote.grpc</AssemblyName>
`linq2db.Remote.Grpc`

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\linq2db.remote.grpc.xml</DocumentationFile>
this should be default path I suppose, so there is no need to add it explicitly?

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
check notes on wcf project - some of them apply here too

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/Dto/GrpcString.cs
> +	[DataContract]
I would like to see a data test where query returns both `null` and empty string and we receive them correctly on client.

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/Dto/GrpcSqlProviderFlags.cs
> +	public class GrpcSqlProviderFlags
`SqlProviderFlags` is already PITA, I don't want to have more places to edit when we change them (and potentially break custom implementations of clients). Let's have generic serialization/deserialization logic in `SqlProviderFlags` class and in contracts use serialized `string` for flags value.

`SqlProviderFlags` created once per-provider and not edited after it so it is safe to to cache serialized value as field in `SqlProviderFlags` and even use by-string-value deserialization cache.

2022-01-29 11:15 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/Dto/GrpcLinqServiceInfo.cs
> +				SqlProviderFlags = new GrpcSqlProviderFlags
see `GrpcSqlProviderFlags` notes below

2022-01-29 18:31 UTC, lsoft commented on Source/LinqToDB.Remote.Wcf/LinqToDB.Remote.Wcf.csproj
> +		<AssemblyName>linq2db.remote.wcf</AssemblyName>
should I fix the casing of the namespace too? `<RootNamespace>LinqToDB.Remote.Wcf</RootNamespace>`

2022-01-29 18:35 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<TargetFrameworks>net6.0</TargetFrameworks>
`protobuf-net.Grpc.AspNetCore` supports `.NETCoreApp 3.1` and `NET 5` only... may be it make sense to add `netcoreapp3.1` ? but end of support for net core 3.1 is December 3, 2022, so I'm not sure.

2022-01-29 18:36 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\linq2db.remote.grpc.xml</DocumentationFile>
it was copy-pasted-fixed from `LinqToDB.csproj`, should I remote it here anyway?

2022-01-29 18:39 UTC, lsoft commented on Examples/Remote/Wcf/Client/Client.csproj
> +    <PackageReference Include="linq2db.t4models" Version="3.6.0" />
probably the tip has been lost.

2022-01-30 08:56 UTC, MaceWindu requested changes

2022-01-30 08:56 UTC, MaceWindu commented on .gitignore
> +/**/packages/*
```
.vs/
packages/
```
should be enough

2022-01-30 08:57 UTC, MaceWindu commented on Examples/Remote/Wcf/Client/Client.csproj
> +    <PackageReference Include="linq2db.t4models" Version="3.6.0" />
updated

2022-01-30 08:59 UTC, MaceWindu commented on Source/LinqToDB.Remote.Wcf/LinqToDB.Remote.Wcf.csproj
> +		<AssemblyName>linq2db.remote.wcf</AssemblyName>
yep

2022-01-30 09:00 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<TargetFrameworks>net6.0</TargetFrameworks>
I see, then add `netcoreapp3.1`

2022-01-30 09:00 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\linq2db.remote.grpc.xml</DocumentationFile>
let's leave it for now

2022-01-31 12:00 UTC, lsoft commented on Examples/Remote/Soap/Soap.sln
> +﻿
as I can understand I need to create a `Compile.cmd` for examples? Should I put it to the root or to `Examples` folder? What is the name of the file you would like to see?

2022-01-31 12:17 UTC, lsoft commented on Tests/Model/Tests.Model.csproj
> +	  <ProjectReference Include="..\..\Source\LinqToDB.Remote.Wcf\LinqToDB.Remote.Wcf.csproj" />
wcf is needed because of `TestWcfDataContext` class; here is a question: will we test soap and grpc transports in test.model? if so, I need to add grpc-ref, otherwise I need to remove soap-ref.

2022-01-31 12:18 UTC, lsoft commented on Examples/Remote/Soap/Client/Client.csproj
> +    <!-- ����� �������� ����� - ��� �4 ��������� ����� "������" ������; ���� �������� ���-�� ���������� �� �������� �������, �� �������� ��� -->
that comment has been removed.

2022-01-31 12:18 UTC, lsoft commented on Source/LinqToDB/Remote/LinqService.cs
> +		/// In case of change of the logic of this method, DO NOT FORGET
this is fixed, PTAL

2022-01-31 12:19 UTC, lsoft commented on Source/LinqToDB.Remote.Wcf/LinqToDB.Remote.Wcf.csproj
> +		<TargetFrameworks>net45;net46;net472;</TargetFrameworks>
net45, net46 has been removed from this csproj and from the wcf-example.

2022-01-31 12:43 UTC, lsoft commented on Examples/Remote/Wcf/Client/Client.csproj
> +    <PackageReference Include="linq2db.t4models" Version="3.6.0" />
hmm... may I missed something? but I have an issue to include `ttinclude` files from local filesystem... for example some of that files need a compiled dll `<#@ assembly name="$(LinqToDBT4SharedTools)linq2db.dll" #>`... of course I can declare `LinqToDBT4SharedTools` in my csproj and target it to the `Source\LinqToDB\bin\Debug\<tfm>\linq2db.dll`, but it does not looks good. what do you think?

2022-01-31 12:45 UTC, lsoft commented on Examples/Remote/Wcf/Client/Client.csproj
> +    <PackageReference Include="linq2db.t4models" Version="3.6.0" />
so, I added

```
	<PropertyGroup>
		<LinqToDBT4SqlServerTemplatesPath>$(MSBuildThisFileDirectory)..\..\..\..\Source\LinqToDB.Templates\</LinqToDBT4SqlServerTemplatesPath>
		<LinqToDBT4SharedTools>$(MSBuildThisFileDirectory)..\..\..\..\Source\LinqToDB\bin\Debug\net472\</LinqToDBT4SharedTools> 
	</PropertyGroup>
```

to my csproj, and finally I have

```Severity	Code	Description	Project	File	Line	Suppression State
Error		Compiling transformation: The type 'IAsyncDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.		C:\projects\github\linq2db\Examples\Remote\Wcf\Client\..\..\..\..\Source\LinqToDB.Templates\LinqToDB.SqlServer.ttinclude	89	```

huh

2022-01-31 13:20 UTC, lsoft commented on Source/LinqToDB/Remote/ILinqService.cs
> +{
good catch. do you know how wcf will work with the signatures with `CancellationToken`.

```
//wcf
		public Task<string?> ExecuteScalarAsync(string? configuration, string queryData, CancellationToken ct)
		{
			return Channel.ExecuteScalarAsync(configuration, queryData, ct);
		}
```

will it work from the client side as we expect? I don't know honestly...

2022-02-02 17:54 UTC, lsoft commented on Examples/Remote/Soap/Soap.sln
> +﻿
I've created `Example\Compile.cmd`

2022-02-02 17:55 UTC, lsoft commented on Examples/Remote/Wcf/Client/Client.csproj
> +    <PackageReference Include="linq2db.t4models" Version="3.6.0" />
Switched to `linq2db.t4models` nuget v4 preview

2022-02-02 17:55 UTC, lsoft commented on Source/LinqToDB/Remote/LinqServiceSerializer.cs
> +				if (!_arrayConverters.TryGetValue(elementType, out converter!))
Fixed

2022-02-02 17:55 UTC, lsoft commented on Source/LinqToDB/Data/DataConnection.QueryRunner.cs
> +			/// <summary>
Fixed.

2022-02-02 17:56 UTC, lsoft commented on Source/LinqToDB.Remote.Wcf/LinqToDB.Remote.Wcf.csproj
> +		<AssemblyName>linq2db.remote.wcf</AssemblyName>
Fixed I believe

2022-02-02 17:56 UTC, lsoft commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Fixed I believe

2022-02-02 17:56 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<TargetFrameworks>net6.0</TargetFrameworks>
Fixed

2022-02-02 17:56 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<AssemblyName>linq2db.remote.grpc</AssemblyName>
Fixed

2022-02-02 17:56 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Fixed I believe

2022-02-02 17:57 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/Dto/GrpcSqlProviderFlags.cs
> +	public class GrpcSqlProviderFlags
PITA don't become bigger for now, fixed

2022-02-02 17:57 UTC, lsoft commented on .gitignore
> +/**/packages/*
Fixed

2022-02-02 17:57 UTC, lsoft commented
@MaceWindu There are stiil a few questions for you, PTAL.

2022-02-02 18:07 UTC, lsoft commented on Examples/Remote/Soap/Client/Client.csproj
> +    <TargetFramework>net452</TargetFramework>
Fixed

2022-02-02 18:08 UTC, lsoft commented on linq2db.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "LinqToDB.Remote.Wcf", "Source\LinqToDB.Remote.Wcf\LinqToDB.Remote.Wcf.csproj", "{CBFFC259-5165-4828-B9AC-15DFB769BFEC}"
is it just a FYI message or I need to perform something? if the latest, I don't understand what. :)

2022-02-02 18:08 UTC, lsoft commented on Examples/Remote/Grpc/Server/Server.csproj
> +    <PackageReference Include="protobuf-net.Grpc.AspNetCore" Version="1.0.152" />
Fixed I believe

2022-02-02 18:09 UTC, lsoft commented on Examples/Remote/Grpc/Client/Client.csproj
> +    <PackageReference Include="Grpc.Net.Client" Version="2.42.0" />
`Examples\linq2db.Examples.props` has been created, PTAL.

2022-02-02 18:09 UTC, lsoft commented on Directory.Packages.props
> +		<PackageReference Include="Grpc.Net.Client"                         Version="2.42.0" />
done

2022-02-03 13:39 UTC, MaceWindu requested changes
don't forget to add nuspecs for new projects and register them in pack.bat

2022-02-03 13:39 UTC, MaceWindu commented on .gitignore
> +/**/packages/*
I still see old version

2022-02-03 13:39 UTC, MaceWindu commented on linq2db.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "LinqToDB.Remote.Wcf", "Source\LinqToDB.Remote.Wcf\LinqToDB.Remote.Wcf.csproj", "{CBFFC259-5165-4828-B9AC-15DFB769BFEC}"
no action required

2022-02-03 13:39 UTC, MaceWindu commented on Examples/Remote/Grpc/Client/Program.cs
> +			Console.WriteLine("---------------------------------------------------------------------");
maybe remove those lines? I see that methods already log their progress

2022-02-03 13:39 UTC, MaceWindu commented on Examples/Remote/Grpc/Client/Client.csproj
> +		<TargetFrameworks>netcoreapp3.1;net6.0</TargetFrameworks>
remove `net6` - I don't see any `net6`-specific code

2022-02-03 13:39 UTC, MaceWindu commented on Examples/Remote/Grpc/Server/Server.csproj
> +		<TargetFrameworks>netcoreapp3.1;net6.0</TargetFrameworks>
net6 not needed here

2022-02-03 13:39 UTC, MaceWindu commented on Examples/Remote/Soap/Client/Program.cs
> +			Console.WriteLine("---------------------------------------------------------------------");
same here - probably remove lines printing?

2022-02-03 13:39 UTC, MaceWindu commented on Examples/Remote/Soap/WebHost/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2016")]
2022?

2022-02-03 13:39 UTC, MaceWindu commented on Examples/Remote/Wcf/Client/Program.cs
> +			Console.WriteLine("---------------------------------------------------------------------");
also remove lines?

2022-02-03 13:39 UTC, MaceWindu commented on Examples/linq2db.Examples.props
> +		<RepositoryType>git</RepositoryType>
let's remove whole block. Don't want to maintain it for examples

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/IGrpcLinqService.cs
> +		//Task<LinqServiceInfo> GetInfoAsync(GrpcConfiguration configuration, CallContext context = default);
why it's not enabled?

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<Nullable>enable</Nullable>
I think nullable already enabled by imported props.
Also do we need explicit net6 target?

2022-02-03 13:39 UTC, MaceWindu commented on Tests/Base/TestUtils.cs
> +			if (db is TestWcfDataContext linqDb)
For better test-coverage it would be nice to implement grpc-based test context too and use it for .net core tests. This will:
- enable remote context testing in .net core
- will test grpc implementation with our tests

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> +	[DataContract]
@sdanyliv , @it guys, your opinion about serialization annotations here?

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB/Remote/LinqService.cs
> +		/// </summary>
convert to regular comment

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB/Remote/LinqService.cs
> +		/// </summary>
convert to regular comment

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB/Remote/LinqService.cs
> +		/// In case of change of the logic of this method, DO NOT FORGET
Still see xml-doc

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB/Remote/LinqService.cs
> +		/// </summary>
convert to regular comment

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB/Remote/LinqService.cs
> +		/// </summary>
convert to regular comment

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB/Remote/LinqService.cs
> +		/// </summary>
convert to regular comment

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB/Remote/ILinqService.cs
> +{
AFAIK it is not supported by WCF (at least in .net framework)

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Wcf/LinqToDB.Remote.Wcf.csproj
> +		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
move to previous ItemGroup

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Wcf/LinqToDB.Remote.Wcf.csproj
> +	<PropertyGroup Condition=" '$(TargetFramework)' != 'net45' AND '$(TargetFramework)' != 'net46' ">
condition could be removed but I don't think we use this symbol in wcf project so it could be removed?
But I think you should just enable net45 for project as otherwise it will be compatibility regression

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +		<TargetFrameworks>net45;net46;net472;</TargetFrameworks>
net46 probably could be removed

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
remove

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +		<DefineConstants>OVERRIDETOSTRING;$(DefineConstants)</DefineConstants>
remove

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +	<ItemGroup Condition=" '$(TargetFramework)' == 'net45' OR '$(TargetFramework)' == 'net46' OR '$(TargetFramework)' == 'net472' ">
remove condition

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<DefineConstants>NATIVE_ASYNC;$(DefineConstants)</DefineConstants>
remove

2022-02-03 13:39 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<DefineConstants>OVERRIDETOSTRING;$(DefineConstants)</DefineConstants>
remove

2022-02-03 14:01 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<PackageReference Include="protobuf-net.Grpc.AspNetCore" />
probably we can reference [protobuf-net.Grpc](https://www.nuget.org/packages/protobuf-net.Grpc/) only? this way we can target `netstandard2.0`

2022-02-03 14:22 UTC, viceroypenguin commented on CONTRIBUTING.md
> +- `NET6_PLUS` - `net6.0` and the next ones (i.e. NET 7 etc) target ifdef.
This is not necessary, since `NET60_OR_GREATER` exists by default.

2022-02-03 14:22 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/IGrpcLinqService.cs
> +		//Task<LinqServiceInfo> GetInfoAsync(GrpcConfiguration configuration, CallContext context = default);
that method has nothing to `await`, so sync sibling is enough.

2022-02-03 14:31 UTC, lsoft commented on CONTRIBUTING.md
> +- `NET6_PLUS` - `net6.0` and the next ones (i.e. NET 7 etc) target ifdef.
@viceroypenguin I have difficulties to find info about 'NET60_OR_GREATER'. Nothing in `linq2db` can be found by this string, and google known [nothing about it.](https://www.google.com/search?q="NET60_OR_GREATER")

Can you add more details?

2022-02-03 14:38 UTC, viceroypenguin commented on CONTRIBUTING.md
> +- `NET6_PLUS` - `net6.0` and the next ones (i.e. NET 7 etc) target ifdef.
- https://github.com/dotnet/designs/blob/main/accepted/2020/or-greater-defines/or-greater-defines.md
- https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-a-target-framework (scroll down to "The complete list of preprocessor symbols for .NET target frameworks is:")

As of .net5 sdk (VS'19, msbuild 16, etc.), any version you build for will automatically include `_OR_GREATER` defines for all earlier versions. This also retroactively applies to earlier versions of .net core if built with a modern sdk (.net core app 3.1 will now include `NETCOREAPP1_0_OR_GREATER`, etc.). Since l2db is built with a modern sdk, we can rely on these defines. I should probably do a separate PR to clean up some of the existing l2db defines accordingly.

2022-02-03 15:00 UTC, lsoft commented on CONTRIBUTING.md
> +- `NET6_PLUS` - `net6.0` and the next ones (i.e. NET 7 etc) target ifdef.
@viceroypenguin Thank you! Fixed!

2022-02-03 15:40 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
> +		<PackageReference Include="protobuf-net.Grpc.AspNetCore" />
👍 good catch!

2022-02-03 16:37 UTC, MaceWindu commented on Examples/Compile.cmd
> +"%msbuild_path%" /v:m Remote\Wcf\Wcf.sln /property:Configuration=Release
some voodoo magic

```sh
for /f "delims=" %%a in ('dir /s /b .\*.sln') do (
"%msbuild_path%" /v:m /target:Clean %%a /property:Configuration=Debug
"%msbuild_path%" /v:m /target:Clean %%a /property:Configuration=Release
"%msbuild_path%" /v:m %%a /property:Configuration=Debug
"%msbuild_path%" /v:m %%a /property:Configuration=Release
)
```

2022-02-03 16:42 UTC, lsoft commented on Examples/Compile.cmd
> +"%msbuild_path%" /v:m Remote\Wcf\Wcf.sln /property:Configuration=Release
not sure it's better. are we expect more transports to have? unlikely. so, naive solution is better, because it's easy to understand.

2022-02-03 16:43 UTC, lsoft commented on Examples/Compile.cmd
> +"%msbuild_path%" /v:m Remote\Wcf\Wcf.sln /property:Configuration=Release
let me know if you insist, I will change in that case :)

2022-02-03 16:44 UTC, lsoft commented on Examples/Compile.cmd
> +"%msbuild_path%" /v:m Remote\Wcf\Wcf.sln /property:Configuration=Release
`for /f "delims=" %%a in ('dir /s /b .\*.sln') do (` I had an experience with this magic, yeah)) so I know it's cannot be understanded by 90% of people)))

2022-02-03 16:44 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/IGrpcLinqService.cs
> +		//Task<LinqServiceInfo> GetInfoAsync(GrpcConfiguration configuration, CallContext context = default);
implementation is sync, but at least client contract could use async version for async network call?

2022-02-03 16:45 UTC, MaceWindu commented on Source/LinqToDB.Remote.Grpc/IGrpcLinqService.cs
> +		//Task<LinqServiceInfo> GetInfoAsync(GrpcConfiguration configuration, CallContext context = default);
well, maybe it's belong to transports...

2022-02-03 16:47 UTC, MaceWindu commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +	<ItemGroup Condition=" '$(TargetFramework)' != 'net45' AND '$(TargetFramework)' != 'net46' ">
there is no net46 target framework for this project

2022-02-03 16:47 UTC, MaceWindu commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +	<PropertyGroup Condition=" '$(TargetFramework)' != 'net45' AND '$(TargetFramework)' != 'net46' ">
remove net46

2022-02-03 16:51 UTC, MaceWindu commented on Source/LinqToDB.Remote.Wcf/WcfLinqService.cs
> +}
no async methods? should be supported by WCF

2022-02-03 16:55 UTC, MaceWindu commented on Examples/Compile.cmd
> +"%msbuild_path%" /v:m Remote\Wcf\Wcf.sln /property:Configuration=Release
it's not for more transports but for more examples (like for migration of examples repo to this folder in future)

2022-02-03 16:58 UTC, lsoft commented on Source/LinqToDB.Remote.Grpc/IGrpcLinqService.cs
> +		//Task<LinqServiceInfo> GetInfoAsync(GrpcConfiguration configuration, CallContext context = default);
we will need to modify `RemoteDataContextBase` to have async sibling methods in addition to existing ones.  probably it makes sense, not sure about the balance of pro and contras. 

![изображение](https://user-images.githubusercontent.com/5988558/152390757-61f682e1-5d90-42ca-882f-aef0c4509748.png)

2022-02-03 17:15 UTC, lsoft commented on Source/LinqToDB.Remote.Wcf/WcfLinqService.cs
> +}
server side async in wcf? interesting. i will take a look.

2022-02-03 17:27 UTC, lsoft commented on Examples/Compile.cmd
> +"%msbuild_path%" /v:m Remote\Wcf\Wcf.sln /property:Configuration=Release
👍works as is. fixed.

2022-02-03 17:27 UTC, lsoft commented on Source/LinqToDB.Remote.Soap/LinqToDB.Remote.Soap.csproj
> +	<ItemGroup Condition=" '$(TargetFramework)' != 'net45' AND '$(TargetFramework)' != 'net46' ">
no more 4.6 in soap scope.

2022-02-16 14:43 UTC, MaceWindu commented
/azp run test-all

2022-02-16 14:44 UTC, MaceWindu commented on Tests/Tests.Playground/Tests.Playground.csproj
> +<!--
revert

2022-02-16 14:45 UTC, MaceWindu commented on Tests/Model/Tests.Model.csproj
> +	<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.1' OR '$(TargetFramework)' == 'net5.0' OR '$(TargetFramework)' == 'net6.0' ">
should be safe to reference unconditionally

2022-02-17 11:25 UTC, MaceWindu commented
/azp run test-all

2022-02-17 15:20 UTC, MaceWindu commented
/azp run test-all

2022-02-19 08:28 UTC, MaceWindu commented on Tests/Model/Remote/Grpc/TestGrpcDataContext.cs
> +							ServerCertificateCustomValidationCallback =
you can assign existing handler `HttpClientHandler.DangerousAcceptAnyServerCertificateValidator`

2022-02-19 08:29 UTC, MaceWindu commented on Examples/Remote/Grpc/Client/ExampleGrpcDataContext.cs
> +							ServerCertificateCustomValidationCallback =
use DangerousAcceptAnyServerCertificateValidator here too

2022-02-19 08:47 UTC, lsoft commented on Examples/Remote/Grpc/Client/ExampleGrpcDataContext.cs
> +							ServerCertificateCustomValidationCallback =
fixed

2022-02-19 08:47 UTC, lsoft commented on Tests/Model/Remote/Grpc/TestGrpcDataContext.cs
> +							ServerCertificateCustomValidationCallback =
fixed

2022-02-19 08:50 UTC, MaceWindu commented
/azp run test-all

2022-02-19 15:16 UTC, MaceWindu commented
/azp run test-all

2022-02-22 14:24 UTC, viceroypenguin commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> +	[DataContract]
Fine with me.

2022-03-29 11:03 UTC, MaceWindu commented
/azp run test-all

2022-03-29 11:11 UTC, MaceWindu commented
/azp run test-all

2022-03-31 10:14 UTC, MaceWindu commented
/azp run test-postgresql

2022-03-31 11:29 UTC, MaceWindu commented
/azp run test-all

2022-03-31 13:27 UTC, MaceWindu commented
/azp run test-all

2022-03-31 21:05 UTC, MaceWindu commented
/azp run test-all

2022-04-02 15:20 UTC, MaceWindu commented
/azp run test-all

2022-04-03 16:26 UTC, MaceWindu commented
/azp run test-all

2022-04-03 17:23 UTC, MaceWindu commented
/azp run test-all

2022-04-03 17:24 UTC, MaceWindu commented
/azp run test-all

2022-04-03 18:32 UTC, MaceWindu commented
/azp run test-all

2022-04-03 18:57 UTC, MaceWindu commented
/azp run test-all

2022-04-03 19:16 UTC, MaceWindu commented
/azp run test-all

2022-04-03 19:34 UTC, viceroypenguin commented on Build/Azure/pipelines/templates/build-job.yml
> +    displayName: Build Examles (verify)
```suggestion
    displayName: Build Examples (verify)
```

2022-04-03 19:46 UTC, MaceWindu commented
/azp run test-all

2022-04-03 19:52 UTC, viceroypenguin requested changes

2022-04-03 19:52 UTC, viceroypenguin commented on Examples/Remote/Grpc/Client/ExampleDataContext.cs
> +					  HttpClient = new HttpClient(
Per [this](https://docs.microsoft.com/en-us/dotnet/core/extensions/http-client) document, no one should be creating `HttpClient` on the fly. While I recognize this is a demo, we should probably not encourage bad practice. Maybe update to receive an `HttpClient` from the constructor?

2022-04-03 19:52 UTC, viceroypenguin commented on Source/LinqToDB/Linq/QueryFlagsHelper.cs
> +			// TODO: v4: move QueryFlags to IDataContext?
If we're doing this to v4 after all, then this should be addressed (either remove the comment or fix per the comment).

2022-04-03 19:52 UTC, viceroypenguin commented on Tests/Linq/Extensions/SqlServerTests.cs
> +#if NETFRAMEWORK
Is `NETFRAMEWORK` an appropriate distinction here? I know Wcf can be run on netcore, and I don't know any reason Grpc couldn't be run on netfx.

2022-04-03 20:16 UTC, MaceWindu commented on Tests/Linq/Extensions/SqlServerTests.cs
> +#if NETFRAMEWORK
we use wcf for netfx tests and grpc for net core

2022-04-03 20:17 UTC, MaceWindu commented on Source/LinqToDB/Linq/QueryFlagsHelper.cs
> +			// TODO: v4: move QueryFlags to IDataContext?
this will be done in separate pr

2022-04-03 22:28 UTC, viceroypenguin commented on Tests/Linq/Extensions/SqlServerTests.cs
> +#if NETFRAMEWORK
I understand that, but what I'm saying is that since both (wcf/grpc) can be used on both (netfx/netcore),

a) should we do more complete testing, and 
b) whether we do more complete testing, maybe we should use a pair of DEFINEs in the csproj to determine which/if to use here.

2022-04-04 07:39 UTC, MaceWindu commented on Tests/Linq/Extensions/SqlServerTests.cs
> +#if NETFRAMEWORK
it requires additional work:
- WCF in .NET Core is a mess (thanks to MS). There is client-only implementation in runtime, there is https://github.com/CoreWCF/CoreWCF and there is https://github.com/DigDes/SoapCore - I don't want to decide which one to support or support all of them right now. If we get support request for specific implementation - we can add it easily
- gRPC testing in .net framework: my main problem is that it requires additional work to create testing infrastructure. In .net core we can host server in process using https://www.nuget.org/packages/protobuf-net.Grpc.AspNetCore/. How to host it in .net framework - I don't even want to think about such scary things :)

2022-04-04 08:23 UTC, MaceWindu commented on Examples/Remote/Grpc/Client/ExampleDataContext.cs
> +					  HttpClient = new HttpClient(
I will add comment. Caller code shared with WCF sample

2022-04-04 11:21 UTC, viceroypenguin commented on Tests/Linq/Extensions/SqlServerTests.cs
> +#if NETFRAMEWORK
Fair enough on a).  I still say b) we should use a pair of DEFINEs in the csproj file so that we are not intrinsically tying one to the other? We already use the conditional to mark which library we import from nuget; using similar defines on a `<PropertyGroup/>` to set the DEFINE would be more consistent I think.

2022-04-04 12:58 UTC, MaceWindu commented on Tests/Linq/Extensions/SqlServerTests.cs
> +#if NETFRAMEWORK
For now it doesn't make much sense as they will be the same as TFM defines - both wcf and grpc test classes cannot be compiled for other targets currently.

2022-04-04 14:48 UTC, MaceWindu commented
/azp run test-all

2022-04-04 18:59 UTC, MaceWindu commented
/azp run test-all

2022-04-04 22:00 UTC, MaceWindu commented
/azp run test-all

2022-04-05 11:35 UTC, MaceWindu commented
/azp run test-all

2022-04-05 15:29 UTC, MaceWindu commented
/azp run test-all

2022-04-05 19:46 UTC, MaceWindu approved these changes

2022-04-05 20:41 UTC, MaceWindu commented
https://twitter.com/SputnikATO

2022-04-05 20:41 UTC, MaceWindu commented
/azp run test-all

2022-04-06 09:19 UTC, MaceWindu commented
/azp run test-all

2022-04-07 12:05 UTC, MaceWindu commented
/azp run test-all

2022-04-07 15:44 UTC, MaceWindu commented
/azp run test-all

2022-04-09 23:55 UTC, viceroypenguin approved these changes

2022-04-10 15:45 UTC, MaceWindu commented
/azp run test-all

2022-04-11 22:16 UTC, igor-tkachev commented on Source/LinqToDB/Data/DataConnection.QueryRunner.cs
> +			static async Task<object?> ExecuteScalarImplAsync(
Do we replace all the sync methods with async version?

2022-04-11 22:16 UTC, igor-tkachev commented on Source/LinqToDB/Data/DataConnection.QueryRunner.cs
> +			static async Task<object?> ExecuteScalarImplAsync(
Are all these changes related to Remoting?

2022-04-16 12:17 UTC, MaceWindu commented on NuGet/linq2db.Remote.Grpc.nuspec
> +				<dependency id="linq2db"           version="3.0.0"   />
I've bumped it in another PR, but it anyways rewritten on nuspec generation, so value here is not important

2022-04-16 12:20 UTC, MaceWindu commented on Source/LinqToDB.Remote.Wcf/IWcfLinqService.cs
> +	public interface IWcfLinqService
We can adopt MS guidelines: uppercase for 2 letter abbr and Pascal case for 3+-letter abbreviations. So Wcf. Will update PR

2022-04-16 12:20 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +		internal async Task<int> ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
Probably name conflict, will check

2022-04-16 12:21 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnection.QueryRunner.cs
> +			static async Task<object?> ExecuteScalarImplAsync(
It's not replaced - we added async version of same method, used for sync remoting only (so there were no async version). but git diff shows it in ugly way

2022-04-16 12:34 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +		internal async Task<int> ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
Confirmed, it is not rename, it is addition of new method. git diff is confused  here (same as below)

2022-04-16 12:36 UTC, MaceWindu commented on Source/LinqToDB/Configuration/Linq2DbSettings.cs
> +	public class Linq2DbSettings : ILinqToDBSettings
We also have `LinqToDbConnectionOptions`. Maybe we should also rename it to `LinqToDBConnectionOptions` while we can?

2022-04-16 12:38 UTC, MaceWindu commented on Source/LinqToDB/Configuration/Linq2DbSettings.cs
> +	public class Linq2DbSettings : ILinqToDBSettings
Will rename in separate commit so we can easily revert it

2022-04-16 12:52 UTC, MaceWindu commented
/azp run test-all

2022-04-16 13:04 UTC, MaceWindu commented
/azp run test-all

2022-04-16 14:05 UTC, MaceWindu commented
/azp run test-all

2022-04-16 14:20 UTC, igor-tkachev approved these changes

2022-04-16 16:17 UTC, merged