Mark some structs as readonly
linq2db/linq2db pull request #3498
Opened 2022-04-10 13:51 UTC by MaceWindu

We also can mark `DbDataType` as readonly, but it has delayed hashcode calculation, so it requires benchmarking as it could result in performance degradation instead.

2022-04-10 13:52 UTC, MaceWindu commented
/azp run test-all

2022-04-10 13:57 UTC, MaceWindu commented
/azp run test-all

2022-04-10 13:59 UTC, sdanyliv approved these changes

2022-04-10 14:55 UTC, MaceWindu commented
/azp run test-all

2022-04-10 15:45 UTC, MaceWindu commented
/azp run test-all

2022-04-10 16:30 UTC, viceroypenguin requested changes

2022-04-10 16:30 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/ReaderInfo.cs
> +				var hashCode = 639348056;
Should use `HashCode.Combine()`. We can use Microsoft nuget https://www.nuget.org/packages/Microsoft.Bcl.HashCode/ to provide this function for .net framework.

2022-04-16 21:39 UTC, MaceWindu commented
/azp run test-all

2022-04-17 15:50 UTC, to11mtm commented on Source/LinqToDB/Common/RawSqlString.cs
> +		public readonly string Format;
Devils advocate question; is there an impact (if negligble) on overall code size? I'm pretty certain the JIT would elide the property access but it will still live in typeinfo (and method tables, assuming those work that way for structs.)

Again, likely negligble in the singular. Mostly bringing it up because I know code size has been a concern in the past and maybe over the whole lib it could make a difference? Possibly something to look into separately.

2022-04-17 23:02 UTC, viceroypenguin commented on Source/LinqToDB/Common/RawSqlString.cs
> +		public readonly string Format;
In the JIT code, a simple property like this is always elided to a simple pointer access. This is the most common case for properties, and is heavily optimized by the JIT to be as fast as field access.

Now yes, it technically does add space to the typeinfo and such. However, using properties is heavily recommended because a property can change implementation without breaking binary compatibility, while changing a field is not binary compatible. Is that important here? Possibly not, but I don't see any reason to go against the recommendation here.

2022-04-18 10:45 UTC, closed without merging