Add DateOnly support
linq2db/linq2db pull request #3502
Opened 2022-04-12 21:20 UTC by viceroypenguin

2022-04-12 21:21 UTC, viceroypenguin commented
/azp run test-all

2022-04-13 01:12 UTC, viceroypenguin commented
/azp run test-all

2022-04-13 08:19 UTC, MaceWindu requested changes
timeonly?

2022-04-13 08:19 UTC, MaceWindu commented on Source/LinqToDB/Common/Converter.cs
> +			SetConverter<string,         DateOnly>   (v => DateOnly.Parse(v));
I wonder what we parse here (and in DateTime above) as we don't specify format.

2022-04-13 08:19 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/DB2/DB2MappingSchema.cs
> +			if (DateOnly.TryParse(value, out var res))
Better to use ParseExact only, don't want issues with day and month positions jumping around based on user locale.

2022-04-13 08:19 UTC, MaceWindu commented on Source/LinqToDB/Linq/Expressions.cs
> +			{ M(() => Sql.MakeDateOnly(0, 0, 0)      ), N(() => L<int?,int?,int?,DateOnly?>((int? y,int? m,int? d) => (DateOnly?)Sql.Convert(Sql.DateOnly, y.ToString() + "-" + m.ToString() + "-" + d.ToString(
we should always use two digits (and InvariantCulture parameter will not harm for ToString calls) for month and day here (I suspect same issue exists for other similar code in this class)

2022-04-13 08:19 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
> +			AddScalarType(typeof(SqlDateTime),  DataType.Date);
I don't get it - why datetime mapped to date for .net 6 ?

2022-04-13 08:19 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.DateOnly.cs
> +		[Sql.Extension(PN.DB2,        "",                                                ServerSideOnly = false, PreferServerSide = false, BuilderType = typeof(DatePartBuilderDB2))] // TODO: Not checked
please remove this copy-paste TODO. I've already sent PR to remove it from other two places :smile:

2022-04-13 08:19 UTC, MaceWindu commented on Tests/Base/TestBase.cs
> +			public static readonly DateOnly DateOnly                      = new (2020, 2, 29);
maybe add and use another test value with 1-digit day and month (but different digits) to catch possible formatting/parsing issues

2022-04-13 11:11 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Expressions.cs
> +			{ M(() => Sql.MakeDateOnly(0, 0, 0)      ), N(() => L<int?,int?,int?,DateOnly?>((int? y,int? m,int? d) => (DateOnly?)Sql.Convert(Sql.DateOnly, y.ToString() + "-" + m.ToString() + "-" + d.ToString(
I was going to ask why this code works for `DateTime`, but not for `DateOnly`. I'll give it a try if I force to two digits here and for `DateTime`.

2022-04-13 11:11 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
> +			AddScalarType(typeof(SqlDateTime),  DataType.Date);
oops... 😂

2022-04-13 12:18 UTC, viceroypenguin commented on Source/LinqToDB/Common/Converter.cs
> +			SetConverter<string,         DateOnly>   (v => DateOnly.Parse(v));
Specifying format fixes it to that format only. If we do so, we force the assumption that dbs will always return data in ISO format. Not specifying a format allows the system to use a generic list of possible formats and try all of them.

2022-04-13 12:19 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/DB2/DB2MappingSchema.cs
> +			if (DateOnly.TryParse(value, out var res))
We do use parse exact in the following lines. I did add `CultureInfo.InvariantCulture` though, for that reason.

2022-04-13 12:20 UTC, viceroypenguin commented
> timeonly?

I need `DateOnly` right now, and I don't need `TimeOnly`.... It's on my list.

2022-04-13 13:36 UTC, viceroypenguin commented
/azp run test-all

2022-04-13 14:32 UTC, viceroypenguin commented
/azp run test-all

2022-04-14 19:25 UTC, viceroypenguin commented
/azp run test-all

2022-04-14 19:25 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Expressions.cs
> +			{ M(() => Sql.MakeDateOnly(0, 0, 0)      ), N(() => L<int?,int?,int?,DateOnly?>((int? y,int? m,int? d) => (DateOnly?)Sql.Convert(Sql.DateOnly, y.ToString() + "-" + m.ToString() + "-" + d.ToString(
Added `Sql.ZeroPad()` to solve this

2022-04-14 21:03 UTC, viceroypenguin commented
/azp run test-all

2022-04-18 00:35 UTC, viceroypenguin commented
/azp run test-all

2022-04-18 01:31 UTC, viceroypenguin commented
/azp run test-all

2022-04-18 11:21 UTC, viceroypenguin commented
/azp run test-all

2022-04-19 02:54 UTC, viceroypenguin commented
/azp run test-all

2022-04-19 07:45 UTC, MaceWindu commented
/azp run test-all

2022-04-19 13:01 UTC, viceroypenguin commented
/azp run test-all

2022-04-19 14:51 UTC, viceroypenguin commented
/azp run test-all

2022-04-19 22:37 UTC, viceroypenguin commented
/azp run test-all

2022-04-19 23:44 UTC, viceroypenguin commented
/azp run test-informix

2022-04-19 23:44 UTC, viceroypenguin commented
/azp run test-sybase

2022-04-19 23:44 UTC, viceroypenguin commented
/azp run test-oracle

2022-04-20 00:37 UTC, viceroypenguin commented
/azp run test-sybase

2022-04-20 01:51 UTC, viceroypenguin commented
/azp run test-sybase

2022-04-20 02:23 UTC, viceroypenguin commented
/azp run test-all

2022-04-20 09:18 UTC, MaceWindu requested changes
I will test/fix native sap hana and sybase providers locally as we cannot test it on CI

2022-04-20 09:18 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/DB2/DB2MappingSchema.cs
> +				new[] { DateParseFormats[0], },
can we avoid array allocation here?

2022-04-20 09:18 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs
> +#if NET6_0_OR_GREATER
~please add comment that we need to skip this branch conditionally after fb client 9 release~
maybe just add boolean flag to provider adapter with false value and I will update it after fbclient 9 release

2022-04-20 09:18 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlDataProvider.cs
> +			if (value is DateOnly d)
mysqlconnector 2.0+ supports date-only. we need to add boolean support flag to provider adapter and use it here

2022-04-20 09:18 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs
> +			if (Name == ProviderName.SQLiteClassic && value is DateOnly d)
introduce provider adapter flag instead of Name check

2022-04-20 09:18 UTC, MaceWindu commented on Source/LinqToDB/Sql/Sql.DateOnly.cs
> +					case Sql.DateParts.Week: expStr += "({1}*7) || ' Day')"; break;
formatting

2022-04-20 09:18 UTC, MaceWindu commented on Tests/Linq/Linq/DataTypesTests.cs
> +		public void TestDateOnly([DataSources(false, TestProvName.AllAccess, ProviderName.SqlCe, TestProvName.AllSqlServer2005, TestProvName.AllSQLiteClassic)] string context)
I would like to have no provider exceptions for tests in this class except situations where it is unavoidable (like non-nullable bit type in sybase). For access/sqlce/sql2005 we can use datetime database type and try to find solution for sqlite  too

2022-04-20 09:33 UTC, MaceWindu commented
`tip. Scrip `document.querySelectorAll('.file-header[data-path*="Tests.Linq.DateOnlyFunctionTests."] .js-reviewed-checkbox:not(:checked)').forEach(e => e.click())` will hide most of `
will remove noize from baselines pr review :)

2022-04-20 09:50 UTC, MaceWindu commented
DateTimeFunctionsTests baselines look much better :+1:

2022-04-20 09:57 UTC, MaceWindu commented
Ok, with baselines I see only 2 tests with unexpected changes that we need to fix:
- `SapHanaTests.TestDataTypes`
- `SapHanaTests.TestDate`

type parameter changed from `Date` to `DateTime`

2022-04-20 09:59 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SapHana/SapHanaOdbcDataProvider.cs
> +					dataType = dataType.WithDataType(DataType.DateTime);
This line changed date parameter to have datetime type

2022-04-20 11:32 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/DB2/DB2MappingSchema.cs
> +				new[] { DateParseFormats[0], },
Done.

2022-04-20 11:39 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs
> +			if (Name == ProviderName.SQLiteClassic && value is DateOnly d)
Should I update the other two items in `SetParameter()` similarly, since those are also name checks - that's where I copied from.

2022-04-20 11:40 UTC, viceroypenguin commented on Source/LinqToDB/Sql/Sql.DateOnly.cs
> +					case Sql.DateParts.Week: expStr += "({1}*7) || ' Day')"; break;
Done

2022-04-20 11:41 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SapHana/SapHanaOdbcDataProvider.cs
> +					dataType = dataType.WithDataType(DataType.DateTime);
Sorry, blind change when I was still trying to figure this out; removed.

2022-04-20 11:43 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs
> +			if (Name == ProviderName.SQLiteClassic && value is DateOnly d)
nope, only this one

2022-04-20 12:00 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs
> +			if (Name == ProviderName.SQLiteClassic && value is DateOnly d)
Done

2022-04-20 12:10 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs
> +#if NET6_0_OR_GREATER
Done

2022-04-20 12:13 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/MySql/MySqlDataProvider.cs
> +			if (value is DateOnly d)
Done

2022-04-20 12:14 UTC, viceroypenguin commented
/azp run test-all

2022-04-23 15:50 UTC, MaceWindu commented
/azp run test-all

2022-04-24 10:38 UTC, MaceWindu approved these changes

2022-04-24 12:25 UTC, MaceWindu commented
/azp run test-saphana

2022-04-24 13:51 UTC, Shane32 approved these changes

2022-04-24 13:51 UTC, Shane32 commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
> +
```suggestion

```

2022-04-24 13:51 UTC, Shane32 commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
> +}
```suggestion
		}
```

2022-04-24 13:52 UTC, Shane32 commented
Nice to see the addition of `DateOnly` @viceroypenguin - good work!

2022-04-25 08:05 UTC, MaceWindu commented
/azp run test-firebird

2022-04-25 08:46 UTC, MaceWindu commented
/azp run test-firebird

2022-04-26 11:04 UTC, merged