Refactoring options.
linq2db/linq2db pull request #3530
Opened 2022-04-28 17:36 UTC by sdanyliv

Work still in progress.

- [ ] Copy static configuration to options
- [ ] Add `UseMiniProfiler`
- [ ] Add `UseNodaTime`

2022-05-02 14:31 UTC, sdanyliv commented
/azp run test-all

2022-05-02 16:36 UTC, sdanyliv commented
/azp run test-all

2022-05-03 11:06 UTC, sdanyliv commented
/azp run test-all

2022-05-03 12:47 UTC, sdanyliv commented
/azp run test-all

2022-05-03 15:17 UTC, sdanyliv commented
/azp run test-all

2022-05-03 17:06 UTC, sdanyliv commented
/azp run test-all

2022-05-04 09:31 UTC, sdanyliv commented
/azp run test-all

2022-05-04 13:59 UTC, sdanyliv commented
/azp run test-all

2022-05-04 16:51 UTC, sdanyliv commented
/azp run test-all

2022-05-18 02:23 UTC, igor-tkachev commented
/azp run test-all

2022-05-23 01:08 UTC, igor-tkachev commented
/azp run test-all

2022-05-23 05:21 UTC, igor-tkachev commented
/azp run test-all

2022-05-23 15:50 UTC, igor-tkachev commented
/azp run test-all

2022-05-23 17:31 UTC, igor-tkachev commented
/azp run test-all

2022-05-23 19:26 UTC, igor-tkachev commented
/azp run test-all

2022-05-23 21:15 UTC, igor-tkachev commented
/azp run test-all

2022-05-23 23:55 UTC, igor-tkachev commented
/azp run test-all

2022-05-24 03:43 UTC, igor-tkachev commented
/azp run test-all

2022-05-24 03:56 UTC, igor-tkachev commented
/azp run test-all

2022-05-24 05:29 UTC, igor-tkachev commented
/azp run test-all

2022-05-26 09:34 UTC, MaceWindu commented
More issues that could be fixed or will benefit from this featue:
- #2137 - add SqlServer-specific configuration extension
- #2401
- #3009 - good candidate for option api?

2022-06-15 03:50 UTC, igor-tkachev commented
/azp run test-all

2022-06-15 07:58 UTC, sdanyliv commented
/azp run test-all

2022-06-16 00:32 UTC, igor-tkachev commented
/azp run test-all

2022-06-16 02:22 UTC, igor-tkachev commented
/azp run test-all

2022-06-16 04:14 UTC, igor-tkachev commented
/azp run test-all

2022-06-16 21:49 UTC, igor-tkachev commented
/azp run test-all

2022-06-17 00:31 UTC, igor-tkachev commented
/azp run test-all

2022-06-17 03:11 UTC, igor-tkachev commented
/azp run test-all

2022-06-17 16:34 UTC, igor-tkachev commented
/azp run test-all

2022-06-18 01:34 UTC, igor-tkachev commented
/azp run test-all

2022-06-18 03:47 UTC, igor-tkachev commented
/azp run test-all

2022-06-18 04:59 UTC, igor-tkachev commented
/azp run test-all

2022-06-19 15:20 UTC, igor-tkachev commented
/azp run test-all

2022-06-19 22:34 UTC, igor-tkachev commented
/azp run test-all

2022-06-20 17:39 UTC, igor-tkachev submitted a review, later dismissed

2022-06-20 17:42 UTC, sdanyliv commented
@igor-tkachev, I would like to see `UseNodaTime` implementation at least. It should prove that abstraction is well designed.

2022-06-20 18:45 UTC, viceroypenguin commented on Source/LinqToDB/Data/CommandInfo.cs
> +				(type: parameters.GetType(), ((IConfigurationID)dataConnection).ConfigurationID),
Is there a reason the cast should be required? In other words, is there a way we could do this without the cast?

2022-06-20 18:45 UTC, viceroypenguin commented on Source/LinqToDB/DataContext.cs
> +		bool _disposed;
```suggestion
		private bool _disposed;
```

2022-06-20 18:45 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Access/AccessODBCDataProvider.cs
> +		static readonly MappingSchema _mappingSchemaInstance = new AccessMappingSchema.OdbcMappingSchema();
```suggestion
		private static readonly MappingSchema _mappingSchemaInstance = new AccessMappingSchema.OdbcMappingSchema();
```

2022-06-20 18:45 UTC, viceroypenguin commented on Source/LinqToDB/Extensions/DataContextExtensions.cs
> +	static class DataContextExtensions
```suggestion
	internal static class DataContextExtensions
```

2022-06-21 03:50 UTC, igor-tkachev commented on Source/LinqToDB.Remote.Wcf/WcfDataContext.cs
> +		WcfDataContext() : base(new DataOptions())
'private' keyword here is syntactical garbage.

2022-06-21 04:07 UTC, igor-tkachev commented
/azp run test-all

2022-06-21 04:07 UTC, igor-tkachev commented on Source/LinqToDB/Data/CommandInfo.cs
>  					(readerType, dataConnection.DataProvider.DataReaderType),
no

2022-06-21 04:08 UTC, igor-tkachev commented on Source/LinqToDB/Data/CommandInfo.cs
>  					(readerType, dataConnection.DataProvider.DataReaderType),
no

2022-06-21 12:01 UTC, viceroypenguin commented on Source/LinqToDB/Data/CommandInfo.cs
> +				(type: parameters.GetType(), ((IConfigurationID)dataConnection).ConfigurationID),
rephrase question: why is the `IConfigurationID` implementation explicit instead of implicit? Is there a conflict on the type, or are we trying to hide the property from public?

2022-06-26 01:54 UTC, igor-tkachev commented on Source/LinqToDB.Remote.Wcf/WcfDataContext.cs
> +		WcfDataContext() : base(new DataOptions())
ok, if you do not like 'garbage' I can call syntactical noise. It does not improve any readability to me. For b) case - I use it.

2022-06-29 11:45 UTC, sdanyliv commented on Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> +			var version = SqlServerTools.DetectServerVersionCached(provider, connectionString) ?? SqlServerVersion.v2008;
I think we have to invent something better than detecting provider version during options building.

2022-07-07 03:18 UTC, igor-tkachev commented
/azp run test-all

2022-07-07 03:25 UTC, igor-tkachev commented
/azp run test-all

2022-07-07 04:22 UTC, igor-tkachev commented
/azp run test-all

2022-07-08 04:55 UTC, igor-tkachev commented
/azp run test-all

2022-07-11 03:59 UTC, igor-tkachev commented
/azp run test-all

2022-07-11 04:59 UTC, igor-tkachev commented
/azp run test-all

2022-07-11 21:24 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> +			var version = SqlServerTools.DetectServerVersionCached(provider, connectionString) ?? SqlServerVersion.v2008;
fixed

2022-07-11 21:27 UTC, igor-tkachev commented on Source/LinqToDB/Data/CommandInfo.cs
> +				(type: parameters.GetType(), ((IConfigurationID)dataConnection).ConfigurationID),
this is API that should not be used by users, so no need to expose it explicitly

2022-08-05 21:45 UTC, igor-tkachev commented
/azp run test-all

2022-09-28 00:51 UTC, igor-tkachev commented
/azp run test-all

2022-09-29 05:17 UTC, igor-tkachev commented
/azp run test-all

2022-10-03 16:11 UTC, igor-tkachev commented
/azp run test-all

2022-10-20 02:14 UTC, igor-tkachev commented
/azp run test-all

2022-10-20 02:25 UTC, igor-tkachev commented
/azp run test-all

2022-10-20 13:29 UTC, igor-tkachev commented
/azp run test-all

2022-11-28 14:02 UTC, MaceWindu commented
/azp run test-all

2022-11-28 16:05 UTC, MaceWindu commented
/azp run test-all

2022-11-28 18:29 UTC, MaceWindu commented
/azp run test-all

2022-12-01 16:25 UTC, MaceWindu commented
/azp run test-all

2022-12-09 17:05 UTC, igor-tkachev commented
/azp run test-all

2022-12-09 17:19 UTC, igor-tkachev commented
/azp run test-all

2022-12-09 17:30 UTC, igor-tkachev commented
/azp run test-all

2022-12-25 16:16 UTC, MaceWindu commented on Tests/Tests.Playground/Tests.Playground.csproj
> +		<Compile Include="..\Linq\Common\ConnectionBuilderTests.cs" Link="ConnectionBuilderTests.cs" />
revert changes to this file

2022-12-25 16:17 UTC, MaceWindu commented on Tests/Tests.Playground/Tests.Playground.csproj
> +		<Compile Include="..\Linq\Common\ConnectionBuilderTests.cs" Link="ConnectionBuilderTests.cs" />
I would recommend to add it to .gitignore (after revert) as this issue happens on regular basis

2022-12-25 16:49 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs.BASE
> +﻿using System;
!!! merge artifact

2022-12-25 16:50 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs.LOCAL
> +﻿using System;
another merge artifact

2022-12-25 16:50 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs.REMOTE
> +﻿using System;
merge artifact

2022-12-25 16:55 UTC, MaceWindu commented on Source/LinqToDB.Tools/DataModel/Model/DataContextModel.cs
>  		public bool                   HasTypedOptionsConstructor               { get; set; }
not used anymore?

2022-12-25 17:08 UTC, MaceWindu commented on Source/LinqToDB/DataOptionsT.cs
> +	public class DataOptions<T>
xml doc missing

2022-12-25 17:18 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs.BASE
> +﻿using System;
merge artifact

2022-12-25 17:18 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs.LOCAL
> +﻿using System;
merge artifact

2022-12-25 17:18 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs.REMOTE
> +﻿using System;
merge artifact

2022-12-26 20:15 UTC, igor-tkachev commented
/azp run test-all

2022-12-26 21:43 UTC, igor-tkachev commented
/azp run test-all

2022-12-27 10:19 UTC, MaceWindu commented on Tests/Tests.Playground/Tests.Playground.csproj
> +		<Compile Include="..\Linq\Common\ConnectionBuilderTests.cs" Link="ConnectionBuilderTests.cs" />
actually not possible in git

2022-12-27 11:37 UTC, MaceWindu commented
/azp run test-all

2022-12-27 11:38 UTC, MaceWindu commented
it would be nice if we can implement provider options for all providers before release (with ProviderOptionsBase {BulkCopyType } base option class)

2022-12-27 11:48 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> +							IsQueryParameter = !QueryHelper.NeedParameterInlining(takeExpr)
@sdanyliv suspicious

2022-12-27 12:19 UTC, sdanyliv commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> +							IsQueryParameter = !QueryHelper.NeedParameterInlining(takeExpr)
Refactored in new parser. But yes, for current version it should be rolled back.

2022-12-27 12:33 UTC, MaceWindu commented
baselines clear :heavy_check_mark:

2022-12-27 14:57 UTC, viceroypenguin commented on Source/LinqToDB.AspNet/ServiceConfigurationExtensions.cs
> +			ServiceLifetime lifetime = ServiceLifetime.Scoped)
Per style:
```suggestion
			Func<IServiceProvider,DataOptions,DataOptions> configure,
			ServiceLifetime                                lifetime = ServiceLifetime.Scoped)
```

2022-12-27 14:57 UTC, viceroypenguin commented on Source/LinqToDB.AspNet/ServiceConfigurationExtensions.cs
> +			ServiceLifetime lifetime  = ServiceLifetime.Scoped)
Same as above

2022-12-27 14:57 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/CacheEntryExtensions.cs
> +			CacheItemPriority              priority)
Slightly off
```suggestion
			this ICacheEntry<TKey,TEntry> entry,
			CacheItemPriority             priority)
```

2022-12-27 14:57 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/CacheEntryExtensions.cs
> +			IChangeToken                   expirationToken)
Same

2022-12-27 14:57 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/CacheEntryExtensions.cs
> +			TimeSpan                       relative)
Same

2022-12-27 14:57 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/CacheEntryExtensions.cs
> +			DateTimeOffset                 absolute)
Same, and others in this file.

2022-12-27 14:57 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/Cache/CacheEntryHelper.cs
>  				Scopes = scopes;
Why not:
```suggestion
				Scopes = CacheEntryStack<TKey,TEntry>.Empty;
```

2022-12-27 14:57 UTC, viceroypenguin reviewed
Does it make sense to break out the `MemoryCache` changes into a smaller PR before the full one?

2022-12-27 15:17 UTC, viceroypenguin commented on Source/LinqToDB/Data/CommandInfo.cs
> +using LinqToDB.Common.Internal;
Per style: Should move down to inside `namespace` with `using Common.Internal;` instead

2022-12-27 15:17 UTC, viceroypenguin commented on Source/LinqToDB/DataContext.cs
> +			public static void Apply(DataContext dataContext, ConnectionOptions options)
This method does not appear to be used; `options.Apply(DataContext)` is used on L85, which would not translate to this method.

2022-12-27 15:17 UTC, viceroypenguin commented on Source/LinqToDB/DataContext.cs
> +		public string?       ConfigurationString { get; private set; }
If we are keeping `Options`, and `Options` is readonly and immutable, then is there a need for `ConfigurationString` and `ConnectionString` to be on `DataContext` instead of being proxied through `Options` object?

2022-12-27 19:50 UTC, igor-tkachev commented
> it would be nice if we can implement provider options for all providers before release (with ProviderOptionsBase {BulkCopyType } base option class)

What API do you think we should have?

2022-12-27 20:02 UTC, igor-tkachev commented on Tests/Tests.Playground/Tests.Playground.csproj
> +		<Compile Include="..\Linq\Common\ConnectionBuilderTests.cs" Link="ConnectionBuilderTests.cs" />
fixed

2022-12-27 20:52 UTC, igor-tkachev commented on Source/LinqToDB/DataContext.cs
> +			public static void Apply(DataContext dataContext, ConnectionOptions options)
ConnectionOptions.cs:102

2022-12-27 21:01 UTC, igor-tkachev commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> +							IsQueryParameter = !QueryHelper.NeedParameterInlining(takeExpr)
fixed

2022-12-27 21:02 UTC, igor-tkachev commented
/azp run test-all

2022-12-27 21:05 UTC, igor-tkachev commented on Source/LinqToDB/DataContext.cs
> +		public string?       ConfigurationString { get; private set; }
Options may not contain ConfigurationString. In this case we assign DataConnection.DefaultConfiguration to ConfigurationString.

2022-12-28 01:20 UTC, igor-tkachev commented
/azp run test-all

2022-12-28 05:17 UTC, igor-tkachev commented
/azp run test-all

2022-12-28 11:23 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> -							IsQueryParameter = !QueryHelper.NeedParameterInlining(skipExpr) && Configuration.Linq.ParameterizeTakeSkip
there is another place with option use disappeared

2022-12-28 12:05 UTC, MaceWindu commented
> > it would be nice if we can implement provider options for all providers before release (with ProviderOptionsBase {BulkCopyType } base option class)
> 
> What API do you think we should have?

1. all providers have `<db>Tools.DefaultBulkCopyType` which could be added to base provider options class
2. SQL Server: `SqlServerConfiguration.GenerateScopeIdentity`
3. SQLite: `SQLiteTools.AlwaysCheckDbNull`
4. SQLCE: `SqlCeConfiguration.InlineFunctionParameters`
5. PGSQL: `PostgreSQLTools.NormalizeTimestampData`, `PostgreSQLSqlBuilder.IdentifierQuoteMode`
6. ORacle: `OracleTools.DontEscapeLowercaseIdentifiers`
7. MySQL: `MySqlSqlBuilder.ParameterSymbol`, `MySqlSqlBuilder.TryConvertParameterSymbol`, `MySqlSqlBuilder.CommandParameterPrefix`, `MySqlSqlBuilder.SprocParameterPrefix`, `MySqlSqlBuilder.ConvertParameterSymbols`. But those options looks like BS and we better remove them (need to check history to see when and why they were added)
8. Informix: `InformixConfiguration.ExplicitFractionalSecondsSeparator`
9. Firebird: `FirebirdConfiguration.IdentifierQuoteMode`, `FirebirdConfiguration.IsLiteralEncodingSupported`
10. DB2: `DB2SqlBuilderBase.IdentifierQuoteMode`
11. ClickHouse: `ClickHouseConfiguration.UseStandardCompatibleAggregates`

2022-12-29 06:49 UTC, igor-tkachev commented
/azp run test-all

2022-12-29 19:38 UTC, igor-tkachev commented
/azp run test-all

2022-12-30 06:00 UTC, igor-tkachev commented
/azp run test-all

2022-12-30 21:20 UTC, igor-tkachev commented
/azp run test-all

2022-12-31 05:23 UTC, igor-tkachev commented
/azp run test-all

2023-01-01 17:01 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/DB2/DB2Options.cs
> +		DB2IdentifierQuoteMode IdentifierQuoteMode = DB2IdentifierQuoteMode.Auto
add IdentifierQuoteMode help

2023-01-01 17:05 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/ClickHouse/ClickHouseOptions.cs
> +		BulkCopyType BulkCopyType = BulkCopyType.ProviderSpecific
ClickHouseConfiguration.UseStandardCompatibleAggregates missing

2023-01-01 17:22 UTC, MaceWindu requested changes
another code review comment: there is no `Use<DB>` overloads for new provider options. Only for `UseOracle`

2023-01-01 21:37 UTC, igor-tkachev commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> -							IsQueryParameter = !QueryHelper.NeedParameterInlining(skipExpr) && Configuration.Linq.ParameterizeTakeSkip
fixed

2023-01-01 21:37 UTC, igor-tkachev commented on Source/LinqToDB/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("linq2db.Tests, PublicKey=002400000480000094000000060200000024000052534131000400000100010021259e121b7fbc7882afdb9118a5e5ac4684296d9a48db3411402ec45fb65cb5f2b5f157856da82
done

2023-01-01 21:37 UTC, igor-tkachev commented on Source/LinqToDB/Linq/Query.cs
> +				public bool Compare(IDataContext context, Expression queryExpression, QueryFlags queryFlags, DataOptions dataOptions)
fixed

2023-01-01 21:38 UTC, igor-tkachev commented on Source/LinqToDB/Linq/Query.cs
> +				public DataOptions DataOptions { get; }
fixed

2023-01-03 02:52 UTC, igor-tkachev commented
/azp run test-all

2023-01-03 02:52 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.cs
> +		#region BulkCopyOptions
done

2023-01-03 02:52 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.cs
> +		public static DataOptions RemoveInterceptor(this DataOptions options, IInterceptor interceptor)
done

2023-01-03 02:54 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.cs
> +		public static DataOptions UseConnectionString(this DataOptions options, string providerName, string connectionString)
done

2023-01-03 02:54 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.cs
> +
done

2023-01-03 02:56 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerOptions.cs
> +		bool         GenerateScopeIdentity = true
no original comment

2023-01-03 02:57 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SQLite/SQLiteTools.cs
> +		[Obsolete("Use SQLiteOptions.Default.BulkCopyType instead.")]
fixed

2023-01-03 02:57 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SQLite/SQLiteOptions.cs
> +		bool         AlwaysCheckDbNull = true
no original comment

2023-01-03 02:58 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLOptions.cs
> +		PostgreSQLIdentifierQuoteMode IdentifierQuoteMode    = PostgreSQLIdentifierQuoteMode.Auto
no original comment

2023-01-03 02:59 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Oracle/OracleOptions.cs
> +		AlternativeBulkCopy AlternativeBulkCopy            = AlternativeBulkCopy.InsertAll,
fixed

2023-01-03 02:59 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/MySql/MySqlOptions.cs
> +		IReadOnlyList<char>? ConvertParameterSymbols   = default
which one? last one or all of them?

2023-01-03 03:00 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/DataProviderOptions.cs
> +		/// Default value: <c>OracleOptions(BulkCopyType.MultipleRows, AlternativeBulkCopy.InsertAll)</c>
fixed

2023-01-03 03:01 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/DB2/DB2Options.cs
> +		DB2IdentifierQuoteMode IdentifierQuoteMode = DB2IdentifierQuoteMode.Auto
no original comment

2023-01-03 03:01 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/ClickHouse/ClickHouseOptions.cs
> +		BulkCopyType BulkCopyType = BulkCopyType.ProviderSpecific
done

2023-01-10 00:18 UTC, igor-tkachev commented
/azp run test-all

2023-01-10 12:40 UTC, MaceWindu commented
/azp run test-all

2023-01-11 10:49 UTC, MaceWindu approved these changes

2023-01-11 10:49 UTC, merged