MySql lock hints
linq2db/linq2db pull request #3932
Opened 2023-01-27 05:48 UTC by igor-tkachev

#3905

2023-01-27 05:50 UTC, igor-tkachev commented
/azp run test-all

2023-01-27 15:55 UTC, igor-tkachev commented
/azp run test-all

2023-01-27 16:19 UTC, MaceWindu commented on Tests/Base/Remote/TestGrpcLinqService.cs
> +			if (configuration?.StartsWith(ProviderName.MariaDB) == true)
use `configuration.IsAnyOf(TestProvName.AllMariaDB)`

2023-01-28 13:55 UTC, MaceWindu requested changes

2023-01-28 13:55 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +//						|| sqlBuilder.MappingSchema.ConfigurationList.Contains(ProviderName.PostgreSQL15))
remove

2023-01-28 13:55 UTC, MaceWindu commented on Source/LinqToDB/ProviderName.cs
> +		/// Used as an additional configuration name for MySql mapping schema <see cref="DataProvider.MySql.MySqlMappingSchema"/>.
should reference MariaDB, not MySql

2023-01-28 13:55 UTC, MaceWindu commented on Tests/Base/Remote/ServerContainer/GrpcServerContainer.cs
> +			if (configuration.StartsWith(TestProvName.MariaDB))
1. if we add MariaDB to `ProviderName` we should remove it from `TestProvName`
2. use `configuration.IsAnyOf(TestProvName.AllMariaDB)` to check for mariadb test database

2023-01-28 13:55 UTC, MaceWindu commented on Tests/Base/Remote/ServerContainer/TestLinqService.cs
> +			if (configuration?.StartsWith(ProviderName.MariaDB) == true)
use `configuration.IsAnyOf(TestProvName.AllMariaDB)` to check for mariadb test database

2023-01-28 13:55 UTC, MaceWindu commented on Tests/Base/TestBase.cs
> +			else if (configuration.StartsWith(TestProvName.MariaDB))
use `configuration.IsAnyOf(TestProvName.AllMariaDB)` to check for mariadb test database

2023-01-28 19:31 UTC, igor-tkachev commented
/azp run test-all

2023-01-28 22:05 UTC, igor-tkachev commented
/azp run test-mysql

2023-01-28 22:07 UTC, igor-tkachev commented on Tests/Base/Remote/TestGrpcLinqService.cs
> +			if (configuration?.StartsWith(ProviderName.MariaDB) == true)
fixed

2023-01-28 22:09 UTC, igor-tkachev commented on Source/LinqToDB/ProviderName.cs
> +		/// Used as an additional configuration name for MySql mapping schema <see cref="DataProvider.MySql.MySqlMappingSchema"/>.
Do we have MariaDB provider?

2023-01-28 22:09 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +//						|| sqlBuilder.MappingSchema.ConfigurationList.Contains(ProviderName.PostgreSQL15))
done

2023-01-28 22:13 UTC, igor-tkachev commented on Tests/Base/Remote/ServerContainer/GrpcServerContainer.cs
> +			if (configuration.StartsWith(TestProvName.MariaDB))
fixed

2023-01-28 22:14 UTC, igor-tkachev commented on Tests/Base/Remote/ServerContainer/TestLinqService.cs
> +			if (configuration?.StartsWith(ProviderName.MariaDB) == true)
fixed

2023-01-28 22:14 UTC, igor-tkachev commented on Tests/Base/TestBase.cs
> +			else if (configuration.StartsWith(TestProvName.MariaDB))
fixed

2023-01-28 22:58 UTC, igor-tkachev commented
/azp run test-all

2023-01-30 09:43 UTC, MaceWindu approved these changes

2023-01-30 09:46 UTC, sdanyliv approved these changes

2023-01-30 09:48 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +					stringBuilder.Append("-- ");
What does it mean? Why we generate hint as comment?

2023-01-30 14:23 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
> +					stringBuilder.Append("-- ");
It means that this sql dialect does not support this feature.

2023-01-31 11:07 UTC, merged