Add [Source] to Merge Output
linq2db/linq2db pull request #3950
Opened 2023-02-03 01:08 UTC by igor-tkachev

#3643

2023-02-03 01:09 UTC, igor-tkachev commented
/azp run test-all

2023-02-03 02:41 UTC, igor-tkachev commented
/azp run test-all

2023-02-03 02:58 UTC, viceroypenguin approved these changes

2023-02-03 06:28 UTC, igor-tkachev commented
/azp run test-all

2023-02-04 14:57 UTC, MaceWindu requested changes
I've added failing test

2023-02-04 14:57 UTC, MaceWindu commented on Source/LinqToDB/Linq/Builder/MergeBuilder.cs
> +					var sourceTable = new SqlTable(args[1])
it doesn't look right. We should use already existing source context instead of fake table. `Source` is not a special table, but alias for merge statement source:
- while we use hardcoded `Source` name for this alias, it could be any name
- more important, if source is a query, we generate columns in source based on used fields in different parts of merge statement and if user will reference unused anywhere else column in output - it will generate incorrect sql

2023-02-04 15:01 UTC, MaceWindu commented
/azp run test-all

2023-02-04 15:04 UTC, MaceWindu commented
/azp run test-all

2023-02-04 18:35 UTC, igor-tkachev commented on Source/LinqToDB/Linq/Builder/MergeBuilder.cs
> +					var sourceTable = new SqlTable(args[1])
I tried. It was my first attempt. This solution does not change any existing logic. Other way requires some questionable modifications. I can do it again, so you will be able to compare them.

2023-02-06 14:31 UTC, MaceWindu commented
/azp run test-all

2023-02-07 09:47 UTC, MaceWindu approved these changes

2023-02-07 09:47 UTC, merged