Added missing CreateTempTable overrides
linq2db/linq2db pull request #3962
Opened 2023-02-10 04:38 UTC by igor-tkachev

CreateTempTable overrides to support anonymous types Fluent Mapping.

2023-02-10 04:38 UTC, igor-tkachev commented
/azp run test-all

2023-02-10 05:32 UTC, sdanyliv commented
Do we need another overload? I think better to add another optional parameter and mention breaking change in release notes.

2023-02-10 08:47 UTC, MaceWindu requested changes

2023-02-10 08:47 UTC, MaceWindu commented on Source/LinqToDB/TempTable.cs
> +		{
I think overloads with `EntityDescriptor` parameter should be internal

2023-02-10 08:47 UTC, MaceWindu commented on Source/LinqToDB/TempTable.cs
> +			: this(db, tableDescriptor, items, options, tableName, databaseName, schemaName, serverName, tableOptions)
mark internal?

2023-02-10 22:44 UTC, igor-tkachev commented on Source/LinqToDB/TempTable.cs
> +		{
We do not need it at all.

2023-02-10 22:47 UTC, igor-tkachev commented
/azp run test-all

2023-02-10 22:49 UTC, viceroypenguin approved these changes

2023-02-10 22:53 UTC, viceroypenguin commented
@sdanyliv I think I'd rather have the overload rather than the optional parameter, but that's just imho

2023-02-11 17:55 UTC, igor-tkachev commented
/azp run test-all

2023-02-11 19:39 UTC, viceroypenguin approved these changes

2023-02-12 13:43 UTC, MaceWindu submitted a review, later dismissed

2023-02-12 14:42 UTC, MaceWindu commented
sql 2019 should be disabled for tests as we use case-sensitive collation for sql 2019 tests which conflicts with tempdb collation

2023-02-13 13:53 UTC, MaceWindu commented
/azp run test-all

2023-02-14 09:00 UTC, merged