ClickHouse does not support EXISTS, switch to IN
linq2db/linq2db pull request #3966
Opened 2023-02-11 17:59 UTC by igor-tkachev

2023-02-11 18:01 UTC, viceroypenguin approved these changes

2023-02-11 18:02 UTC, igor-tkachev commented
/azp run test-all

2023-02-12 11:51 UTC, MaceWindu requested changes
That's not correct. ClickHouse supports EXISTS, but doesn't support correlated subqueries https://github.com/ClickHouse/ClickHouse/issues/6697

2023-02-12 11:53 UTC, MaceWindu commented
My point is:
- user should write queries taking into account this behavior
- or: we should implement set of optimizations in ClickHouseSqlOptimizer to rewrite queries that use correlated columns when it is possible

2023-02-12 23:36 UTC, igor-tkachev commented
The problem is when you use `expr.Cotains(subQuery)' l2db generates EXISTS in the way that ClickHouse does not support. If l2db generates IN, it works just fine. So, there is no way for user to write queries taking into account ClickHouse capabilities.

2023-02-12 23:41 UTC, igor-tkachev commented
BTW, maybe it's a good idea to always generate IN for scalar expression and EXISTS for objects. Another option is to and an 'Option.PrefereExistsThenIn' (or something), so user will be able to control it explicitly.

2023-02-12 23:42 UTC, viceroypenguin commented
I would say `IN` is the more natural operator for scalars, so I'm not opposed to switching to `IN` by default and using `EXISTS` only for non-scalars.

2023-02-13 18:19 UTC, igor-tkachev commented
/azp run test-all

2023-02-13 18:24 UTC, viceroypenguin submitted a review, later dismissed

2023-02-13 18:24 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Builder/ContainsBuilder.cs
> +using LinqToDB.Extensions;
Move inside namespace with other l2db usings.

2023-02-13 18:34 UTC, igor-tkachev commented
/azp run test-all

2023-02-13 18:45 UTC, viceroypenguin submitted a review, later dismissed

2023-02-15 21:29 UTC, igor-tkachev commented
/azp run test-all

2023-02-16 08:23 UTC, MaceWindu commented
/azp run test-all

2023-02-22 20:23 UTC, igor-tkachev commented
/azp run test-all

2023-02-23 17:42 UTC, igor-tkachev commented
/azp run test-all

2023-02-23 18:47 UTC, MaceWindu commented
/azp run test-all

2023-02-24 15:50 UTC, MaceWindu commented
/azp run test-all

2023-02-25 09:57 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSqlOptimizer.cs
> +					return new SqlFunction(f.SystemType, f.Name, f.Parameters[0], new SqlValue(1), new SqlValue(0));
Why it was added?

2023-02-25 10:12 UTC, MaceWindu commented on Source/LinqToDB/Linq/Builder/ContainsBuilder.cs
> +using System.Security.Cryptography.X509Certificates;
randomly selected using kindly added by Visual Studio

2023-02-26 20:37 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSqlOptimizer.cs
> +					return new SqlFunction(f.SystemType, f.Name, f.Parameters[0], new SqlValue(1), new SqlValue(0));
This code is not supported by Octonica provider

```sql
SELECT
	CASE
		WHEN (NOT EXISTS(
			SELECT
				*
			FROM
				Child c_1
			WHERE
				c_1.ParentID <= toInt32(3)
		))
			THEN true -- toInt32(1)
		ELSE false        -- toInt32(0)
	END
```

```
Octonica.ClickHouseClient.Exceptions.ClickHouseException : The type "Bool" is not supported.
```

```toInt32(1)``` solves the problem.

2023-02-26 21:20 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSqlOptimizer.cs
> +					return new SqlFunction(f.SystemType, f.Name, f.Parameters[0], new SqlValue(1), new SqlValue(0));
Only ClickHouse.Client fully support it.

2023-02-26 21:21 UTC, igor-tkachev commented
/azp run test-all

2023-02-27 08:21 UTC, MaceWindu approved these changes

2023-02-27 08:21 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSqlOptimizer.cs
> +					return new SqlFunction(f.SystemType, f.Name, f.Parameters[0], new SqlValue(1), new SqlValue(0));
```suggestion
					return new SqlFunction(f.SystemType, f.Name, f.Parameters[0], new SqlValue((byte)1), new SqlValue((byte)0));
```

2023-02-27 08:23 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSqlOptimizer.cs
> +					return new SqlFunction(f.SystemType, f.Name, f.Parameters[0], new SqlValue(1), new SqlValue(0));
better use byte, as `boolean` is mapped to `UInt8`. Actually boolean support already added to Octonica provider, but we don't update it as it currently breaks bulk copy for booleans (awaiting for fix release)

2023-02-27 08:24 UTC, MaceWindu commented
/azp run test-all

2023-02-27 08:24 UTC, MaceWindu approved these changes

2023-02-27 12:10 UTC, merged