DataOptions: fix equality operators nullability
linq2db/linq2db pull request #3967
Opened 2023-02-12 15:18 UTC by MaceWindu

Discovered during ef.core extension migration

2023-02-12 15:18 UTC, MaceWindu commented
/azp run test-all

2023-02-12 16:21 UTC, MaceWindu commented
/azp run test-all

2023-02-12 16:21 UTC, MaceWindu commented
/azp run test-all

2023-02-12 23:39 UTC, viceroypenguin requested changes

2023-02-12 23:39 UTC, viceroypenguin commented on Source/LinqToDB/DataOptions.cs
> +		public static bool operator !=(DataOptions? t1, DataOptions? t2)
Better to abstract `!=` as `!(t1 == t2)`, so that logic between the two cannot accidentally get mixed up.

2023-02-12 23:39 UTC, viceroypenguin commented on Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> +		/// Configure connection to use specific SQL Server provider, dialect and provider-specific options.
Changes to this file do not appear to be related to nullability. Perhaps better in a separate PR?

2023-02-13 07:20 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> +			SqlServerVersion  dialect                              = SqlServerVersion. AutoDetect,
Does it make any sense? What is the use case?

2023-02-13 07:55 UTC, MaceWindu commented on Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> +			SqlServerVersion  dialect                              = SqlServerVersion. AutoDetect,
To allow provider options configuration for ef.core integration. Connection string is already known there

https://github.com/linq2db/linq2db.EntityFrameworkCore/pull/293/files#diff-e669fdecf3f6f7caa0689c39fa9a7914c75472bfafbac50a9cb6981401ad0c2dR64

2023-02-13 08:54 UTC, jods4 commented on Source/LinqToDB/DataOptions.cs
> +			if (ReferenceEquals(t1, t2))
You can put `ReferenceEquals` first and drop the first check.
`ReferenceEquals` will be true if both `t1` and `t2` are both `null`.

2023-02-13 13:43 UTC, MaceWindu commented on Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> +		/// Configure connection to use specific SQL Server provider, dialect and provider-specific options.
#3970

2023-02-13 13:49 UTC, MaceWindu commented
/azp run test-all

2023-02-14 08:59 UTC, merged