Move EntityDescriptorCreatedCallback to options
linq2db/linq2db pull request #3969
Opened 2023-02-13 13:32 UTC by MaceWindu

Fix #1592
Fix #1822

2023-02-13 13:32 UTC, MaceWindu commented
/azp run test-all

2023-02-13 14:33 UTC, igor-tkachev requested changes

2023-02-13 14:33 UTC, igor-tkachev commented on Tests/Linq/UserTests/Issue1128Tests.cs
> +			var ed1 = ms.GetEntityDescriptor(typeof(FluentBase), null);
Create either default parameter or overload.

2023-02-13 14:33 UTC, igor-tkachev commented on Source/LinqToDB/Mapping/MappingSchema.cs
> +		public EntityDescriptor GetEntityDescriptor(Type type, Action<MappingSchema, IEntityChangeDescriptor>? onEntityDescriptorCreated)
Make parameter default or create overload without parameter.

2023-02-13 14:35 UTC, MaceWindu commented on Source/LinqToDB/Mapping/MappingSchema.cs
> +		public EntityDescriptor GetEntityDescriptor(Type type, Action<MappingSchema, IEntityChangeDescriptor>? onEntityDescriptorCreated)
I thought about it - it's useful for tests but in library code we don't pass `null` (and shouldn't)

2023-02-13 14:36 UTC, igor-tkachev commented on Source/LinqToDB/Mapping/MappingSchema.cs
> +		public EntityDescriptor GetEntityDescriptor(Type type, Action<MappingSchema, IEntityChangeDescriptor>? onEntityDescriptorCreated)
... and compatibility.

2023-02-13 14:45 UTC, MaceWindu commented
/azp run test-all

2023-02-13 14:48 UTC, igor-tkachev approved these changes

2023-02-13 15:06 UTC, viceroypenguin approved these changes

2023-02-13 19:23 UTC, sdanyliv approved these changes

2023-02-14 08:46 UTC, MaceWindu commented
/azp run test-all

2023-02-14 09:41 UTC, MaceWindu commented
/azp run test-all

2023-02-14 10:25 UTC, MaceWindu commented
/azp run test-all

2023-02-14 16:43 UTC, merged