Temporal table support
linq2db/linq2db pull request #4001
Opened 2023-02-27 22:41 UTC by igor-tkachev

https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables

2023-02-27 22:45 UTC, igor-tkachev commented
/azp run test-all

2023-02-27 22:54 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServer2016SqlBuilder.cs
> +using LinqToDB.Common;
Move down to other `LinqToDB` `using`s.

2023-02-27 22:54 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
> +using LinqToDB.Common;
Move down to other `LinqToDB` `using`s.

2023-02-27 22:54 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
> +							                       StringBuilder.Append($"CROSS ").Append(h).Append(" JOIN "); return false;
This should remain as the interpolated version. On .net6+, `.Append($"")` references [this](https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append?view=net-7.0) overload, which is (probably only slightly) better than three separate `.Append(string)` calls.

2023-02-27 22:54 UTC, viceroypenguin commented on Source/LinqToDB/Sql/Sql.QueryExtensionScope.cs
> +			TableNameHint
```suggestion
			TableNameHint,
```

With a comma here, future changes only show the added line, rather than the modification of this line.

2023-02-28 02:03 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
> +							                       StringBuilder.Append($"CROSS ").Append(h).Append(" JOIN "); return false;
|        Method |                Job |            Runtime |     Mean |    Error |   StdDev |
|-------------- |------------------- |------------------- |---------:|---------:|---------:|
|        Append |           .NET 6.0 |           .NET 6.0 | 12.09 ns | 0.082 ns | 0.077 ns |
| Interpolation |           .NET 6.0 |           .NET 6.0 | 13.08 ns | 0.033 ns | 0.028 ns |
|        Append |           .NET 7.0 |           .NET 7.0 | 12.01 ns | 0.022 ns | 0.018 ns |
| Interpolation |           .NET 7.0 |           .NET 7.0 | 13.87 ns | 0.114 ns | 0.106 ns |
|        Append | .NET Framework 4.8 | .NET Framework 4.8 | 32.22 ns | 0.091 ns | 0.080 ns |
| Interpolation | .NET Framework 4.8 | .NET Framework 4.8 | 28.36 ns | 0.210 ns | 0.187 ns |

Looks like they optimized StringBuilder in new frameworks.

2023-02-28 02:13 UTC, igor-tkachev commented
/azp run test-all

2023-02-28 02:14 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
> +							                       StringBuilder.Append($"CROSS ").Append(h).Append(" JOIN "); return false;
I'd be curious about the code you used. I just tested as well, and found `Append` and `Interpolation` to have the same runtime on .net7.

```
// * Summary *

BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22623.1325)
Intel Core i7-1065G7 CPU 1.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.200
  [Host] : .NET 7.0.3 (7.0.323.6910), X64 RyuJIT AVX2
```

|        Method |     Mean |    Error |   StdDev |   Gen0 |   Gen1 | Allocated |
|-------------- |---------:|---------:|---------:|-------:|-------:|----------:|
|        Append | 58.77 ns | 0.981 ns | 0.918 ns | 0.0631 | 0.0001 |     264 B |
| Interpolation | 58.61 ns | 1.094 ns | 1.023 ns | 0.0631 | 0.0001 |     264 B |


<details><summary>Code</summary>

```csharp
#load "BenchmarkDotNet"

void Main()
{
	RunBenchmark();
}

[Benchmark]
public string Append()
{
	var sb = new StringBuilder();
	var h = "OUTER";
	sb.Append("CROSS ").Append(h).Append(" JOIN ");
	return sb.ToString();
}


[Benchmark]
public string Interpolation()
{
	var sb = new StringBuilder();
	var h = "OUTER";
	sb.Append($"CROSS {h} JOIN ");
	return sb.ToString();
}
```

</details>

2023-02-28 02:14 UTC, igor-tkachev commented
/azp run test-all

2023-02-28 08:07 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
> +							                       StringBuilder.Append($"CROSS ").Append(h).Append(" JOIN "); return false;
You test here mainly StringBuilder conversion to string.

<details><summary>Here is my code</summary>

```c#
using System;
using System.Text;

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

namespace Benchmark
{
	public static class Program
	{
		public static void Main(string[] args)
		{
			var summary = BenchmarkRunner.Run<StringBuilderBenchmark>();
		}

		[SimpleJob(RuntimeMoniker.Net60)]
		[SimpleJob(RuntimeMoniker.Net70)]
		[SimpleJob(RuntimeMoniker.Net48)]
		public class StringBuilderBenchmark
		{
			StringBuilder _aStringBuilder = new();
			StringBuilder _iStringBuilder = new();
			string        _hint = "MERGE";

			[Benchmark]
			public void Append()
			{
				_aStringBuilder.Append("RIGHT ").Append(_hint).Append(" JOIN ");

				if (_aStringBuilder.Length > 1000)
					_aStringBuilder.Length = 0;
			}

			[Benchmark]
			public void Interpolation()
			{
				_iStringBuilder.Append($"RIGHT {_hint}  JOIN ");

				if (_iStringBuilder.Length > 1000)
					_iStringBuilder.Length = 0;
			}
		}
	}
}
```

</details>

Anyway, latest frameworks are almost the same, so we can use interpolation for short strings..

2023-02-28 15:48 UTC, sdanyliv approved these changes

2023-03-01 12:12 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/SqlServer/SqlServer2016SqlBuilder.cs
> +		public bool ConvertDateTimeAsLiteral;
`public` -> `protected`?

2023-03-01 15:58 UTC, igor-tkachev commented on Tests/linq2db.TestProjects.props
> +		<ProjectReference Include="..\..\Source\LinqToDB.Tools\LinqToDB.Tools.csproj" />
fixed

2023-03-01 15:59 UTC, igor-tkachev commented on Source/LinqToDB.Tools/LinqToDB.Tools.csproj
> +		<TargetFrameworks>net45;net46;net472;netstandard2.0;netstandard2.1;netcoreapp3.1;net6.0;net7.0</TargetFrameworks>
fixed

2023-03-01 15:59 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/SqlServer/SqlServer2016SqlBuilder.cs
> +		public bool ConvertDateTimeAsLiteral;
internal

2023-03-01 23:00 UTC, viceroypenguin submitted a review, later dismissed

2023-03-02 10:50 UTC, MaceWindu approved these changes

2023-03-02 10:52 UTC, MaceWindu requested changes
We should disable baselines as they change after every testrun

2023-03-02 15:00 UTC, MaceWindu commented
/azp run test-all

2023-03-02 15:00 UTC, MaceWindu approved these changes

2023-03-02 18:05 UTC, viceroypenguin approved these changes

2023-03-03 08:26 UTC, merged