Metrics
linq2db/linq2db pull request #4005
Opened 2023-03-02 05:18 UTC by igor-tkachev

2023-03-02 05:19 UTC, igor-tkachev commented
/azp run test-all

2023-03-02 06:27 UTC, igor-tkachev commented
/azp run test-all

2023-03-02 10:57 UTC, MaceWindu commented
if we collect metrics, maybe it's time to look at opentelementry support? https://github.com/linq2db/linq2db/issues/3405

2023-03-02 11:36 UTC, jods4 requested changes

2023-03-02 11:36 UTC, jods4 commented on Source/LinqToDB/Tools/Metric.cs
> +		public IDisposable Start()
This is neither thread-safe nor re-entrant because a single Stopwatch is shared per metric.

It will fail to work properly if a metric is started in nested calls.
For instance, if a builder calls into `BuildSequence` recursively (and I'm pretty sure some do).

2023-03-02 14:31 UTC, Shane32 commented
See:
- https://github.com/dotnet/aspnetcore/blob/main/src/Shared/ValueStopwatch/ValueStopwatch.cs

2023-03-02 14:35 UTC, Shane32 commented
> if we collect metrics, maybe it's time to look at opentelementry support? #3405

We just added OpenTelemetry support in GraphQL.NET. DiagnosticSource has enough methods in .NET 5+ to add telemetry without a dependency. So we added the code behind ifdefs.

OpenTelemetry is rather new, we figured, and not so likely that someone would attempt to use OpenTelemetry with prior versions of .NET. The alternative is to take a dependency on the System.Diagnostics.DiagnosticSource nuget package

2023-03-02 14:47 UTC, MaceWindu commented
Yep, sorry. I meant `DiagnosticSource` support as abstraction

2023-03-02 15:12 UTC, igor-tkachev commented on Source/LinqToDB/Tools/Metric.cs
> +		public IDisposable Start()
Do we run any tests in parallel?

2023-03-02 15:14 UTC, jods4 commented on Source/LinqToDB/Tools/Metric.cs
> +		public IDisposable Start()
It is also not re-entrant.
"For instance, if a builder calls into BuildSequence recursively (and I'm pretty sure some do)."

2023-03-02 15:30 UTC, jods4 commented
@igor-tkachev You are basically adding a CPU profiler in the codebase manually (counting calls in time spent (incl. descendants)).

That's a lot of noise, esp. with the `#ifdef`... how are you gonna use it? Would there be a way to use a real profiler instead?

For example if you're gonna look at this manually, if you have VS Professional (or Ultimate), you can profile unit tests individually.

If this becomes some automated stats in our CI, I kind of wish we could use a Profiler library or AOP to achieve a similar thing without having to modify our code so much in every place that could be of interest.

2023-03-02 16:11 UTC, igor-tkachev commented
@jods4 There will be some noise, of cause.
These metrics are not for profiling. When I need to profile l2db, I prefer to create a project with a specific case I am going to profile. Also I do not need any linq2db profiling code in my other projects.

The idea of this code is to compare different solutions for optimization. It is not working yet, but we should get reports like the following:

```
+---------------------------+------------------+-----------+------------------+
| Name                      | Elapsed          | CallCount | TimePerCall      |
+---------------------------+------------------+-----------+------------------+
| IQueryProvider.Execute<T> | 00:00:09.6755964 |        80 | 00:00:00.1209449 |
| IQueryProvider.Execute    | 00:00:00         |         0 | 00:00:00         |
|   OnTraceInternal         | 00:00:00.3502372 |       200 | 00:00:00.0017511 |
|   GetQuery                | 00:00:00.7787958 |        80 | 00:00:00.0097349 |
|     Find                  | 00:00:00.3175412 |        80 | 00:00:00.0039692 |
|       Expose              | 00:00:00.1014083 |        80 | 00:00:00.0012676 |
|       Find                | 00:00:00.2161111 |        80 | 00:00:00.0027013 |
|     Create                | 00:00:00.4612266 |        76 | 00:00:00.0060687 |
|       Build               | 00:00:00.3923171 |        76 | 00:00:00.0051620 |
|         BuildSequence     | 00:00:00.0131293 |       228 | 00:00:00.0000575 |
|           CanBuild        | 00:00:00.0005601 |       487 | 00:00:00.0000011 |
|           Build           | 00:00:00.0125966 |       228 | 00:00:00.0000552 |
|   GetIEnumerable          | 00:00:00         |         0 | 00:00:00         |
|   ExecuteElement          | 00:00:08.8949492 |        80 | 00:00:00.1111868 |
| Total                     | 00:00:17.4146554 |         1 | 00:00:17.4146554 |
+---------------------------+------------------+-----------+------------------+
```

For example, we are discussing `CanBuild` performance [here](https://github.com/linq2db/linq2db/pull/3913). If we add metrics to existing code and new one, we will be able to compare performance and make better decision. What I see from the report above, elapsed time of the `CanBuild` method is one thousandth of the `GetQuery` method. Of cause, this is example for just a couple of tests only and we need to get it for all the tests.

2023-03-02 16:15 UTC, igor-tkachev commented
@Shane32 Do not you think that adding telemetry permanently to linq2db will not kill performance permanently as well? :)

2023-03-02 16:24 UTC, igor-tkachev commented on Source/LinqToDB/Tools/Metric.cs
> +		public IDisposable Start()
You right, will redo.

2023-03-02 16:48 UTC, igor-tkachev commented on Source/LinqToDB/Tools/Metric.cs
> +		public IDisposable Start()
fixed

2023-03-02 16:49 UTC, igor-tkachev commented
/azp run test-all

2023-03-02 16:52 UTC, viceroypenguin commented on Source/LinqToDB/Tools/Metric.cs
> +		public void Stop(Stopwatch stopwatch)
Three recommendations:
* Make `Stop` a `private` method, so that it is only called by `Watcher`s.
* Make `Watcher` an `internal`/`private` class, so that it is an implementation detail rather than a public contract
* Make `_elapsed` a `long`, so that you can use `Interlocked.Add()`, and change `Elapsed => new TimeSpan(_elapsed)`

2023-03-02 16:54 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
> +			using var m = LinqToDB.Tools.Metrics.Build.Start();
I wonder if it would make sense to move the `#if METRICS` to `Metric.Start()`, to return a value in `METRICS` and `null` otherwise. If `Start()` is marked `AggressiveInlining`, then it should have negligible perf impact in Release, but be able to keep the code cleaner vis-a-vis having these `#if`s all over the place.

2023-03-02 17:56 UTC, Shane32 commented
> @Shane32 Do not you think that adding telemetry permanently to linq2db will not kill performance permanently as well? :)

`ActivitySource.StartActivity` returns `null` if there are no attached listeners.  Also, there is `activity.IsAllDataRequested` that can be checked before any tags requiring significant CPU work are added.  So essentially the telemetry is only recording data on an as-needed basis.

Within GraphQL.NET we did not build OpenTelemetry support directly into the codebase but rather implemented it as a plugin.  This is not really the recommended approach, and I have no problem building the OpenTelemetry support directly into the codebase.  But to make it configurable, it would have required breaking API changes, which we were not prepared to do at this time.

I would endorse adding telemetry directly to the linq2db codebase.  So long as the source has not been enabled, it should not affect performance at all.  And if the source is enabled, we can assume the user wants the telemetry regardless of the performance impact.  Finally, if the telemetry is sampled, as is often the case, we will not be expending any excessive CPU time on data that will be discarded.

2023-03-02 18:01 UTC, Shane32 commented
Another common implementation pattern is to provide a separate nuget package with an OpenTelemetry plugin.  For example, see the NuGet package [Npgsql.OpenTelemetry](https://www.nuget.org/packages/Npgsql.OpenTelemetry).  The plugin can contain the required dependency on [System.Diagnostics.DiagnosticSource](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource), making it compatible with .NET Framework or older .NET Core use cases.

We considered this for GraphQL.NET but figured that if someone wanted OpenTelemetry support for .NET Framework or .NET Core 3.1, they can just copy the 100 lines of code necessary to implement it (most of which are comments).  We may review this decision in the future.

2023-03-02 18:26 UTC, igor-tkachev commented
> Another common implementation pattern is to provide a separate nuget package with an OpenTelemetry plugin. For example, see the NuGet package [Npgsql.OpenTelemetry](https://www.nuget.org/packages/Npgsql.OpenTelemetry).

I thought about this solution and I like it more.

2023-03-03 07:54 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
> +			using var m = LinqToDB.Tools.Metrics.Build.Start();
@viceroypenguin Yeah, I've given some thoughts how calling sites could be simplified, too. I'm not fan of those `#if .. #endif` everywhere.

My idea was to use `[Conditional("METRICS")]` on the methods, but sadly I don't see a way to make it fully work with `using`.

`using` introduces a `try..finally` block and in my tests, even if they are empty they are not removed by compiler. It adds quite a few ASM instructions.

Not using `using` is an option, of course, but it is inconvenient when you want to time methods that have a `return` because you can't stop the timer after the return statement.

This is why I asked if we couldn't use AOP or some kind of profiler to instrument the code instead.
Ideas being:
- for AOP we'd just put an attribute on methods that must be timed, and that attribute could be `[Conditionnal("METRICS")]` so it wouldn't even exist outside tests.
- if we used a profiler we may indicate the methods we want to time with a filter/selector/list.

2023-03-03 07:59 UTC, jods4 commented
@Shane32 if we introduce `DiagnosticSource` we'll need to give some thoughts what users may want vs what @igor-tkachev wants to benchmark. 
I don't think it makes a lot of sense to publicly expose all internal steps, although that's the granularity we need to benchmark linq2db internally.

So if we go `DiagnosticSource`, I assume we would create some public sources (for things like query compilation, execution, etc); and some private sources (for all the internal bits)?

2023-03-03 15:08 UTC, Shane32 commented
> @Shane32 if we introduce `DiagnosticSource` we'll need to give some thoughts what users may want vs what @igor-tkachev wants to benchmark. I don't think it makes a lot of sense to publicly expose all internal steps, although that's the granularity we need to benchmark linq2db internally.
> 
> So if we go `DiagnosticSource`, I assume we would create some public sources (for things like query compilation, execution, etc); and some private sources (for all the internal bits)?

Offhand, I’d say distributed tracing isn’t designed for profiling. One concern I’d have is that it may be possible to enable all sources within OpenTelemetry. (I’m not sure). If so then end users would receive excessive tracing in their logs. 

Also, it’s possible that with the amount of tracing needed for profiling, the overhead for distributed tracing outweighs the cpu time in many of the short methods. (I’m not sure)

We can also consider the use of metrics instead of distributed tracing for this profiling data. 

Here is some MS links:
- https://learn.microsoft.com/en-us/dotnet/core/diagnostics/
- https://learn.microsoft.com/en-us/dotnet/core/diagnostics/compare-metric-apis

2023-07-25 00:32 UTC, igor-tkachev commented
/azp run test-all

2023-07-25 01:35 UTC, igor-tkachev commented
/azp run test-all

2023-07-25 01:52 UTC, igor-tkachev commented
/azp run test-all

2023-07-25 02:19 UTC, igor-tkachev commented
/azp run test-all

2023-07-25 22:51 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 00:11 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 03:33 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 03:33 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 03:59 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 04:07 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 04:07 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 15:33 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +
Move inside `namespace LinqToDB.Data` to match existing style.

2023-07-26 15:34 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +					: await CurrentCommand!.ExecuteReaderAsync(commandBehavior, cancellationToken).ConfigureAwait(Common.Configuration.ContinueOnCapturedContext);
```suggestion
			using (ActivityService.Start(ActivityID.CommandExecuteReaderAsync))
			{
				dr = result.HasValue
					? result.Value
					: await CurrentCommand!.ExecuteReaderAsync(commandBehavior, cancellationToken).ConfigureAwait(Common.Configuration.ContinueOnCapturedContext);
			}
```

2023-07-26 15:35 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.QueryRunner.cs
> +
Move inside `namespace LinqToDB.Data` to match existing style.

2023-07-26 15:35 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.cs
> +					: command.ExecuteNonQuery();
```suggestion
			using var m = ActivityService.Start(ActivityID.CommandExecuteNonQuery);
			{
				return result.HasValue
					? result.Value
					: command.ExecuteNonQuery();
			}
```

2023-07-26 15:35 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.cs
> +					: _command!.ExecuteReader(commandBehavior);
```suggestion
			using (ActivityService.Start(ActivityID.CommandExecuteReader))
			{
				rd = result.HasValue
					? result.Value
					: _command!.ExecuteReader(commandBehavior);
			}
```

2023-07-26 15:36 UTC, viceroypenguin commented on Source/LinqToDB/Data/RetryPolicy/RetryingDbCommand.cs
> +
Move inside `namespace LinqToDB.Data.RetryPolicy` to match existing style.

2023-07-26 15:37 UTC, viceroypenguin commented on Source/LinqToDB/Linq/ExpressionQuery.cs
> +
Move inside `namespace LinqToDB.Linq` to match existing style.

2023-07-26 15:37 UTC, viceroypenguin commented on Source/LinqToDB/Linq/QueryRunner.cs
> +
Move inside `namespace LinqToDB.Linq` to match existing style.

2023-07-26 15:38 UTC, viceroypenguin commented on Source/LinqToDB/Tools/ActivityService.cs
> +		public static void SetFactory(Func<ActivityID,IActivity>? factory)
Is this for public to access, or just internal testing?

2023-07-26 15:40 UTC, viceroypenguin commented on Tests/Base/TestBase.cs
Perhaps should be in same PR as `BaselinesWriter.cs` change

2023-07-26 15:41 UTC, viceroypenguin commented on Tests/Linq/Linq/WhereTests.cs
> +			if (list is [..])
Dead code, or purpose?

2023-07-26 15:48 UTC, viceroypenguin requested changes
I have serious concerns about the changes in linq2db.baselines. The data in Metrics.txt is too precise - every PR will now have 3k+ files changed due to the metrics.txt data changing. Perhaps we can reduce the level of precision to only 3-4 digits on each timestamp, so that the normal variances of processing don't create enormous PRs?

2023-07-26 16:28 UTC, igor-tkachev commented
Yes, I do not like it either. I think we can keep only one or two metrics for SqlServer and some other configuration.

2023-07-26 20:16 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 21:09 UTC, igor-tkachev commented
/azp run test-all

2023-07-26 21:10 UTC, igor-tkachev commented
/azp run test-all

2023-07-27 04:11 UTC, igor-tkachev commented
/azp run test-all

2023-07-27 04:42 UTC, igor-tkachev commented
/azp run test-all

2023-07-27 04:59 UTC, igor-tkachev commented
/azp run test-all

2023-07-27 05:51 UTC, igor-tkachev commented on Source/LinqToDB/Tools/ActivityService.cs
> +		public static void SetFactory(Func<ActivityID,IActivity>? factory)
public

2023-07-27 13:23 UTC, igor-tkachev commented
/azp run test-all

2023-07-27 17:20 UTC, igor-tkachev commented
/azp run test-sqlserver2022

2023-07-27 17:20 UTC, igor-tkachev commented
/azp run test-sqlserver

2023-07-27 17:21 UTC, igor-tkachev commented
/azp run test-sqlserver

2023-07-27 20:15 UTC, igor-tkachev commented
/azp run test-sqlserver2022

2023-07-27 20:19 UTC, igor-tkachev commented
/azp run test-sqlserver2019

2023-07-27 20:20 UTC, igor-tkachev commented
/azp run test-sqlserver-2019

2023-07-27 20:48 UTC, igor-tkachev commented
/azp run test-sqlserver-2022

2023-07-27 20:49 UTC, igor-tkachev commented
/azp run test-sqlserver-2019

2023-07-27 22:10 UTC, igor-tkachev commented
/azp run test-sqlserver-2019

2023-07-27 22:14 UTC, igor-tkachev commented
/azp run test-sqlserver-2019

2023-07-28 00:30 UTC, igor-tkachev commented
/azp run test-sqlserver-2022

2023-07-28 00:30 UTC, igor-tkachev commented
/azp run test-sqlserver-2022

2023-07-28 00:34 UTC, igor-tkachev commented
/azp run test-sqlserver-2019

2023-07-28 02:33 UTC, igor-tkachev commented
/azp run test-sqlserver-2019

2023-07-28 02:33 UTC, igor-tkachev commented
/azp run test-sqlserver-2019

2023-07-28 04:28 UTC, igor-tkachev commented
/azp run test-sqlserver-2019

2023-07-28 09:36 UTC, MaceWindu commented
/azp run test-sqlserver-2022

2023-07-28 09:37 UTC, MaceWindu commented
/azp run test-sqlserver-2019

2023-07-28 09:37 UTC, MaceWindu commented
/azp run test-sqlserver

2023-07-28 09:39 UTC, MaceWindu commented
/azp run test-sqlserver

2023-07-28 13:33 UTC, MaceWindu commented
/azp run test-sqlserver-2022

2023-07-28 15:35 UTC, igor-tkachev commented
/azp run test-sqlserver-2022

2023-07-28 15:35 UTC, igor-tkachev commented
/azp run test-sqlserver-2022

2023-07-28 23:05 UTC, igor-tkachev commented
/azp run test-all

2023-07-31 01:38 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 15:15 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 15:15 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 19:04 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 19:09 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 19:11 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 23:35 UTC, igor-tkachev commented
/azp run test-all

2023-08-02 00:06 UTC, igor-tkachev commented
/azp run test-all

2023-08-02 06:11 UTC, igor-tkachev commented
/azp run test-all

2023-08-02 22:02 UTC, igor-tkachev commented
/azp run test-all

2023-08-07 20:03 UTC, jods4 commented on Source/LinqToDB.Tools/Activity/ActivityHierarchy.cs
> +		[ThreadStatic]
Do we have a guarantee the metrics code will only ever be used on synchronous code?

If someone attempts to benchmark an async operation (which would look simple enough with your `using` approach), this shouldbe `AsyncLocal`.

2023-08-07 20:11 UTC, jods4 commented on Source/LinqToDB.Tools/Activity/StatActivity.cs
> +			lock (this)
Why two storages `_elapsed` and `_elapsedTicks` for a single property `Elapsed`? 
Why the lock when everything else is lock-free with `Interlocked`? 

`TimeSpan` has a `Ticks` property, can't you reuse `Interlocked.Add(ref _elapsedTicks, stopwatch.ElapsedTicks)`?
Given the `StatActivity` is used across threads, it also feels like there could be a bug in mixing calls to `Stop(Stopwatch)` and `Stop(Timestamp)` as they don't share the same tally field, and only one is exposed by `Elapsed`.

2023-08-07 20:27 UTC, jods4 commented on Source/LinqToDB/Tools/ActivityService.cs
> +		{
I like the idea of erasing the metrics code as much as possible from our published build.
Should we have a compilation symbol `METRICS` and when `#if !METRICS` simplify this to:
```cs
public static IActivity? Start(ActivityID _) => null;
```

I know your code also returns `null` when there's no factory registered, but the JIT compiler cannot know that.

With simple `return null` implementation, this will get inlined, the JIT will still the using is always null so no Dispose call required, etc. There will be practically no overhead left.

Compare in this [SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAUEEsC2UECeAwgPYB2yMCcAxjCQsgDQwhTI4A+AAgEwCMAWABQI7gGYABFjIwICMFBoRJASQCCdLADcsMApJBqAIlmQAHEsijAANhBEBvAL4ixUvpM0wdeg0Y0tXX0nEUlwyQlpWTUAE0lHSQBzCBgAbklXYQjJMIio7199AAoZGGlYgEo88McanLjJAF4KtPqs+qjuABZJUwsrCGLKhKyO4S7+ADZI3i8gvwBleV1lUOz8j2m1QuCCAH5JRZh8GFKYpR891SrmgD5JMjhbWzaN8M6tmcCrv0OAWVS2Bo53KlyKBBuIyaDzIEAA7vNfiVwdcqm9xl05tx+AB2XLCOrvSIeXoAFRQMAAojhzCVqsSiQ18gAGSTafCSAD6zSREOWCFWEAAdMdTsVurxKm8clkcp9IuTKQB5YAAKwgdGG9SZzMibI5CG5vN2SxWWGUwsBVAtEqlMoiYyAA) the ASM disassembly of `StartEmpty` vs `StartObject`.

2023-08-07 20:28 UTC, jods4 commented on Source/LinqToDB/Tools/IActivity.cs
> +	public interface IActivity : IDisposable
Do we need this interface? It has no method, so `ActivityService.Start()` could just as well return `IDisposable`.

2023-08-10 01:50 UTC, igor-tkachev commented on Source/LinqToDB.Tools/Activity/ActivityHierarchy.cs
> +		[ThreadStatic]
accepted

2023-08-10 01:54 UTC, igor-tkachev commented on Source/LinqToDB.Tools/Activity/StatActivity.cs
> +			lock (this)
`Stopwatch` Linux version does not work correctly. It shows completely insane values.

2023-08-10 03:04 UTC, igor-tkachev commented on Source/LinqToDB/Tools/IActivity.cs
> +	public interface IActivity : IDisposable
I am sure 999% we will extend it.

2023-08-10 03:05 UTC, igor-tkachev commented on Source/LinqToDB/Tools/ActivityService.cs
> +		{
I did some optimizations, but I cant do it in this way, as I already need this functionality for my work project.

2023-08-10 03:08 UTC, igor-tkachev commented
/azp run test-all

2023-08-10 03:11 UTC, igor-tkachev commented
/azp run test-all

2023-08-10 03:42 UTC, igor-tkachev commented
/azp run test-all

2023-08-10 11:47 UTC, jods4 commented on Source/LinqToDB.Tools/Activity/StatActivity.cs
> +			lock (this)
I undertstood that. I suggest you rewrite this overload like so:
```cs
void Stop(TimeSpan time) => Interlocked.Add(ref _elapsedTicks, time.Ticks);`
```
If you do that, you don't need locking anymore and you can remove `_elapsed` field and simplify `Elapsed` property.

2023-08-10 19:39 UTC, igor-tkachev commented
/azp run test-all

2023-08-11 04:58 UTC, igor-tkachev commented
/azp run test-all

2023-08-15 01:11 UTC, igor-tkachev commented
/azp run test-all

2023-08-15 22:00 UTC, igor-tkachev commented
/azp run test-all

2023-08-20 19:20 UTC, igor-tkachev commented
/azp run test-all

2023-08-20 19:36 UTC, igor-tkachev commented
/azp run test-all

2023-08-20 22:57 UTC, igor-tkachev commented
/azp run test-all

2023-09-03 14:18 UTC, MaceWindu commented
/azp run test-all

2023-09-03 15:15 UTC, MaceWindu commented
/azp run test-all

2023-09-03 15:17 UTC, MaceWindu commented
/azp run test-all

2023-09-03 17:42 UTC, MaceWindu requested changes

2023-09-03 17:42 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityHierarchy.cs
> +		// TODO: Change to AsyncLocal<T> after removing FW 4.5 support.
Copy `AsyncLocal` `net45` implementation from `Compatibility` folder in `linq2db` project

2023-09-03 17:42 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityStatistics.cs
> +				Percent = FixUnixPercentFormat($"{(m.CallCount == 0 ? (decimal?)null : m.Elapsed.Ticks / totalTime),7:P}")
is it needed with invariant culture formatting?

2023-09-03 17:42 UTC, MaceWindu commented on Source/LinqToDB/Async/AsyncDbConnection.cs
> +			using var _ = ActivityService.Start(ActivityID.ConnectionOpenAsync);
here and in similar places: does it have any value to collect metrics for non-awaited tasks?

2023-09-03 17:42 UTC, MaceWindu commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
> +				var mc       = ActivityService.Start(ActivityID.BuildSequenceCanBuild);
I would prefer to use `using`/`finally` here and in several similar places. `IActivity` implementation provided by user with unknown disposal logic.

2023-09-03 17:42 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +			using var m = ActivityService.Start(ActivityID.CommandExecuteNonQueryAsync);
is it correct in some other places we start activity only for `Execute` branch for ternary expression

2023-11-14 02:32 UTC, igor-tkachev commented on Tests/Base/Tests.Base.csproj
> +		<LangVersion>latest</LangVersion>
fixed

2023-11-14 02:33 UTC, igor-tkachev commented on Source/LinqToDB/Tools/IActivity.cs
> +	public interface IActivity : IDisposable
fixed

2023-11-14 03:00 UTC, igor-tkachev commented on Source/LinqToDB.Tools/Activity/ActivityStatistics.cs
> +				Percent = FixUnixPercentFormat($"{(m.CallCount == 0 ? (decimal?)null : m.Elapsed.Ticks / totalTime),7:P}")
yes, different behavior for Win and Lin

2023-11-14 07:07 UTC, igor-tkachev commented
/azp run test-all

2023-11-15 04:53 UTC, igor-tkachev commented
/azp run test-all

2023-11-25 00:31 UTC, igor-tkachev commented
/azp run test-all

2023-12-06 21:29 UTC, igor-tkachev commented
/azp run test-all

2023-12-13 23:29 UTC, igor-tkachev commented
/azp run test-all

2023-12-27 20:15 UTC, igor-tkachev commented
/azp run test-all

2023-12-27 20:31 UTC, igor-tkachev commented
/azp run test-all

2023-12-28 07:46 UTC, igor-tkachev commented
/azp run test-all

2024-01-01 21:25 UTC, MaceWindu requested changes
Added some review comments, will finish review tomorrow

2024-01-01 21:25 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityHierarchy.cs
> +			else if (activityID is not (ActivityID.QueryProviderExecuteT or ActivityID.QueryProviderGetEnumeratorT))
not needed branch/missing code?

2024-01-01 21:25 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityHierarchy.cs
> +						Print(c, indent + 2);
maybe allow user to provide indent size?

2024-01-01 21:25 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityStatistics.cs
xml-docs missing on public api

2024-01-01 21:25 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityStatistics.cs
> +					ExecuteScalar2                  = new("  Execute Scalar 2"),
`2` here in in other places is not clear. Could we improve those names somehow (or clarify in corresponding member xml-doc)?

2024-01-01 21:25 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityStatistics.cs
> +				null!
maybe add `// Total, set below` comment

2024-01-01 21:25 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityStatistics.cs
> +				ActivityID.TransactionDisposeAsync         => TransactionCommitAsync,
wrong return values

2024-01-01 21:25 UTC, MaceWindu commented on Source/LinqToDB.Tools/Activity/ActivityStatistics.cs
> +			static string FixUnixPercentFormat(string str)
maybe we shouldn't mess with system-provided format? It depends on used system culture and could be overrided by user in both windows/linux

2024-01-02 14:51 UTC, MaceWindu requested changes
remaining part review

2024-01-02 14:51 UTC, MaceWindu commented on Source/LinqToDB/Tools/IActivity.cs
> +	/// Represents a user defined operation with context to be used for Activity Service events.
`user-defined`

2024-01-02 14:51 UTC, MaceWindu commented on Source/LinqToDB/Tools/ActivityService.cs
> +			var factory = _factory!;
I would prefer if we handle null here and return null/throw explicit exception

2024-01-02 14:51 UTC, MaceWindu commented on Source/LinqToDB/AsyncExtensions.cs
> +#if NATIVE_ASYNC
👍

2024-01-02 14:51 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +			await using (ActivityService.StartAndConfigureAwait(ActivityID.CommandExecuteNonQueryAsync))
Interceptors case is interesting. Should we include interceptor call into activity scope or just ignore time spent it it eve if interceptor provides result value like it is implemented now?

2024-01-02 14:51 UTC, MaceWindu commented on Source/LinqToDB/ITableT.cs
> +		// TODO: IT: WTF? it should be 'class'.
we can review it in v6, not earlier

2024-01-02 14:51 UTC, MaceWindu commented on Source/LinqToDB/Linq/QueryRunner.cs
> +				var a = Configuration.TraceMaterializationActivity ? ActivityService.Start(ActivityID.Materialization) : null;
Could you create tracing article in docs repo based on examples doc and incude information about new configuration options?

2024-01-03 06:39 UTC, igor-tkachev commented
/azp run test-all

2024-01-03 14:40 UTC, MaceWindu submitted a review, later dismissed

2024-01-03 20:19 UTC, viceroypenguin commented on Source/LinqToDB.Tools/Activity/StatActivity.cs
> +			lock (this)
@igor-tkachev ping to fix this. I agree, you can use an `Interlocked.Add()` here for better behavior.

2024-01-03 20:24 UTC, viceroypenguin commented on Source/LinqToDB/Async/AsyncDbConnection.cs
> +				await using (activity)
All `await using` should use `await using (activity.ConfigureAwait(Common.Configuration.ContinueOnCapturedContext))`. This will match existing and correct behavior regarding returning to correct async context.

2024-01-03 20:32 UTC, viceroypenguin commented on Source/LinqToDB/Tools/ActivityService.cs
> +		sealed class AsyncDisposableWrapper(ConfiguredAsyncDisposable configured) : IAsyncDisposable
This wraps a configured disposable, but removes the vital information necessary for the calling code to configure properly. If the calling code `await`s on an `AsyncDisposableWrapper`, then the awaiter that they wait on is the state machine in `DisposeAsync()` instead of the configured awaiter that informs the continuation to skip the context reset.

2024-01-04 01:38 UTC, igor-tkachev commented on Source/LinqToDB/Tools/ActivityService.cs
> +		sealed class AsyncDisposableWrapper(ConfiguredAsyncDisposable configured) : IAsyncDisposable
Yeh. `await using` probably the stupidest part of C# design.

2024-01-04 02:30 UTC, igor-tkachev commented
/azp run test-all

2024-01-04 13:17 UTC, viceroypenguin requested changes
last change before my approval.

2024-01-04 13:17 UTC, viceroypenguin commented on Source/LinqToDB.Tools/Activity/StatActivity.cs
> +		}
```suggestion
		void Stop(TimeSpan time) 
			=> Interlocked.Add(ref _elapsedTicks, time.Ticks);
```

2024-01-04 18:28 UTC, igor-tkachev commented on Source/LinqToDB.Tools/Activity/StatActivity.cs
> +		}
Lets see if works for Linux.

2024-01-04 18:29 UTC, viceroypenguin submitted a review, later dismissed

2024-01-04 18:31 UTC, igor-tkachev commented
/azp run test-all

2024-01-05 10:19 UTC, sdanyliv commented on Source/LinqToDB.Tools/Activity/ActivityStatistics.cs
> +		static IStatActivity[] All;
Why not mark everything as read-only?

2024-01-05 10:50 UTC, sdanyliv submitted a review, later dismissed
Approving, **squash and merge** but you have to resolve conflicts with `refactor/parsing` branch.

2024-01-18 11:03 UTC, MaceWindu approved these changes

2024-01-19 04:25 UTC, igor-tkachev commented
/azp run test-all

2024-01-23 00:46 UTC, viceroypenguin approved these changes

2024-01-23 18:17 UTC, merged