#4172: Fixes issue with empty string check in Oracle
linq2db/linq2db pull request #4173
Opened 2023-06-20 05:59 UTC by divyanshbhatia1

Update Oracle11SqlOptimizer to add null check based on operator

#4172

2023-06-20 07:27 UTC, MaceWindu commented
/azp run test-all

2023-06-20 14:11 UTC, MaceWindu requested changes
We need test(s), that demonstrate this behavior

2023-06-23 07:49 UTC, MaceWindu requested changes

2023-06-23 07:49 UTC, MaceWindu commented on Tests/Linq/DataProvider/OracleTests.cs
> +				using var users = db.CreateTable<ISSUE4172TABLE>();
Use CreateLocalTable helper instead of try/catch with delete

2023-06-23 07:49 UTC, MaceWindu commented on Tests/Linq/DataProvider/OracleTests.cs
> +				using var users = db.CreateTable<ISSUE4172TABLE>();
use CreateLocalTable

2023-06-23 15:03 UTC, MaceWindu commented
/azp run test-all

2023-06-23 15:28 UTC, jods4 requested changes

2023-06-23 15:28 UTC, jods4 commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
> +								}
This changes the behaviors of operators >= and <=. 
It's a breaking change for `Code >= ""`, admittedly an edge case but there's no good reason to break this.

I suggest to simplify to:
```csharp 
bool isNotEqual = expr.Operator == SqlPredicate.Operator.NotEqual;

sc.Conditions.Add(new(
  isNot: false, 
  new SqlPredicate.IsNull(expr.Expr2, isNot: isNotEqual),
  isOr: !isNotEqual)
);
```

2023-06-23 15:28 UTC, jods4 commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
> +								}
Same as comment on `expr.Expr2 == ""`

2023-06-26 22:09 UTC, igor-tkachev commented
/azp run test-all

2023-06-27 08:23 UTC, jods4 commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
> +								  new SqlPredicate.IsNull(expr.Expr2, isNot: isNotEqual),
Copy-paste mistake. It should be `expr.Expr1` on this side.

2023-06-27 08:44 UTC, jods4 approved these changes

2023-06-27 08:45 UTC, jods4 commented
/azp run test-all

2023-07-30 13:33 UTC, MaceWindu approved these changes

2023-07-30 13:33 UTC, merged