Fix association fields mapping.
linq2db/linq2db pull request #4201
Opened 2023-07-11 02:08 UTC by igor-tkachev

2023-07-11 02:08 UTC, igor-tkachev commented
/azp run test-all

2023-07-11 03:00 UTC, igor-tkachev commented
/azp run test-all

2023-07-11 04:00 UTC, igor-tkachev commented
/azp run test-all

2023-07-11 04:06 UTC, igor-tkachev commented
/azp run test-all

2023-07-11 11:40 UTC, MaceWindu commented
/azp run test-all

2023-07-11 11:43 UTC, MaceWindu requested changes

2023-07-11 11:43 UTC, MaceWindu commented on Source/LinqToDB/Common/ConvertBuilder.cs
> +		internal static readonly MethodInfo _defaultConverter = MemberHelper.MethodOf(() => ConvertDefault(null!, typeof(int)));
`_defaultConverter ` -> `DefaultConverter `

2023-07-11 17:50 UTC, MaceWindu commented
Access tests fail

2023-07-11 23:20 UTC, igor-tkachev commented on Source/LinqToDB/Common/ConvertBuilder.cs
> +		internal static readonly MethodInfo _defaultConverter = MemberHelper.MethodOf(() => ConvertDefault(null!, typeof(int)));
fixed

2023-07-11 23:20 UTC, igor-tkachev commented
/azp run test-access

2023-07-11 23:21 UTC, igor-tkachev commented
/azp run test-all

2023-07-11 23:31 UTC, igor-tkachev commented
/azp run test-all

2023-07-12 11:00 UTC, MaceWindu commented
/azp run test-all

2023-07-30 21:09 UTC, MaceWindu commented
/azp run test-all

2023-08-04 16:46 UTC, MaceWindu requested changes

2023-08-04 16:46 UTC, MaceWindu commented on Tests/Linq/UserTests/AssociationTests.cs
> +		public void Test([DataSources] string context)
it would be better to execute query against database so we can validate generated sql and have baselines

2023-08-06 02:13 UTC, igor-tkachev commented
/azp run test-all

2023-08-06 02:13 UTC, igor-tkachev commented on Tests/Linq/UserTests/AssociationTests.cs
> +		public void Test([DataSources] string context)
fixed

2023-08-06 09:05 UTC, MaceWindu approved these changes

2023-08-06 09:06 UTC, MaceWindu commented
btw, enum join condition looks awful...

2023-08-06 09:08 UTC, merged