Fixed hints for UNION.
linq2db/linq2db pull request #4202
Opened 2023-07-11 03:54 UTC by igor-tkachev

2023-07-11 03:58 UTC, igor-tkachev commented
/azp run test-all

2023-07-11 12:38 UTC, sdanyliv approved these changes

2023-07-11 14:05 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
> +				BuildStep = Step.QueryExtensions; BuildQueryExtensions(statement, false, true);
```suggestion
				BuildStep = Step.QueryExtensions; BuildQueryExtensions(statement, buildQueryHints: false, buildSubQueryHints: true);
```

2023-07-11 14:05 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Oracle/OracleSqlBuilderBase.cs
> +				BuildQueryExtensions(HintBuilder, statement.SqlQueryExtensions, null, " ", null, true, true);
```suggestion
				BuildQueryExtensions(HintBuilder, statement.SqlQueryExtensions, null, " ", null, buildQueryHints: true, buildSubQueryHints: true);
```

2023-07-11 14:07 UTC, viceroypenguin commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +			BuildStep = Step.QueryExtensions; BuildQueryExtensions  (statement, false, true);
```suggestion
			BuildStep = Step.QueryExtensions; BuildQueryExtensions  (statement, buildQueryHints: false, buildSubQueryHints: true);
```

2023-07-11 14:08 UTC, viceroypenguin commented on Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
> +				BuildStep = Step.QueryExtensions; BuildQueryExtensions(statement, false, true);
```suggestion
				BuildStep = Step.QueryExtensions; BuildQueryExtensions(statement, buildQueryHints: false, buildSubQueryHints: true);
```

2023-07-13 05:05 UTC, igor-tkachev commented
/azp run test-all

2023-07-13 10:44 UTC, viceroypenguin submitted a review, later dismissed

2023-07-30 21:10 UTC, MaceWindu commented
/azp run test-all

2023-08-04 17:16 UTC, MaceWindu commented on Tests/Linq/Extensions/QueryExtensionTests.cs
> +			.AsPostgreSQL()
is it correct? postgresql disabled for this test

2023-08-04 17:20 UTC, MaceWindu commented
I wonder why we need wrapping subquery for second query (`ClickHouseTests.ClickHouseUnionTest`)

```sql
SELECT
	p.ID,
	p.TS
FROM
	ReplacingMergeTreeTable p FINAL
UNION DISTINCT
SELECT
	t2.ID,
	t2.TS
FROM
	(
		SELECT
			p_1.ID as ID,
			p_1.TS as TS
		FROM
			ReplacingMergeTreeTable p_1,
			(
				SELECT
					*
				FROM
					ReplacingMergeTreeTable t1
			) c_1 FINAL
	) t2
SETTINGS convert_query_to_cnf=false
```

2023-08-04 17:27 UTC, MaceWindu requested changes
subqueries with hints break subquery elimination which result in non-linear UNION. This will result in SQL errors in recursive CTEs with hints

2023-08-04 17:32 UTC, MaceWindu commented
My bad, there is no issue with union, but still I wonder why we generate so many subqueries that look unnecessary

2023-08-04 17:46 UTC, MaceWindu commented
Reviewed baselines once again, here are my questions:
- UnionTest: enable pgsql or remove pgsql hints
- PostgreSQLUnionTest: AsSubQuery moved joined table to subquery, but hint applied to main query which should put lock to both joined tables instead of one
- MySqlUnionTest: same issue with subquery and hint as with postgresql test. Also query hint location looks strange - I think it will apply to first subquery only

2023-08-06 06:58 UTC, igor-tkachev commented
/azp run test-all

2023-08-06 07:02 UTC, igor-tkachev commented on Tests/Linq/Extensions/QueryExtensionTests.cs
> +			.AsPostgreSQL()
fixed

2023-08-06 07:03 UTC, igor-tkachev commented
> My bad, there is no issue with union, but still I wonder why we generate so many subqueries that look unnecessary

Is this related to this fix?

2023-08-06 07:05 UTC, igor-tkachev commented
/azp run test-all

2023-08-06 09:10 UTC, MaceWindu approved these changes

2023-08-06 09:11 UTC, MaceWindu commented
/azp run test-all

2023-08-30 18:53 UTC, MaceWindu commented
/azp run test-all

2023-08-31 07:39 UTC, merged