BUG: Using hint in subquery.
linq2db/linq2db pull request #4203
Opened 2023-07-11 17:55 UTC by igor-tkachev

2023-07-13 06:48 UTC, igor-tkachev commented
/azp run test-all

2023-07-13 10:40 UTC, viceroypenguin commented on Source/LinqToDB/Common/Internal/MethodCache.cs
> +		}
```suggestion
		class Info
		{
			public bool IsQueryable { get; set; }
		}
```

2023-07-13 14:32 UTC, igor-tkachev commented
/azp run test-all

2023-07-19 18:58 UTC, MaceWindu requested changes
Could you provide more details what wasn't working properly?

2023-07-19 18:58 UTC, MaceWindu commented on Source/LinqToDB/Common/Internal/MethodCache.cs
> +					var attrs = m.GetAttribute<IsQueryableAttribute>();
use `HasAttribute` API instead of `GetAttribute` + length check

2023-07-19 18:58 UTC, MaceWindu commented on Source/LinqToDB/Common/Internal/MethodCache.cs
> +		public static void ClearCache()
not called by linq2db and unreachable to user as cache class is internal. I propose to make class public

2023-07-19 18:58 UTC, MaceWindu commented on Source/LinqToDB/Common/Internal/MethodCache.cs
> +		static MemberCache()
not needed? or cache cleaners registration should be enabled?

2023-07-20 03:27 UTC, igor-tkachev commented on Source/LinqToDB/Expressions/InternalExtensions.cs
> +				MemberCache.GetMemberInfo(method.Method).IsQueryable;
The fix.

2023-07-20 03:35 UTC, igor-tkachev commented on Source/LinqToDB/Common/Internal/MethodCache.cs
> +		public static void ClearCache()
I am not sure we need it at all.

2023-07-20 03:38 UTC, igor-tkachev commented on Source/LinqToDB/Common/Internal/MethodCache.cs
> +					var attrs = m.GetAttribute<IsQueryableAttribute>();
done

2023-07-20 03:39 UTC, igor-tkachev commented on Source/LinqToDB/Common/Internal/MethodCache.cs
> +		static MemberCache()
done

2023-07-20 03:39 UTC, igor-tkachev commented
/azp run test-all

2023-07-20 03:40 UTC, igor-tkachev commented on Source/LinqToDB/Common/Internal/MethodCache.cs
> +		public static void ClearCache()
fixed

2023-07-20 16:03 UTC, MaceWindu approved these changes

2023-07-30 21:10 UTC, MaceWindu commented
/azp run test-all

2023-07-30 21:10 UTC, MaceWindu commented
/azp run test-all

2023-08-04 16:17 UTC, MaceWindu approved these changes

2023-08-04 16:18 UTC, merged