Nullable bool comparison
linq2db/linq2db pull request #4217
Opened 2023-07-20 05:45 UTC by igor-tkachev

2023-07-20 05:46 UTC, igor-tkachev commented
/azp run test-all

2023-07-20 05:48 UTC, igor-tkachev commented
/azp run test-all

2023-07-20 05:48 UTC, igor-tkachev commented
/azp run test-all

2023-07-20 06:05 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 13:11 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 13:12 UTC, igor-tkachev commented
/azp run test-all

2023-08-01 16:39 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +					isNullable = value == null && (typeof(bool?) == left.Type || r.CanBeNull);
It seems to me this extra check has no effect.

If `value` is null, then the next `if (value != null && ...)` block is not entered and the value of `isNullable` is never read.

2023-08-01 16:39 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +					isNullable = value == null && (typeof(bool?) == right.Type || l.CanBeNull);
Same here, for the same reason as previous comment.

2023-08-01 16:39 UTC, jods4 commented on Tests/Linq/Linq/WhereTests.cs
> +				Contains("[t].[Value] = 1 AND [t].[Value] IS NOT NULL"));
I don't quite like checking syntax because it's fragile. 
I'd rather test that the outcome for every possible case amongst true/false/null, is correct.

The problem with syntax is that it's easily gonna break:
- when we use this test with another DB provider that doesn't use `[t]` as name quotes;
- when the sql formatting changes and line breaks are inserted
- when for some reason the sql generation changes and inverts the AND order.
- when we upgrade to a better syntax such as `t.Value IS NOT FALSE` (supported in dbs such as Postgres or Oracle 23).

2023-08-01 16:39 UTC, jods4 commented on Tests/Linq/Linq/WhereTests.cs
> +		public void NullableBoolTest1([DataSources(TestProvName.AllSybase)] string context)
Why test Sybase only? 
If you run the query and check the results, we could verify this works in all providers.
It would be a good thing given bools can be represented very differently depending on provider.

2024-01-25 01:21 UTC, igor-tkachev commented on Tests/Linq/Linq/WhereTests.cs
> +		public void NullableBoolTest1([DataSources(TestProvName.AllSybase)] string context)
Except Sybase. Sybase does not allow null values for BIT columns.

2024-01-25 04:47 UTC, igor-tkachev commented
/azp run test-all

2024-01-26 19:47 UTC, MaceWindu commented on Directory.Packages.props
> +		<PackageVersion Include="Octonica.ClickHouseClient"                             Version="2.3.2"         />
don't update Octonica provider. It is fixed on 2.2.9 as newer versions contain regressions

2024-01-26 19:47 UTC, MaceWindu requested changes
not ready, tests failing

2024-01-26 21:03 UTC, jods4 commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
Can you please add tests (and support if needed) for `CompareNullsAsValue: false`?

I'd like C# `t.Value != true` to compile to SQL `value <> True`, like every other type does without `CompareNullsAsValue`.

2024-02-01 04:53 UTC, igor-tkachev commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
It needs more development as `bool` comparison is hardly hardcoded by some reason.

2024-02-01 04:54 UTC, igor-tkachev commented
/azp run test-all

2024-02-01 09:33 UTC, MaceWindu commented on Directory.Packages.props
> +		<PackageVersion Include="Octonica.ClickHouseClient"                             Version="2.3.2"         />
Still not reverted. versions > 2.2.9 are broken

2024-02-01 22:07 UTC, igor-tkachev commented
/azp run test-all

2024-02-02 00:17 UTC, jods4 commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
ok it needs dev. but why did you resolve the comment, what's the plan?

please do not release half the feature. If you do, then implementing `CompareNullsAsValue: false` later will be a breaking change (which we _really_ want to make).

2024-02-02 02:33 UTC, igor-tkachev commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
We have two topics here:
- `CompareNullsAsValue: false` - I added this parameter to the test.
- `t.Value != true` - no plans until new parser release. Anyway, this is out of scope of this PR. You can create new issue/PR to remember it.

2024-02-02 09:57 UTC, jods4 commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
Ok 👍
No problem with adding comparisons to bools later, I just wanted to ensure that whatever is in the PR works in all configurations.

2024-02-02 12:32 UTC, igor-tkachev commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
You can always add any additional tests to any PRs you are interested in.
Can I resolve it now? :)

2024-02-02 13:44 UTC, jods4 commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
I'm sorry I don't have much time right now to contribute.
I see `NotNullableTest` tests `compareNullsAsValues` but it's not meaningful as the source is non-nullable so there's no change in codegen between the two modes.

Can please you add `compareNullsAsValues` to this test (`ValueTest`)  so that nullable values and differences in codegen are covered? After that the PR is good for me 👍

2024-02-02 15:24 UTC, sdanyliv commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
Why `t.Value != true` to `value <> True`? I know that I have implemented code which always translates to equal operator, in this case `value == False`

2024-02-02 18:40 UTC, jods4 commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
@sdanyliv for bools sure the outcome is indeed the same, so is there any reason why you made that flip?
I like that the SQL is a straightforward translation of my code, as much as possible: if I write `x != true` I expect `x <> True` in SQL and if I write `x == false` I expect `x = False`, although as I said: it doesn't matter much as both expressions are equivalent.

Note that similar transformations do not apply to `IS` operators. RDBMS that supports boolean types usually also support `IS [NOT] [TRUE|FALSE|UNKNOWN]` (where `NULL` is often supported instead of `UNKNOWN`).
In this context, `IS NOT TRUE` is **not** equivalent to `IS FALSE`.

2024-02-03 17:55 UTC, MaceWindu commented on Tests/Linq/Linq/NullableBoolTests.cs
> +		const string ProvidersThatDoNotSupportNullableBool = $"{TestProvName.AllAccess},{TestProvName.AllSybase},{ProviderName.ClickHouseOctonica}";
```suggestion

```suggestion

		// octonica blocked by https://github.com/Octonica/ClickHouseClient/issues/56
		const string ProvidersThatDoNotSupportNullableBool = $"{TestProvName.AllAccess},{TestProvName.AllSybase},{ProviderName.ClickHouseOctonica}";
```
				const string ProvidersThatDoNotSupportNullableBool = $"{TestProvName.AllAccess},{TestProvName.AllSybase},{ProviderName.ClickHouseOctonica}";
```

2024-02-03 17:55 UTC, MaceWindu commented on Tests/Linq/Linq/NullableBoolTests.cs
> +		// octonica blocked by https://github.com/Octonica/ClickHouseClient/issues/56
added comment to unblock testing when Octonica provider becames usable again

2024-02-03 17:57 UTC, MaceWindu commented on Tests/Linq/Linq/NullableBoolTests.cs
> +		// octonica blocked by https://github.com/Octonica/ClickHouseClient/issues/56
and yes, this specific issue fixed (partially) in 2.2.10, but more issues that cannot be workarounded were introduced

2024-02-03 18:03 UTC, MaceWindu commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
I'm not sure I like this discussion :) If we have more cases to cover in future,  it makes sense to add tests now and mark them with `ActiveIssue`

2024-02-03 19:08 UTC, MaceWindu submitted a review, later dismissed

2024-02-03 21:40 UTC, igor-tkachev commented on Tests/Linq/Linq/NullableBoolTests.cs
> +				Assert.That(LastQuery, Contains.Substring("IS NULL"));
> Why `t.Value != true` to `value <> True`? I know that I have implemented code which always translates to equal operator, in this case `value == False`

I think user should get what he writes. If user writes `Field != false`, this is his business and he should get the same SQL. The magic you added can be unwanted, should not be default, and should be implemented only with compatibility flag.

2024-02-03 21:51 UTC, igor-tkachev commented
/azp run test-all

2024-02-04 11:33 UTC, MaceWindu approved these changes

2024-02-05 20:43 UTC, igor-tkachev commented
/azp run test-all

2024-02-05 22:17 UTC, MaceWindu commented
/azp run test-all

2024-02-10 17:47 UTC, MaceWindu commented
@linq2db/developers any reviews pending or it could be merged?

2024-02-10 17:50 UTC, viceroypenguin approved these changes

2024-02-12 04:23 UTC, merged