Add tests and fix for UniqueParameterNormalizer
linq2db/linq2db pull request #4230
Opened 2023-07-30 03:30 UTC by Shane32

Currently the `UniqueParameterNormalizer` fails when attempting to shorten duplicated input names that are longer than `MaxLength` (default of 50 chars).  This patches that (see [here](https://github.com/linq2db/linq2db/pull/4146#discussion_r1278475938)).  Also it patches an infinite loop in the case where `MaxLength` is very short and the loop cannot find a unique parameter name.  Finally, I optimized the `MakeValidName` method to use `stackalloc` rather than attempting to use the `ObjectPool` to pull and use a `StringBuilder` instance.  Although perhaps there are no allocations either way (except for the final allocation), it should be faster, as there are no locks.  For older TFMs `stackalloc` is not used, as it requires a NuGet reference to `System.Memory`, and `string.ToCharArray()` is used, which causes an additional allocation.  (It still should be faster than an object pool for short strings, based on my experiences with GraphQL.NET, but I did not run benchmarks for this exact scenario.)  I also added unit tests for the `UniqueParameterNormalizer` class.

2023-07-30 04:17 UTC, Shane32 commented
/azp run test-all

2023-07-30 11:11 UTC, MaceWindu approved these changes
👍

2023-07-30 11:21 UTC, MaceWindu commented
> The implementation converts null to the value of DefaultName. If this is expected behavior, why is the return type nullable? Perhaps because NoopParameterNormalizer returns the input value without changes (including returning null for null). So then should not UniqueParametersNormalizer return null when the input is null? Or we could ask why is the input value nullable? It would seem that the behavior of null should be consistent and defined in the interface -- either it should return null for null or it should return a string for null. Just a thought; this PR does not address that, and it is likely that there is a valid reason here.

Yep, because:
- input could be null at least according to existing anntations and it is not easy to track down wether we can get null here or not
- output is null also only because of `NoopParameterNormalizer`. This is acceptable only for this normalizer instance because it is used with providers which doesn't use provider names. Feel free to improve annotations if you have ideas how to do it :)

> Any reason Normalize is not marked virtual? Not a big deal since a derived class can implement IQueryParametersNormalizer on the derived class, but I'm not sure why that choice was made whereas most of the other methods are protected virtual.

No big reason, just don't see value in virtual here currently

2023-07-30 13:46 UTC, Shane32 commented
Looks like some of the tests failed on the "checkout test baselines" step.  Is there a way to re-run the failed tests?

2023-07-30 13:50 UTC, MaceWindu commented
nope, currently our workflow not restartable if no baselines modified + we have storage issue with oracle 21/23 images, so they will not run anyways. You can run specific db pipeline (e.g. `/azp run test-oracle`), but as I said, it will fail for oracle

2023-07-30 14:07 UTC, Shane32 commented
> The implementation converts null to the value of DefaultName ...

> ... Feel free to improve annotations if you have ideas how to do it :)

Well, we could add `[return: NotNullIfNotNull(nameof(originalName))]` - but it is not needed for the only use case, so I think it's good as-is.

2023-07-30 19:05 UTC, igor-tkachev approved these changes

2023-07-30 21:12 UTC, MaceWindu commented
/azp run test-all

2023-08-05 18:41 UTC, Shane32 commented on Tests/Linq/DataProvider/UniqueParametersNormalizerTests.cs
> +		public async Task CalledWithCorrectNames([DataSources(false)] string context)
This test currently fails.  The normalizer should be called with "search" as the argument 3 times, but instead for the 3rd select query in the union, it is called with "search_1", so the generated names are "search", "search_1" and "search_1_1".

2023-08-05 18:54 UTC, Shane32 commented on Tests/Linq/DataProvider/UniqueParametersNormalizerTests.cs
> +		public async Task ExecutesDeterministically([DataSources(false)] string context)
This test currently fails.  Any query should execute the same way for subsequent executions (regardless of the behavior of the normalizer).  Here the second execution results in different SQL.

2023-08-06 14:05 UTC, MaceWindu commented on Tests/Linq/DataProvider/UniqueParametersNormalizerTests.cs
> +		public async Task ExecutesDeterministically([DataSources(false)] string context)
I will look into it

2023-08-06 17:32 UTC, MaceWindu commented on Tests/Linq/DataProvider/UniqueParametersNormalizerTests.cs
> +		public async Task ExecutesDeterministically([DataSources(false)] string context)
should be fixed now

2023-08-06 17:33 UTC, MaceWindu commented
/azp run test-all

2023-08-06 17:35 UTC, MaceWindu submitted a review, later dismissed
last commit probably will introduce some baselines noise, but all should work now

2023-08-06 20:07 UTC, Shane32 commented
My test does not work on MySQL due to:

> You cannot refer to a TEMPORARY table more than once in the same query.

https://dev.mysql.com/doc/refman/8.0/en/temporary-table-problems.html

This would be proper, correct: `[DataSources(false, TestProvName.AllMySql)]`?

2023-08-06 22:05 UTC, Shane32 commented
Looking at the baselines, many parameter names have been cleaned up, but also in a number of spots there are duplicated parameters.  Could it be that linq2db was deduplicating parameters previously and now isn't?

2023-08-06 22:09 UTC, Shane32 commented
These tests are failing for all Oracle versions:
- XmlTableTest1
- XmlTableTest2
- XmlTableTest3
- XmlTableTest7
- XmlTableTest9

Errors look like this:

```
Error Message:
   System.ArgumentException : Value does not fall within the expected range.
DataConnection: Total Execution Time (Completed): 00:00:00.0012149. Rows Count: 0.

Stack Trace:
   at Oracle.ManagedDataAccess.Client.OracleParameter.set_Value(Object value)
   at LinqToDB.DataProvider.DataProviderBase.SetParameter(DataConnection dataConnection, DbParameter parameter, String name, DbDataType dataType, Object value) in D:\a\1\s\Source\LinqToDB\DataProvider\DataProviderBase.cs:line 396
   at LinqToDB.DataProvider.Oracle.OracleDataProvider.SetParameter(DataConnection dataConnection, DbParameter parameter, String name, DbDataType dataType, Object value) in D:\a\1\s\Source\LinqToDB\DataProvider\Oracle\OracleDataProvider.cs:line 243
   at LinqToDB.Data.DataConnection.QueryRunner.CreateParameter(DataConnection dataConnection, DbCommand command, SqlParameter parameter, SqlParameterValue parmValue, Boolean forGetSqlText) in D:\a\1\s\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 313
   at LinqToDB.Data.DataConnection.QueryRunner.GetParameters(DataConnection dataConnection, PreparedQuery pq, IReadOnlyParameterValues parameterValues, Boolean forGetSqlText) in D:\a\1\s\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 283
   at LinqToDB.Data.DataConnection.QueryRunner.CreateExecutionQuery(DataConnection dataConnection, IQueryContext context, IReadOnlyParameterValues parameterValues, Boolean forGetSqlText) in D:\a\1\s\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 192
   at LinqToDB.Data.DataConnection.QueryRunner.SetQuery(IReadOnlyParameterValues parameterValues, Boolean forGetSqlText) in D:\a\1\s\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 323
   at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean forGetSqlText) in D:\a\1\s\Source\LinqToDB\Linq\QueryRunnerBase.cs:line 72
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in D:\a\1\s\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 622
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber)+MoveNext() in D:\a\1\s\Source\LinqToDB\Linq\QueryRunner.cs:line 400
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tests.DataProvider.OracleTests.XmlTableTest9(String context) in D:\a\1\s\Tests\Linq\DataProvider\OracleTests.cs:line 2112
```

2023-08-23 07:40 UTC, MaceWindu commented
@Shane32 could you add/verify regression test for #4254?

2023-08-23 07:42 UTC, Shane32 commented
Probably. Let me take a look.

2023-08-24 03:33 UTC, Shane32 commented
@MaceWindu Done.  I only use MS SQL, but I can verify that the added test fails on MS SQL under the `master` branch (similar error to the reported one) and passes under this branch.  The test is set up as `[IncludeDataSources(TestProvName.AllPostgreSQL95Plus, TestProvName.AllSqlServer2008Plus)]` so we can see if it passes with postgres also.

To replicate the user's scenario most closely, the data connection is closed and reopened multiple times during the test.  Due to this I am using non-temporary tables, named with a prefix of `issue_4254_`, which are dropped at the end of the test.  It is likely enough that I can simplify the test to use a single connection, and then use temporary tables/etc.  Let me know if I should change it - thanks!

2023-08-24 03:33 UTC, Shane32 commented
/azp run test-all

2023-08-24 11:59 UTC, MaceWindu commented
@Shane32 thanks!

2023-08-30 13:34 UTC, MaceWindu commented
/azp run test-all

2023-08-31 16:07 UTC, MaceWindu commented
/azp run test-all

2023-08-31 16:08 UTC, MaceWindu approved these changes

2023-08-31 17:57 UTC, MaceWindu requested changes
note to myself: check why deduplication of parameters doesn't work for some baselines

2023-09-01 10:18 UTC, MaceWindu approved these changes

2023-09-01 10:19 UTC, merged