Support Guid ToString in SqLite, add test for mssql and sqlite
linq2db/linq2db pull request #4297
Opened 2023-10-10 11:51 UTC by jogibear9988

2023-10-14 13:58 UTC, sdanyliv commented on Source/LinqToDB/DataProvider/SQLite/SQLiteSqlOptimizer.cs
> +						if (ftype == typeof(string) && func.Parameters[1].SystemType == typeof(Guid))
It is really bad place to do that. Ask @MaceWindu for details.

2023-10-14 14:26 UTC, jogibear9988 commented on Source/LinqToDB/DataProvider/SQLite/SQLiteSqlOptimizer.cs
> +						if (ftype == typeof(string) && func.Parameters[1].SystemType == typeof(Guid))
@MaceWindu could you help me?

2023-10-15 15:29 UTC, jogibear9988 commented
Should I add "Guid.ToString" in Expressions.cs and create a Builder wich does nothing in Standard and in Sqlite I implement the logic. Same as I've done for TimeSpan in this: https://github.com/linq2db/linq2db/pull/3994/files#diff-0381ba7e238d0f1809d47075f54b06e6c5fb0dfd9c7f0ed1017188c0eab15e38
Would this be a better solution?

2023-10-23 09:42 UTC, MaceWindu commented
I'm a bit lost here. What you need to achieve? If you need guid.ToString mapping to SQL you should implement it in mappings (Expressions.cs probably).

Another thing that looks incorrect is that proposed mapping generates upper-case guid. It is common to use lowercased guid string and default mapping should generate lowercased guid.

2023-10-23 11:44 UTC, jogibear9988 commented
> I'm a bit lost here. What you need to achieve? If you need guid.ToString mapping to SQL you should implement it in mappings (Expressions.cs probably).
> 
> Another thing that looks incorrect is that proposed mapping generates upper-case guid. It is common to use lowercased guid string and default mapping should generate lowercased guid.

I'd like to be able to use for example guid.ToString().Contains("aa") in LINQ.
I can change to a lowercase. And I look to move to expressions

2024-01-19 22:21 UTC, igor-tkachev commented
We already have it for other types. See `Expressions.cs` line 555.

2024-01-25 21:25 UTC, jogibear9988 commented
@igor-tkachev 
changed code to use expression.cs and a converter in Sql Helper class

2024-01-25 21:44 UTC, jogibear9988 commented
/azp run test-all

2024-01-27 12:49 UTC, jogibear9988 commented
/azp run test-all

2024-01-27 12:58 UTC, jogibear9988 commented
The test 3791 does not work for ClickHouse with this change

ClickHouse.Client.ClickHouseServerException : Code: 53. DB::Exception: Can't infer common type for joined columns: OtherId: Nullable(String) at left, a_Association.Id: UUID at right. There is no supertype for types String, UUID because some of them are String/FixedString and some of them are not. (TYPE_MISMATCH) (version 23.12.2.59 (official build))



		public void Issue3791Test([DataSources] string context)
		{
			var ms = new MappingSchema();
			ms.SetConvertExpression<Guid, string>(a => a.ToString());
			ms.SetConvertExpression<string, Guid>(a => Guid.Parse(a));

			using var db = GetDataContext(context);

			using var table = db.CreateLocalTable<Issue3791Table>();
			using var _     = db.CreateLocalTable<Issue3791GuidTable>();

			table.LoadWith(a => a.Association).ToList();
		}


but for me it's not clear, when the convertExpression is used. Do I need to change smth. or need this to be fixed inside of linq2db?

2024-01-27 14:39 UTC, jogibear9988 commented
Is the  ms.SetConvertExpression<Guid, string> used before my handling of ToSting in Expressions.cs?

2024-01-27 16:38 UTC, jogibear9988 commented
/azp run test-all

2024-01-27 19:52 UTC, jogibear9988 commented
/azp run test-all

2024-01-28 03:50 UTC, jods4 commented on Tests/Linq/UserTests/Issue4295Tests.cs
> +		public void TestGuidToString([IncludeDataSources(TestProvName.AllSQLite, TestProvName.AllSqlServer)] string context)
shouldn't we test for all RDBMS?

2024-01-28 07:36 UTC, jogibear9988 commented
I'll add test for every DBMS, and remove the Mapping in Expression.cs.
I thought it would only be used on explicit "ToString" calls, but it also seems to be used when Guid is mapped to a string, or compared inside of Database with a string column.
This maybe then would break.
I rename the function to "GuidToNormalizedString".
When we have the possiblity to create own additions to "Expressions.cs" as we said in the Regex Pull, everybody could map for themself

2024-01-28 09:24 UTC, jogibear9988 commented
/azp run test-all

2024-01-28 19:16 UTC, jogibear9988 commented
/azp run test-all

2024-01-29 09:20 UTC, jogibear9988 commented
/azp run test-all

2024-01-29 17:47 UTC, jogibear9988 commented
/azp run test-all

2024-01-29 23:13 UTC, jogibear9988 commented
all tests work, ready for review

2024-01-29 23:42 UTC, viceroypenguin commented on Source/LinqToDB/Sql/Sql.cs
> +		public static string? GuidToNormalizedString(Guid? guid)
```suggestion
		[return: NotNullIfNotNull(nameof(guid))]
		public static string? GuidToNormalizedString(Guid? guid)
```

2024-01-31 13:40 UTC, viceroypenguin submitted a review, later dismissed

2024-01-31 13:42 UTC, viceroypenguin submitted a review, later dismissed

2024-01-31 13:43 UTC, viceroypenguin commented
/azp run test-all

2024-01-31 19:44 UTC, jogibear9988 commented
1 test failed, but it's unrelated to the pull req, cause the Code from the pull req is only used in the new test...

<img width="739" alt="image" src="https://github.com/linq2db/linq2db/assets/364896/5a5ae9b3-2aff-4a17-97d7-a75e6d060c56">

2024-02-01 01:37 UTC, igor-tkachev requested changes

2024-02-01 01:37 UTC, igor-tkachev commented on Source/LinqToDB/Sql/Sql.cs
> +		[Extension("", BuilderType = typeof(GuidToStringBuilder), PreferServerSide = true)]
Also add Sql Server conversion as `CAST({0} AS char(36))`.

2024-02-01 01:37 UTC, igor-tkachev commented on Source/LinqToDB/Linq/Expressions.cs
Should we add specific `Guid.ToString()` mapping and use your function?
But in this case it should be lower-cased.

2024-02-01 01:37 UTC, igor-tkachev commented on Source/LinqToDB/Sql/Sql.cs
> +		[Expression(PN.PostgreSQL, "Upper(Cast({0} as VarChar(36)))", IsNullable = IsNullableType.IfAnyParameterNullable, PreferServerSide = true)]
Why `Upper`? In most cases the conversion is done to lowercase by default.

2024-02-01 05:57 UTC, jogibear9988 commented on Source/LinqToDB/Linq/Expressions.cs
No. I had it inside and removed it. Because for example in some tests there is already a Join of some tables against a string representation of guid. And this will then break cause every database converted the Guid to string differently. I had it inside in my first commits and removed it cause of this. Everybody who do not yet use String Guids and does not depend on the legacy behaviour can add the Expression for the ToString themselves.

I also had it first lowercase and changed to uppercase cause I thought it was more common (it was the default in SQLServer when casting). But now most of the other databses need an Upper. I think, I find lowercase nicer, what do you think? I can change it.

2024-02-01 05:57 UTC, jogibear9988 commented on Source/LinqToDB/Sql/Sql.cs
> +		[Extension("", BuilderType = typeof(GuidToStringBuilder), PreferServerSide = true)]
will do

2024-02-01 06:17 UTC, jogibear9988 commented on Source/LinqToDB/Sql/Sql.cs
> +		[Expression(PN.PostgreSQL, "Upper(Cast({0} as VarChar(36)))", IsNullable = IsNullableType.IfAnyParameterNullable, PreferServerSide = true)]
changed it

2025-02-10 21:46 UTC, jogibear9988 commented
/azp run test-all

2025-02-12 17:12 UTC, sdanyliv commented
Superseeded by https://github.com/linq2db/linq2db/pull/4828

2025-02-12 17:12 UTC, closed without merging