test for issue #4337
linq2db/linq2db pull request #4339
Opened 2023-11-08 15:21 UTC by jogibear9988

2023-11-20 16:06 UTC, MaceWindu commented
still fails with new parser
```sql
System.InvalidOperationException : Element: 't100[91].Id' has unknown source.
-----------------------------------------
In Statement:
-----------------------------------------
(89) SELECT 
	*
FROM (
		(73) SELECT 
			*
		FROM (
				(57) SELECT 
					t57[58].ResourceID = t70[57].ResourceID
				FROM (
						(38) SELECT 
							t38[49].Id = t54[48].Id
						FROM (
								(21) SELECT 
									t21[29].Id = t16[28].Id
								FROM (
										(16) SELECT 
											t16[5].MaterialID = t10[4].MaterialID,
											t16[28].Id        = t10[27].Id
										FROM (
												(10) SELECT 
													t10[1].AisleID    = t11.AisleID,
													t10[4].MaterialID = t11.MaterialID,
													t10[27].Id        = t11.Id
												FROM [ChannelDTO(11)] as t11 (<none>)
											) as t10 (c)
												INNER JOIN (
													(18) SELECT 
														t18[3].Id = t13[2].Id
													FROM (
															(13) SELECT 
																t13[2].Id = t14.Id
															FROM [AisleDTO(14)] as t14 (<none>)
														) as t13 (a)
												) as t18 (<none>) ON ([UID:65](t10[1].AisleID) = (t18[3].Id))
									) as t16 (<none>)
										OUTER APPLY (
											(35) SELECT 
												*
											FROM (
													(33) SELECT 
														t33[17].Id                    = t30[7].Id,
														t33[18].MaterialNumber        = t30[8].MaterialNumber?,
														t33[19].MaterialDescription_1 = t30[9].MaterialDescription_1?,
														t33[20].MaterialDescription_2 = t30[10].MaterialDescription_2?,
														t33[21].MaterialDescription_3 = t30[11].MaterialDescription_3?,
														t33[22].CategoryABC           = t30[12].CategoryABC?,
														t33[23].CategoryCustoms       = t30[13].CategoryCustoms?,
														t33[24].CategoryDimensions    = t30[14].CategoryDimensions?,
														t33[25].CategoryQuality       = t30[15].CategoryQuality?,
														t33[26].CategoryTemperature   = t30[16].CategoryTemperature?
													FROM (
															(30) SELECT 
																t30[7].Id                     = t31.Id,
																t30[8].MaterialNumber         = t31.MaterialNumber?,
																t30[9].MaterialDescription_1  = t31.MaterialDescription_1?,
																t30[10].MaterialDescription_2 = t31.MaterialDescription_2?,
																t30[11].MaterialDescription_3 = t31.MaterialDescription_3?,
																t30[12].CategoryABC           = t31.CategoryABC?,
																t30[13].CategoryCustoms       = t31.CategoryCustoms?,
																t30[14].CategoryDimensions    = t31.CategoryDimensions?,
																t30[15].CategoryQuality       = t31.CategoryQuality?,
																t30[16].CategoryTemperature   = t31.CategoryTemperature?
															FROM [MaterialDTO(31)] as t31 (<none>)
														) as t30 (m)
													WHERE
														(([UID:87](t16[5].MaterialID) = (t30[7].Id)))
												) as t33 (m)
										) as t35 (m) ON 
							) as t21 (<none>)
								OUTER APPLY (
									(54) SELECT 
										t54[48].Id = t51[40].Id
									FROM (
											(51) SELECT 
												t51[40].Id              = t48[34].Id,
												t51[41].ChannelID       = t48[32].ChannelID,
												t51[42].Name            = t48[35].Name?,
												t51[43].Status          = t48[36].Status,
												t51[44].AisleNumber     = t48[37].AisleNumber,
												t51[45].CategoryABC     = t48[38].CategoryABC?,
												t51[46].HeightClass     = t48[39].HeightClass,
												t51[47].DepthCoordinate = t48[33].DepthCoordinate
											FROM (
													(48) SELECT 
														t48[32].ChannelID       = t49.ChannelID,
														t48[33].DepthCoordinate = t49.DepthCoordinate,
														t48[34].Id              = t49.Id,
														t48[35].Name            = t49.Name?,
														t48[36].Status          = t49.Status,
														t48[37].AisleNumber     = t49.AisleNumber,
														t48[38].CategoryABC     = t49.CategoryABC?,
														t48[39].HeightClass     = t49.HeightClass
													FROM [StorageShelfDTO(49)] as t49 (<none>)
												) as t48 (a1)
											WHERE
												((([UID:111](t21[29].Id) = (t48[32].ChannelID))) AND (([UID:112](1) = (t48[33].DepthCoordinate))))
										) as t51 (a1)
								) as t54 (a1) ON 
					) as t38 (<none>)
						OUTER APPLY (
							(70) SELECT 
								t70[57].ResourceID = t68[56].ResourceID
							FROM (
									(68) SELECT 
										t68[54].Id             = t65[52].Id,
										t68[55].StorageShelfID = t65[51].StorageShelfID,
										t68[56].ResourceID     = t65[53].ResourceID
									FROM (
											(65) SELECT 
												t65[51].StorageShelfID = t66.StorageShelfID,
												t65[52].Id             = t66.Id,
												t65[53].ResourceID     = t66.ResourceID
											FROM [RefResourceStorageShelfDTO(66)] as t66 (<none>)
										) as t65 (b1)
									WHERE
										(([UID:125](t38[49].Id)? = (t65[51].StorageShelfID)))
								) as t68 (b1)
						) as t70 (b1) ON 
			) as t57 (<none>)
				OUTER APPLY (
					(86) SELECT 
						*
					FROM (
							(84) SELECT 
								t84[71].Id            = t81[60].Id,
								t84[72].Status        = t81[61].Status,
								t84[73].ResourceLabel = t81[62].ResourceLabel?,
								t84[74].CustomField1  = t81[63].CustomField1,
								t84[75].CustomField2  = t81[64].CustomField2,
								t84[76].CustomField3  = t81[65].CustomField3,
								t84[77].CustomLong1   = t81[66].CustomLong1,
								t84[78].CustomLong2   = t81[67].CustomLong2,
								t84[79].CustomLong3   = t81[68].CustomLong3,
								t84[80].HeightClass   = t81[69].HeightClass,
								t84[81].TypeID        = t81[70].TypeID
							FROM (
									(81) SELECT 
										t81[60].Id            = t82.Id,
										t81[61].Status        = t82.Status,
										t81[62].ResourceLabel = t82.ResourceLabel?,
										t81[63].CustomField1  = t82.CustomField1,
										t81[64].CustomField2  = t82.CustomField2,
										t81[65].CustomField3  = t82.CustomField3,
										t81[66].CustomLong1   = t82.CustomLong1,
										t81[67].CustomLong2   = t82.CustomLong2,
										t81[68].CustomLong3   = t82.CustomLong3,
										t81[69].HeightClass   = t82.HeightClass,
										t81[70].TypeID        = t82.TypeID
									FROM [WmsLoadCarrierDTO(82)] as t82 (<none>)
								) as t81 (c1)
							WHERE
								(([UID:154](t57[58].ResourceID)? = (t81[60].Id)))
						) as t84 (c1)
				) as t86 (c1) ON 
	) as t73 (<none>)
		OUTER APPLY (
			(123) SELECT 
				*
			FROM (
					(121) SELECT 
						t121[107].Id             = t118[95].Id,
						t121[108].Status         = t118[94].Status,
						t121[109].ResourceID     = t118[96].ResourceID,
						t121[110].ProductStatus  = t118[97].ProductStatus,
						t121[111].BatchNumber    = t118[98].BatchNumber?,
						t121[112].BundleUnit     = t118[99].BundleUnit,
						t121[113].CustomField1   = t118[100].CustomField1,
						t121[114].CustomField2   = t118[101].CustomField2,
						t121[115].CustomField3   = t118[102].CustomField3,
						t121[116].MaterialID     = t118[103].MaterialID,
						t121[117].InfeedAdviceID = t118[104].InfeedAdviceID?,
						t121[118].ExpiryDate     = t118[105].ExpiryDate,
						t121[119].CustomDate1    = t118[106].CustomDate1
					FROM (
							(118) SELECT 
								t118[94].Status          = t119.Status,
								t118[95].Id              = t119.Id,
								t118[96].ResourceID      = t119.ResourceID,
								t118[97].ProductStatus   = t119.ProductStatus,
								t118[98].BatchNumber     = t119.BatchNumber?,
								t118[99].BundleUnit      = t119.BundleUnit,
								t118[100].CustomField1   = t119.CustomField1,
								t118[101].CustomField2   = t119.CustomField2,
								t118[102].CustomField3   = t119.CustomField3,
								t118[103].MaterialID     = t119.MaterialID,
								t118[104].InfeedAdviceID = t119.InfeedAdviceID?,
								t118[105].ExpiryDate     = t119.ExpiryDate,
								t118[106].CustomDate1    = t119.CustomDate1
							FROM [Invent [...]

2023-11-20 16:10 UTC, MaceWindu commented
sql in 5.2.2
```sql
    -- SQLite.MS SQLite
DECLARE @take  -- Int32
SET     @take = 1
DECLARE @take_1  -- Int32
SET     @take_1 = 1

SELECT
	[x_10].[Id],
	[x_10].[AisleID],
	[x_10].[MaterialID],
	[x_10].[Id_1],
	[x_10].[AisleNumber],
	[x_10].[PlantID],
	[x_10].[Name],
	[x_10].[m_1],
	[x_10].[MaterialNumber],
	[x_10].[MaterialDescription_1],
	[x_10].[MaterialDescription_2],
	[x_10].[MaterialDescription_3],
	[x_10].[CategoryABC],
	[x_10].[CategoryCustoms],
	[x_10].[CategoryDimensions],
	[x_10].[CategoryQuality],
	[x_10].[CategoryTemperature],
	[x_10].[Id_2],
	[x_10].[ChannelID],
	[x_10].[Name_1],
	[x_10].[Status],
	[x_10].[AisleNumber_1],
	[x_10].[CategoryABC_1],
	[x_10].[HeightClass],
	[x_10].[DepthCoordinate],
	[x_10].[c1],
	[x_10].[ResourceLabel],
	[x_10].[Status_1],
	[x_10].[CustomLong2],
	[x_10].[HeightClass_1],
	[x_10].[TypeID],
	[x_10].[m1],
	[x_10].[MaterialNumber_1],
	[x_10].[MaterialDescription_1_1],
	[x_10].[CategoryABC_2],
	[x_10].[i1],
	[x_10].[BatchNumber],
	[x_10].[ProductStatus],
	[x_10].[ExpiryDate],
	[x_10].[CustomDate1],
	[x_10].[ir1ic],
	[x_10].[ror1],
	[x_10].[ir1mim],
	[a2n].[Id],
	[a2n].[ChannelID],
	[a2n].[Name],
	[a2n].[Status],
	[a2n].[AisleNumber],
	[a2n].[CategoryABC],
	[a2n].[HeightClass],
	[a2n].[DepthCoordinate],
	[c2n].[Id],
	[c2n].[ResourceLabel],
	[c2n].[Status],
	[c2n].[CustomLong2],
	[c2n].[HeightClass],
	[c2n].[TypeID],
	[m2n].[Id],
	[m2n].[MaterialNumber],
	[m2n].[MaterialDescription_1],
	[m2n].[CategoryABC],
	[t2].[i2],
	[t2].[BatchNumber],
	[t2].[ProductStatus],
	[t2].[ExpiryDate],
	[t2].[CustomDate1],
	(
		SELECT
			Count(*)
		FROM
			[InventoryResourceDTO] [x_3]
		WHERE
			[x_3].[Status] < 99 AND [x_3].[ResourceID] = [c2n].[Id]
	),
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[RefOutfeedTransportOrderResourceDTO] [x_4]
			WHERE
				[x_4].[ResourceID] = [c2n].[Id]
		)
			THEN 1
		ELSE 0
	END,
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[InventoryResourceDTO] [x_5]
			WHERE
				[x_5].[Status] < 99 AND [x_5].[ResourceID] = [c2n].[Id] AND
				([x_5].[InfeedAdviceID] IS NULL OR EXISTS(
					SELECT
						*
					FROM
						[InfeedAdvicePositionDTO] [y_1]
					WHERE
						[y_1].[Id] = [x_5].[InfeedAdviceID] AND [y_1].[InfeedAdviceType] = 10
				))
		)
			THEN 1
		ELSE 0
	END
FROM
	(
		SELECT
			[c_1].[Id],
			[c_1].[AisleID],
			[c_1].[MaterialID],
			[a].[Id] as [Id_1],
			[a].[AisleNumber],
			[a].[PlantID],
			[a].[Name],
			[mn].[Id] as [m_1],
			[mn].[MaterialNumber],
			[mn].[MaterialDescription_1],
			[mn].[MaterialDescription_2],
			[mn].[MaterialDescription_3],
			[mn].[CategoryABC],
			[mn].[CategoryCustoms],
			[mn].[CategoryDimensions],
			[mn].[CategoryQuality],
			[mn].[CategoryTemperature],
			[a1n].[Id] as [Id_2],
			[a1n].[ChannelID],
			[a1n].[Name] as [Name_1],
			[a1n].[Status],
			[a1n].[AisleNumber] as [AisleNumber_1],
			[a1n].[CategoryABC] as [CategoryABC_1],
			[a1n].[HeightClass],
			[a1n].[DepthCoordinate],
			[c1n].[Id] as [c1],
			[c1n].[ResourceLabel],
			[c1n].[Status] as [Status_1],
			[c1n].[CustomLong2],
			[c1n].[HeightClass] as [HeightClass_1],
			[c1n].[TypeID],
			[m1n].[Id] as [m1],
			[m1n].[MaterialNumber] as [MaterialNumber_1],
			[m1n].[MaterialDescription_1] as [MaterialDescription_1_1],
			[m1n].[CategoryABC] as [CategoryABC_2],
			[t1].[i1],
			[t1].[BatchNumber],
			[t1].[ProductStatus],
			[t1].[ExpiryDate],
			[t1].[CustomDate1],
			(
				SELECT
					Count(*)
				FROM
					[InventoryResourceDTO] [x]
				WHERE
					[x].[Status] < 99 AND [x].[ResourceID] = [c1n].[Id]
			) as [ir1ic],
			CASE
				WHEN EXISTS(
					SELECT
						*
					FROM
						[RefOutfeedTransportOrderResourceDTO] [x_1]
					WHERE
						[x_1].[ResourceID] = [c1n].[Id]
				)
					THEN 1
				ELSE 0
			END as [ror1],
			CASE
				WHEN EXISTS(
					SELECT
						*
					FROM
						[InventoryResourceDTO] [x_2]
					WHERE
						[x_2].[Status] < 99 AND [x_2].[ResourceID] = [c1n].[Id] AND
						([x_2].[InfeedAdviceID] IS NULL OR EXISTS(
							SELECT
								*
							FROM
								[InfeedAdvicePositionDTO] [y]
							WHERE
								[y].[Id] = [x_2].[InfeedAdviceID] AND [y].[InfeedAdviceType] = 10
						))
				)
					THEN 1
				ELSE 0
			END as [ir1mim]
		FROM
			[ChannelDTO] [c_1]
				INNER JOIN [AisleDTO] [a] ON [c_1].[AisleID] = [a].[Id]
				LEFT JOIN [MaterialDTO] [mn] ON [c_1].[MaterialID] = [mn].[Id]
				LEFT JOIN [StorageShelfDTO] [a1n] ON [c_1].[Id] = [a1n].[ChannelID] AND 1 = [a1n].[DepthCoordinate]
				LEFT JOIN [RefResourceStorageShelfDTO] [b1n] ON [a1n].[Id] = [b1n].[StorageShelfID]
				LEFT JOIN [WmsLoadCarrierDTO] [c1n] ON [b1n].[ResourceID] = [c1n].[Id]
				LEFT JOIN (
					SELECT
						[x_6].[Id] as [i1],
						[x_6].[MaterialID],
						[x_6].[BatchNumber],
						[x_6].[ProductStatus],
						[x_6].[ExpiryDate],
						[x_6].[CustomDate1]
					FROM
						[InventoryResourceDTO] [x_6]
					WHERE
						[x_6].[Status] < 99
				) [t1] ON (
					SELECT
						[x_7].[Id]
					FROM
						[InventoryResourceDTO] [x_7]
					WHERE
						[x_7].[Status] < 99 AND [x_7].[ResourceID] = [b1n].[ResourceID]
					LIMIT @take
				) = [t1].[i1]
				LEFT JOIN [MaterialDTO] [m1n] ON [t1].[MaterialID] = [m1n].[Id]
	) [x_10]
		LEFT JOIN [StorageShelfDTO] [a2n] ON [x_10].[Id] = [a2n].[ChannelID] AND 2 = [a2n].[DepthCoordinate]
		LEFT JOIN [RefResourceStorageShelfDTO] [b2n] ON [a2n].[Id] = [b2n].[StorageShelfID]
		LEFT JOIN [WmsLoadCarrierDTO] [c2n] ON [b2n].[ResourceID] = [c2n].[Id]
		LEFT JOIN (
			SELECT
				[x_8].[Id] as [i2],
				[x_8].[MaterialID],
				[x_8].[BatchNumber],
				[x_8].[ProductStatus],
				[x_8].[ExpiryDate],
				[x_8].[CustomDate1]
			FROM
				[InventoryResourceDTO] [x_8]
			WHERE
				[x_8].[Status] < 99
		) [t2] ON (
			SELECT
				[x_9].[Id]
			FROM
				[InventoryResourceDTO] [x_9]
			WHERE
				[x_9].[Status] < 99 AND [x_9].[ResourceID] = [b2n].[ResourceID]
			LIMIT @take_1
		) = [t2].[i2]
		LEFT JOIN [MaterialDTO] [m2n] ON [t2].[MaterialID] = [m2n].[Id]
```

2024-01-23 05:29 UTC, igor-tkachev commented
@MaceWindu, the braking commit is marked with this tag - https://github.com/linq2db/linq2db/releases/tag/issue-4337. See my commit in this PR. Changes in the TableT.cs fix this issue, but break your TestContextLeak test.

2024-01-23 22:02 UTC, igor-tkachev commented
/azp run test-all

2024-01-23 22:33 UTC, igor-tkachev commented
/azp run test-all

2024-01-25 04:51 UTC, igor-tkachev approved these changes

2024-01-25 20:30 UTC, jogibear9988 commented
LGTM

2024-01-27 15:26 UTC, MaceWindu submitted a review, later dismissed

2024-01-27 15:26 UTC, MaceWindu commented on Source/LinqToDB/DataExtensions.cs
> +					Expression.Constant(null, typeof(IDataContext)), Expression.Constant(sql)));
we can move new constant to ExpressionConstants instead of removing it

2024-01-29 23:11 UTC, igor-tkachev commented
/azp run test-all

2024-01-29 23:12 UTC, igor-tkachev approved these changes

2024-01-30 13:31 UTC, viceroypenguin requested changes

2024-01-30 13:31 UTC, viceroypenguin commented on Source/LinqToDB/Expressions/ExpressionInstances.cs
> +		public static readonly Expression IntNegative1521134295 = Expression.Constant(-1521134295);
I would use a more descriptive name than `IntNegative1521134295`. Perhaps `HashMultiplier`?

2024-01-30 13:31 UTC, viceroypenguin commented on Source/LinqToDB/Expressions/ExpressionEvaluator.cs
> +					static (dc, e) => e is ConstantExpression { Value : null } ce && ce.Type == typeof(IDataContext) ? Expression.Constant(dc) : e);
```suggestion
					static (dc, e) => e is ConstantExpression { Value : null, Type: var t } && t == typeof(IDataContext) ? Expression.Constant(dc) : e);
```

2024-01-30 13:31 UTC, viceroypenguin commented on Source/LinqToDB/Expressions/ExpressionEvaluator.cs
> +			if (dataContext != null)
add braces

2024-01-30 13:31 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Builder/AssociationHelper.cs
> +//			var dataContextConstant = Expression.Constant(builder.DataContext, builder.DataContext.GetType());
Remove commented out line.

2024-01-30 13:31 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Builder/AssociationHelper.cs
> +//						parameterMatch.Add(definedQueryMethod.Parameters[1], dataContextConstant);
Remove commented out line

2024-01-30 13:31 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Builder/AssociationHelper.cs
> +//				var queryParam = Expression.Call(Methods.LinqToDB.GetTable.MakeGenericMethod(objectType), dataContextConstant);
Remove commented out line

2024-01-30 13:31 UTC, viceroypenguin commented on Source/LinqToDB/LinqExtensions.Merge.cs
> +					((IQueryable<TOutput>)outputTable).Expression,
Does `outputTable.Expression` return a different value from `((IQueryable<TOutput>)outputTable).Expression`?

2024-01-30 14:25 UTC, jogibear9988 commented on Source/LinqToDB/Expressions/ExpressionInstances.cs
> +		public static readonly Expression IntNegative1521134295 = Expression.Constant(-1521134295);
Don't know if it is more descriptive. It may be at the place where the expression is used, but not at the Place where it is defined. It is only a Constant Expression with this value.

2024-01-30 14:30 UTC, viceroypenguin commented on Source/LinqToDB/Expressions/ExpressionInstances.cs
> +		public static readonly Expression IntNegative1521134295 = Expression.Constant(-1521134295);
This is the equivalent of:
```cs
public const int Five = 5;
```

What happens if you need to change `Five`? What happens if someone comes along later and reads the code and wants to know what it's for? What happens if every place that needs a five specifically references `Five`, but they need five for different reasons.

Constants should be defined by their use, not their value. Then you can a) understand why the constant exists, and b) you can change the value appropriately. 

Better to have:
```cs
public const int FooCount = 5;
public const int BarCount = 5;
```

Similarly, this constant should be defined by how it's being used: as the `HashMultiplier`. Or maybe `HashMultiplierExpressionConstant`.

2024-01-30 14:49 UTC, jogibear9988 commented on Source/LinqToDB/Expressions/ExpressionInstances.cs
> +		public static readonly Expression IntNegative1521134295 = Expression.Constant(-1521134295);
![image](https://github.com/linq2db/linq2db/assets/364896/f7c8899a-2549-4362-a784-b721644f7247)

then most of those constants are wrong

2024-01-30 14:52 UTC, viceroypenguin commented on Source/LinqToDB/Expressions/ExpressionInstances.cs
> +		public static readonly Expression IntNegative1521134295 = Expression.Constant(-1521134295);
These two specifically, I would agree. Given their use in Oracle for a specific purpose, they should have a better name than `Constant26` and `Constant29`.

2024-01-30 15:51 UTC, jogibear9988 commented on Source/LinqToDB/LinqExtensions.Merge.cs
> +					((IQueryable<TOutput>)outputTable).Expression,
this I can not answer, rest is resolved

2024-01-30 15:53 UTC, jogibear9988 commented on Source/LinqToDB/LinqExtensions.Merge.cs
> +					((IQueryable<TOutput>)outputTable).Expression,
I looked, yes this are 2 different Expressions:

outputTable.Expression => is in the IQueryable
((IQueryable<TOutput>)outputTable).Expression => 
![image](https://github.com/linq2db/linq2db/assets/364896/cfb12fdb-4ed9-46f8-a289-49f7aa3f08c4)

2024-01-30 15:53 UTC, viceroypenguin approved these changes

2024-01-30 17:20 UTC, MaceWindu approved these changes

2024-01-30 17:20 UTC, MaceWindu commented
/azp run test-all

2024-01-30 20:49 UTC, MaceWindu commented
/azp run test-all

2024-01-31 07:36 UTC, jogibear9988 commented
The one not workin test for me seems unrelated to this pull req. Could we merge?

2024-01-31 13:14 UTC, MaceWindu commented
/azp run test-clickhouse

2024-01-31 19:26 UTC, merged