Fix discovered issues with systems with non-gregorian calendar
linq2db/linq2db pull request #4380
Opened 2024-01-20 12:42 UTC by MaceWindu

Fix #4371

2024-01-20 19:53 UTC, MaceWindu commented
/azp run test-all

2024-01-21 12:16 UTC, MaceWindu commented
/azp run test-all

2024-01-21 15:16 UTC, MaceWindu commented
/azp run test-all

2024-01-21 18:32 UTC, MaceWindu commented
/azp run test-all

2024-01-21 18:53 UTC, MaceWindu commented
/azp run test-all

2024-01-21 20:10 UTC, MaceWindu commented
/azp run test-all

2024-01-21 20:14 UTC, igor-tkachev submitted a review, later dismissed

2024-01-21 20:21 UTC, MaceWindu commented
/azp run test-all

2024-01-21 20:33 UTC, MaceWindu commented
/azp run test-all

2024-01-22 09:22 UTC, MaceWindu commented
/azp run test-all

2024-01-22 23:47 UTC, igor-tkachev submitted a review, later dismissed

2024-01-23 00:12 UTC, viceroypenguin requested changes
I'm not going to go through every file and point out `sb.Append(.., $"")` improvements, but these will generally be better than `.AppendFormat()`.

2024-01-23 00:12 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.cs
> +					sb.Value.AppendFormat(CultureInfo.InvariantCulture, "{0}", info.TraceInfoStep);
```suggestion
					sb.Value.Append(CultureInfo.InvariantCulture, $"{info.TraceInfoStep}");
```

2024-01-23 00:12 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.cs
> +					sb.Value.AppendFormat(CultureInfo.InvariantCulture, "{0}", info.TraceInfoStep);
And others in file

2024-01-23 00:12 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Access/AccessMappingSchema.cs
> +			stringBuilder.AppendFormat(CultureInfo.InvariantCulture, "chr({0})", value);
```suggestion
			stringBuilder.Append(CultureInfo.InvariantCulture, "chr({value})");
```

2024-01-23 00:12 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Access/AccessODBCSchemaProvider.cs
> +	using System.Globalization;
Should be with other `System.*` usings at top

2024-01-23 00:12 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Access/AccessOleDbSchemaProvider.cs
> +	using System.Globalization;
Should be with other `System.*` usings at top

2024-01-23 00:12 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/ClickHouse/ClickHouseMappingSchema.cs
> +						stringBuilder.AppendFormat(CultureInfo.InvariantCulture, "{0:x2}{1:x2}", value[i], value[i + 1]);
```suggestion
						stringBuilder.Append(CultureInfo.InvariantCulture, $"{value[i]:x2}{value[i + 1]:x2}");
```

2024-01-27 19:52 UTC, MaceWindu commented
/azp run test-all

2024-01-28 06:42 UTC, MaceWindu commented
/azp run test-all

2024-01-28 21:26 UTC, igor-tkachev approved these changes

2024-01-28 22:36 UTC, viceroypenguin submitted a review, later dismissed

2024-01-28 22:36 UTC, viceroypenguin commented on Source/LinqToDB/Data/CommandInfo.cs
> +#if NETFRAMEWORK || NETCOREAPP3_1 || NETSTANDARD2_0 || NETSTANDARD2_1
This is not repeated in other files. Necessary?

2024-01-29 07:42 UTC, MaceWindu commented on Source/LinqToDB/Data/CommandInfo.cs
> +#if NETFRAMEWORK || NETCOREAPP3_1 || NETSTANDARD2_0 || NETSTANDARD2_1
it depends on used types in file, some need it only for polyfills

2024-01-29 07:43 UTC, merged