Add [Pure] to options.
linq2db/linq2db pull request #4381
Opened 2024-01-21 01:51 UTC by igor-tkachev

Adding [Pure] to Option API.

2024-01-23 18:58 UTC, MaceWindu requested changes
maybe don't

2024-01-23 18:58 UTC, MaceWindu commented on Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> +		/// <summary>
Remove new methods. I plan to resolve inconsistencies in provider configuration APIs here in v6 and it's better to not introduce new conflicts where it wasn't requested by users

2024-01-24 02:04 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> +		/// <summary>
Done. Do not forget.

2024-01-24 16:07 UTC, MaceWindu approved these changes

2024-01-24 16:07 UTC, merged