Support for one way converter.
linq2db/linq2db pull request #4382
Opened 2024-01-22 05:36 UTC by igor-tkachev

PR for #4368.
It is possible to convert data differently depending on source/destination (FromDatabase/ToDatabase) type.

2024-01-22 23:43 UTC, igor-tkachev commented
/azp run test-all

2024-01-23 01:44 UTC, igor-tkachev commented
/azp run test-all

2024-01-24 15:39 UTC, viceroypenguin requested changes

2024-01-24 15:39 UTC, viceroypenguin commented on Source/LinqToDB/Common/ConvertInfo.cs
> -		public void Set(DbDataType from, DbDataType to, LambdaInfo expr)
source and binary breaking change. leave the old method in place, as a proxy to the new one with a default `conversionType` value. (note: for all deleted methods in this file, x6)

2024-01-24 15:39 UTC, viceroypenguin commented on Source/LinqToDB/Common/Converter.cs
> -		public static object? ChangeType(object? value, Type conversionType, MappingSchema? mappingSchema = null)
source and binary breaking change. leave the old method in place, as a proxy to the new one with a default `conversionType` value. (note: for all deleted methods in this file, x2)

2024-01-24 16:00 UTC, igor-tkachev commented on Source/LinqToDB/Common/ConvertInfo.cs
> -		public void Set(DbDataType from, DbDataType to, LambdaInfo expr)
`ConvertInfo` is not a public class.

2024-01-24 16:03 UTC, igor-tkachev commented on Source/LinqToDB/Common/Converter.cs
> -		public static object? ChangeType(object? value, Type conversionType, MappingSchema? mappingSchema = null)
Are you sure about source breaking change?

2024-01-24 16:41 UTC, viceroypenguin commented on Source/LinqToDB/Common/Converter.cs
> -		public static object? ChangeType(object? value, Type conversionType, MappingSchema? mappingSchema = null)
> Are you sure about source breaking change?

ah, nope. copy/paste from the other file. just a binary breaking change.

2024-01-24 18:47 UTC, igor-tkachev commented on Source/LinqToDB/Common/Converter.cs
> -		public static object? ChangeType(object? value, Type conversionType, MappingSchema? mappingSchema = null)
Do you really upgrade nugets without recompiling your projects? Or maybe you know someone?

2024-01-25 00:55 UTC, igor-tkachev commented
/azp run test-all

2024-01-27 14:45 UTC, MaceWindu requested changes

2024-01-27 14:45 UTC, MaceWindu commented on Source/LinqToDB.Tools/CodeModel/Types/WellKnownTypes.cs
> +				/// <see cref="Converter.ChangeTypeTo{T}(object?, MappingSchema?,ConversionType)"/> method reference.
Adding extra parameter requires changes to method call generation for both methods

2024-01-27 14:45 UTC, MaceWindu commented on Source/LinqToDB/Common/ConversionType.cs
> +	public enum ConversionType
Add xml-doc

2024-01-27 14:45 UTC, MaceWindu commented on Source/LinqToDB/Common/ConvertInfo.cs
> +			{
remove brackets

2024-01-28 22:29 UTC, igor-tkachev commented on Source/LinqToDB.Tools/CodeModel/Types/WellKnownTypes.cs
> +				/// <see cref="Converter.ChangeTypeTo{T}(object?, MappingSchema?,ConversionType)"/> method reference.
This parameter has a default value. Generated code should be fine.

2024-01-28 22:39 UTC, igor-tkachev commented on Source/LinqToDB/Common/ConvertInfo.cs
> +			{
It will make this code not compliable as these brackets limit the scope of some local variables.

2024-01-28 22:41 UTC, igor-tkachev commented
/azp run test-all

2024-01-29 07:44 UTC, MaceWindu approved these changes

2024-01-31 19:28 UTC, MaceWindu commented
/azp run test-all

2024-02-01 13:33 UTC, viceroypenguin commented on Source/LinqToDB/Common/Converter.cs
> -		public static object? ChangeType(object? value, Type conversionType, MappingSchema? mappingSchema = null)
The issue is not for direct consumers - only source compatibility is necessary for them, because they will recompile when upgrading. The issue is for intermediate consumers: App -> Lib -> L2db.  If App upgrades to a new version of l2db, but lib does not, then binary compatibility is important for lib to keep working. Examples would be: https://github.com/akkadotnet/Akka.Persistence.Sql, https://github.com/OrchardCoreContrib/OrchardCoreContrib, https://github.com/Synnotech-AG/Synnotech.Linq2Db, etc.. That said, these methods are _probably_ not directly referenced by such libraries, so it's probably fine.

2024-02-01 13:48 UTC, merged