Issue/4394
linq2db/linq2db pull request #4395
Opened 2024-01-26 10:20 UTC by jogibear9988

2024-01-28 18:27 UTC, MaceWindu commented
/azp run test-metrics

2024-01-28 19:05 UTC, MaceWindu commented
![image](https://github.com/linq2db/linq2db/assets/1099238/1d8bf02c-d4fd-4775-96ca-d50af1d04216)

2024-01-28 19:42 UTC, MaceWindu commented
and in release
![image](https://github.com/linq2db/linq2db/assets/1099238/e83e38ca-3661-41a0-bfd5-f6e47e6320e8)

2024-01-28 19:53 UTC, jogibear9988 commented
I merged #4339 in this pull request, cause without the query would not run at all.

2024-01-28 19:58 UTC, MaceWindu commented
I doubt it makes sense to do anything here before new parser lends. Profiler shows about half of time spent in this visitor https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs#L455-L468

@sdanyliv ?

2024-01-28 20:00 UTC, MaceWindu commented
![image](https://github.com/linq2db/linq2db/assets/1099238/7b8b98a2-c8cc-4285-926b-b59b4df56b0c)

2024-01-28 20:27 UTC, viceroypenguin commented
> I doubt it makes sense to do anything here before new parser lends. Profiler shows about half of time spent in this method https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs#L453-L482
> 
> @sdanyliv ?

To be specific, it's in the lambda from L455-L468

2024-01-28 20:30 UTC, MaceWindu commented
new parser shows similar numbers currently, but as I said - it's better leave it for later as slow areas will be heavy refactored there

2024-02-01 21:18 UTC, igor-tkachev commented
> new parser shows similar numbers currently, but as I said - it's better leave it for later as slow areas will be heavy refactored there

This is a bug that has to be fixed ASAP. We don't know how long the new parser will still be in development and how long it will take us to fix bugs in it. Will this bug be present in the library all this time?

2024-02-02 00:07 UTC, igor-tkachev commented
I like this test. Profiler shows a lot of points to optimize.

2024-02-02 08:46 UTC, sdanyliv commented
Profiler adds additional delays. Without profiler in Release, whole query is executed under 550-600 milliseconds. Second run with cache hit is 8 msec. There are a lot of ways how to improve SelectQuery optimization  and I will make research for new LINQ Translator but after all tests are passed. Not too much left.

Note that SelectQuery optimization is fully REWRITTEN, making cardinal changes in current version will be discarded .

2024-02-05 14:14 UTC, sdanyliv requested changes

2024-02-05 16:52 UTC, jogibear9988 commented
@sdanyliv 

Your coments were already resolved in pull req for issue #4337, wich I needed, without this didn't run at all

2024-02-05 18:10 UTC, sdanyliv commented on Tests/Linq/UserTests/Issue4337Tests.cs
> +using static Tests.UserTests.Issue4394Tests;
Remove that

2024-02-05 18:28 UTC, sdanyliv commented
Tested on V6
In Release second query executes approx 8 seconds without Stack Overflow. In Debug it crashes with SO, Probably too much debug information

Good test for optimizing translator, bad for production. 

Your goal to kill `linq2db` or make job done?

2024-06-08 17:13 UTC, merged