Concurrency issue in DataConnection options
linq2db/linq2db pull request #4399
Opened 2024-01-27 21:51 UTC by igor-tkachev

Closes #4398

2024-01-27 21:52 UTC, igor-tkachev commented
/azp run test-all

2024-01-27 21:59 UTC, jods4 commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
You need a memory barrier here, otherwise it's possible for concurrent code to see the new `_sets` pointer it sees the initialized `Dictionary` fields (write re-ordering).

Use `Thread.VolatileWrite(ref _sets, ...)` or declare `volatile _sets`.

2024-01-27 22:01 UTC, viceroypenguin commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
this definitely fixes so there's no race condition in manipulating the dictionary, but a) are we concerned about memory/perf issue in creating a new one every time? and b) are we concerned about potential loss of assignment if two threads are creating separate dictionaries at the same time (aka last assignment wins, and doesn't have the `typeof(TSet)` from the previous one)?

2024-01-27 22:12 UTC, jods4 commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
This is not thread-safe lock-free code for two reasons:
- I mentioned above that the "publish" of new reference is not a "releasing write", it lacks a memory barrier.
- You are right: "read `_sets`, modify, then write" will lose data if there are concurrent changes.

If we want to keep things lock-free, the solution to both problems at once is to use `Interlocked.CompareExchange` to pulbish the new dictionary, ensuring that the overwritten reference is the one that was read and modified (and looping if there was a concurrent change).

RE memory usage, if we have concerns `ImmutableDictionary` could be an option with better perf.

2024-01-27 22:15 UTC, igor-tkachev commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
Performance should not be an issue as this is a very rare case and all the option initializations should be done once at the beginning.
Last assignment wins - agreed.

2024-01-27 22:17 UTC, viceroypenguin commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
I'd probably prefer to see `ConcurrentDictionary<>` be used. Perhaps a `Lazy<ConcurrentDictionary<>>` if we want to protect initialization.

2024-01-27 22:18 UTC, jods4 commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
> Last assignment wins - agreed.

What?
This is not assignment to the same option (which I would agree).
It might be different options and one would simply be lost -- why not fix this?

2024-01-27 22:21 UTC, viceroypenguin commented on Source/LinqToDB/Common/OptionsContainer.cs
> +				_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
I like this better, but with a `lock`, we don't need a new assignment every time.
```suggestion
			lock (_sync)
				(_sets ??= new())[typeof(TSet)] = set = new();
```

2024-01-27 22:22 UTC, igor-tkachev commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
Fixed.

2024-01-27 22:24 UTC, viceroypenguin requested changes
if we did `ConcurrentDictionary<Type, IOptionSet> _sets = [];` and `_sets.GetOrAdd(typeof(TSet), _ => new());`, then we don't need to worry about concurrency issues.

2024-01-27 22:25 UTC, igor-tkachev commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
`ConcarrentDictionary` is good if read/write ration is 90/10 or less. Here we are going to have 1M+/1.

2024-01-27 22:26 UTC, jods4 commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
@viceroypenguin `ConcurrentDictionary<>` is pretty heavy. 
As options are only modified a few times at startup and then used a lot as a readonly structure, I tend to think a plain `Dictionary` or `SortedList` is most efficient here.
I'd favor `ConcurrentDictionary` if there was sustained concurrent modifications.

2024-01-27 22:30 UTC, jods4 commented on Source/LinqToDB/Common/OptionsContainer.cs
> +				_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
Yeah the approach with a lock is safe as long as we publish a new `Dictionary` and don't mutate the existing one (which would require a lock on readers as well). 👍

2024-01-27 22:30 UTC, jods4 approved these changes

2024-01-27 22:35 UTC, viceroypenguin approved these changes

2024-01-27 22:41 UTC, igor-tkachev commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
> What?

This code works for non-standard options that are not predifined. Such as specific provider options. If we do not have it in Option Container, we add it once. It can happen if we run the following code in parallel:

```c#
DefaultDataOptions = DefaultDataOptions.WithOption<PostgreSQLOptions>(...)
DefaultDataOptions = DefaultDataOptions.WithOption<SqlServerOptions>(...)
```

2024-01-27 22:45 UTC, viceroypenguin commented on Source/LinqToDB/Common/OptionsContainer.cs
> +			_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
The new `lock` code does. The previous version did not. Either `PostgreSQLOptions` or `SqlServerOptions` would get added, but not both, because they were assigned in two different dictionaries and only one got saved to `_sets`. The current version avoids that concern though.

2024-01-27 22:51 UTC, igor-tkachev commented on Source/LinqToDB/Common/OptionsContainer.cs
> +				_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
If we do not assign it every time, we need to use lock everywhere we read `_sets` which is much worse.
Again, this code will be called once for Option Container and all its copies. Once for each exotic option for the entire application run-time.

2024-01-27 22:54 UTC, igor-tkachev commented
/azp run test-all

2024-01-28 08:52 UTC, jogibear9988 commented on Source/LinqToDB/Common/OptionsContainer.cs
> +				_sets = new (_sets ?? []) { [typeof(TSet)] = set = new() };
but do we really need "volatile"?

2024-01-28 11:35 UTC, MaceWindu approved these changes

2024-01-28 11:35 UTC, merged