test for issue #4415
linq2db/linq2db pull request #4416
Opened 2024-02-06 12:19 UTC by jogibear9988

2024-02-06 22:52 UTC, jogibear9988 commented
I added a fix in BasicSqlOptimizer, but don't know if it's the correct way to fix.

Is v.Context.subQuery.Select.Columns[0].Expression always an SqlFunction? or do I also need to check for smth. else (or if the is check returns null?)

2024-02-07 07:54 UTC, jogibear9988 commented
/azp run test-all

2024-02-10 17:54 UTC, jogibear9988 commented
with this issue, we still need to look why it fails in newer linq2db. I think it did never work, but this means the default mapping has changed. Because this query breaks on our software after a linq2db update.

2024-02-10 18:00 UTC, MaceWindu requested changes

2024-02-10 18:01 UTC, MaceWindu commented
What exactly doesn't work? I don't see any failing tests

2024-02-10 18:11 UTC, jogibear9988 commented on Tests/Linq/UserTests/Issue4415Tests.cs
> +			finally
copied code

2024-02-10 18:12 UTC, jogibear9988 commented on Tests/Linq/UserTests/Issue4415Tests.cs
> +		public void TestIssue4415_Test1([IncludeDataSources(TestProvName.AllSQLite, TestProvName.AllPostgreSQL, TestProvName.AllAccess, TestProvName.AllOracle)] string configuration)
I add a true, but don't know what you mean

2024-02-10 18:12 UTC, jogibear9988 commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> +							if (e is SqlWhereClause w && w == v.Context.subQuery.Where && (v.Context.subQuery.Select.Columns[0].Expression is not SqlFunction f || !f.IsAggregate))
I'll move the code

2024-02-10 18:12 UTC, jogibear9988 commented
> What exactly doesn't work? I don't see any failing tests

why should you see a failing test? I've fixed it in the pull

2024-02-10 18:14 UTC, MaceWindu commented on Tests/Linq/UserTests/Issue4415Tests.cs
> +		public void TestIssue4415_Test4([IncludeDataSources(TestProvName.AllSQLite, TestProvName.AllPostgreSQL, TestProvName.AllAccess, TestProvName.AllOracle)] string configuration)
what we test here?

2024-02-10 18:14 UTC, MaceWindu commented on Tests/Linq/UserTests/Issue4415Tests.cs
> +		public void TestIssue4415_Test1([IncludeDataSources(TestProvName.AllSQLite, TestProvName.AllPostgreSQL, TestProvName.AllAccess, TestProvName.AllOracle)] string configuration)
Test1 and Test2 are technically the same, remove one

2024-02-10 18:18 UTC, MaceWindu commented
Change in behavior caused by NULL values handing fix https://github.com/linq2db/linq2db/pull/4196 in 5.3.0

2024-02-10 18:19 UTC, jogibear9988 commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> +							if (e is SqlWhereClause w && w == v.Context.subQuery.Where && (v.Context.subQuery.Select.Columns[0].Expression is not SqlFunction f || !f.IsAggregate))
I don't know wich part I should move to the helper?

     subQuery.Select.Columns[0].Expression
     
isn't this very specific to this part, as we only check the first Column? How should it look like in the helper?

2024-02-10 18:24 UTC, jogibear9988 commented on Tests/Linq/UserTests/Issue4415Tests.cs
> +		public void TestIssue4415_Test4([IncludeDataSources(TestProvName.AllSQLite, TestProvName.AllPostgreSQL, TestProvName.AllAccess, TestProvName.AllOracle)] string configuration)
can be removed

2024-02-10 18:24 UTC, MaceWindu commented on Tests/Linq/UserTests/Issue4415Tests.cs
> +		public void TestIssue4415_Test1([IncludeDataSources(TestProvName.AllSQLite, TestProvName.AllPostgreSQL, TestProvName.AllAccess, TestProvName.AllOracle)] string configuration)
`DataSources` attribute has remote contexts enabled by default
`IncludeDataSources` has them disabled, so you need to enable them manually except cases when your test is not compatible with remote context

2024-02-10 18:24 UTC, jogibear9988 commented on Tests/Linq/UserTests/Issue4415Tests.cs
> +		public void TestIssue4415_Test1([IncludeDataSources(TestProvName.AllSQLite, TestProvName.AllPostgreSQL, TestProvName.AllAccess, TestProvName.AllOracle)] string configuration)
i only did 2, cause I did not know if the nullable should be default. Cause with the old linq2db version it was not

2024-02-10 18:30 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> +							if (e is SqlWhereClause w && w == v.Context.subQuery.Where && (v.Context.subQuery.Select.Columns[0].Expression is not SqlFunction f || !f.IsAggregate))
I'm talking about function probing code (`(v.Context.subQuery.Select.Columns[0].Expression is not SqlFunction f || !f.IsAggregate`)

Use `QueryHelper.IsAggregationFunction()` helper instead of duplicating this check

2024-02-10 18:50 UTC, MaceWindu commented on Source/LinqToDB/SqlQuery/QueryHelper.cs
> +		public static bool IsAggregationFunction(this ISqlExpression expr)
remove, QueryHelper already contains `IsAggregationFunction` method

2024-02-10 20:11 UTC, MaceWindu commented
/azp run test-all

2024-02-10 20:12 UTC, MaceWindu approved these changes

2024-02-10 20:28 UTC, viceroypenguin approved these changes

2024-02-11 03:54 UTC, jogibear9988 commented
@MaceWindu 
your last query does not return a row in oracle.
but when I look at the linq, it should not return a row in all databses, so the test is wrong?

if you try this: (the same query in linq2objects)

			var p_2 = db.GetTable<LanguageDTO>().ToList();
			var qry_2 = p_2.GroupBy(x => x.Name).Select(x => x.Max(y => y.LanguageID) + "test");
			var qry2_2 = p_2.Where(x => qry_2.Contains(x.LanguageID));
			var lst_2 = qry2_2.ToList();
			
it does not return a row...

2024-02-11 08:17 UTC, MaceWindu commented
test is correct, oracle just never heard of SQL standards

2024-02-11 08:19 UTC, MaceWindu commented
/azp run test-all

2024-02-13 19:44 UTC, MaceWindu commented
/azp run test-all

2024-02-17 12:34 UTC, merged