Added support for IQueryExpressionInterceptor.
linq2db/linq2db pull request #4479
Opened 2024-04-15 13:08 UTC by sdanyliv

2024-04-15 13:09 UTC, sdanyliv commented
/azp run test-all

2024-04-15 13:11 UTC, viceroypenguin commented on Source/LinqToDB/Data/CommandInfo.cs
> +						if (DataConnection is IInterceptable<IUnwrapDataObjectInterceptor> { Interceptor: not null } interceptable)
same for others
```suggestion
if (DataConnection is IInterceptable<IUnwrapDataObjectInterceptor> { Interceptor: { } interceptor })
{
  using (...)
    reader = interceptor...
}
```

2024-04-15 13:13 UTC, viceroypenguin commented on Source/LinqToDB/Remote/RemoteDataContextBase.Interceptors.cs
> +		IInterceptable<IQueryExpressionInterceptor>
```suggestion
		IInterceptable<IQueryExpressionInterceptor>,
```

2024-04-15 13:20 UTC, sdanyliv commented on Source/LinqToDB/Data/CommandInfo.cs
> +						if (DataConnection is IInterceptable<IUnwrapDataObjectInterceptor> { Interceptor: not null } interceptable)
Good point will fix that.

2024-04-15 13:31 UTC, sdanyliv commented
/azp run test-all

2024-04-15 13:31 UTC, viceroypenguin approved these changes

2024-04-15 13:54 UTC, sdanyliv commented
/azp run test-all

2024-04-15 13:58 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +					if (((IInterceptable<IConnectionInterceptor>)this).Interceptor != null)
could you do:
```cs
if (this is IInterceptable<IConnectionInterceptor> { Interceptor: { } interceptor })
```
like the other pattern matching ones?

2024-04-15 23:43 UTC, igor-tkachev requested changes
Is this PR about Interceptors or Options? I see a lot of questionable Options refactoring. Can you split it, so we will be able to discuss it separately?

2024-04-15 23:43 UTC, igor-tkachev commented on Source/LinqToDB/Common/OptionsContainer.cs
> -		protected void Apply<TA>(TA obj)
What's wrong with this code?

2024-04-16 08:12 UTC, sdanyliv commented on Source/LinqToDB/Common/OptionsContainer.cs
> -		protected void Apply<TA>(TA obj)
Tight coupling with DataConnection, DataContext, RemoteDataContext. Options should know nothing about these classes. Also current code has strange unpredictable side effects. 

Removing all of this strange stuff made code readable, simpler, predictable and performant.

2024-04-16 14:31 UTC, igor-tkachev commented on Source/LinqToDB/Common/OptionsContainer.cs
> -		protected void Apply<TA>(TA obj)
Then split this PR, so it will be easier to revert it later, when I will need to extend it.

2024-04-18 13:43 UTC, sdanyliv commented on Source/LinqToDB/Common/OptionsContainer.cs
> -		protected void Apply<TA>(TA obj)
Reverted this change, will create new PR for that after merging with `version_6` branch.

2024-05-07 18:38 UTC, MaceWindu approved these changes

2024-05-07 18:38 UTC, MaceWindu commented
/azp run test-all

2024-05-08 09:57 UTC, merged