Improve `IAsyncEnumerable` usage
linq2db/linq2db pull request #4486
Opened 2024-04-21 20:40 UTC by viceroypenguin

This PR does two things:
* Updates `InsertWithOutputAsync`, `UpdateWithOutputAsync`, and `DeleteWithOutputAsync` to return `IAsyncEnumerable` properly. This is a binary-compatible change, as the existing methods are kept. However, these methods are now marked with `[Obsolete]` to encourage source migration to the newer `IAsyncEnumerable` method. 
* Adds `QueryToAsyncEnumerable` in places where `QueryToArrayAsync` and `QueryToListAsync` are provided. This allows consumers to use `IAsyncEnumerable` if desired. No obsoletions are planned here, though consumers are allowed and encouraged to upgrade if the query has many rows. 
  > [!NOTE]
  > This change only applies to `NATIVE_ASYNC`.

## 💣 Breaking Change
* The new versions of `XxxWithOutputAsync` are not source compatible, so this is a v6.0 breaking change. Consumers will need to add `.ToListAsync()` or similar to address this change. This is to restore consistency between `InsertWithOutputAsync`/`UpdateWithOutputAsync`/`DeleteWithOutputAsync` with `MergeWithOutputAsync`; this consistency has been chosen to use the more flexible and modern approach.

Replaces #4323

2024-04-21 20:57 UTC, viceroypenguin commented
/azp run test-all

2024-04-21 21:07 UTC, Shane32 commented
Just for clarity when reviewing this PR, I'd like to point out the difference between the old and new signatures:

```cs
// old
public static Task<TOutput[]> DeleteWithOutputAsync<TSource,TOutput>(
    this IQueryable<TSource>           source,
    Expression<Func<TSource, TOutput>> outputExpression,
    CancellationToken                  token = default)

// new methods
public static IAsyncEnumerable<TOutput> DeleteWithOutputAsync<TSource,TOutput>(
    this IQueryable<TSource>           source,
    Expression<Func<TSource, TOutput>> outputExpression)

public static Task<TOutput[]> DeleteWithOutputAsync<TSource, TOutput>(
    this IQueryable<TSource> source,
    Expression<Func<TSource, TOutput>> outputExpression,
    CancellationToken token)
```

This means that the following code will immediately break for v6 due to the cancellation token not being specified:

```cs
// old syntax; immediately broken with v6
var ret = await query.DeleteWithOutputAsync(x => x.Id);

// required fix to use obsolete method
var ret = await query.DeleteWithOutputAsync(x => x.Id, default);
```

As specified, however, the change is binary compatible - already-compiled code will continue to function with v6, as the optional parameter is built into the caller's compiled code and so will match on the obsolete method.

2024-04-21 22:04 UTC, jods4 commented on Source/LinqToDB/Data/CommandInfo.cs
> +				await DataConnection.EnsureConnectionAsync(cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext);
Didn't you have another PR open to clean up `ConfigureAwait`?

The creep of needing a `Configuration` instance everywhere async to do `ConfigureAwait(ContinueOnCapturedContext)` when it's actually against standard .net patterns and should just be `ConfigureAwait(false)` is real.

Hopefully with upcoming major version number (for the parser rewrite?) we can obsolete this config.

2024-04-21 22:05 UTC, viceroypenguin commented on Source/LinqToDB/Data/CommandInfo.cs
> +				await DataConnection.EnsureConnectionAsync(cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext);
No, definitely wasn't me.

2024-04-21 22:39 UTC, Shane32 commented on Source/LinqToDB/LinqExtensions.Delete.cs
> +		[Obsolete("Will be removed in l2db 7.0")]
I suggest a longer obsolete message that explains to the developer the replacement syntax when they are fixing their code.

```suggestion
		[Obsolete("Will be removed in linq2db 7.0. Please remove the cancellation token and use await foreach or ToListAsync instead.")]
```

Not sure exactly, but something like that.

2024-04-22 02:01 UTC, viceroypenguin commented on Source/LinqToDB/LinqExtensions.Delete.cs
> +		[Obsolete("Will be removed in l2db 7.0")]
I would argue it doesn't really matter, since the only way to call this method is: 
```cs
LinqExtensions.DeleteWithOutputAsync(dbContext, ...);
```
since the `this` has been removed.

2024-04-22 02:01 UTC, viceroypenguin commented
/azp run test-all

2024-04-22 07:20 UTC, jods4 commented on Source/LinqToDB/Data/CommandInfo.cs
> +				await DataConnection.EnsureConnectionAsync(cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext);
Right, it was @MaceWindu in #4475.

2024-04-22 07:43 UTC, Shane32 commented on Source/LinqToDB/LinqExtensions.Delete.cs
> +		[Obsolete("Will be removed in l2db 7.0")]
So it’s only there for binary compatibility at all then?

2024-04-22 07:48 UTC, sdanyliv commented
@viceroypenguin , check mergeability with this PR https://github.com/linq2db/linq2db/pull/3401

2024-04-22 11:32 UTC, viceroypenguin commented on Source/LinqToDB/LinqExtensions.Delete.cs
> +		[Obsolete("Will be removed in l2db 7.0")]
Correct

2024-04-23 13:30 UTC, viceroypenguin commented
> @viceroypenguin , check mergeability with this PR #3401

@sdanyliv no merge conflicts; and shouldn't have any impact on #3401.

2024-04-23 14:51 UTC, sdanyliv approved these changes

2024-04-24 13:27 UTC, igor-tkachev submitted a review, later dismissed

2024-05-11 10:30 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnectionExtensions.cs
> +		public static IAsyncEnumerable<T> QueryToAsyncEnumerable<T>(this DataConnection connection, string sql, DataParameter parameter)
Why we have this overload for linq2db-mapped method?

2024-05-11 10:31 UTC, MaceWindu commented on Source/LinqToDB/Data/DataConnectionExtensions.cs
> +		public static IAsyncEnumerable<T> QueryToAsyncEnumerable<T>(this DataConnection connection, T template, string sql, params DataParameter[] parameters)
and why for template-based specification it is only 2 overloads?

2024-05-11 10:38 UTC, MaceWindu commented on Source/LinqToDB/LinqExtensions.Delete.cs
> +		[Obsolete("Will be removed in l2db 7.0")]
let's not invent another name for Linq To DB 🥲  Please use `Linq To DB 7` here

2024-05-11 10:43 UTC, MaceWindu requested changes
minor updates needed

2024-05-14 07:14 UTC, merged