Do not allow EXISTS optimization to remove columns from UNION queries.
linq2db/linq2db pull request #4522
Opened 2024-05-30 13:16 UTC by sdanyliv

2024-05-30 15:14 UTC, viceroypenguin approved these changes

2024-05-30 21:34 UTC, MaceWindu commented
/azp run test-all

2024-05-31 11:41 UTC, MaceWindu commented
/azp run test-sybase

2024-05-31 12:45 UTC, MaceWindu commented
/azp run test-sybase

2024-05-31 15:10 UTC, MaceWindu requested changes
Actually no, access baselines shows bad query. Could we improve test somehow to fail in such cases?

2024-05-31 16:04 UTC, MaceWindu commented
/azp run test-access

2024-05-31 16:08 UTC, MaceWindu commented
/azp run test-access

2024-05-31 18:07 UTC, merged