Add misssing cancellation token parameter
linq2db/linq2db pull request #4535
Opened 2024-06-17 16:17 UTC by MaceWindu

Fix #4534

2024-06-17 16:18 UTC, viceroypenguin approved these changes

2024-06-17 16:58 UTC, sdanylivsoftserve approved these changes

2024-06-17 16:59 UTC, sdanyliv approved these changes

2024-06-17 17:15 UTC, sdanyliv requested changes

2024-06-17 17:15 UTC, sdanyliv commented on Source/LinqToDB/LinqExtensions.cs
> +			                CancellationToken token = default)
Please use `cancellationToken`

2024-06-18 08:08 UTC, MaceWindu commented on Source/LinqToDB/LinqExtensions.cs
> +			                CancellationToken token = default)
I plan to do it for all parameters in separate PR

2024-06-18 08:23 UTC, sdanyliv approved these changes

2024-06-18 08:45 UTC, merged