Null comparison changes, rebased #3537
linq2db/linq2db pull request #4547
Opened 2024-06-24 12:42 UTC by jods4

See #3537 for all details, this is a rebase on v6 `master`.
The rebase was rather messy due to the many changes that have been made in v6 since 2022, let's see how the tests fail.

2024-06-24 12:53 UTC, jods4 commented
/azp run test-all

2024-06-24 13:31 UTC, jods4 commented
/azp run test-all

2024-06-25 01:25 UTC, jods4 commented
/azp run test-all

2024-06-27 23:14 UTC, viceroypenguin commented on Source/LinqToDB/Common/Configuration.cs
> +			/// If set to LikeCSharp nullable fields would be checked for IS NULL in Equal/NotEqual comparisons.
```suggestion
			/// If set to <see cref="CompareNulls.LikeCSharp" /> nullable fields would be checked for IS NULL in Equal/NotEqual comparisons.
```
(and similar for other references to values from the enum)

2024-06-27 23:14 UTC, viceroypenguin commented on Source/LinqToDB/Common/Configuration.cs
> +			/// but sniffs parameters values and changes = into IS NULL when parameters are null.
Use `<c></c>` to mark code blocks, like `<c>IS NULL</c>`

2024-06-27 23:14 UTC, viceroypenguin commented on Source/LinqToDB/Common/Configuration.cs
> +			/// Default value: <c>LikeCSharp</c>.
Use `<see />` instead of `<c>` here

2024-06-27 23:14 UTC, viceroypenguin commented on Source/LinqToDB/Common/Configuration.cs
> +			public static bool CompareNullsAsValues
Add `[EditorBrowsable(EditorBrowsableState.None)]` (or `Advanced`, but I think `None` is better for `[Obsolete]` properties) to hide accidental use.

2024-06-27 23:14 UTC, viceroypenguin commented on Source/LinqToDB/Common/Configuration.cs
> +				[Obsolete("Use CompareNulls instead: true maps to LikeCSharp and false to LikeSqlExceptParameters")]
Why is this on the `set` and not the property as a whole?

2024-06-27 23:14 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +							var withNullValue = compareNulls == CompareNulls.LikeCSharp
```suggestion
							var withNullValue = compareNulls is CompareNulls.LikeCSharp
```
(and others)

2024-06-27 23:14 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Translation/ProviderMemberTranslatorDefault.cs
> +				translationContext.DataOptions.LinqOptions.CompareNulls == CompareNulls.LikeCSharp ? true : null)
```suggestion
			var predicate = new SqlPredicate
				.ExprExpr(
					sqlExpression,
					SqlPredicate.Operator.Equal, 
					new SqlValue(0),
					translationContext.DataOptions.LinqOptions.CompareNulls == CompareNulls.LikeCSharp ? true : null)
```

2024-07-04 19:20 UTC, sdanyliv commented
/azp run test-all

2024-07-04 19:23 UTC, viceroypenguin commented on Source/LinqToDB/SqlQuery/SqlPredicate.cs
> +					if (Operator is Operator.Equal)
should this be converted to a `switch`

2024-07-04 20:22 UTC, sdanyliv commented on Source/LinqToDB/SqlQuery/SqlPredicate.cs
> +					if (Operator is Operator.Equal)
Please do not convert everything to switch. It is not converted specially to be more clear and debuggable.

2024-07-04 20:24 UTC, viceroypenguin commented on Source/LinqToDB/SqlQuery/SqlPredicate.cs
> +					if (Operator is Operator.Equal)
I'll challenge you this case though.

```cs
if (Op is Equal)
{
}
else if (Op is NotEqual)
{
}
else
{
}
```
vs 
```cs
switch (op)
{
  case Equal: break;
  case NotEqual: break;
  default: break;
}
```
should have the same debuggability, and be _more_ clear.

2024-07-05 20:21 UTC, igor-tkachev requested changes

2024-07-05 20:21 UTC, igor-tkachev commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
> +						(dataOptions.LinqOptions.CompareNulls != CompareNulls.LikeSql &&
It looks like you removed some optimizations.

2024-07-05 20:21 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.cs
>  		[Pure]
Do not remove it. Make it `Obsolete`.

2024-07-05 20:21 UTC, igor-tkachev commented on Source/LinqToDB/Extensions/DataOptionsExtensions.cs
>  		{
Do not remove it. Make it `Obsolete`.

2024-07-13 12:27 UTC, MaceWindu commented
@jods4 status?

2024-07-15 08:54 UTC, jods4 commented
@MaceWindu sorry, recently I've not had a great time at work, so I don't feel like coding when I come home.
I'll try to take a look this week so that we can finalize and merge.

2024-07-16 17:59 UTC, sdanyliv commented
`LikeCSharp` ? Why not `LikeCLR`?

2024-07-17 20:41 UTC, jods4 commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +							var withNullValue = compareNulls == CompareNulls.LikeCSharp
@viceroypenguin as much as I like C# pattern matching, it doesn't make any difference here, does it? Same number of chars in source, same compiled bytecode?

2024-07-17 20:45 UTC, jods4 commented on Source/LinqToDB/Common/Configuration.cs
> +				[Obsolete("Use CompareNulls instead: true maps to LikeCSharp and false to LikeSqlExceptParameters")]
@viceroypenguin This was at the very beginning and my thought was that I wanted to discourage users to set this option, but still be able to read it in our code. Then I noticed with the new options we mustn't read the global config anymore anyway, so you're right the whole thing is deprecated.

2024-07-17 20:46 UTC, jods4 commented on Source/LinqToDB/Common/Configuration.cs
> +			public static bool CompareNullsAsValues
I thought this would be implied by `[Obsolete]` slightly disappointed by MS that it's not!

2024-07-17 21:01 UTC, jods4 commented on Source/LinqToDB/Extensions/DataOptionsExtensions.cs
>  		[Pure]
Good catch, I thought the new Options were added to 6.0 but they already shipped in 5.x.

I'm putting back an [Obsolete] WithCompareNullsAsValues.

2024-07-17 21:09 UTC, jods4 commented
@sdanyliv Sure, let me rename.

2024-07-17 21:43 UTC, jods4 commented on Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
> +						(dataOptions.LinqOptions.CompareNulls != CompareNulls.LikeSql &&
It has changed, yes. In commit 2840efac I fixed Oracle empty strings handling (it was buggy).

This method indicates whether compilation is dependent on actual parameter values.
The transformation is made in OracleSqlExpressionConvertVisitor.ConvertExprExprPredicate.
So basically the condition here must be the same, and it is.

You can check if the new transformation looks correct to you in OracleSqlExpressionConvertVisitor.cs.
The explanation why this expression is what it is can be found in comments on lines 39-43.
It's not intuitive but after reviewing one more time it looks ok to me.

2024-07-17 21:45 UTC, jods4 commented
/azp run test-all

2024-07-18 10:40 UTC, MaceWindu requested changes
baselines:

- OrmBattleTests.DateTimeTest : not sure how to feel about this change, looks suspicious
- Issue3148Tests.TestDefaultExpression_10 : doesn't look right @sdanyliv ?

2024-07-18 10:40 UTC, MaceWindu commented on Source/LinqToDB/Common/CompareNulls.cs
> +	/// <summary>Defines how null values are compared in compiled queries.</summary>
I would prefer to avoid use of `compiled query` as it means something else (Compiled Query API). Better to use `generated SQL`

2024-07-18 10:40 UTC, MaceWindu commented on Source/LinqToDB/Common/CompareNulls.cs
> +		LikeSqlExceptParameters,
maybe add c#+SQL examples to comments. Now they expect from users to have good understanding what they do 😄 . Also examples are always easier to understand

2024-07-18 15:34 UTC, jods4 commented on Source/LinqToDB/Common/CompareNulls.cs
> +		LikeSqlExceptParameters,
I have copied the example from configuration API + added a little bit more notes in comments.

2024-07-18 15:35 UTC, jods4 commented
/azp run test-all

2024-07-19 08:02 UTC, MaceWindu commented
/azp run test-all

2024-07-19 08:02 UTC, MaceWindu commented
/azp run test-all

2024-07-19 08:06 UTC, MaceWindu commented
/azp run test-all

2024-07-19 10:54 UTC, jods4 commented
/azp run test-all

2024-07-19 15:33 UTC, jods4 commented
Linux Oracle 19 is unrelated, flaky failure `ORA-01000: maximum open cursors exceeded`

2024-07-19 19:51 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Oracle/OracleSqlExpressionConvertVisitor.cs
> +					aValue is string { Length: 0 })
why not 
```suggestion
					aValue is "")
```

2024-07-20 23:51 UTC, jods4 commented on Source/LinqToDB/DataProvider/Oracle/OracleSqlExpressionConvertVisitor.cs
> +					aValue is string { Length: 0 })
I think it's a mechanical rewriting of previous code.

Old code did it in two steps, first `if (value2 is string string2)` then later `if (string2.Length == 0)`.
It just got mindlessly merged into a single `is string { Length: 0 }` check.

Replacing with `aValue is ""` would be exactly the same. This actually occurs 4 times in this file, twice here and twice on lines 30-37.

Fun fact I was looking at the JIT disasembly and although the logic is exactly the same, the quality of `is ""` is lower. JIT actually tests if the pointer is null twice for some reason:
https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcDMACR2DC2A3utmbjgPYBGAVgKYDGwA/NgJ4Dcp5PZW2apUoAbbAFkkACkIAPAJTE+5fgHZssgHTtsASwjYARIe5oVAX2XKBQ0RIQyNikmZXk46rTv24kABmJsABl6ADsAc2AACxBsAPNTC3RzIA==

As a result asm code for `is ""` is 9 bytes longer than `is { Length: 0 }`.
I doesn't matter though, we can change if you want. If I had written this code from scratch, I'd probably have written `is ""`, it's more natural.

2024-07-21 00:05 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Oracle/OracleSqlExpressionConvertVisitor.cs
> +					aValue is string { Length: 0 })
Shorter ASM is good enough reason for me to support `is { Length: 0 }`. Leave it, imo.

2024-07-21 13:57 UTC, jods4 commented on Source/LinqToDB/DataProvider/Oracle/OracleSqlExpressionConvertVisitor.cs
> +					aValue is string { Length: 0 })
@viceroypenguin for what it's worth, MS seems to have fixed that redundant null check in .net 9.0
https://github.com/dotnet/runtime/issues/105191

2024-07-21 15:00 UTC, MaceWindu commented
@jods4 , could you please add this regression test to oracletests.cs to see if it is fixed (require some changes to `UseCompareNullsAsValues`)

```cs
#region Issue 4163
[Test]
public void Issue4163Test([IncludeDataSources(true, TestProvName.AllOracle)] string context, [Values] bool compareNullsAsValues)
{
	using var db = GetDataContext(context, o => o.UseCompareNullsAsValues(compareNullsAsValues));
	using var tb = db.CreateLocalTable(Issue4163TableForCreate.Data);

	var cnt = db.GetTable<Issue4163Table>().Where(r => r.Method != PaymentMethod.Unknown).Count();

	Assert.That(cnt, Is.EqualTo(2));
}

[Table("Issue4163Table")]
sealed class Issue4163TableForCreate
{
	[Column] public int Id { get; set; }
	[Column(CanBeNull = true)] public PaymentMethod Method { get; set; }

	public static readonly Issue4163TableForCreate[] Data = new[]
	{
		new Issue4163TableForCreate() { Id = 1, Method = PaymentMethod.Unknown },
		new Issue4163TableForCreate() { Id = 2, Method = PaymentMethod.Cheque },
		new Issue4163TableForCreate() { Id = 3, Method = PaymentMethod.EFT },
	};
}

[Table("Issue4163Table")]
sealed class Issue4163Table
{
	[Column] public int Id { get; set; }
	[Column(CanBeNull = false)] public PaymentMethod Method { get; set; }

	public static readonly Issue4163Table[] Data = new[]
	{
		new Issue4163Table() { Id = 1, Method = PaymentMethod.Unknown },
		new Issue4163Table() { Id = 2, Method = PaymentMethod.Cheque },
		new Issue4163Table() { Id = 3, Method = PaymentMethod.EFT },
	};
}

enum PaymentMethod
{
	[MapValue("")]
	Unknown,

	[MapValue("C")]
	Cheque,

	[MapValue("E")]
	EFT
}
#endregion
```

2024-07-21 16:15 UTC, jods4 commented
@MaceWindu Here you go.

/azp run test-all

2024-07-21 16:16 UTC, jods4 commented
/azp run test-all

2024-07-22 09:57 UTC, MaceWindu commented
/azp run test-all

2024-07-22 13:31 UTC, MaceWindu commented
ok (not really), test fails...

2024-07-22 14:04 UTC, MaceWindu commented
```sql
    SELECT
	COUNT(*)
FROM
	"Issue4163Table" r
```

optimizer removed condition, because it was reduced to `true`

2024-07-22 14:12 UTC, jods4 commented
@MaceWindu The logic is simple but the resolution might not be.

The field is declared as a non-nullable enum.

1. The source condition is `Method != Enum.Unknown`
2. Mapping to strings turns into `Method != ""`
3. Oracle empty strings turns into `Method IS NOT NULL`
4. Optimizer sees "non-nullable field is not null" and simplifies to `true`

Mapped enums here are a very special case, but it's fair to assume that not all Oracle users always mark their string fields nullable, so that bug could easily surface in other situations.

One possibily solution could be for Oracle provider to always consider any field of type string as intrinsically nullable. This isn't strictly true as you can declare a `varchar` column as `not null` and that simply implies you can't store the empty string in it. But it's better to produce slightly less optimized SQL that works rather than SQL that does not.

2024-07-22 14:16 UTC, MaceWindu commented
Will try to change tests first

2024-07-22 15:02 UTC, MaceWindu commented
Ok, I've updated tests to not force not-null and now there are two issues.

1. `LikeClr` test case doesn't work with remote context

expected
```sql
SELECT
   	COUNT(*)
FROM
   	"Issue4163Table" r
WHERE
   	r."Method" IS NOT NULL
```
but was
```sql
SELECT
   	COUNT(*)
FROM
   	"Issue4163Table" r
WHERE
   	(r."Method" IS NOT NULL OR r."Method" IS NULL)
```

something lost during ast de/serialization probably

2. We infer nullability from enum map values, but it doesn't handle empty string as null. Will check if we can configure it easily for oracle

2024-07-23 10:53 UTC, MaceWindu commented
No idea for now what to do with test failing over remote context. We use different query optimization approach for it and it doesn't work well in this case. Maybe @sdanyliv will come with some solution later. I will disable test for now

2024-07-23 11:00 UTC, MaceWindu commented
/azp run test-all

2024-07-23 16:09 UTC, MaceWindu approved these changes

2024-07-24 08:21 UTC, merged