Refactored Coalesce to use appropriate SqlCoalesceExpression
linq2db/linq2db pull request #4548
Opened 2024-06-28 13:55 UTC by sdanyliv

Baded on https://github.com/linq2db/linq2db/pull/4533, so it is blocked until merged.

2024-07-03 20:52 UTC, sdanyliv commented
/azp run test-all

2024-07-04 13:37 UTC, sdanyliv commented
/azp run test-all

2024-07-05 14:47 UTC, sdanyliv commented
/azp run test-all

2024-07-08 15:16 UTC, MaceWindu commented
OrderByTests.OrderBy7 baselines are incorrect (also looks like test data is not good as it didn't failed test, maybe try another divider?)

2024-07-08 15:21 UTC, MaceWindu requested changes
I would prefer orderby builder changes and test renames going to separate PRs (2 more) to simplify baselines review

2024-07-08 19:48 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/OracleSqlExpressionConvertVisitor.cs
> -				case { Name: "Coalesce", Parameters.Length: 2 }:
👍

2024-07-09 09:04 UTC, sdanyliv commented
/azp run test-all

2024-07-09 16:20 UTC, merged

2024-07-09 16:23 UTC, viceroypenguin commented on Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
> +			if (startFrom is SqlSelectStatement)
Dead code?

2024-07-09 16:23 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +				// TODO: Review. Actually it can be removed. Currently only strange NullableBoolTests.NullTest test fails.
Does this need to be reviewed?

2024-07-09 16:23 UTC, viceroypenguin commented on Source/LinqToDB/SqlQuery/QueryHelper.cs
> +					//TODO: probably remove, we have SqlCoalesceExpression
Should this be confirmed?

2024-07-10 09:35 UTC, sdanyliv commented on Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
> +				// TODO: Review. Actually it can be removed. Currently only strange NullableBoolTests.NullTest test fails.
If you can yes. I have no time yet.

2024-07-10 09:36 UTC, sdanyliv commented on Source/LinqToDB/SqlQuery/QueryHelper.cs
> +					//TODO: probably remove, we have SqlCoalesceExpression
If you can handle it, I have no objections.