Add `IExceptionInterceptor`
linq2db/linq2db pull request #4552
Opened 2024-06-29 22:15 UTC by viceroypenguin

2024-06-29 22:15 UTC, viceroypenguin commented
/azp run test-all

2024-07-03 12:25 UTC, viceroypenguin commented
/azp run test-all

2024-07-04 00:18 UTC, viceroypenguin commented
/azp run test-all

2024-07-05 19:27 UTC, igor-tkachev requested changes

2024-07-05 19:27 UTC, igor-tkachev commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +			if (((IInterceptable<ICommandInterceptor>)this).Interceptor is { } cInterceptor)
```c#
protected virtual async Task<int> ExecuteNonQueryAsync(CancellationToken cancellationToken)
{
	var cInterceptor = ((IInterceptable<ICommandInterceptor>)  this).Interceptor;
	var eInterceptor = ((IInterceptable<IExceptionInterceptor>)this).Interceptor;

	if (cInterceptor != null || eInterceptor != null)
	{
		try
		{
			await using (cInterceptor == null ? null : ActivityService.StartAndConfigureAwait(ActivityID.CommandExecuteNonQueryAsync))
			await using (eInterceptor == null ? null : ActivityService.StartAndConfigureAwait(ActivityID.CommandExecuteNonQueryAsync))
			{
				if (cInterceptor != null)
				{
					var result = await cInterceptor.ExecuteNonQueryAsync(new(this), _command!, Option<int>.None, cancellationToken)
						.ConfigureAwait(Common.Configuration.ContinueOnCapturedContext);

					if (result.HasValue)
						return result.Value;
				}

				return await _command!.ExecuteNonQueryAsync(cancellationToken)
					.ConfigureAwait(Common.Configuration.ContinueOnCapturedContext);
			}
		}
		catch (Exception ex)
		{
			if (eInterceptor != null)
				using (ActivityService.Start(ActivityID.ExceptionInterceptorProcessException))
					eInterceptor.ProcessException(new(this), ex);
			throw;
		}
	}

	await using (ActivityService.StartAndConfigureAwait(ActivityID.CommandExecuteNonQueryAsync))
	{
		return await _command!.ExecuteNonQueryAsync(cancellationToken)
			.ConfigureAwait(Common.Configuration.ContinueOnCapturedContext);
	}
}
```

2024-07-05 19:27 UTC, igor-tkachev commented on Source/LinqToDB/Interceptors/AggregatedExceptionInterceptor.cs
> +	sealed class AggregatedExceptionInterceptor : AggregatedInterceptor<IExceptionInterceptor>, IExceptionInterceptor
Do we need a new class for this? I would move this method to `AggregatedInterceptor`.

2024-07-05 19:55 UTC, viceroypenguin commented on Source/LinqToDB/Interceptors/AggregatedExceptionInterceptor.cs
> +	sealed class AggregatedExceptionInterceptor : AggregatedInterceptor<IExceptionInterceptor>, IExceptionInterceptor
Simply following the pattern of the other interceptors. If we want to try and change the pattern, I'm open to that, but that should be a fuller discussion.

2024-07-05 20:30 UTC, igor-tkachev commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +			if (((IInterceptable<ICommandInterceptor>)this).Interceptor is { } cInterceptor)
- a developer can return None, which means l2db should handle this in the regular way,
- if I used both interceptors, I wouldn't do the work of ExceptionInterceptor in CommandInterceptor.

2024-07-06 17:49 UTC, viceroypenguin commented on Source/LinqToDB/Data/DataConnection.Async.cs
> +			if (((IInterceptable<ICommandInterceptor>)this).Interceptor is { } cInterceptor)
Addressed

2024-07-06 17:49 UTC, viceroypenguin commented
/azp run test-all

2024-07-06 17:58 UTC, viceroypenguin commented
/azp run test-all

2024-07-08 13:06 UTC, viceroypenguin commented
/azp run test-all

2024-07-08 14:53 UTC, MaceWindu approved these changes

2024-07-08 14:53 UTC, MaceWindu commented on Source/LinqToDB/Interceptors/IExceptionInterceptor.cs
> +		///	Event, Triggered when an exception is thrown while executing a database command/query.
```suggestion
		///	Event, triggered when an exception is thrown while executing a database command/query.
```

2024-07-08 16:40 UTC, viceroypenguin commented
/azp run test-all

2024-07-09 07:47 UTC, MaceWindu approved these changes

2024-07-09 15:18 UTC, merged