Validate `IQueryable<>` is valid
linq2db/linq2db pull request #4580
Opened 2024-07-18 22:29 UTC by viceroypenguin

Part of #4475

2024-07-18 23:30 UTC, viceroypenguin commented
/azp run test-all

2024-07-19 04:26 UTC, sdanyliv commented
I do not see reason why you have added this validation. In 95% it is not needed. Just build tree. Validation needed only for Async methods.

2024-07-19 07:32 UTC, MaceWindu commented
@sdanyliv we discussed it before - if we validate correctness of call for async, it will be strange to not do it for sync apis

2024-07-19 07:36 UTC, MaceWindu commented on Source/LinqToDB/LinqExtensions.cs
> +			var currentSource = grouping.GetLinqToDBSource();
Not reviewed all changes, but this one failed in tests. We should validate only final methods, not those that return query

2024-07-19 11:34 UTC, viceroypenguin commented
/azp run test-all

2024-07-19 16:09 UTC, viceroypenguin commented
/azp run test-all

2024-07-22 13:27 UTC, MaceWindu requested changes

2024-07-22 13:27 UTC, MaceWindu commented on Source/LinqToDB/Async/IQueryProviderAsync.cs
> +		Expression Expression { get; }
Why do we need it? It duplicates `IQueryProvider.Expression` property

2024-07-22 13:27 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/DatabaseSpecificQueryable.cs
> +	abstract class DatabaseSpecificQueryable<TSource> : IQueryable<TSource>, IQueryProviderAsync
Where do we need it? (just want to know, I'm fine with this change)

2024-07-22 13:30 UTC, viceroypenguin commented on Source/LinqToDB/Async/IQueryProviderAsync.cs
> +		Expression Expression { get; }
`IQueryable` provides `Expression`. `IQueryProvider` does not. Since in most cases we're validating and returning an `IQueryProviderAsync` back from the validation method, which is based on the `ProcessSourceQueryable`, we need the new `Expression`, so adding here allows us to use it for processing.

2024-07-22 13:34 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/DatabaseSpecificQueryable.cs
> +	abstract class DatabaseSpecificQueryable<TSource> : IQueryable<TSource>, IQueryProviderAsync
Provider specific `IQueryable<>`s, like `AccessSpecificQueryable` need to implement `IQueryProviderAsync` or they will get kicked out when finishing the query.

2024-07-22 13:35 UTC, viceroypenguin commented on Source/LinqToDB/LinqExtensions.cs
> +            return currentSource.Provider.CreateQuery<TSource>(expr);
What's suspicious about this?

2024-07-22 13:41 UTC, MaceWindu commented on Source/LinqToDB/LinqExtensions.cs
> +            return currentSource.Provider.CreateQuery<TSource>(expr);
github renders it smaller than it should

2024-07-22 14:18 UTC, viceroypenguin commented on Source/LinqToDB/LinqExtensions.Delete.cs
> +		public static async Task<int> DeleteWithOutputIntoAsync<TSource,TOutput>(
I'll disagree with you, but I'm good with it either way.

2024-07-22 14:19 UTC, viceroypenguin commented
/azp run test-all

2024-07-22 14:22 UTC, MaceWindu commented on Source/LinqToDB/LinqExtensions.Delete.cs
> +		public static async Task<int> DeleteWithOutputIntoAsync<TSource,TOutput>(
Well:
1. we don't use this approach anywhere else
2. it goes in different direction with https://github.com/linq2db/linq2db/issues/3437. But personally I don't expect changes like that could be an improvement for such heavy-weight task as ORM

2024-07-22 14:25 UTC, viceroypenguin commented on Source/LinqToDB/LinqExtensions.Delete.cs
> +		public static async Task<int> DeleteWithOutputIntoAsync<TSource,TOutput>(
1. Valid, then yeah, it's worth having a conversation at some point.
2. For an ORM, where a majority of the time is gonna be db related, and heavy allocations due to loading objects, I'm less concerned about the allocation of a `Task`, and more concerned about having accurate stack traces.

2024-07-23 15:27 UTC, MaceWindu approved these changes

2024-07-23 16:26 UTC, sdanyliv approved these changes

2024-07-24 08:19 UTC, merged