Add decimal overload function of power
linq2db/linq2db pull request #4635
Opened 2024-09-25 17:48 UTC by riktimmondal

Fix for #4528.

2024-09-26 09:13 UTC, MaceWindu commented
Looks good, thanks! Please add test for new overload here https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/MathFunctionTests.cs#L193-L200

2024-09-27 08:29 UTC, riktimmondal commented
@MaceWindu Added test. Please review.

2024-09-27 08:43 UTC, MaceWindu requested changes

2024-09-27 08:43 UTC, MaceWindu commented on Tests/Linq/Linq/MathFunctionTests.cs
> +		public void Pow1([DataSources(ProviderName.SQLiteMS)] string context)
don't rename existing tests as it will mess with our test baselines. Just name new test e.g. `PowDecimal`

2024-09-27 08:43 UTC, MaceWindu commented on Source/LinqToDB/Linq/Expressions.cs
> +			{ M(() => Math.Pow        (0,0) ), N(() => L<decimal,decimal,decimal>    ((decimal x,decimal y) => Sql.Power(x, y)!.Value )) },
I looked at list of available overloads and see that Math.Pow has only `double` version, which means we cannot map it for double. Please remove this line as it will override previous mapping

2024-09-27 08:43 UTC, MaceWindu commented on Tests/Linq/Linq/MathFunctionTests.cs
> +					from t in from p in Types select Math.Floor((decimal)(8.7345*Math.Pow((double)p.MoneyValue, 2))) where t != 0 select t,
As discussed above, because we don't have decimal version of Math.Pow, test should use Sql.Power directly (`MoneyValue` is decimal, so it will call proper overload):

```cs
Math.Floor(Sql.Power(p.MoneyValue, 3))
```

2024-09-27 08:46 UTC, MaceWindu commented
@jods4, am I correct about having only Sql.Power for decimal? I don't see how we can map Math.Pow here without ton of ugly code. Also Math.Pow doesn't handle null values, which makes it even more useless

2024-09-27 08:49 UTC, riktimmondal commented on Tests/Linq/Linq/MathFunctionTests.cs
> +		public void Pow1([DataSources(ProviderName.SQLiteMS)] string context)
Understood

2024-09-27 08:49 UTC, riktimmondal commented on Tests/Linq/Linq/MathFunctionTests.cs
> +					from t in from p in Types select Math.Floor((decimal)(8.7345*Math.Pow((double)p.MoneyValue, 2))) where t != 0 select t,
Understood

2024-09-27 08:51 UTC, riktimmondal commented on Source/LinqToDB/Linq/Expressions.cs
> +			{ M(() => Math.Pow        (0,0) ), N(() => L<decimal,decimal,decimal>    ((decimal x,decimal y) => Sql.Power(x, y)!.Value )) },
Understood

2024-09-27 09:03 UTC, MaceWindu commented
/azp run test-all

2024-09-27 09:25 UTC, MaceWindu commented
There are build errors https://dev.azure.com/linq2db/linq2db/_build/results?buildId=13791&view=results

You can alter test in this way

```cs
Math.Floor(Sql.Power(p.MoneyValue, 3)!.Value)
```

2024-09-27 09:46 UTC, MaceWindu commented
/azp run test-all

2024-09-27 13:06 UTC, MaceWindu commented on Tests/Linq/Linq/MathFunctionTests.cs
> +		public void PowDecimal([DataSources(ProviderName.SQLiteMS)] string context)
Changes to disable ASE testing. Not worth fixing for now
```suggestion
		// Sybase: https://stackoverflow.com/questions/25281843
		[Test]
		public void PowDecimal([DataSources(ProviderName.SQLiteMS, TestProvName.AllSybase)] string context)
```

2024-09-27 14:31 UTC, MaceWindu commented
- for sybase failure I already proposed to disable test
- sql server failures could be ignored. Caused by recent change to CI images [#899](https://github.com/microsoft/mssql-docker/issues/899) and will be handled by separate PR
- oracle/firebird - unrelated failures, should go away after re-run

2024-10-02 08:02 UTC, MaceWindu approved these changes

2024-10-11 14:58 UTC, merged