[WIP] Refactored SQL gneration. More bugfixes.
linq2db/linq2db pull request #4676
Opened 2024-10-08 16:09 UTC by sdanyliv

2024-10-08 16:10 UTC, sdanyliv commented
/azp run test-sqlite

2024-10-08 16:54 UTC, viceroypenguin commented on Tests/Linq/Linq/NullableBoolTests.cs
> +			//TODO: weird test, we should not check for NULL in this case
Calling out `TODO` for further discussion in PR

2024-10-08 17:24 UTC, sdanyliv commented on Tests/Linq/Linq/NullableBoolTests.cs
> +			//TODO: weird test, we should not check for NULL in this case
TODO for further removing bad test code. I need to discuss about this with IT.

2024-10-08 17:27 UTC, sdanyliv commented
/azp run test-sqlite

2024-10-08 19:20 UTC, sdanyliv commented
/azp run test-sqlite

2024-10-08 21:13 UTC, sdanyliv commented
/azp run test-all

2024-10-11 15:08 UTC, sdanyliv commented
/azp run test-sqlserver

2024-10-11 17:35 UTC, sdanyliv commented
/azp run test-sqlserver

2024-10-11 17:54 UTC, MaceWindu commented
/azp run test-all

2024-10-11 20:49 UTC, sdanyliv commented
/azp run test-all

2024-10-11 20:56 UTC, sdanyliv commented
/azp run test-all

2024-10-11 23:33 UTC, viceroypenguin commented
/azp run test-all

2024-10-11 23:57 UTC, viceroypenguin commented
/azp run test-all

2024-10-12 17:46 UTC, sdanyliv commented
/azp run test-all

2024-10-12 19:19 UTC, sdanyliv commented
/azp run test-all

2024-10-12 20:23 UTC, sdanyliv commented
/azp run test-all

2024-10-14 18:14 UTC, sdanyliv commented
/azp run test-all

2024-10-14 18:18 UTC, viceroypenguin commented on Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizerVisitor.cs
> +				return Visit(node.Operand);
should this be `node.Operand.Operand`, since we're canceling the two `not`s out?

2024-10-14 19:43 UTC, sdanyliv commented on Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizerVisitor.cs
> +				return Visit(node.Operand);
You are right. Good catch.

2024-10-14 19:45 UTC, sdanyliv commented
/azp run test-all

2024-10-17 15:07 UTC, sdanyliv commented
/azp run test-all

2024-10-29 19:52 UTC, sdanyliv commented
/azp run test-all

2024-10-30 15:41 UTC, sdanylivsoftserve commented
/azp run test-all

2024-10-30 15:42 UTC, sdanyliv commented
/azp run test-all

2024-10-31 17:37 UTC, sdanyliv commented
/azp run test-all

2024-11-01 16:26 UTC, sdanyliv commented
/azp run test-all

2024-11-02 08:58 UTC, sdanyliv commented
/azp run test-all

2024-11-02 18:15 UTC, sdanyliv commented
/azp run test-all

2024-11-02 19:05 UTC, sdanyliv commented
/azp run test-all

2024-11-03 17:44 UTC, sdanyliv commented
/azp run test-all

2024-11-05 10:14 UTC, MaceWindu commented
/azp run test-all

2024-11-05 15:09 UTC, MaceWindu commented
/azp run test-all

2024-11-05 22:21 UTC, MaceWindu commented
/azp run test-all

2024-11-06 09:29 UTC, MaceWindu commented
/azp run test-all

2024-11-06 12:17 UTC, MaceWindu requested changes

2024-11-06 12:17 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs
> +			SqlProviderFlags.IsDistinctFromSupported                               = true;
That's doesn't look right, maybe we don't have test coverage for it. Oracle doesn't have `DISTINCT FROM` operator.

2024-11-06 12:17 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> +		public bool IsDistinctFromSupported { get; set; }
probably we can enable it for SQLite as it is available since v3.39.0

2024-11-06 12:17 UTC, MaceWindu commented on Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
> +		public bool IsDistinctFromSupported { get; set; }
Also available in SQL Server 2022

2024-11-06 13:37 UTC, MaceWindu commented on Tests/Linq/UserTests/Issue4414Tests.cs
> +		/*[Test]
why it is disabled?

2024-11-06 17:25 UTC, MaceWindu commented
/azp run test-all

2024-11-06 20:05 UTC, MaceWindu commented
/azp run test-all

2024-11-06 20:52 UTC, MaceWindu commented
/azp run test-all

2024-11-08 10:21 UTC, MaceWindu commented
/azp run test-all

2024-11-08 12:22 UTC, MaceWindu commented
/azp run test-all

2024-11-08 17:36 UTC, MaceWindu commented
/azp run test-all

2024-11-11 10:26 UTC, MaceWindu commented
/azp run test-all

2024-11-11 20:44 UTC, MaceWindu commented
/azp run test-all

2024-11-11 20:46 UTC, MaceWindu commented
/azp run test-all

2024-11-11 22:39 UTC, MaceWindu commented
/azp run test-all

2024-11-12 16:03 UTC, MaceWindu commented
/azp run test-informix

2024-11-12 16:52 UTC, MaceWindu commented
/azp run test-informix

2024-11-12 17:02 UTC, MaceWindu commented
/azp run test-informix

2024-11-12 17:02 UTC, MaceWindu commented
/azp run test-db2

2024-11-12 17:56 UTC, MaceWindu commented
/azp run test-db2

2024-11-12 19:51 UTC, MaceWindu commented
/azp run test-all

2024-11-13 08:11 UTC, sdanyliv commented
/azp run test-all

2024-11-13 22:25 UTC, MaceWindu commented
/azp run test-all

2024-11-14 08:47 UTC, MaceWindu commented
/azp run test-all

2024-11-14 08:58 UTC, MaceWindu commented
/azp run test-all

2024-11-14 16:54 UTC, MaceWindu commented
/azp run test-all

2024-11-16 22:27 UTC, MaceWindu commented
/azp run test-all

2024-11-17 12:29 UTC, MaceWindu commented
/azp run test-all

2024-11-17 13:13 UTC, MaceWindu commented
/azp run test-all

2024-11-17 15:44 UTC, MaceWindu commented
/azp run test-all

2024-11-17 15:49 UTC, sdanyliv commented
/azp run test-all

2024-11-17 16:47 UTC, MaceWindu commented
/azp run test-all

2024-11-17 17:20 UTC, MaceWindu commented
/azp run test-all

2024-11-18 12:26 UTC, MaceWindu commented
/azp run test-all

2024-11-18 15:49 UTC, MaceWindu commented
/azp run test-all

2024-11-18 16:47 UTC, MaceWindu commented
/azp run test-all

2024-11-19 08:11 UTC, MaceWindu commented
/azp run test-all

2024-11-19 16:51 UTC, MaceWindu commented
/azp run test-all

2024-11-19 22:53 UTC, MaceWindu commented
/azp run test-all

2024-11-20 15:43 UTC, MaceWindu commented
/azp run test-all

2024-11-20 22:03 UTC, MaceWindu commented
/azp run test-all

2024-11-21 08:17 UTC, MaceWindu commented
/azp run test-all

2024-11-21 16:08 UTC, MaceWindu commented
/azp run test-all

2024-11-22 12:38 UTC, MaceWindu commented
/azp run test-all

2024-11-23 09:53 UTC, MaceWindu commented
/azp run test-all

2024-11-23 16:38 UTC, MaceWindu commented
/azp run test-all

2024-11-23 19:12 UTC, MaceWindu commented
/azp run test-all

2024-11-24 13:05 UTC, MaceWindu commented
/azp run test-all

2024-11-24 22:40 UTC, MaceWindu commented
/azp run test-all

2024-11-25 11:04 UTC, MaceWindu commented
/azp run test-all

2024-11-25 14:24 UTC, MaceWindu commented
/azp run test-all

2024-11-25 15:56 UTC, MaceWindu commented
/azp run test-all

2024-11-26 13:52 UTC, MaceWindu commented
/azp run test-all

2024-11-26 14:36 UTC, viceroypenguin commented on Source/LinqToDB/DataProvider/Access/AccessODBCSqlBuilder.cs
> +			if (DataProvider is AccessDataProvider provider && provider.Provider == AccessProvider.OleDb)
Should this be `AccessProvider.ODBC`?

2024-11-26 14:37 UTC, MaceWindu commented on Source/LinqToDB/DataProvider/Access/AccessODBCSqlBuilder.cs
> +			if (DataProvider is AccessDataProvider provider && provider.Provider == AccessProvider.OleDb)
It should

2024-11-26 14:49 UTC, MaceWindu commented
/azp run test-all

2024-11-26 23:07 UTC, MaceWindu commented
/azp run test-all

2024-11-26 23:21 UTC, MaceWindu commented
/azp run test-all

2024-11-27 12:55 UTC, MaceWindu commented
/azp run test-all

2024-11-27 15:22 UTC, MaceWindu commented
/azp run test-all

2024-11-28 13:54 UTC, MaceWindu commented
/azp run test-all

2024-11-28 16:02 UTC, MaceWindu commented
/azp run test-all

2024-11-28 17:11 UTC, MaceWindu commented
/azp run test-all

2024-11-28 17:18 UTC, MaceWindu commented
/azp run test-all

2024-11-28 17:21 UTC, MaceWindu commented
/azp run test-all

2024-11-28 19:09 UTC, MaceWindu commented
/azp run test-all

2024-11-28 19:54 UTC, MaceWindu commented
/azp run test-all

2024-11-29 16:55 UTC, MaceWindu commented
/azp run test-all

2024-11-30 15:38 UTC, MaceWindu commented
/azp run test-all

2024-11-30 16:21 UTC, MaceWindu commented
/azp run test-all

2024-12-01 20:37 UTC, sdanyliv commented
/azp run test-all

2024-12-03 09:42 UTC, MaceWindu commented
/azp run test-all

2024-12-03 14:08 UTC, MaceWindu commented
/azp run test-all

2024-12-06 13:33 UTC, MaceWindu commented
/azp run test-all

2024-12-07 16:35 UTC, MaceWindu commented
/azp run test-all

2024-12-07 19:27 UTC, MaceWindu commented
/azp run test-all

2024-12-07 19:28 UTC, MaceWindu commented
/azp run test-all

2024-12-07 19:37 UTC, MaceWindu commented
/azp run test-all

2024-12-08 15:10 UTC, MaceWindu commented
/azp run test-all

2024-12-08 17:50 UTC, MaceWindu commented
/azp run test-all

2024-12-09 12:10 UTC, MaceWindu commented
/azp run test-all

2024-12-11 14:18 UTC, MaceWindu commented
/azp run test-all

2024-12-12 12:24 UTC, MaceWindu commented
/azp run test-all

2024-12-12 18:52 UTC, sdanyliv commented
/azp run test-all

2024-12-12 20:38 UTC, sdanyliv commented
/azp run test-all

2024-12-13 10:29 UTC, MaceWindu commented
/azp run test-all

2024-12-13 14:19 UTC, MaceWindu commented
/azp run test-all

2024-12-13 15:46 UTC, MaceWindu commented
/azp run test-all

2024-12-13 22:36 UTC, MaceWindu commented
/azp run test-all

2024-12-14 18:18 UTC, sdanyliv commented
/azp run test-all

2024-12-14 20:53 UTC, sdanyliv commented
/azp run test-all

2024-12-14 20:57 UTC, sdanyliv commented
/azp run test-all

2024-12-15 18:00 UTC, sdanyliv commented
/azp run test-all

2024-12-16 16:24 UTC, MaceWindu commented
/azp run test-all

2024-12-16 17:07 UTC, MaceWindu commented
/azp run test-all

2024-12-16 17:51 UTC, MaceWindu commented
/azp run test-all

2024-12-17 17:04 UTC, MaceWindu commented
/azp run test-all

2024-12-17 19:22 UTC, MaceWindu commented
/azp run test-all

2024-12-18 10:15 UTC, MaceWindu commented
/azp run test-all

2024-12-19 16:49 UTC, MaceWindu commented
/azp run test-all

2024-12-19 16:55 UTC, MaceWindu commented
/azp run test-all

2024-12-19 19:46 UTC, MaceWindu commented
/azp run test-all

2024-12-19 22:53 UTC, MaceWindu approved these changes

2024-12-20 08:51 UTC, merged